"""
add_new_presets_v15_full.py
바디페인팅 확장 40개 — 데이터 직접 포함
"""

import json
from pathlib import Path

PRESETS_DIR = Path("presets")
PRESETS_DIR.mkdir(exist_ok=True)

new_presets = {
    # 🎨 명화/작가 — 퍼블릭 도메인 14개
    "cezanne_body": {"tag":"Cezanne Body","subject":"a post-impressionist Cezanne body art female model","body":"soft glamour model, feminine curves, painterly Cezanne geometric presence","outfit":"Cezanne post-impressionist geometric patterns painted across body, angular brushstroke body art, Mont Sainte-Victoire color palette","material":"Cezanne geometric angular paint, ochre green blue structured pattern, post-impressionist body art","environment":"Provencal landscape, warm southern France light, Cezanne painting atmosphere","lighting":"warm Provencal light, structured geometric shadow, post-impressionist glow","style":"Cezanne post-impressionist body art editorial, geometric painterly glamour photography","quality":"shot on Hasselblad H6D, warm Provencal grade, portrait 2:3 vertical"},
    "gauguin_tropics": {"tag":"Gauguin Tropics","subject":"a Gauguin Tahitian body art female model","body":"glamour model, exotic tropical curves, Gauguin primitive goddess presence","outfit":"Gauguin Tahitian patterns painted across body, tropical primitive color body art, Polynesian motif","material":"Gauguin bold tropical paint, rich orange brown yellow pattern, primitive Tahitian body art","environment":"Tahitian tropical paradise, lush palm backdrop, Gauguin painting atmosphere","lighting":"warm tropical light, primitive exotic atmosphere, Gauguin golden glow","style":"Gauguin Tahitian body art editorial, primitive tropical glamour photography","quality":"shot on Phase One XF IQ4, warm tropical grade, portrait 2:3 vertical"},
    "toulouse_lautrec": {"tag":"Toulouse Lautrec","subject":"a Toulouse-Lautrec Moulin Rouge body art female model","body":"slim elegance model, cabaret dancer figure, Parisian belle epoque presence","outfit":"Toulouse-Lautrec Moulin Rouge poster style painted across body, cabaret dancer motifs, belle epoque body art","material":"Lautrec bold flat color paint, Moulin Rouge poster pattern, belle epoque body art","environment":"Moulin Rouge Paris, belle epoque cabaret atmosphere, gaslit Parisian night","lighting":"warm gaslight Moulin Rouge atmosphere, belle epoque cabaret glow, Parisian night light","style":"Toulouse-Lautrec body art editorial, Moulin Rouge glamour photography","quality":"shot on Leica SL2, warm belle epoque grade, portrait 2:3 vertical"},
    "schiele_body": {"tag":"Schiele Body","subject":"a Egon Schiele expressionist body art female model","body":"slim elegance model, angular raw expressionist figure, intense Schiele presence","outfit":"Egon Schiele expressionist patterns painted across body, angular raw line body art, Viennese expressionism","material":"Schiele angular raw paint, ochre black line expressionist pattern, Viennese body art","environment":"dark Viennese studio, raw expressionist atmosphere, Schiele painting space","lighting":"harsh raw expressionist light, angular shadow, intense Viennese atmosphere","style":"Schiele expressionist body art editorial, raw angular glamour photography","quality":"shot on Hasselblad H6D, raw expressionist grade, portrait 2:3 vertical"},
    "degas_dancer": {"tag":"Degas Dancer","subject":"a Degas ballerina body art female model","body":"ballerina physique, slender elongated figure, ethereal Degas dancer presence","outfit":"Degas pastel ballerina patterns painted across body, tutu motifs and ballet dancer art, impressionist dance body art","material":"Degas soft pastel paint, ballet dancer pattern, impressionist dance body art","environment":"Paris Opera ballet studio, soft rehearsal light, Degas painting atmosphere","lighting":"soft rehearsal studio light, pastel impressionist atmosphere, ethereal dancer glow","style":"Degas ballerina body art editorial, impressionist dance glamour photography","quality":"shot on Hasselblad H6D, soft pastel impressionist grade, portrait 2:3 vertical"},
    "renoir_soft": {"tag":"Renoir Soft","subject":"a Renoir impressionist body art female model","body":"soft glamour model, feminine gentle curves, warm Renoir impression presence","outfit":"Renoir impressionist soft patterns painted across body, warm flesh tone body art, French impressionism","material":"Renoir soft warm paint, peach pink impressionist pattern, French body art","environment":"sun-dappled French garden, warm impressionist light, Renoir painting atmosphere","lighting":"warm dappled garden light, soft impressionist atmosphere, Renoir golden glow","style":"Renoir impressionist body art editorial, soft warm glamour photography","quality":"shot on Phase One XF IQ4, warm impressionist grade, portrait 2:3 vertical"},
    "botticelli_venus": {"tag":"Botticelli Venus","subject":"a Botticelli Birth of Venus body art female model","body":"slim elegance model, Renaissance goddess figure, divine Botticelli Venus presence","outfit":"Botticelli Birth of Venus patterns painted across body, flowing golden hair and shell motifs, Renaissance goddess body art","material":"Botticelli tempera-style paint, gold pink blue Renaissance pattern, divine goddess body art","environment":"Mediterranean seashore, golden shell backdrop, Botticelli painting atmosphere","lighting":"golden Renaissance divine light, Mediterranean atmosphere, Venus goddess glow","style":"Botticelli Venus body art editorial, Renaissance divine glamour photography","quality":"shot on Hasselblad H6D, golden Renaissance grade, portrait 2:3 vertical"},
    "titian_goddess": {"tag":"Titian Goddess","subject":"a Titian Renaissance goddess body art female model","body":"luxury glamour model, Renaissance goddess curves, Titian divine sensual presence","outfit":"Titian Renaissance oil painting patterns across body, Venetian goddess motifs, rich Renaissance body art","material":"Titian rich oil paint texture, deep red gold Venetian pattern, Renaissance body art","environment":"Venetian Renaissance palace, rich Titian painting atmosphere, golden Venetian light","lighting":"warm Venetian golden light, Renaissance palace atmosphere, Titian rich glow","style":"Titian Renaissance body art editorial, Venetian goddess glamour photography","quality":"shot on Phase One XF IQ4, warm Venetian gold grade, portrait 2:3 vertical"},
    "rubens_baroque": {"tag":"Rubens Baroque","subject":"a Rubens baroque body art female model","body":"soft glamour model, baroque abundant curves, Rubens dramatic divine presence","outfit":"Rubens baroque painting patterns across body, dramatic swirling baroque motifs, Flemish master body art","material":"Rubens rich baroque paint, dramatic swirling pattern, Flemish baroque body art","environment":"Flemish baroque studio, dramatic baroque atmosphere, rich Rubens painting space","lighting":"dramatic baroque chiaroscuro light, Flemish master atmosphere, rich dramatic glow","style":"Rubens baroque body art editorial, Flemish master glamour photography","quality":"shot on Hasselblad H6D, rich baroque grade, portrait 2:3 vertical"},
    "ingres_odalisque": {"tag":"Ingres Odalisque","subject":"a Ingres odalisque body art female model","body":"slim elegance model, neoclassical odalisque figure, Ingres refined sensual presence","outfit":"Ingres neoclassical odalisque patterns painted across body, orientalist motifs, neoclassical body art","material":"Ingres precise neoclassical paint, ivory blue orientalist pattern, neoclassical body art","environment":"orientalist harem interior, soft exotic light, Ingres painting atmosphere","lighting":"soft orientalist interior light, neoclassical refined atmosphere, Ingres ivory glow","style":"Ingres odalisque body art editorial, neoclassical glamour photography","quality":"shot on Phase One XF IQ4, soft neoclassical grade, portrait 2:3 vertical"},
    "waterhouse_nymph": {"tag":"Waterhouse Nymph","subject":"a Waterhouse Pre-Raphaelite nymph body art female model","body":"slim elegance model, Pre-Raphaelite ethereal figure, Waterhouse mythological presence","outfit":"Waterhouse Pre-Raphaelite nymph patterns painted across body, mythological water nymph motifs, Victorian body art","material":"Waterhouse Pre-Raphaelite paint, blue green nymph water pattern, mythological body art","environment":"enchanted lake, Pre-Raphaelite woodland atmosphere, Waterhouse painting space","lighting":"soft Pre-Raphaelite woodland light, enchanted nymph atmosphere, Waterhouse ethereal glow","style":"Waterhouse nymph body art editorial, Pre-Raphaelite glamour photography","quality":"shot on Hasselblad H6D, soft Pre-Raphaelite grade, portrait 2:3 vertical"},
    "rossetti_dante": {"tag":"Rossetti Dante","subject":"a Rossetti Pre-Raphaelite body art female model","body":"slim elegance model, Pre-Raphaelite romantic figure, Rossetti dreamy presence","outfit":"Dante Gabriel Rossetti Pre-Raphaelite patterns painted across body, medieval romantic motifs, Victorian romantic body art","material":"Rossetti rich Pre-Raphaelite paint, deep red gold medieval pattern, romantic body art","environment":"Pre-Raphaelite medieval studio, romantic Victorian atmosphere, Rossetti painting space","lighting":"soft romantic Pre-Raphaelite light, medieval atmosphere, Rossetti golden glow","style":"Rossetti Pre-Raphaelite body art editorial, romantic Victorian glamour photography","quality":"shot on Leica SL2, rich Pre-Raphaelite grade, portrait 2:3 vertical"},
    "alma_tadema": {"tag":"Alma Tadema","subject":"a Alma-Tadema classical antiquity body art female model","body":"slim elegance model, Greco-Roman goddess figure, classical antiquity divine presence","outfit":"Alma-Tadema classical Roman patterns painted across body, marble and rose petal motifs, Victorian classicism body art","material":"Alma-Tadema precise classical paint, marble white rose antiquity pattern, classical body art","environment":"classical Roman marble baths, antiquity atmosphere, Alma-Tadema painting space","lighting":"warm Mediterranean classical light, marble antiquity atmosphere, Alma-Tadema divine glow","style":"Alma-Tadema classical body art editorial, Victorian classicism glamour photography","quality":"shot on Phase One XF IQ4, warm classical grade, portrait 2:3 vertical"},
    "vigee_lebrun": {"tag":"Vigee Lebrun","subject":"a Vigee Le Brun rococo portrait body art female model","body":"slim elegance model, aristocratic rococo figure, Marie Antoinette era divine presence","outfit":"Vigee Le Brun rococo portrait patterns painted across body, aristocratic French court motifs, rococo body art","material":"Vigee Le Brun soft rococo paint, powder blue pink court pattern, aristocratic body art","environment":"Versailles court interior, rococo aristocratic atmosphere, Vigee Le Brun painting space","lighting":"soft Versailles court light, aristocratic rococo atmosphere, Vigee Le Brun elegant glow","style":"Vigee Le Brun rococo body art editorial, aristocratic French glamour photography","quality":"shot on Hasselblad H6D, soft rococo grade, portrait 2:3 vertical"},

    # 🎨 생존/최근 작가 6개
    "banksy_stencil": {"tag":"Banksy Stencil","subject":"a Banksy street art stencil body art female model","body":"slim elegance model, urban street art figure, Banksy subversive presence","outfit":"Banksy graffiti stencil patterns painted across body, iconic rat and balloon girl motifs, street art body art","material":"Banksy black stencil spray paint, street art graffiti pattern, urban body art","environment":"urban brick wall backdrop, street art atmosphere, Banksy stencil world","lighting":"urban street light, graffiti atmosphere, raw street art glow","style":"Banksy street art body art editorial, urban subversive glamour photography","quality":"shot on Sony A7R V, urban street grade, portrait 2:3 vertical"},
    "keith_haring_body": {"tag":"Keith Haring Body","subject":"a Keith Haring neo-pop body art female model","body":"slim toned model, energetic pop art figure, Keith Haring vibrant presence","outfit":"Keith Haring neo-pop line figure patterns painted across body, dancing figures and radiant baby motifs, NYC pop body art","material":"Keith Haring bold neon line paint, red yellow blue pop figure pattern, neo-pop body art","environment":"NYC subway station, Keith Haring pop art atmosphere, urban neo-pop world","lighting":"bright pop art light, neon figure atmosphere, Keith Haring vibrant glow","style":"Keith Haring neo-pop body art editorial, vibrant pop glamour photography","quality":"shot on Canon EOS R5, vibrant neon pop grade, portrait 2:3 vertical"},
    "yayoi_kusama": {"tag":"Yayoi Kusama","subject":"a Yayoi Kusama infinity dots body art female model","body":"slim elegance model, polka dot infinity figure, Kusama obsessive presence","outfit":"Yayoi Kusama infinity polka dot patterns covering entire body, obsessive repetitive dots body art, infinity room motifs","material":"Kusama repetitive polka dot paint, red black white infinity pattern, obsessive body art","environment":"Kusama infinity mirror room, endless reflection dots atmosphere","lighting":"infinity mirror room light, dot reflection atmosphere, Kusama obsessive glow","style":"Kusama infinity body art editorial, polka dot glamour photography","quality":"shot on Hasselblad H6D, infinity dot grade, portrait 2:3 vertical"},
    "takashi_murakami": {"tag":"Takashi Murakami","subject":"a Takashi Murakami superflat body art female model","body":"slim elegance model, superflat anime figure, Murakami kawaii pop presence","outfit":"Takashi Murakami superflat flower and smiling skull patterns across body, jellyfish eyes motifs, superflat body art","material":"Murakami superflat bright paint, rainbow flower skull pattern, Japanese pop body art","environment":"Murakami superflat exhibition space, bright pop art atmosphere, Japanese contemporary art","lighting":"bright superflat pop art light, Murakami rainbow atmosphere, kawaii pop glow","style":"Murakami superflat body art editorial, Japanese pop glamour photography","quality":"shot on Sony A7R V, superflat rainbow grade, portrait 2:3 vertical"},
    "jean_dubuffet": {"tag":"Jean Dubuffet","subject":"a Jean Dubuffet art brut body art female model","body":"slim elegance model, raw primitive art brut figure, Dubuffet outsider presence","outfit":"Dubuffet art brut raw patterns painted across body, primitive outsider art motifs, raw untrained body art","material":"Dubuffet raw textured paint, primitive rough pattern, art brut body art","environment":"raw outsider art studio, Dubuffet art brut atmosphere, primitive art space","lighting":"raw primitive light, outsider art atmosphere, Dubuffet raw glow","style":"Dubuffet art brut body art editorial, raw outsider glamour photography","quality":"shot on Leica SL2, raw textured grade, portrait 2:3 vertical"},
    "jean_cocteau": {"tag":"Jean Cocteau","subject":"a Jean Cocteau poetic line body art female model","body":"slim elegance model, poetic surrealist figure, Cocteau elegant linear presence","outfit":"Jean Cocteau elegant line drawing patterns painted across body, poetic profile and hand motifs, French surrealist body art","material":"Cocteau elegant line paint, black white poetic line pattern, surrealist body art","environment":"Parisian surrealist salon, Cocteau poetic atmosphere, French art deco space","lighting":"elegant Parisian salon light, poetic surrealist atmosphere, Cocteau linear glow","style":"Cocteau poetic line body art editorial, French surrealist glamour photography","quality":"shot on Hasselblad H6D, elegant Parisian grade, portrait 2:3 vertical"},

    # 🌍 부족/문화 계열 10개
    "bodi_clay": {"tag":"Bodi Clay","subject":"a Ethiopian Bodi tribe clay body art female model","body":"athletic fitness model, powerful toned body, Ethiopian warrior goddess presence","outfit":"Ethiopian Bodi tribe white clay and ochre patterns painted across body, ritual clay body art, East African warrior","material":"white clay and ochre paint, Ethiopian tribal pattern, ritual warrior body art","environment":"Ethiopian Omo Valley landscape, tribal ceremony atmosphere, East African ritual","lighting":"harsh African sun light, tribal ceremony atmosphere, warrior ritual glow","style":"Bodi clay body art editorial, Ethiopian tribal glamour photography","quality":"shot on Phase One XF IQ4, warm African grade, portrait 2:3 vertical"},
    "ndebele_pattern": {"tag":"Ndebele Pattern","subject":"a South African Ndebele geometric body art female model","body":"slim elegance model, graceful figure, Ndebele geometric goddess presence","outfit":"South African Ndebele bold geometric patterns painted across body, angular black white color body art, Ndebele house motifs","material":"Ndebele bold geometric paint, angular black white red yellow pattern, South African body art","environment":"Ndebele painted house backdrop, South African cultural atmosphere","lighting":"bright South African daylight, geometric pattern atmosphere, Ndebele vibrant glow","style":"Ndebele geometric body art editorial, South African cultural glamour photography","quality":"shot on Canon EOS R5, vibrant geometric grade, portrait 2:3 vertical"},
    "tuareg_indigo": {"tag":"Tuareg Indigo","subject":"a Tuareg nomad indigo body art female model","body":"slim elegance model, nomadic desert figure, blue Sahara goddess presence","outfit":"Tuareg deep indigo blue patterns painted across body, Saharan nomad textile motifs, blue people body art","material":"deep indigo blue paint, Tuareg geometric textile pattern, Saharan nomad body art","environment":"Sahara desert landscape, Tuareg nomad atmosphere, endless sand dunes","lighting":"harsh Saharan sun, indigo blue contrast, nomadic desert atmosphere glow","style":"Tuareg indigo body art editorial, Saharan nomad glamour photography","quality":"shot on Hasselblad H6D, deep indigo blue grade, portrait 2:3 vertical"},
    "mursi_lip": {"tag":"Mursi Lip","subject":"a Ethiopian Mursi tribe ceremonial body art female model","body":"athletic fitness model, powerful figure, Mursi warrior queen presence","outfit":"Ethiopian Mursi tribe ochre and white ceremonial patterns painted across body, warrior ritual body art","material":"ochre white clay paint, Mursi ceremonial pattern, Ethiopian warrior body art","environment":"Ethiopian highland landscape, Mursi tribal ceremony atmosphere, Omo Valley ritual","lighting":"dramatic African highland light, tribal ceremony atmosphere, warrior ritual glow","style":"Mursi ceremonial body art editorial, Ethiopian warrior glamour photography","quality":"shot on Phase One XF IQ4, warm ochre grade, portrait 2:3 vertical"},
    "himba_ochre": {"tag":"Himba Ochre","subject":"a Namibian Himba ochre body art female model","body":"slim elegance model, graceful Namibian figure, Himba goddess red ochre presence","outfit":"Namibian Himba red ochre paste covering entire body, otjize clay and fat body art, terracotta red body","material":"Himba red ochre otjize paste, deep terracotta red coverage, Namibian body art","environment":"Namibian desert landscape, Himba village atmosphere, Kunene region","lighting":"warm Namibian desert light, terracotta red body glow, Himba ochre atmosphere","style":"Himba ochre body art editorial, Namibian cultural glamour photography","quality":"shot on Phase One XF IQ4, deep terracotta grade, portrait 2:3 vertical"},
    "surma_body": {"tag":"Surma Body","subject":"a Ethiopian Surma tribe body painting female model","body":"slim toned model, Ethiopian body painter figure, Surma artistic presence","outfit":"Ethiopian Surma tribe colorful body painting patterns, natural pigment geometric designs, East African body art","material":"natural pigment paint, Surma colorful geometric pattern, Ethiopian artistic body art","environment":"Surma village, Omo Valley Ethiopia, body painting ceremony atmosphere","lighting":"soft Ethiopian highland light, artistic ceremony atmosphere, Surma creative glow","style":"Surma body painting editorial, Ethiopian artistic glamour photography","quality":"shot on Canon EOS R5, natural pigment grade, portrait 2:3 vertical"},
    "asaro_mudmen": {"tag":"Asaro Mudmen","subject":"a Papua New Guinea Asaro mud body art female model","body":"powerful athletic model, mud-covered primal figure, ancient mud spirit presence","outfit":"Papua New Guinea Asaro white mud covering entire body, spirit mask motifs, ancient highland body art","material":"white volcanic mud paint, Asaro spirit mask pattern, Papua highland body art","environment":"Papua New Guinea highland jungle, Asaro mud ceremony atmosphere, ancient spirit ritual","lighting":"dramatic jungle light through mist, ancient spirit atmosphere, Asaro mud glow","style":"Asaro mudmen body art editorial, Papua highland glamour photography","quality":"shot on Hasselblad H6D, dramatic misty grade, portrait 2:3 vertical"},
    "kayapo_brasil": {"tag":"Kayapo Brasil","subject":"a Brazilian Kayapo tribe body art female model","body":"athletic fitness model, Amazon warrior figure, Kayapo goddess presence","outfit":"Brazilian Kayapo tribe black genipap and red urucum patterns painted across body, Amazon warrior body art","material":"genipap black urucum red paint, Kayapo Amazon geometric pattern, Brazilian tribal body art","environment":"Amazon rainforest, Kayapo village ceremony, Brazilian indigenous atmosphere","lighting":"Amazon jungle light, tribal ceremony atmosphere, Kayapo warrior glow","style":"Kayapo Amazon body art editorial, Brazilian tribal glamour photography","quality":"shot on Phase One XF IQ4, warm Amazon grade, portrait 2:3 vertical"},
    "nuba_scarification": {"tag":"Nuba Scarification","subject":"a Sudanese Nuba scarification pattern body art female model","body":"athletic fitness model, powerful Nuba figure, ancient Sudan warrior presence","outfit":"Sudanese Nuba scarification and body paint patterns, ritual geometric body art, ancient warrior marks","material":"Nuba scarification pattern paint, ash and oil body art, ancient warrior body art","environment":"Sudanese Nuba hills, ancient warrior ceremony atmosphere, East African ritual","lighting":"dramatic East African light, ancient warrior atmosphere, Nuba ritual glow","style":"Nuba scarification body art editorial, Sudanese warrior glamour photography","quality":"shot on Phase One XF IQ4, dramatic warm grade, portrait 2:3 vertical"},
    "kayan_neck": {"tag":"Kayan Neck","subject":"a Myanmar Kayan tribe ornamental body art female model","body":"slim elegance model, graceful Kayan figure, long-neck goddess ornamental presence","outfit":"Myanmar Kayan tribe brass coil and traditional pattern body art, ornamental tribal costume","material":"Kayan traditional pattern paint, brass coil motif body art, Myanmar tribal","environment":"Myanmar Shan State, Kayan village atmosphere, traditional tribal setting","lighting":"soft Myanmar highland light, traditional tribal atmosphere, Kayan ornamental glow","style":"Kayan ornamental body art editorial, Myanmar tribal glamour photography","quality":"shot on Hasselblad H6D, warm Myanmar grade, portrait 2:3 vertical"},

    # 🔬 과학/자연 계열 10개
    "thermal_scan": {"tag":"Thermal Scan","subject":"a thermal infrared scan body art female model","body":"slim elegance model, heat signature figure, thermal imaging presence","outfit":"thermal infrared camera heat signature patterns painted across body, temperature gradient body art","material":"thermal infrared gradient paint, heat signature blue red yellow pattern, temperature body art","environment":"dark thermal imaging studio, heat signature atmosphere","lighting":"thermal imaging color cast, heat signature glow, infrared atmosphere","style":"thermal scan body art editorial, scientific glamour photography","quality":"shot on Sony A7R V, thermal infrared grade, portrait 2:3 vertical"},
    "bioluminescent_deep": {"tag":"Bioluminescent Deep","subject":"a deep sea bioluminescent body art female model","body":"slim elegance model, deep ocean creature figure, abyssal bioluminescent presence","outfit":"deep sea bioluminescent creature patterns painted across body, abyssal light organ patterns, deep ocean body art","material":"bioluminescent blue green paint, deep sea creature pattern, abyssal body art","environment":"total darkness deep ocean, bioluminescent glow atmosphere, abyssal realm","lighting":"pure bioluminescent glow, total darkness atmosphere, deep sea creature light","style":"deep sea bioluminescent body art editorial, abyssal glamour photography","quality":"shot on Sony A7R V, deep blue bioluminescent grade, portrait 2:3 vertical"},
    "microscope_pollen": {"tag":"Microscope Pollen","subject":"a microscopic pollen body art female model","body":"slim elegance model, delicate microscopic figure, pollen grain intricate presence","outfit":"microscopic pollen grain patterns painted across body, scientific magnification body art, botanical science","material":"pollen grain detailed paint, microscopic botanical pattern, scientific body art","environment":"laboratory microscope atmosphere, scientific beauty, magnified botanical world","lighting":"clean laboratory light, microscopic detail atmosphere, scientific botanical glow","style":"microscope pollen body art editorial, scientific botanical glamour photography","quality":"shot on Hasselblad H6D, clean scientific grade, portrait 2:3 vertical"},
    "xray_body": {"tag":"Xray Body","subject":"a X-ray skeleton body art female model","body":"slim elegance model, X-ray revealed figure, medical science presence","outfit":"X-ray skeleton and bone structure patterns painted across body, medical imaging body art, skeletal overlay","material":"X-ray white grey bone paint, skeletal structure pattern, medical body art","environment":"dark medical studio, X-ray light box atmosphere, clinical science","lighting":"X-ray blue white light, clinical atmosphere, skeletal body art glow","style":"X-ray body art editorial, medical science glamour photography","quality":"shot on Sony A7R V, cool X-ray grade, portrait 2:3 vertical"},
    "mri_scan_body": {"tag":"MRI Scan Body","subject":"a MRI brain scan body art female model","body":"slim elegance model, MRI cross-section figure, neurological science presence","outfit":"MRI brain and body scan cross-section patterns painted across body, neurological imaging body art","material":"MRI scan gradient paint, brain cross-section pattern, neurological body art","environment":"dark MRI imaging studio, neurological science atmosphere, clinical art space","lighting":"MRI scan color gradient light, neurological atmosphere, brain scan glow","style":"MRI scan body art editorial, neurological science glamour photography","quality":"shot on Hasselblad H6D, MRI gradient grade, portrait 2:3 vertical"},
    "neural_map": {"tag":"Neural Map","subject":"a neural network brain map body art female model","body":"slim elegance model, neural network figure, synaptic connection presence","outfit":"neural network synapse connection patterns painted across body, brain mapping body art, neuroscience","material":"neural synapse paint, gold blue synaptic connection pattern, neuroscience body art","environment":"dark neuroscience studio, synaptic glow atmosphere, brain mapping space","lighting":"synaptic electrical glow, neural connection atmosphere, brain map light","style":"neural map body art editorial, neuroscience glamour photography","quality":"shot on Sony A7R V, neural synaptic grade, portrait 2:3 vertical"},
    "geologic_strata": {"tag":"Geologic Strata","subject":"a geological strata body art female model","body":"slim elegance model, earth layer figure, geological time presence","outfit":"geological rock strata layer patterns painted across body, sedimentary layer body art, earth science","material":"geological strata paint, layered earth tone pattern, rock formation body art","environment":"canyon geological formation, layered earth atmosphere, geological time scale","lighting":"warm canyon light, geological atmosphere, earth strata glow","style":"geological strata body art editorial, earth science glamour photography","quality":"shot on Phase One XF IQ4, warm earth tone grade, portrait 2:3 vertical"},
    "crystal_lattice": {"tag":"Crystal Lattice","subject":"a crystal lattice structure body art female model","body":"slim elegance model, geometric crystal figure, molecular structure presence","outfit":"crystal atomic lattice structure patterns painted across body, molecular geometry body art, crystallography","material":"crystal lattice geometric paint, atomic structure pattern, crystallography body art","environment":"clean laboratory studio, crystal structure atmosphere, scientific precision space","lighting":"clean precise laboratory light, crystal structure atmosphere, lattice geometric glow","style":"crystal lattice body art editorial, crystallography glamour photography","quality":"shot on Hasselblad H6D, clean geometric grade, portrait 2:3 vertical"},
    "solar_system_body": {"tag":"Solar System Body","subject":"a solar system planetary body art female model","body":"slim elegance model, cosmic scale figure, solar system goddess presence","outfit":"solar system planets and orbits painted across body, planetary motifs body art, astronomical","material":"solar system gradient paint, planet orbit ring pattern, astronomical body art","environment":"dark space void, solar system scale atmosphere, astronomical realm","lighting":"solar system planet glow, space atmosphere, astronomical body art light","style":"solar system body art editorial, astronomical glamour photography","quality":"shot on Sony A7R V, deep space grade, portrait 2:3 vertical"},
    "dna_double_helix": {"tag":"DNA Double Helix","subject":"a DNA double helix body art female model","body":"slim elegance model, genetic code figure, DNA spiral presence","outfit":"DNA double helix spiral patterns painted across entire body, genetic code body art, molecular biology","material":"DNA helix blue green paint, base pair spiral pattern, molecular biology body art","environment":"dark molecular biology studio, DNA helix glow atmosphere, genetic science space","lighting":"DNA helix color glow, molecular atmosphere, genetic code light","style":"DNA double helix body art editorial, molecular biology glamour photography","quality":"shot on Phase One XF IQ4, molecular science grade, portrait 2:3 vertical"},
}

added = 0
skipped = 0
for name, data in new_presets.items():
    path = PRESETS_DIR / f"{name}.json"
    if path.exists():
        print(f"⏭️  skip: {name}")
        skipped += 1
    else:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"✅ added: {name}")
        added += 1

print(f"\n완료: {added}개 추가, {skipped}개 스킵")
print(f"총 프리셋: 480 → {480 + added}개")
print(f"바디페인팅: 101 → {101 + added}개")
