"""
add_new_presets_v12.py
순수 바디페인팅 프리셋 18개 추가

🎨 명화 계열 (7개)
  rembrandt_chiaroscuro, klimt_silver, matisse_cutout, mondrian_body,
  basquiat_street, warhol_pop, lichtenstein_dot

🌍 문명/부족 계열 (6개)
  huli_wigman, nuba_body, wodaabe_beauty, mehndi_full, mayan_ritual, haida_totem

🔬 과학/자연 계열 (5개)
  aurora_skin, crystal_mineral, tide_pool, magnetic_field, cell_division

총 프리셋: 371 → 389개
바디페인팅 카테고리: 48 → 66개
"""

import json
from pathlib import Path

PRESETS_DIR = Path("presets")
PRESETS_DIR.mkdir(exist_ok=True)

new_presets = {
    "rembrandt_chiaroscuro": {"tag": "Rembrandt Chiaroscuro", "subject": "a dramatic Rembrandt chiaroscuro body painted female model", "body": "soft glamour model, feminine gentle curves, dramatically lit sensual presence", "outfit": "full body Rembrandt chiaroscuro painting, deep shadow and golden light painted across skin, Old Master technique", "material": "oil paint texture, dramatic golden light patches on dark shadow, Rembrandt lighting pattern painted on skin", "environment": "dark baroque studio, single dramatic window light, Old Master painting atmosphere", "lighting": "single source dramatic chiaroscuro light, deep shadow half face, golden skin luminosity", "style": "Rembrandt chiaroscuro body art editorial, Old Master fine art photography", "quality": "shot on Hasselblad H6D, warm golden dark contrast grade, portrait 2:3 vertical"},
    "klimt_silver": {"tag": "Klimt Silver", "subject": "a ethereal Klimt silver body painted female model", "body": "slim elegance model, graceful elongated figure, ethereal silver presence", "outfit": "Gustav Klimt silver and white mosaic pattern painted across entire body, Art Nouveau silver leaf decoration", "material": "silver leaf, white and pearl mosaic pattern, Art Nouveau silver decorative paint", "environment": "cool silver Byzantine interior, moonlit silver backdrop, Klimt-inspired silver world", "lighting": "cool silver ambient glow, moonlight reflective light, ethereal Art Nouveau luminosity", "style": "Gustav Klimt silver body art editorial, Vienna Secession silver aesthetic", "quality": "shot on Hasselblad H6D, cool silver moonlight grade, portrait 2:3 vertical"},
    "matisse_cutout": {"tag": "Matisse Cutout", "subject": "a vibrant Matisse cutout body painted female model", "body": "slim toned model, lean graceful figure, joyful vibrant presence", "outfit": "Henri Matisse paper cutout patterns painted across body, bold primary colors, organic flowing shapes", "material": "bold flat color paint, Matisse blue and red organic shapes, Jazz series cutout pattern", "environment": "bright white studio, colorful Matisse-inspired paper shapes floating, joyful atmosphere", "lighting": "bright even studio light, vibrant color saturation, joyful Matisse palette", "style": "Matisse cutout body art editorial, French modernist fine art photography", "quality": "shot on Canon EOS R5, vibrant saturated Matisse grade, portrait 2:3 vertical"},
    "mondrian_body": {"tag": "Mondrian Body", "subject": "a graphic Mondrian body painted female model", "body": "slim elegance model, clean geometric figure, bold graphic presence", "outfit": "Piet Mondrian primary color grid painted across entire body, bold black lines dividing red blue yellow white blocks", "material": "flat primary color paint, bold black grid lines, De Stijl geometric pattern", "environment": "stark white minimalist studio, Mondrian-inspired geometric backdrop, De Stijl world", "lighting": "clean even bright studio light, flat color enhancement, graphic bold atmosphere", "style": "Mondrian body art editorial, De Stijl geometric fine art photography", "quality": "shot on Hasselblad H6D, clean graphic primary color grade, portrait 2:3 vertical"},
    "basquiat_street": {"tag": "Basquiat Street", "subject": "a raw Basquiat street art body painted female model", "body": "athletic fitness model, powerful toned body, raw energetic urban presence", "outfit": "Jean-Michel Basquiat neo-expressionist graffiti painted across body, crown motifs, raw text, anatomical sketches", "material": "raw acrylic paint, Basquiat crown symbols, scratched text, neo-expressionist marks", "environment": "New York urban street, graffiti walls, raw downtown energy, 1980s NYC atmosphere", "lighting": "harsh urban street light, raw gritty atmosphere, downtown New York energy", "style": "Basquiat street art body editorial, neo-expressionist urban fine art photography", "quality": "shot on Sony A7R V, gritty urban raw grade, portrait 2:3 vertical"},
    "warhol_pop": {"tag": "Warhol Pop", "subject": "a iconic Warhol pop art body painted female model", "body": "slim toned model, graphic pop figure, iconic glamorous presence", "outfit": "Andy Warhol pop art repeated pattern painted across body, Marilyn-style repetition, bold flat colors", "material": "flat screen print paint texture, Warhol signature bold color blocks, pop art repeat pattern", "environment": "Factory-style silver studio, Warhol silver foil walls, pop art icon atmosphere", "lighting": "flat even pop art lighting, bold color saturation, Factory glamour atmosphere", "style": "Warhol pop art body editorial, Factory glamour fine art photography", "quality": "shot on Canon EOS R5, bold pop art saturated grade, portrait 2:3 vertical"},
    "lichtenstein_dot": {"tag": "Lichtenstein Dot", "subject": "a graphic Lichtenstein dot body painted female model", "body": "slim elegance model, graphic comic figure, bold pop art presence", "outfit": "Roy Lichtenstein Ben-Day dot pattern painted across entire body, bold comic book outlines, primary color dots", "material": "Ben-Day dot paint pattern, bold black comic outline, primary color halftone dots", "environment": "comic book pop art environment, bold graphic backdrop, Lichtenstein-inspired world", "lighting": "bright flat comic book lighting, bold dot pattern enhancement, pop art atmosphere", "style": "Lichtenstein dot body art editorial, pop art comic fine art photography", "quality": "shot on Hasselblad H6D, bold comic pop grade, portrait 2:3 vertical"},
    "huli_wigman": {"tag": "Huli Wigman", "subject": "a spectacular Huli wigman body painted female model", "body": "athletic fitness model, powerful toned body, fierce warrior tribal presence", "outfit": "Papua New Guinea Huli warrior face and body painting, yellow ochre face paint, red and black tribal patterns, feather headdress", "material": "natural ochre and clay body paint, Huli traditional pigments, feather and bone accessories", "environment": "Papua New Guinea highland jungle, dramatic tribal ceremony, lush tropical forest", "lighting": "warm tropical ceremonial light, jungle dappled light, dramatic tribal atmosphere", "style": "Huli warrior body art editorial, Papua New Guinea tribal fine art photography", "quality": "shot on Phase One XF IQ4, warm tribal natural grade, portrait 2:3 vertical"},
    "nuba_body": {"tag": "Nuba Body", "subject": "a powerful Nuba body painted female model", "body": "athletic fitness model, strong defined body, powerful African warrior presence", "outfit": "Sudanese Nuba tribe full body painting, ash and ochre geometric body art, intricate scarification patterns", "material": "natural ash, ochre and red earth body paint, Nuba traditional geometric patterns", "environment": "Sudanese savanna landscape, dramatic African sky, ancient Nuba hills", "lighting": "strong African sunlight, warm earth tone atmosphere, dramatic natural light", "style": "Nuba body art editorial, East African tribal fine art photography", "quality": "shot on Phase One XF IQ4, warm African earth grade, portrait 2:3 vertical"},
    "wodaabe_beauty": {"tag": "Wodaabe Beauty", "subject": "a mesmerizing Wodaabe beauty body painted female model", "body": "slim elegance model, graceful elongated figure, exotic striking presence", "outfit": "West African Wodaabe Gerewol festival makeup, white face paint, black lip and eye accents, elaborate headdress", "material": "Wodaabe traditional white clay face paint, ochre body decoration, brass jewelry", "environment": "Sahel desert landscape at dusk, golden sand dunes, Gerewol festival atmosphere", "lighting": "warm Sahel golden hour, desert dusk glow, exotic festival atmosphere", "style": "Wodaabe beauty editorial, West African festival fine art photography", "quality": "shot on Hasselblad H6D, warm desert golden grade, portrait 2:3 vertical"},
    "mehndi_full": {"tag": "Mehndi Full", "subject": "a intricate mehndi full body painted female model", "body": "glamour model, feminine curves, intricately decorated sensual presence", "outfit": "full body Indian mehndi henna art, head to toe intricate floral and geometric patterns, traditional bridal mehndi", "material": "deep burgundy henna paste, intricate mehndi botanical patterns, traditional Indian body art", "environment": "Indian courtyard, marigold flowers, golden fabric backdrop, bridal ceremony atmosphere", "lighting": "warm golden Indian ceremony light, marigold bokeh, intimate celebration glow", "style": "mehndi full body art editorial, Indian bridal fine art photography", "quality": "shot on Hasselblad H6D, warm golden Indian grade, portrait 2:3 vertical"},
    "mayan_ritual": {"tag": "Mayan Ritual", "subject": "a fierce Mayan ritual body painted female model", "body": "athletic fitness model, powerful toned body, ancient divine warrior presence", "outfit": "ancient Mayan ritual body painting, blue Mayan sacred color, serpent and jaguar motifs painted across body", "material": "Mayan blue sacred paint, jaguar spot and serpent patterns, jade and obsidian accessories", "environment": "Mayan pyramid at sunrise, jungle canopy, sacred ritual ceremony, ancient Mesoamerica", "lighting": "dramatic sunrise light over jungle, sacred golden rays, ancient ceremonial atmosphere", "style": "Mayan ritual body art editorial, ancient Mesoamerican fine art photography", "quality": "shot on Sony A7R V, warm ancient jungle grade, portrait 2:3 vertical"},
    "haida_totem": {"tag": "Haida Totem", "subject": "a striking Haida totem body painted female model", "body": "slim elegance model, graceful figure, powerful Northwest Coast indigenous presence", "outfit": "Canadian Haida Nation totem art painted across body, formline design, raven and eagle motifs, black and red traditional patterns", "material": "Haida formline black and red paint, totem animal spirit patterns, Northwest Coast traditional art", "environment": "Pacific Northwest rainforest, ancient cedar totem poles, misty coastal atmosphere", "lighting": "misty Pacific Northwest light, ancient forest atmosphere, dramatic coastal mood", "style": "Haida totem body art editorial, Northwest Coast indigenous fine art photography", "quality": "shot on Phase One XF IQ4, cool misty coastal grade, portrait 2:3 vertical"},
    "aurora_skin": {"tag": "Aurora Skin", "subject": "a ethereal aurora skin body painted female model", "body": "slim elegance model, graceful elongated figure, otherworldly luminous presence", "outfit": "northern lights aurora borealis painted across entire body, flowing green pink purple light waves on skin", "material": "luminescent aurora paint, flowing light wave patterns, bioluminescent pigments", "environment": "arctic night sky, real aurora borealis dancing above, snow-covered landscape", "lighting": "real aurora light reflecting on painted skin, cold arctic night glow, magical luminosity", "style": "aurora skin body art editorial, arctic borealis fine art photography", "quality": "shot on Phase One XF IQ4, ethereal aurora color grade, portrait 2:3 vertical"},
    "crystal_mineral": {"tag": "Crystal Mineral", "subject": "a geological crystal mineral body painted female model", "body": "slim elegance model, sculpted figure, crystalline geological presence", "outfit": "mineral cross-section patterns painted across body, amethyst geode, malachite, lapis lazuli geological art", "material": "mineral pigment paint, crystal formation patterns, geological cross-section colors", "environment": "cave of crystals, massive selenite formations, underground geological wonder", "lighting": "crystal refraction light, prismatic gem-like glow, geological cave atmosphere", "style": "crystal mineral body art editorial, geological fine art photography", "quality": "shot on Hasselblad H6D, jewel-toned mineral grade, portrait 2:3 vertical"},
    "tide_pool": {"tag": "Tide Pool", "subject": "a marine tide pool body painted female model", "body": "slim toned model, graceful aquatic figure, marine ecosystem presence", "outfit": "tide pool marine life painted across body, sea anemones, starfish, sea urchins, coral patterns", "material": "marine organism paint patterns, ocean creature pigments, tide pool ecosystem colors", "environment": "rocky Pacific tide pool, ocean waves crashing nearby, marine paradise", "lighting": "clear ocean light through shallow water, tide pool reflection, marine atmosphere", "style": "tide pool body art editorial, marine biology fine art photography", "quality": "shot on Canon EOS R5, vivid marine ocean grade, portrait 2:3 vertical"},
    "magnetic_field": {"tag": "Magnetic Field", "subject": "a scientific magnetic field body painted female model", "body": "slim elegance model, elongated figure, electromagnetic field-like presence", "outfit": "magnetic field iron filings pattern painted across body, electromagnetic wave lines, physics diagram art", "material": "iron filings pattern paint, magnetic field line pigments, scientific diagram aesthetic", "environment": "dark physics laboratory, electromagnetic equipment, scientific atmosphere", "lighting": "dramatic electromagnetic blue-white light, physics lab atmosphere, scientific glow", "style": "magnetic field body art editorial, scientific fine art photography", "quality": "shot on Sony A7R V, cool electromagnetic blue grade, portrait 2:3 vertical"},
    "cell_division": {"tag": "Cell Division", "subject": "a microscopic cell division body painted female model", "body": "slim elegance model, organic figure, biological microscopic presence", "outfit": "cell division mitosis patterns painted across body, microscope slide art, biological organism patterns", "material": "fluorescent microscopy color paint, cell division pattern pigments, biological art", "environment": "dark scientific void, microscope slide aesthetic, biology laboratory atmosphere", "lighting": "fluorescent microscopy light, biological glow, scientific laboratory atmosphere", "style": "cell division body art editorial, microscopy fine art photography", "quality": "shot on Hasselblad H6D, fluorescent microscopy grade, portrait 2:3 vertical"},
}

added = 0
skipped = 0
for name, data in new_presets.items():
    path = PRESETS_DIR / f"{name}.json"
    if path.exists():
        print(f"⏭️  skip: {name}")
        skipped += 1
    else:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"✅ added: {name}")
        added += 1

print(f"\n완료: {added}개 추가, {skipped}개 스킵")
print(f"총 프리셋: 371 → {371 + added}개")
print(f"바디페인팅 카테고리: 48 → {48 + added}개")