"""
add_new_presets_v14.py
관능적 바디페인팅 35개 추가

💧 액체/흐름 계열 (6개)
  melting_chocolate, liquid_gold_drip, silver_mercury_body,
  ink_pour_body, paint_splash_body, milk_bath_body

🌺 자연 관능 계열 (5개)
  rose_petal_body, orchid_body, vine_wrap_body, lotus_body, poison_flower

🌊 원소 관능 계열 (5개)
  fire_skin, water_ripple_body, frost_crystallize, storm_static_body, smoke_body_art

💋 글래머 관능 계열 (5개)
  lace_body_paint, fishnet_paint, chain_body_paint, jewelry_trompe_loeil, mandala_body

🎨 아트 관능 계열 (5개)
  body_calligraphy, zentangle_body, constellation_body, circuit_erotic, tarot_body

🌙 신비 관능 계열 (4개)
  moon_tattoo_body, rune_body_art, alchemy_body, henna_erotic

🐍 동물 관능 계열 (5개)
  python_scales, jaguar_spots, mermaid_scales, raven_feathers, tiger_stripes_body

총 프리셋: 445 → 480개
바디페인팅 카테고리: 66 → 101개
"""

import json
from pathlib import Path

PRESETS_DIR = Path("presets")
PRESETS_DIR.mkdir(exist_ok=True)

new_presets = {
    "melting_chocolate": {"tag": "Melting Chocolate", "subject": "a sensual melting chocolate body art female model", "body": "hot glamour model, narrow cinched waist, wide round hips, luscious curves perfectly accentuated", "outfit": "melting dark chocolate poured across entire body, flowing chocolate streams following curves, chocolate body art", "material": "liquid dark chocolate paint flowing down skin, warm glossy chocolate texture, sensual drip effect", "environment": "luxury chocolate atelier, dark warm studio, chocolate pour atmosphere", "lighting": "warm amber chocolate glow, dramatic drip shadow, sensual intimate light", "style": "melting chocolate sensual body art editorial, luxury confection glamour photography", "quality": "shot on Hasselblad H6D, warm dark chocolate grade, portrait 2:3 vertical"},
    "liquid_gold_drip": {"tag": "Liquid Gold Drip", "subject": "a opulent liquid gold drip body art female model", "body": "super glamour model, tiny waist, very wide round hips, maximum hourglass dripping gold silhouette", "outfit": "liquid gold paint dripping down entire body, golden streams flowing along curves, gold body art drip", "material": "molten liquid gold paint, ultra-glossy gold drip texture, opulent gold flow effect", "environment": "dark luxury studio, pure black backdrop, gold drip atmosphere", "lighting": "dramatic single spotlight on gold drips, warm golden shimmer, opulent contrast light", "style": "liquid gold drip body art editorial, opulent luxury photography", "quality": "shot on Phase One XF IQ4, dramatic gold drip grade, portrait 2:3 vertical"},
    "silver_mercury_body": {"tag": "Silver Mercury Body", "subject": "a ethereal silver mercury body art female model", "body": "slim elegance model, graceful elongated figure, liquid metallic sensual presence", "outfit": "liquid mercury silver paint flowing across body, mercury pools and streams on skin, metallic body art", "material": "liquid silver mercury paint texture, mirror-like metallic flow, quicksilver body art", "environment": "dark minimalist studio, pure black backdrop, mercury flow atmosphere", "lighting": "dramatic side light on mercury reflections, cold metallic shimmer, ethereal glow", "style": "silver mercury body art editorial, liquid metal glamour photography", "quality": "shot on Hasselblad H6D, cool silver mercury grade, portrait 2:3 vertical"},
    "ink_pour_body": {"tag": "Ink Pour Body", "subject": "a dramatic ink pour body art female model", "body": "slim elegance model, graceful figure, darkly sensual ink-covered presence", "outfit": "black ink poured across body, ink spreading and flowing along curves, ink body art", "material": "liquid black ink paint, spreading ink texture, dramatic ink flow body art", "environment": "minimal white studio, stark white backdrop, ink contrast atmosphere", "lighting": "clean studio light, dramatic ink contrast on pale skin, artistic atmosphere", "style": "ink pour body art editorial, dramatic contrast glamour photography", "quality": "shot on Hasselblad H6D, high contrast ink grade, portrait 2:3 vertical"},
    "paint_splash_body": {"tag": "Paint Splash Body", "subject": "a explosive paint splash body art female model", "body": "athletic fitness model, defined toned body, explosive energetic presence", "outfit": "multicolor paint exploding across body, paint splash impact covering skin, dynamic paint body art", "material": "explosive acrylic paint splash, multicolor impact texture, dynamic paint burst body art", "environment": "art studio splatter environment, colorful paint backdrop, explosive art atmosphere", "lighting": "dramatic studio strobe freeze motion, paint splash captured, explosive color light", "style": "paint splash body art editorial, explosive glamour photography", "quality": "shot on Canon EOS R5, explosive vivid color grade, portrait 2:3 vertical"},
    "milk_bath_body": {"tag": "Milk Bath Body", "subject": "a porcelain milk bath body art female model", "body": "soft glamour model, feminine gentle curves, porcelain delicate sensual presence", "outfit": "white milk paint flowing across body, milky white streams following contours, pure white body art", "material": "liquid white milk paint texture, porcelain white flow, pure white body art", "environment": "minimal dark studio, pure black backdrop, white contrast atmosphere", "lighting": "soft diffused light on white milk streams, porcelain skin glow, pure contrast", "style": "milk bath body art editorial, porcelain beauty glamour photography", "quality": "shot on Hasselblad H6D, pure white contrast grade, portrait 2:3 vertical"},
    "rose_petal_body": {"tag": "Rose Petal Body", "subject": "a romantic rose petal body art female model", "body": "soft glamour model, feminine gentle curves, romantic sensual presence", "outfit": "rose petals painted across entire body, red and pink petal patterns following curves, floral body art", "material": "painted rose petal texture, layered red pink petal pattern, romantic floral body art", "environment": "dark romantic studio, scattered real rose petals on floor, romantic atmosphere", "lighting": "warm romantic candlelight, rose petal bokeh, intimate sensual glow", "style": "rose petal body art editorial, romantic sensual glamour photography", "quality": "shot on Hasselblad H6D, warm romantic rose grade, portrait 2:3 vertical"},
    "orchid_body": {"tag": "Orchid Body", "subject": "a exotic orchid body art female model", "body": "slim elegance model, graceful elongated figure, exotic sensual presence", "outfit": "exotic orchid flower patterns painted across body, purple and white orchid art following curves", "material": "detailed orchid petal paint, exotic purple white flower pattern, sensual botanical body art", "environment": "tropical orchid greenhouse, lush exotic flowers, tropical luxury atmosphere", "lighting": "soft tropical greenhouse light, exotic flower bokeh, sensual botanical glow", "style": "orchid body art editorial, exotic botanical sensual photography", "quality": "shot on Phase One XF IQ4, exotic tropical grade, portrait 2:3 vertical"},
    "vine_wrap_body": {"tag": "Vine Wrap Body", "subject": "a seductive vine wrap body art female model", "body": "slim elegance model, graceful figure, nature-entwined sensual presence", "outfit": "climbing vines and leaves painted spiraling up entire body, botanical wrap body art, nature claiming skin", "material": "detailed vine and leaf paint, botanical spiral pattern, nature wrap body art", "environment": "dark enchanted forest, dappled light through canopy, nature reclaiming atmosphere", "lighting": "dappled forest light, botanical shadow play, nature-entwined sensual glow", "style": "vine wrap body art editorial, botanical sensual glamour photography", "quality": "shot on Hasselblad H6D, lush dark green grade, portrait 2:3 vertical"},
    "lotus_body": {"tag": "Lotus Body", "subject": "a divine lotus body art female model", "body": "slim elegance model, graceful Eastern figure, divine spiritual sensual presence", "outfit": "lotus flower mandala patterns painted across body, pink and gold lotus art emanating from center", "material": "lotus flower petal paint, pink gold spiritual pattern, divine lotus body art", "environment": "serene lotus pond, still water reflection, spiritual atmosphere", "lighting": "soft spiritual golden light, lotus pond reflection, divine sensual glow", "style": "lotus body art editorial, divine Eastern sensual glamour photography", "quality": "shot on Phase One XF IQ4, spiritual pink gold grade, portrait 2:3 vertical"},
    "poison_flower": {"tag": "Poison Flower", "subject": "a dangerous poison flower body art female model", "body": "slim elegance model, deadly beautiful figure, dangerously seductive presence", "outfit": "deadly nightshade and poison flower patterns painted across body, dark botanical danger art", "material": "dark botanical poison flower paint, purple black dangerous petal pattern, deadly beauty body art", "environment": "dark dangerous garden, toxic flowers blooming, dark botanical atmosphere", "lighting": "eerie botanical light, dangerous flower shadow, deadly beautiful glow", "style": "poison flower body art editorial, deadly botanical glamour photography", "quality": "shot on Leica SL2, dark dangerous botanical grade, portrait 2:3 vertical"},
    "fire_skin": {"tag": "Fire Skin", "subject": "a scorching fire skin body art female model", "body": "athletic fitness model, powerful toned body, burning fierce sensual presence", "outfit": "pure flame patterns painted across entire body, fire consuming skin, burning body art", "material": "detailed flame paint, red orange yellow fire pattern, pure fire body art", "environment": "dark void studio, pure black backdrop, fire isolated atmosphere", "lighting": "fire light glow on skin, warm orange red dramatic light, burning sensual atmosphere", "style": "fire skin body art editorial, elemental burning glamour photography", "quality": "shot on Sony A7R V, warm fire grade, portrait 2:3 vertical"},
    "water_ripple_body": {"tag": "Water Ripple Body", "subject": "a fluid water ripple body art female model", "body": "slim elegance model, fluid graceful figure, aquatic sensual presence", "outfit": "water ripple concentric patterns painted across body, aqua blue ripple waves following curves", "material": "aqua blue ripple wave paint, concentric water circle pattern, fluid body art", "environment": "dark still water studio, water surface reflection, aquatic atmosphere", "lighting": "aqua caustic water light, ripple reflection shimmer, fluid sensual glow", "style": "water ripple body art editorial, aquatic glamour photography", "quality": "shot on Hasselblad H6D, aqua blue water grade, portrait 2:3 vertical"},
    "frost_crystallize": {"tag": "Frost Crystallize", "subject": "a ethereal frost crystallize body art female model", "body": "slim elegance model, pale ethereal figure, ice crystal sensual presence", "outfit": "ice crystal frost patterns growing across skin, crystalline frost body art, winter forming on skin", "material": "ice crystal frost paint, crystalline growing pattern, ethereal frost body art", "environment": "frozen winter void, crystal clear ice atmosphere, frost forming", "lighting": "cold ice blue light, crystal refraction shimmer, ethereal frost glow", "style": "frost crystallize body art editorial, winter ethereal glamour photography", "quality": "shot on Phase One XF IQ4, cold crystal blue grade, portrait 2:3 vertical"},
    "storm_static_body": {"tag": "Storm Static Body", "subject": "a electric storm static body art female model", "body": "athletic fitness model, defined toned body, electrified powerful sensual presence", "outfit": "electric static lightning patterns painted across body, storm electricity body art, charged skin", "material": "electric blue white lightning paint, static electricity pattern, storm body art", "environment": "dark charged atmosphere, electric void, storm energy building", "lighting": "electric blue-white light, storm energy atmosphere, charged static glow", "style": "storm static body art editorial, electric power glamour photography", "quality": "shot on Sony A7R V, electric storm grade, portrait 2:3 vertical"},
    "smoke_body_art": {"tag": "Smoke Body Art", "subject": "a mysterious smoke body art female model", "body": "slim elegance model, ethereal figure, smoke-wrapped mysterious sensual presence", "outfit": "smoke swirl patterns painted across body, grey white smoke flowing along curves, smoke body art", "material": "soft grey white smoke paint, swirling smoke pattern, mysterious smoke body art", "environment": "dark mysterious studio, real smoke wisps, mysterious atmosphere", "lighting": "soft diffused light through smoke, mysterious haze glow, sensual smoke atmosphere", "style": "smoke body art editorial, mysterious sensual glamour photography", "quality": "shot on Leica SL2, soft mysterious smoke grade, portrait 2:3 vertical"},
    "lace_body_paint": {"tag": "Lace Body Paint", "subject": "a intricate lace body paint female model", "body": "slim elegance model, graceful figure, delicate yet deeply sensual presence", "outfit": "intricate lace patterns painted directly on skin, trompe l'oeil lace body art, painted lingerie illusion", "material": "detailed white lace paint on skin, intricate lacework pattern, trompe l'oeil body art", "environment": "minimal dark elegant studio, dark backdrop, lace contrast atmosphere", "lighting": "dramatic single key light, intricate lace shadow detail, sensual elegant glow", "style": "lace body paint trompe l'oeil editorial, intricate sensual glamour photography", "quality": "shot on Hasselblad H6D, high detail contrast grade, portrait 2:3 vertical"},
    "fishnet_paint": {"tag": "Fishnet Paint", "subject": "a seductive fishnet paint body art female model", "body": "hot glamour model, narrow cinched waist, wide round hips, dramatic hourglass fishnet silhouette", "outfit": "fishnet mesh patterns painted directly on skin, trompe l'oeil fishnet body art, painted hosiery illusion", "material": "detailed black fishnet paint on skin, mesh grid pattern, trompe l'oeil fishnet body art", "environment": "dark dramatic studio, moody backdrop, fishnet contrast atmosphere", "lighting": "dramatic hard light, fishnet shadow pattern on skin, bold contrast glow", "style": "fishnet body paint editorial, seductive trompe l'oeil glamour photography", "quality": "shot on Leica SL2, bold contrast fishnet grade, portrait 2:3 vertical"},
    "chain_body_paint": {"tag": "Chain Body Paint", "subject": "a powerful chain body paint female model", "body": "athletic fitness model, defined toned body, strong yet sensual chained presence", "outfit": "gold and silver chain link patterns painted across body, trompe l'oeil chain body art, painted jewelry illusion", "material": "detailed gold silver chain paint, interlocking chain link pattern, chain body art", "environment": "dark industrial studio, minimal dark backdrop, chain contrast atmosphere", "lighting": "dramatic hard light on chain details, metallic paint shimmer, powerful contrast", "style": "chain body paint editorial, powerful trompe l'oeil glamour photography", "quality": "shot on Phase One XF IQ4, metallic chain grade, portrait 2:3 vertical"},
    "jewelry_trompe_loeil": {"tag": "Jewelry Trompe Loeil", "subject": "a opulent jewelry trompe l'oeil body art female model", "body": "luxury glamour model, defined waist, wide hips, jewel-adorned sensual presence", "outfit": "elaborate diamond necklace and jewelry painted directly on skin, trompe l'oeil jewel body art, painted luxury", "material": "detailed diamond jewelry paint, sparkling gemstone illusion pattern, luxury trompe l'oeil body art", "environment": "dark luxury studio, velvet backdrop, jewel opulence atmosphere", "lighting": "sparkle light on painted jewels, diamond shimmer glow, opulent contrast", "style": "jewelry trompe l'oeil editorial, opulent luxury glamour photography", "quality": "shot on Hasselblad H6D, diamond sparkle luxury grade, portrait 2:3 vertical"},
    "mandala_body": {"tag": "Mandala Body", "subject": "a divine mandala body art female model", "body": "slim elegance model, centered graceful figure, spiritually sensual presence", "outfit": "intricate mandala patterns radiating from center across entire body, sacred geometry body art", "material": "detailed mandala sacred geometry paint, radiating pattern from navel, spiritual body art", "environment": "meditation space, warm ambient light, sacred geometry atmosphere", "lighting": "warm centered spiritual light, mandala pattern glow, sacred sensual atmosphere", "style": "mandala body art editorial, sacred geometry glamour photography", "quality": "shot on Phase One XF IQ4, warm spiritual grade, portrait 2:3 vertical"},
    "body_calligraphy": {"tag": "Body Calligraphy", "subject": "a poetic body calligraphy art female model", "body": "slim elegance model, graceful figure, written-upon sensual presence", "outfit": "flowing calligraphy script painted across entire body, East Asian ink calligraphy body art", "material": "black ink calligraphy paint, flowing script character pattern, calligraphy body art", "environment": "minimal Japanese studio, rice paper backdrop, ink calligraphy atmosphere", "lighting": "clean side light, calligraphy ink contrast, poetic sensual atmosphere", "style": "body calligraphy art editorial, East Asian ink glamour photography", "quality": "shot on Hasselblad H6D, clean ink contrast grade, portrait 2:3 vertical"},
    "zentangle_body": {"tag": "Zentangle Body", "subject": "a intricate zentangle body art female model", "body": "slim elegance model, detailed figure, meditatively sensual presence", "outfit": "intricate zentangle patterns covering entire body, black and white meditative pattern body art", "material": "detailed zentangle ink pattern, meditative geometric design, full body zentangle art", "environment": "clean minimal white studio, white backdrop, zentangle contrast atmosphere", "lighting": "clean even studio light, zentangle detail enhancement, meditative sensual glow", "style": "zentangle body art editorial, meditative pattern glamour photography", "quality": "shot on Hasselblad H6D, clean black white contrast grade, portrait 2:3 vertical"},
    "constellation_body": {"tag": "Constellation Body", "subject": "a cosmic constellation body art female model", "body": "slim elegance model, ethereal figure, starlit celestial sensual presence", "outfit": "constellation star map painted across body, gold star points connected by fine lines, cosmic body art", "material": "gold star point paint, fine line constellation pattern, celestial body art", "environment": "dark night sky studio, star field backdrop, celestial atmosphere", "lighting": "star glow on gold constellations, dark night atmosphere, celestial sensual light", "style": "constellation body art editorial, celestial glamour photography", "quality": "shot on Phase One XF IQ4, dark celestial gold grade, portrait 2:3 vertical"},
    "circuit_erotic": {"tag": "Circuit Erotic", "subject": "a cybernetic circuit erotic body art female model", "body": "slim elegance model, sleek figure, cybernetically sensual presence", "outfit": "circuit board patterns painted along body curves, electronic circuit erotic body art, tech glamour", "material": "neon green blue circuit paint, PCB trace pattern following curves, cyber body art", "environment": "dark cyberpunk studio, neon circuit backdrop, cyber atmosphere", "lighting": "neon circuit glow, cyberpunk light, electronic sensual atmosphere", "style": "circuit erotic body art editorial, cyberpunk sensual glamour photography", "quality": "shot on Sony A7R V, neon circuit grade, portrait 2:3 vertical"},
    "tarot_body": {"tag": "Tarot Body", "subject": "a mystical tarot body art female model", "body": "slim elegance model, mystical figure, arcane sensual presence", "outfit": "tarot card imagery painted across body, major arcana figures and symbols covering skin, mystical body art", "material": "detailed tarot imagery paint, arcana symbol pattern, mystical body art", "environment": "dark mystical studio, tarot card backdrop, arcane atmosphere", "lighting": "mysterious candlelight, arcane glow, mystical sensual atmosphere", "style": "tarot body art editorial, mystical arcane glamour photography", "quality": "shot on Leica SL2, dark mystical grade, portrait 2:3 vertical"},
    "moon_tattoo_body": {"tag": "Moon Tattoo Body", "subject": "a lunar moon tattoo body art female model", "body": "slim elegance model, graceful figure, lunar mystical sensual presence", "outfit": "moon phases and lunar symbols tattooed across entire body, crescent full moon body art", "material": "detailed moon phase paint, lunar symbol pattern, celestial body art", "environment": "moonlit night outdoor, full moon backdrop, lunar atmosphere", "lighting": "silver moonlight glow, lunar atmosphere, celestial sensual light", "style": "moon tattoo body art editorial, lunar glamour photography", "quality": "shot on Hasselblad H6D, silver moonlight grade, portrait 2:3 vertical"},
    "rune_body_art": {"tag": "Rune Body Art", "subject": "a powerful rune body art female model", "body": "athletic fitness model, powerful toned body, ancient warrior sensual presence", "outfit": "Viking Norse rune symbols painted covering entire body, ancient runic body art, warrior runes", "material": "ancient rune symbol paint, Norse runic pattern, Viking warrior body art", "environment": "dramatic Norse landscape, stormy sky, ancient warrior atmosphere", "lighting": "dramatic storm light, ancient warrior atmosphere, fierce runic glow", "style": "rune body art editorial, ancient Norse glamour photography", "quality": "shot on Phase One XF IQ4, dramatic Norse grade, portrait 2:3 vertical"},
    "alchemy_body": {"tag": "Alchemy Body", "subject": "a mysterious alchemy body art female model", "body": "slim elegance model, mysterious figure, alchemical sensual presence", "outfit": "alchemical symbols and transmutation circles painted across body, philosopher's stone body art", "material": "gold alchemy symbol paint, transmutation circle pattern, mysterious alchemy body art", "environment": "dark alchemist laboratory, mystical equipment, transmutation atmosphere", "lighting": "warm alchemical gold glow, mystical lab light, mysterious sensual atmosphere", "style": "alchemy body art editorial, mystical transmutation glamour photography", "quality": "shot on Leica SL2, warm mystical gold grade, portrait 2:3 vertical"},
    "henna_erotic": {"tag": "Henna Erotic", "subject": "a intricately decorated henna erotic body art female model", "body": "glamour model, feminine sensual curves, intricately adorned seductive presence", "outfit": "elaborate full body henna mehndi art, head to toe intricate patterns emphasizing curves, bridal henna", "material": "deep burgundy henna paste, full body elaborate pattern, sensual curve-following henna art", "environment": "luxury Middle Eastern interior, golden light, ornate backdrop", "lighting": "warm golden Middle Eastern light, intimate sensual glow, ornate atmosphere", "style": "henna erotic body art editorial, sensual Middle Eastern glamour photography", "quality": "shot on Hasselblad H6D, warm golden henna grade, portrait 2:3 vertical"},
    "python_scales": {"tag": "Python Scales", "subject": "a seductive python scales body art female model", "body": "slim elegance model, sinuous graceful figure, serpentine sensual presence", "outfit": "python snake scale patterns painted covering entire body, realistic serpent skin body art", "material": "detailed python scale paint, brown gold serpent pattern, realistic snake skin body art", "environment": "dark jungle atmosphere, exotic serpent realm, dangerous beauty", "lighting": "warm jungle dappled light, serpent scale shimmer, exotic sensual glow", "style": "python scales body art editorial, serpentine glamour photography", "quality": "shot on Phase One XF IQ4, warm exotic serpent grade, portrait 2:3 vertical"},
    "jaguar_spots": {"tag": "Jaguar Spots", "subject": "a fierce jaguar spots body art female model", "body": "athletic fitness model, powerful toned body, wild jaguar sensual presence", "outfit": "jaguar rosette spot patterns painted across entire body, wild cat predator body art", "material": "detailed jaguar rosette paint, gold black spot pattern, wild predator body art", "environment": "dark jungle night, wild cat territory, predator atmosphere", "lighting": "jungle night atmospheric light, jaguar spot pattern glow, wild sensual atmosphere", "style": "jaguar spots body art editorial, wild predator glamour photography", "quality": "shot on Sony A7R V, warm jungle gold grade, portrait 2:3 vertical"},
    "mermaid_scales": {"tag": "Mermaid Scales", "subject": "a enchanting mermaid scales body art female model", "body": "slim elegance model, graceful aquatic figure, enchanting mermaid sensual presence", "outfit": "iridescent mermaid scales painted across lower body and hips, aquatic tail body art, mermaid transformation", "material": "iridescent mermaid scale paint, blue green purple shimmer pattern, aquatic body art", "environment": "underwater coral paradise, crystal blue water, mermaid realm", "lighting": "underwater caustic light, iridescent scale shimmer, enchanting aquatic glow", "style": "mermaid scales body art editorial, aquatic enchanting glamour photography", "quality": "shot on Hasselblad H6D, iridescent aquatic grade, portrait 2:3 vertical"},
    "raven_feathers": {"tag": "Raven Feathers", "subject": "a dark raven feathers body art female model", "body": "slim elegance model, dark mysterious figure, raven dark sensual presence", "outfit": "raven black feather patterns painted across entire body, dark bird body art, corvid feather art", "material": "detailed black raven feather paint, iridescent dark pattern, mysterious bird body art", "environment": "dark mysterious forest, raven atmosphere, dark enchanted wood", "lighting": "dramatic dark forest light, raven feather iridescent shimmer, dark sensual glow", "style": "raven feathers body art editorial, dark mysterious glamour photography", "quality": "shot on Leica SL2, dark iridescent grade, portrait 2:3 vertical"},
    "tiger_stripes_body": {"tag": "Tiger Stripes Body", "subject": "a fierce tiger stripes body art female model", "body": "athletic fitness model, powerful defined body, fierce tiger sensual presence", "outfit": "Bengal tiger stripe patterns painted across entire body, orange black tiger skin body art", "material": "detailed tiger stripe paint, orange black bold pattern, fierce predator body art", "environment": "dramatic jungle, tiger territory, fierce predator atmosphere", "lighting": "dramatic jungle light, tiger stripe shadow play, fierce sensual atmosphere", "style": "tiger stripes body art editorial, fierce predator glamour photography", "quality": "shot on Sony A7R V, dramatic orange black grade, portrait 2:3 vertical"},
}

added = 0
skipped = 0
for name, data in new_presets.items():
    path = PRESETS_DIR / f"{name}.json"
    if path.exists():
        print(f"⏭️  skip: {name}")
        skipped += 1
    else:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"✅ added: {name}")
        added += 1

print(f"\n완료: {added}개 추가, {skipped}개 스킵")
print(f"총 프리셋: 445 → {445 + added}개")
print(f"바디페인팅 카테고리: 66 → {66 + added}개")