"""
add_new_presets_v13.py
신규 프리셋 56개 추가

🍬 팝 & 카와이 추가 (20개)
  gyaru_glam, kogal_style, hime_gyaru, decora_kei, maid_glamour, visual_kei, lolita_gothic,
  disco_barbie, space_babe, bubblegum_pop, rainbow_rave, glitter_bomb, arcade_queen,
  virtual_idol, tokimeki_pop, kpop_idol, korean_ulzzang, kbeauty_goddess, kdrama_heroine, manga_girl

🎌 애니 & 글래머 일본 계열 (15개) ← 신규 카테고리
  zero_suit, battle_bikini, succubus_anime, catgirl_luxe, dark_magical_girl, witch_apprentice,
  fallen_angel_anime, kunoichi_glam, oni_warrior, samurai_bride, dragon_princess,
  android_girl, pilot_suit, neon_android, vampire_seductress

🎌 애니 & 글래머 글로벌 계열 (15개)
  cosmic_warrior_glam, dark_jester_glam, poison_ivy_vines, storm_goddess, dark_sorceress_glam,
  jessica_rabbit_glam, webtoon_heroine, manhwa_villainess, barbarella_retro, vampirella_dark,
  ghost_shell, android_2b, street_fighter_chun, dark_elsa, sailor_moon_dark

✈️ 직업 & 스포츠 추가 (6개)
  ballet_prima, gymnastics_editorial, figure_skater, tennis_champion, archery_goddess, carnival_rio

총 프리셋: 389 → 445개
신규 카테고리: 🎌 애니 & 글래머 (30개)
"""

import json
from pathlib import Path

PRESETS_DIR = Path("presets")
PRESETS_DIR.mkdir(exist_ok=True)

new_presets = {
    "gyaru_glam": {"tag": "Gyaru Glam", "subject": "a fierce Japanese gyaru glamour female model", "body": "hot glamour model, narrow cinched waist, wide round hips, bold provocative presence", "outfit": "ultra-mini gyaru outfit, platform boots, over-the-knee socks, bold crop top, layered accessories", "material": "glossy patent mini skirt, platform vinyl boots, layered chain accessories", "environment": "Shibuya 109 shopping district, neon signs, Japanese street fashion scene", "lighting": "bright Shibuya daylight, colorful street bokeh, vibrant urban atmosphere", "style": "Japanese gyaru street fashion editorial, bold subculture glamour photography", "quality": "shot on Canon EOS R5, vibrant saturated grade, portrait 2:3 vertical"},
    "kogal_style": {"tag": "Kogal Style", "subject": "a playful Japanese kogal glamour female model", "body": "slim toned model, lean figure, playful yet provocative presence", "outfit": "Japanese kogal style, loose socks, ultra-short skirt, open collar blouse, platform shoes glamour reinterpretation", "material": "plaid mini skirt, loose cotton socks, structured blouse, patent platform shoes", "environment": "Tokyo Harajuku street, cherry blossom backdrop, Japanese urban spring", "lighting": "soft spring daylight, sakura bokeh, fresh youthful atmosphere", "style": "Japanese kogal street fashion editorial, playful subculture glamour photography", "quality": "shot on Canon EOS R5, soft warm spring grade, portrait 2:3 vertical"},
    "hime_gyaru": {"tag": "Hime Gyaru", "subject": "a ultra-feminine hime gyaru princess female model", "body": "soft glamour model, feminine gentle curves, princess-like elegant presence", "outfit": "hime gyaru princess outfit, voluminous pink dress, tiara, lace gloves, platform heels, elaborate hair accessories", "material": "heavy pink satin, intricate lace overlay, crystal tiara, satin gloves", "environment": "baroque pink palace interior, rose garden, princess fantasy backdrop", "lighting": "warm soft pink light, rose bokeh, dreamy princess atmosphere", "style": "hime gyaru princess editorial, ultra-feminine Japanese subculture photography", "quality": "shot on Hasselblad H6D, soft pink dream grade, portrait 2:3 vertical"},
    "decora_kei": {"tag": "Decora Kei", "subject": "a maximalist decora kei female model", "body": "slim toned model, energetic playful figure, maximalist colorful presence", "outfit": "decora kei maximalist outfit, dozens of colorful accessories, layered colorful clothing, toy accessories everywhere", "material": "layered colorful cotton, plastic toy accessories, rainbow hair clips, neon fabric layers", "environment": "Harajuku Takeshita Street, colorful kawaii shops, Japanese street fashion paradise", "lighting": "bright colorful street light, rainbow bokeh, maximalist colorful atmosphere", "style": "decora kei maximalist editorial, Harajuku street fashion photography", "quality": "shot on Sony A7R V, maximum saturation rainbow grade, portrait 2:3 vertical"},
    "maid_glamour": {"tag": "Maid Glamour", "subject": "a seductive maid glamour female model", "body": "hot glamour model, narrow cinched waist, wide round hips, playful yet deeply sensual presence", "outfit": "luxury maid costume glamour reinterpretation, corset maid bodice, micro frilly skirt, thigh-high stockings, headdress", "material": "black satin corset, white lace frills, sheer thigh-high stockings, patent heels", "environment": "elegant Victorian mansion interior, dark luxury décor, candlelight atmosphere", "lighting": "warm candlelight glow, intimate mansion atmosphere, dramatic shadows", "style": "luxury maid glamour editorial, seductive cosplay fashion photography", "quality": "shot on Leica SL2, warm dark luxury grade, portrait 2:3 vertical"},
    "visual_kei": {"tag": "Visual Kei", "subject": "a dramatic visual kei rock goddess female model", "body": "slim elegance model, androgynous dramatic figure, intense rock goddess presence", "outfit": "visual kei rock costume, elaborate dramatic makeup, layered dark glamorous outfit, platform boots", "material": "black velvet and leather layers, dramatic lace, studded accessories, extreme platform boots", "environment": "dark concert stage, dramatic colored spotlights, rock performance atmosphere", "lighting": "dramatic colored concert light, intense shadows, rock performance energy", "style": "visual kei rock editorial, Japanese rock glamour photography", "quality": "shot on Sony A7R V, high contrast dramatic grade, portrait 2:3 vertical"},
    "lolita_gothic": {"tag": "Lolita Gothic", "subject": "a dark gothic lolita female model", "body": "slim elegance model, delicate yet darkly powerful figure, gothic princess presence", "outfit": "gothic lolita dress, black and dark purple voluminous skirt, corset bodice, lace parasol, black headpiece", "material": "heavy black satin, intricate dark lace, velvet ribbon details, gothic accessories", "environment": "dark Victorian cemetery, iron gates, dramatic cloudy sky, gothic atmosphere", "lighting": "dramatic overcast light, gothic moody atmosphere, dark romantic ambiance", "style": "gothic lolita dark editorial, Japanese dark fashion photography", "quality": "shot on Leica SL2, dark desaturated gothic grade, portrait 2:3 vertical"},
    "disco_barbie": {"tag": "Disco Barbie", "subject": "a dazzling disco Barbie female model", "body": "VS Angel body, toned flat abs, long legs, maximum hourglass glamorous silhouette", "outfit": "hot pink sequin mini dress, platform disco boots, oversized sunglasses, pink feather boa", "material": "maximum pink iridescent sequins, platform mirror-finish boots, pink feather accessories", "environment": "1970s disco club, mirror ball, colorful strobe lights, dance floor", "lighting": "mirror ball disco light, colorful strobe, pink and gold sparkle atmosphere", "style": "disco Barbie glamour editorial, retro pop luxury photography", "quality": "shot on Canon EOS R5, hot pink vibrant disco grade, portrait 2:3 vertical"},
    "space_babe": {"tag": "Space Babe", "subject": "a futuristic space babe female model", "body": "slim toned model, lean athletic figure, cosmic otherworldly presence", "outfit": "holographic space suit, form-fitting iridescent bodysuit, alien crown, cosmic accessories", "material": "holographic iridescent spacesuit fabric, chrome accessories, cosmic jewelry", "environment": "outer space backdrop, floating stars, nebula colors, zero gravity atmosphere", "lighting": "cosmic nebula light, iridescent holographic shimmer, space atmosphere glow", "style": "space babe futuristic editorial, cosmic glamour photography", "quality": "shot on Sony A7R V, cosmic iridescent grade, portrait 2:3 vertical"},
    "bubblegum_pop": {"tag": "Bubblegum Pop", "subject": "a sweet bubblegum pop female model", "body": "slim elegance model, playful youthful figure, sweet yet provocative presence", "outfit": "bubblegum pink crop top, high-waist mini skirt, platform sneakers, heart accessories", "material": "soft bubblegum pink fabric, shiny vinyl accents, kawaii heart accessories", "environment": "pastel pink bubble dreamscape, bubblegum clouds, candy-colored paradise", "lighting": "soft pink pastel light, bubblegum bokeh, sweet dreamy atmosphere", "style": "bubblegum pop sweet editorial, pastel glamour fashion photography", "quality": "shot on Canon EOS R5, bubblegum pink pastel grade, portrait 2:3 vertical"},
    "rainbow_rave": {"tag": "Rainbow Rave", "subject": "a electric rainbow rave female model", "body": "slim toned model, lean athletic figure, electric rave energy presence", "outfit": "rainbow rave outfit, holographic bikini top, iridescent shorts, LED accessories, platform boots", "material": "UV-reactive rainbow fabric, holographic iridescent vinyl, LED light accessories", "environment": "massive rave festival, rainbow laser beams, UV light, festival crowd", "lighting": "UV rainbow laser light, neon glow, electric festival atmosphere", "style": "rainbow rave festival editorial, electric glamour photography", "quality": "shot on Sony A7R V, UV neon rainbow grade, portrait 2:3 vertical"},
    "glitter_bomb": {"tag": "Glitter Bomb", "subject": "a explosive glitter bomb female model", "body": "hot glamour model, dramatic hourglass figure, explosive glamorous presence", "outfit": "glitter-covered minimal outfit, glitter explosion surrounding body, shimmering everywhere", "material": "full body glitter coverage, iridescent glitter particles, minimal glitter bikini", "environment": "studio glitter explosion, gold and silver glitter raining down", "lighting": "dramatic studio strobe, glitter particle sparkle, explosive shimmer light", "style": "glitter bomb glamour editorial, explosive luxury fashion photography", "quality": "shot on Hasselblad H6D, maximum glitter shimmer grade, portrait 2:3 vertical"},
    "arcade_queen": {"tag": "Arcade Queen", "subject": "a fierce arcade queen female model", "body": "slim toned model, lean athletic figure, gamer goddess presence", "outfit": "retro arcade queen outfit, neon crop top, high-waist shorts, chunky sneakers, joystick accessories", "material": "neon colored athletic fabric, retro arcade print, LED light accents", "environment": "retro arcade game center, neon game screens, pixel art backdrop", "lighting": "neon arcade screen glow, retro pixel atmosphere, colorful game light", "style": "arcade queen retro editorial, gamer glamour photography", "quality": "shot on Sony A7R V, retro neon arcade grade, portrait 2:3 vertical"},
    "virtual_idol": {"tag": "Virtual Idol", "subject": "a holographic virtual idol female model", "body": "slim elegance model, perfect digital figure, ethereal holographic presence", "outfit": "virtual idol holographic costume, translucent digital outfit, floating light particles", "material": "holographic translucent digital fabric, light particle effects, virtual costume", "environment": "digital concert stage, holographic projections, virtual reality concert", "lighting": "holographic digital light, projection mapping glow, virtual concert atmosphere", "style": "virtual idol digital editorial, holographic glamour photography", "quality": "shot on Sony A7R V, holographic digital grade, portrait 2:3 vertical"},
    "tokimeki_pop": {"tag": "Tokimeki Pop", "subject": "a heartwarming tokimeki pop female model", "body": "slim elegance model, delicate youthful figure, heart-fluttering sweet presence", "outfit": "Japanese shojo manga inspired outfit, sailor collar mini dress, ribbons, heart accessories", "material": "soft pastel fabric, shiny ribbon details, heart-shaped accessories, dreamy layers", "environment": "shojo manga dreamscape, floating hearts, pastel sparkles, magical atmosphere", "lighting": "magical sparkle light, floating heart bokeh, dreamy shojo atmosphere", "style": "tokimeki shojo editorial, Japanese romance manga glamour photography", "quality": "shot on Canon EOS R5, dreamy pastel sparkle grade, portrait 2:3 vertical"},
    "kpop_idol": {"tag": "K-pop Idol", "subject": "a radiant K-pop idol female model", "body": "slim toned model, lean athletic build, powerful K-pop star charisma", "outfit": "K-pop idol comeback outfit, sparkly crop top, high-waist mini skirt, thigh-high boots, stage accessories", "material": "crystal-encrusted performance fabric, metallic stage costume, iridescent accessories", "environment": "K-pop music show stage, fan lightstick ocean, dramatic stage production", "lighting": "dramatic K-pop stage lighting, lightstick sea glow, idol spotlight", "style": "K-pop idol stage comeback editorial, Korean pop star glamour photography", "quality": "shot on Canon EOS R5, K-pop vibrant stage grade, portrait 2:3 vertical"},
    "korean_ulzzang": {"tag": "Korean Ulzzang", "subject": "a stunning Korean ulzzang female model", "body": "slim elegance model, delicate Korean beauty figure, fresh yet sensual presence", "outfit": "Korean ulzzang fashion, oversized off-shoulder top, micro mini skirt, sneakers, minimal accessories", "material": "soft cotton oversized top, micro denim skirt, fresh casual luxury", "environment": "Seoul Hongdae street, Korean cafe backdrop, urban Korean aesthetic", "lighting": "soft Korean daylight, cafe bokeh, fresh urban atmosphere", "style": "Korean ulzzang street editorial, Seoul fashion glamour photography", "quality": "shot on Canon EOS R5, fresh Korean beauty grade, portrait 2:3 vertical"},
    "kbeauty_goddess": {"tag": "K-beauty Goddess", "subject": "a flawless K-beauty goddess female model", "body": "slim elegance model, porcelain Korean beauty figure, glass skin radiant presence", "outfit": "Korean beauty goddess look, elegant silk dress, minimal luxury accessories, glass skin focus", "material": "liquid silk dress, minimal gold accessories, glass skin luminosity as texture", "environment": "Korean luxury beauty studio, clean minimal white backdrop, premium atmosphere", "lighting": "perfect beauty dish light, glass skin luminosity, K-beauty editorial light", "style": "K-beauty goddess editorial, Korean luxury beauty photography", "quality": "shot on Hasselblad H6D, glass skin luminosity grade, portrait 2:3 vertical"},
    "kdrama_heroine": {"tag": "K-drama Heroine", "subject": "a captivating K-drama heroine female model", "body": "slim elegance model, graceful Korean figure, emotional yet sensual drama presence", "outfit": "K-drama elegant outfit, sophisticated mini dress, subtle luxury accessories, emotional scene", "material": "flowing silk dress, delicate accessories, Korean drama luxury fashion", "environment": "Han River Seoul night, city lights reflection, romantic Korean drama backdrop", "lighting": "romantic Han River night light, city glow, emotional Korean drama atmosphere", "style": "K-drama heroine editorial, Korean drama glamour photography", "quality": "shot on Leica SL2, romantic Seoul night grade, portrait 2:3 vertical"},
    "manga_girl": {"tag": "Manga Girl", "subject": "a vivid manga girl female model", "body": "slim elegance model, expressive anime-like figure, vivid manga character presence", "outfit": "manga inspired fashion, expressive colorful outfit, exaggerated accessories, manga panel energy", "material": "bold primary color fabric, manga-style graphic accessories, expressive fashion", "environment": "manga panel inspired studio, bold graphic backdrop, comic energy", "lighting": "bold flat manga-inspired lighting, graphic shadow, expressive atmosphere", "style": "manga girl editorial, Japanese comic glamour photography", "quality": "shot on Canon EOS R5, bold manga color grade, portrait 2:3 vertical"},
    "zero_suit": {"tag": "Zero Suit", "subject": "a powerful zero suit female model", "body": "athletic fitness model, defined toned body, powerful athletic glamour presence", "outfit": "sleek zero suit bodysuit, form-fitting full body suit, futuristic athletic glamour", "material": "second-skin metallic bodysuit, ultra-fitted performance fabric, futuristic sheen", "environment": "futuristic space station, sci-fi corridor, dramatic mission atmosphere", "lighting": "dramatic sci-fi corridor light, powerful athletic atmosphere, futuristic glow", "style": "zero suit action glamour editorial, futuristic athlete photography", "quality": "shot on Sony A7R V, cool futuristic grade, portrait 2:3 vertical"},
    "battle_bikini": {"tag": "Battle Bikini", "subject": "a fierce battle bikini warrior female model", "body": "athletic fitness model, powerful toned body, fierce fantasy warrior presence", "outfit": "fantasy battle bikini armor, ornate metal breastplate bikini, armored skirt, warrior weapons", "material": "hammered metal armor pieces, chainmail bikini elements, fantasy warrior accessories", "environment": "epic fantasy battlefield, dramatic sky, ancient ruins, warrior atmosphere", "lighting": "dramatic epic battle light, heroic atmosphere, fantasy golden rays", "style": "battle bikini fantasy editorial, warrior glamour photography", "quality": "shot on Phase One XF IQ4, epic fantasy grade, portrait 2:3 vertical"},
    "succubus_anime": {"tag": "Succubus Anime", "subject": "a seductive succubus anime female model", "body": "super glamour model, tiny waist, very wide round hips, maximum hourglass demonic silhouette", "outfit": "succubus costume, dark wings, demon horns, revealing dark lingerie-inspired outfit, tail", "material": "glossy black latex-look fabric, dark feather wings, ornate demonic accessories", "environment": "dark demonic realm, hellfire backdrop, mysterious dark atmosphere", "lighting": "hellfire glow from below, dramatic demonic atmosphere, dark seductive light", "style": "succubus dark glamour editorial, demonic fantasy photography", "quality": "shot on Leica SL2, dark hellfire grade, portrait 2:3 vertical"},
    "catgirl_luxe": {"tag": "Catgirl Luxe", "subject": "a seductive luxury catgirl female model", "body": "slim elegance model, graceful feline figure, playful yet deeply sensual cat presence", "outfit": "luxury catgirl costume, velvet cat ears, form-fitting catsuit with cutouts, cat tail, paw accessories", "material": "plush velvet cat ears, sheer cutout catsuit, metallic cat accessories", "environment": "luxury boudoir, velvet furnishings, soft mysterious lighting", "lighting": "warm boudoir light, feline shadow play, intimate luxurious atmosphere", "style": "luxury catgirl glamour editorial, feline seduction photography", "quality": "shot on Leica SL2, warm luxury feline grade, portrait 2:3 vertical"},
    "dark_magical_girl": {"tag": "Dark Magical Girl", "subject": "a corrupted dark magical girl female model", "body": "slim elegance model, delicate yet darkly powerful figure, corrupted magical presence", "outfit": "corrupted magical girl costume, torn dark version of magical outfit, dark magic staff, corrupted accessories", "material": "distressed dark magical fabric, torn lace, dark crystal accessories, corrupted wand", "environment": "dark corrupted magical realm, shattered stained glass, dark energy", "lighting": "dark magical energy glow, corrupted purple light, dramatic dark atmosphere", "style": "dark magical girl editorial, corrupted fantasy glamour photography", "quality": "shot on Sony A7R V, dark purple corrupted grade, portrait 2:3 vertical"},
    "witch_apprentice": {"tag": "Witch Apprentice", "subject": "a seductive witch apprentice female model", "body": "slim elegance model, graceful figure, mischievous sensual magic presence", "outfit": "witch apprentice mini robe, short revealing witch dress, thigh-high stockings, pointed hat, broom", "material": "short dark fabric mini robe, sheer thigh-high stockings, velvet witch hat", "environment": "magical witch academy, potion laboratory, mystical candles and books", "lighting": "warm potion glow, mysterious laboratory candle light, magical atmosphere", "style": "witch apprentice glamour editorial, magical seduction photography", "quality": "shot on Leica SL2, warm mystical grade, portrait 2:3 vertical"},
    "fallen_angel_anime": {"tag": "Fallen Angel Anime", "subject": "a dramatic fallen angel anime female model", "body": "slim elegance model, ethereal yet dark figure, fallen divine sensual presence", "outfit": "fallen angel costume, torn dark wings, revealing dark celestial outfit, halo broken", "material": "distressed dark feather wings, torn celestial white fabric darkened, broken halo", "environment": "fallen heaven realm, crumbling celestial architecture, dark clouds", "lighting": "dramatic fallen divine light, dark celestial atmosphere, broken halo glow", "style": "fallen angel dark editorial, corrupted divine glamour photography", "quality": "shot on Hasselblad H6D, dark celestial grade, portrait 2:3 vertical"},
    "kunoichi_glam": {"tag": "Kunoichi Glam", "subject": "a seductive kunoichi glamour female model", "body": "athletic fitness model, defined toned body, deadly yet sensual ninja presence", "outfit": "kunoichi ninja costume glamour, form-fitting dark bodysuit with slit, ninja accessories, katana", "material": "sleek dark ninja fabric with slits, metallic ninja accessories, katana blade", "environment": "feudal Japan rooftop at night, cherry blossoms, moonlit ninja atmosphere", "lighting": "moonlight ninja atmosphere, cherry blossom bokeh, dramatic shadow play", "style": "kunoichi glamour editorial, Japanese ninja seduction photography", "quality": "shot on Leica SL2, cool moonlit Japanese grade, portrait 2:3 vertical"},
    "oni_warrior": {"tag": "Oni Warrior", "subject": "a powerful oni warrior female model", "body": "power fitness model, muscular defined body, fierce Japanese demon warrior presence", "outfit": "oni demon warrior costume, revealing armor with oni horns, traditional Japanese battle elements", "material": "ornate Japanese armor pieces, oni horn headpiece, dramatic warrior accessories", "environment": "Japanese torii gate at storm, dramatic lightning, oni realm atmosphere", "lighting": "dramatic storm lightning, red oni atmospheric light, fierce warrior energy", "style": "oni warrior editorial, Japanese demon glamour photography", "quality": "shot on Sony A7R V, dramatic red storm grade, portrait 2:3 vertical"},
    "samurai_bride": {"tag": "Samurai Bride", "subject": "a fierce samurai bride female model", "body": "slim elegance model, graceful yet powerful figure, deadly beautiful warrior bride", "outfit": "samurai bride costume, white wedding kimono with armor elements, katana, warrior bride accessories", "material": "white silk kimono with dark armor panels, katana weapon, warrior bride accessories", "environment": "Japanese castle courtyard, cherry blossom storm, dramatic warrior wedding", "lighting": "dramatic cherry blossom storm light, warrior bride atmosphere, golden hour", "style": "samurai bride editorial, Japanese warrior wedding glamour photography", "quality": "shot on Hasselblad H6D, dramatic Japanese grade, portrait 2:3 vertical"},
    "dragon_princess": {"tag": "Dragon Princess", "subject": "a magnificent dragon princess female model", "body": "glamour model, powerful curves, divine dragon royalty presence", "outfit": "dragon princess costume, scale-patterned bodysuit, dragon wing elements, golden crown, tail", "material": "iridescent scale-patterned bodysuit, metallic dragon accessories, golden crown", "environment": "dragon realm castle, fire and gold backdrop, mythical dragon atmosphere", "lighting": "dragon fire golden light, mythical realm atmosphere, powerful divine glow", "style": "dragon princess fantasy editorial, mythical glamour photography", "quality": "shot on Phase One XF IQ4, golden dragon fire grade, portrait 2:3 vertical"},
    "android_girl": {"tag": "Android Girl", "subject": "a stunning android girl female model", "body": "slim elegance model, perfect synthetic figure, half-human half-machine sensual presence", "outfit": "android costume, exposed circuit panel on skin, form-fitting tech suit, mechanical elements", "material": "chrome mechanical panel inserts on skin, sleek tech bodysuit, android accessories", "environment": "futuristic laboratory, holographic displays, android creation chamber", "lighting": "cold blue laboratory light, holographic display glow, android atmosphere", "style": "android girl sci-fi editorial, synthetic glamour photography", "quality": "shot on Sony A7R V, cool synthetic blue grade, portrait 2:3 vertical"},
    "pilot_suit": {"tag": "Pilot Suit", "subject": "a dramatic pilot suit female model", "body": "slim toned model, lean athletic figure, intense mission-ready sensual presence", "outfit": "form-fitting sci-fi pilot suit, tight full body suit, helmet under arm, mission patches", "material": "second-skin pilot suit fabric, metallic mission patches, futuristic helmet", "environment": "giant mecha cockpit, holographic battle displays, dramatic mission atmosphere", "lighting": "cockpit holographic display light, dramatic mission atmosphere, intense glow", "style": "pilot suit sci-fi editorial, mecha pilot glamour photography", "quality": "shot on Sony A7R V, cool cockpit holographic grade, portrait 2:3 vertical"},
    "neon_android": {"tag": "Neon Android", "subject": "a electric neon android female model", "body": "slim elegance model, sleek digital figure, neon-lit synthetic presence", "outfit": "neon android costume, glowing circuit bodysuit, neon light veins on skin, holographic elements", "material": "light-up circuit bodysuit, neon glowing skin veins, holographic android accessories", "environment": "cyberpunk neon city, neon rain, dark futuristic urban android realm", "lighting": "neon circuit body glow, cyberpunk neon rain atmosphere, electric light", "style": "neon android cyberpunk editorial, electric synthetic glamour photography", "quality": "shot on Sony A7R V, neon cyberpunk electric grade, portrait 2:3 vertical"},
    "vampire_seductress": {"tag": "Vampire Seductress", "subject": "a irresistible vampire seductress female model", "body": "luxury glamour model, defined waist, wide hips, immortal seductive dark beauty", "outfit": "vampire seductress outfit, dramatic dark gown with deep plunge, blood drop accessories, fangs", "material": "liquid black satin plunging gown, blood crystal accessories, dark velvet cape", "environment": "gothic castle banquet hall, candlelight, blood moon through window", "lighting": "blood moon red candlelight, gothic castle atmosphere, immortal dark glamour", "style": "vampire seductress dark editorial, immortal glamour photography", "quality": "shot on Leica SL2, blood moon dark red grade, portrait 2:3 vertical"},
    "cosmic_warrior_glam": {"tag": "Cosmic Warrior Glam", "subject": "a powerful cosmic warrior glamour female model", "body": "athletic fitness model, powerful toned body, divine cosmic warrior presence", "outfit": "cosmic warrior outfit, star-patterned armor, divine warrior accessories, cosmic weapon", "material": "star-patterned metallic armor, cosmic energy accessories, divine warrior elements", "environment": "cosmic battlefield, stars and galaxies backdrop, divine warrior realm", "lighting": "cosmic star energy light, divine warrior atmosphere, powerful galaxy glow", "style": "cosmic warrior glamour editorial, divine power photography", "quality": "shot on Phase One XF IQ4, cosmic star grade, portrait 2:3 vertical"},
    "dark_jester_glam": {"tag": "Dark Jester Glam", "subject": "a seductive dark jester glamour female model", "body": "hot glamour model, dramatic hourglass figure, chaotic seductive presence", "outfit": "dark jester costume glamour, diamond pattern corset, asymmetric outfit, jester accessories", "material": "black and red diamond pattern corset, asymmetric mini skirt, jester accessories", "environment": "dark carnival, dramatic chaotic atmosphere, dark circus backdrop", "lighting": "chaotic carnival light, dark circus atmosphere, dramatic red and black", "style": "dark jester glamour editorial, chaotic seduction photography", "quality": "shot on Sony A7R V, chaotic carnival grade, portrait 2:3 vertical"},
    "poison_ivy_vines": {"tag": "Poison Ivy Vines", "subject": "a dangerous poison ivy vines female model", "body": "slim elegance model, nature goddess figure, dangerous botanical beauty presence", "outfit": "vine and leaf body coverage, natural plant armor, botanical goddess costume", "material": "living vine and leaf coverage, flower accessories, botanical natural elements", "environment": "overgrown greenhouse paradise, lush dangerous plants, botanical villain realm", "lighting": "green botanical light, dangerous plant atmosphere, lush jungle glow", "style": "botanical villain glamour editorial, dangerous nature photography", "quality": "shot on Phase One XF IQ4, lush green botanical grade, portrait 2:3 vertical"},
    "storm_goddess": {"tag": "Storm Goddess", "subject": "a commanding storm goddess female model", "body": "power fitness model, defined muscular body, commanding weather goddess presence", "outfit": "storm goddess costume, silver and white dramatic outfit, lightning bolt accessories, flowing storm cape", "material": "silver metallic fabric, storm energy accessories, electric lightning bolt elements", "environment": "dramatic storm clouds, lightning everywhere, storm goddess realm above clouds", "lighting": "dramatic lightning flash, storm energy atmosphere, electric goddess power", "style": "storm goddess power editorial, weather divinity photography", "quality": "shot on Sony A7R V, dramatic electric storm grade, portrait 2:3 vertical"},
    "dark_sorceress_glam": {"tag": "Dark Sorceress Glam", "subject": "a powerful dark sorceress glamour female model", "body": "slim elegance model, mysterious powerful figure, dark magical seductive presence", "outfit": "dark sorceress gown, plunging neckline dark robe, magical staff, dark crystal jewelry", "material": "heavy dark velvet plunging gown, dark crystal staff, magical dark accessories", "environment": "dark sorcery tower, magical dark energy, spell casting atmosphere", "lighting": "dark magical energy glow, sorcery atmosphere, mysterious dark light", "style": "dark sorceress glamour editorial, magical dark power photography", "quality": "shot on Leica SL2, dark magical grade, portrait 2:3 vertical"},
    "jessica_rabbit_glam": {"tag": "Jessica Rabbit Glam", "subject": "a classic jessica rabbit inspired glamour female model", "body": "super glamour model, tiny waist, very wide round hips, maximum hourglass classic pin-up silhouette", "outfit": "classic red sequin strapless mini gown, long red gloves, old Hollywood glamour accessories", "material": "red iridescent sequin strapless gown, satin long gloves, old Hollywood jewelry", "environment": "1940s jazz club, spotlight stage, classic Hollywood glamour atmosphere", "lighting": "classic Hollywood spotlight, warm golden jazz club atmosphere, old glamour light", "style": "classic pin-up glamour editorial, old Hollywood fantasy photography", "quality": "shot on Hasselblad H6D, warm classic Hollywood grade, portrait 2:3 vertical"},
    "webtoon_heroine": {"tag": "Webtoon Heroine", "subject": "a stunning Korean webtoon heroine female model", "body": "slim elegance model, Korean webtoon figure, fresh yet powerfully beautiful presence", "outfit": "Korean webtoon heroine outfit, stylish urban fantasy costume, Korean fashion hero elements", "material": "modern Korean fashion fabric, hero costume elements, webtoon inspired accessories", "environment": "Seoul urban fantasy backdrop, webtoon panel energy, Korean urban scene", "lighting": "Korean webtoon dramatic light, urban fantasy atmosphere, hero moment glow", "style": "Korean webtoon heroine editorial, manhwa glamour photography", "quality": "shot on Canon EOS R5, Korean webtoon grade, portrait 2:3 vertical"},
    "manhwa_villainess": {"tag": "Manhwa Villainess", "subject": "a magnificent manhwa villainess female model", "body": "luxury glamour model, defined waist, wide hips, powerful aristocratic villainess presence", "outfit": "Korean manhwa villainess gown, elaborate aristocratic dress, villain accessories, dark crown", "material": "heavy silk aristocratic gown, dark jewel accessories, villainess crown", "environment": "Korean manhwa palace interior, aristocratic villain throne room", "lighting": "aristocratic palace light, villainess power atmosphere, dramatic court lighting", "style": "manhwa villainess editorial, Korean comic aristocrat photography", "quality": "shot on Phase One XF IQ4, aristocratic manhwa grade, portrait 2:3 vertical"},
    "barbarella_retro": {"tag": "Barbarella Retro", "subject": "a classic barbarella retro sci-fi female model", "body": "VS Angel body, toned flat abs, long legs, retro sci-fi glamorous silhouette", "outfit": "1960s retro sci-fi outfit, space age mini dress, go-go boots, retro space accessories", "material": "metallic retro space fabric, patent go-go boots, 60s sci-fi accessories", "environment": "1960s retro sci-fi space set, psychedelic space backdrop, retro future", "lighting": "retro sci-fi psychedelic light, 1960s space atmosphere, groovy colorful glow", "style": "Barbarella retro sci-fi editorial, 1960s space glamour photography", "quality": "shot on Canon EOS R5, retro psychedelic sci-fi grade, portrait 2:3 vertical"},
    "vampirella_dark": {"tag": "Vampirella Dark", "subject": "a iconic vampirella dark glamour female model", "body": "hot glamour model, dramatic hourglass figure, classic horror glamour iconic presence", "outfit": "vampirella inspired costume, iconic minimal red vampire outfit, dramatic cape, vampire accessories", "material": "minimal red satin vampire costume, dramatic black cape, dark crystal accessories", "environment": "gothic horror castle, blood moon, classic horror atmosphere", "lighting": "blood moon dramatic light, gothic horror castle atmosphere, classic horror glamour", "style": "vampirella dark horror editorial, classic horror glamour photography", "quality": "shot on Leica SL2, blood moon red grade, portrait 2:3 vertical"},
    "ghost_shell": {"tag": "Ghost Shell", "subject": "a cybernetic ghost shell female model", "body": "slim toned model, perfect synthetic human figure, cybernetic enhanced sensual presence", "outfit": "cybernetic bodysuit, thermo-optic camouflage suit, cyber enhancements visible on skin", "material": "thermo-optic camouflage suit, chrome cybernetic enhancement panels, synthetic skin", "environment": "cyberpunk futuristic city rooftop, rain, neon city below, cyber atmosphere", "lighting": "cyberpunk neon rain light, cyber enhanced atmosphere, synthetic glow", "style": "ghost shell cyberpunk editorial, cybernetic glamour photography", "quality": "shot on Sony A7R V, cool cyberpunk synthetic grade, portrait 2:3 vertical"},
    "android_2b": {"tag": "Android 2B", "subject": "a elegant android warrior female model", "body": "slim elegance model, perfect android figure, graceful deadly android presence", "outfit": "android warrior dress, elegant black dress with blindfold, white hair, sword, android accessories", "material": "structured black android dress, white synthetic hair, blindfold, sword", "environment": "post-apocalyptic ruins, overgrown city, android warrior realm", "lighting": "dramatic post-apocalyptic light, ruins atmosphere, elegant android glow", "style": "android warrior elegance editorial, synthetic glamour photography", "quality": "shot on Hasselblad H6D, cool post-apocalyptic grade, portrait 2:3 vertical"},
    "street_fighter_chun": {"tag": "Street Fighter Chun", "subject": "a powerful street fighter champion female model", "body": "athletic fitness model, powerful toned legs, defined muscles, fighting champion presence", "outfit": "Chinese fighting champion costume, qipao mini fighting dress, bun hair with ornaments, fighting gloves", "material": "qipao fighting mini dress, ornate hair ornaments, fighting champion accessories", "environment": "street fighter arena, dramatic battle stage, crowd atmosphere", "lighting": "dramatic arena battle light, fighting champion atmosphere, power stance", "style": "fighting champion editorial, martial arts glamour photography", "quality": "shot on Sony A7R V, dramatic fighting grade, portrait 2:3 vertical"},
    "dark_elsa": {"tag": "Dark Elsa", "subject": "a dark ice queen female model", "body": "slim elegance model, ice queen figure, dark frozen power presence", "outfit": "dark ice queen gown, black and dark blue ice dress, dark ice crown, frost accessories", "material": "dark ice crystal gown, black frost accessories, dark frozen crown", "environment": "dark ice palace, black ice formations, frozen dark realm", "lighting": "dark ice blue glow, frozen dark atmosphere, cold power light", "style": "dark ice queen editorial, frozen dark glamour photography", "quality": "shot on Phase One XF IQ4, dark ice blue grade, portrait 2:3 vertical"},
    "sailor_moon_dark": {"tag": "Sailor Moon Dark", "subject": "a corrupted dark sailor guardian female model", "body": "slim elegance model, corrupted magical figure, dark sailor power presence", "outfit": "corrupted sailor guardian costume, dark version of sailor suit, torn elements, dark tiara", "material": "dark corrupted sailor suit fabric, torn magical elements, dark crystal tiara", "environment": "corrupted moon kingdom, dark energy, fallen magical realm", "lighting": "dark corrupted magical energy, fallen moon atmosphere, dark sailor power", "style": "dark sailor guardian editorial, corrupted magical glamour photography", "quality": "shot on Sony A7R V, dark corrupted magical grade, portrait 2:3 vertical"},
    "ballet_prima": {"tag": "Ballet Prima", "subject": "a breathtaking ballet prima donna female model", "body": "ballerina physique, slender elongated figure, graceful ethereal dancer presence", "outfit": "prima ballerina white tutu, classical ballet costume, pointe shoes, tiara, pure elegance", "material": "pristine white tulle tutu, satin pointe shoes, crystal tiara, classical ballet fabric", "environment": "grand opera house stage, spotlit stage, classical ballet performance", "lighting": "single dramatic spotlight, classical stage lighting, ethereal dancer glow", "style": "prima ballerina editorial, classical dance luxury photography", "quality": "shot on Hasselblad H6D, clean classical stage grade, portrait 2:3 vertical"},
    "gymnastics_editorial": {"tag": "Gymnastics Editorial", "subject": "a elite gymnastics editorial female model", "body": "bikini competition model, extremely defined muscles, flexible powerful physique", "outfit": "elite gymnastics leotard, crystal-encrusted competition leotard, athletic glamour", "material": "crystal-encrusted competition leotard, athletic performance fabric, gymnastics glamour", "environment": "elite gymnastics arena, competition floor, dramatic arena lighting", "lighting": "dramatic competition arena light, athletic power atmosphere, performance spotlight", "style": "elite gymnastics editorial, athletic competition glamour photography", "quality": "shot on Canon EOS R5, dramatic athletic grade, portrait 2:3 vertical"},
    "figure_skater": {"tag": "Figure Skater", "subject": "a elegant figure skating female model", "body": "ballerina physique, slender elegant figure, graceful athletic ice presence", "outfit": "figure skating costume, crystal-encrusted skating dress, ice skates, flowing elements", "material": "crystal competition skating dress, white ice skates, flowing fabric elements", "environment": "Olympic ice rink, dramatic ice arena, skating performance atmosphere", "lighting": "dramatic ice arena spotlight, ice reflection light, elegant performance atmosphere", "style": "figure skating elegance editorial, ice glamour photography", "quality": "shot on Hasselblad H6D, cool ice arena grade, portrait 2:3 vertical"},
    "tennis_champion": {"tag": "Tennis Champion", "subject": "a powerful tennis champion female model", "body": "athletic fitness model, defined toned body, confident champion athletic presence", "outfit": "tennis champion white dress, short tennis dress, visor, tennis racket, champion attitude", "material": "crisp white performance tennis dress, athletic fabric, champion accessories", "environment": "Wimbledon centre court, grass court, championship atmosphere", "lighting": "bright Wimbledon daylight, championship atmosphere, champion power", "style": "tennis champion editorial, Wimbledon glamour photography", "quality": "shot on Canon EOS R5, bright Wimbledon grade, portrait 2:3 vertical"},
    "archery_goddess": {"tag": "Archery Goddess", "subject": "a fierce archery goddess female model", "body": "slim toned model, lean athletic figure, focused warrior goddess presence", "outfit": "archery goddess costume, form-fitting hunting outfit, bow and arrow, forest warrior accessories", "material": "fitted leather hunting outfit, bow and arrow prop, nature warrior accessories", "environment": "ancient forest, dramatic shaft of light, archery goddess realm", "lighting": "dramatic forest light shaft, goddess power atmosphere, ancient warrior glow", "style": "archery goddess editorial, warrior huntress photography", "quality": "shot on Phase One XF IQ4, dramatic forest grade, portrait 2:3 vertical"},
    "carnival_rio": {"tag": "Carnival Rio", "subject": "a spectacular carnival Rio female model", "body": "hot glamour model, narrow cinched waist, wide round hips, Brazilian carnival goddess presence", "outfit": "Rio carnival samba costume, elaborate feather headdress, sequin bikini, feather accessories", "material": "massive feather headdress, crystal sequin bikini, colorful feather accessories", "environment": "Rio Carnival Sambadrome, massive parade float, carnival crowd", "lighting": "dramatic carnival parade light, colorful festival atmosphere, sambadrome spotlight", "style": "Rio carnival glamour editorial, Brazilian festival photography", "quality": "shot on Canon EOS R5, vibrant carnival grade, portrait 2:3 vertical"},
}

added = 0
skipped = 0
for name, data in new_presets.items():
    path = PRESETS_DIR / f"{name}.json"
    if path.exists():
        print(f"⏭️  skip: {name}")
        skipped += 1
    else:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"✅ added: {name}")
        added += 1

print(f"\n완료: {added}개 추가, {skipped}개 스킵")
print(f"총 프리셋: 389 → {389 + added}개")
print("""
신규 카테고리: 🎌 애니 & 글래머 (30개)
  - 일본 계열 15개
  - 글로벌 계열 15개
""")