"""
add_new_presets_v16.py
관능 & 글래머 보강 50개

💋 신규 카테고리: 관능 & 에로틱 글래머 (25개)
  란제리: lingerie_goddess, silk_robe_only, corset_queen, bodycon_power, sheer_negligee, boudoir_noir
  웻룩:   wet_silk_gown, oil_goddess_gold, pool_wet_glam, rain_soaked_dress, sweat_glam
  미니멀: micro_dress_only, barely_covered, deep_plunge_gown, backless_extreme, one_strap_gown
  파워섹시: latex_queen, pvc_goddess, leather_mistress, crystal_mesh_goddess, chain_mail_glam
  핀업:   pinup_classic, vargas_girl, bombshell_retro, bunny_suit, playboy_glam

💫 글래머 & 럭셔리 보강 (8개)
  plunge_gown, slit_maxi, cutout_bodysuit, sheer_overlay,
  jeweled_bikini_top, golden_drape_goddess, crystal_gown, feather_trim_mini

🏖️ 비치 & 리조트 보강 (6개)
  thong_bikini, micro_bikini_gold, sarong_goddess,
  wet_bikini_pool, topless_editorial, nude_beach_art

⚔️ 파워 & 엣지 보강 (5개)
  dominatrix_glam, bondage_fashion, strappy_harness, mesh_bodysuit, latex_catsuit

🔮 판타지 & 다크 보강 (5개)
  dark_succubus, vampire_seduction, witch_sensual, dark_fairy_erotic, shadow_seductress

총 프리셋: 516 → 566개
"""

import json
from pathlib import Path

PRESETS_DIR = Path("presets")
PRESETS_DIR.mkdir(exist_ok=True)

new_presets = {
    "lingerie_goddess": {"tag":"Lingerie Goddess","subject":"a stunning lingerie goddess female model","body":"VS Angel body, toned flat abs, long legs, maximum hourglass glamorous silhouette","outfit":"luxury full lingerie set, intricate lace bralette and high-cut panty, garter belt, silk stockings, Victoria's Secret goddess","material":"delicate lace lingerie, silk stockings, satin garter belt, sheer overlay","environment":"luxury boudoir suite, silk drapes, candlelight atmosphere","lighting":"warm intimate boudoir light, soft shadow play, sensual glow","style":"Victoria's Secret lingerie editorial, luxury intimate glamour photography","quality":"shot on Hasselblad H6D, warm intimate grade, portrait 2:3 vertical"},
    "silk_robe_only": {"tag":"Silk Robe Only","subject":"a seductive silk robe female model","body":"luxury glamour model, defined waist, wide hips, carelessly draped sensual presence","outfit":"luxurious silk robe barely draped open, minimal coverage, falling off shoulder, sensual negligee beneath","material":"liquid silk robe, cascading off body, barely held closed","environment":"luxury penthouse morning, floor to ceiling windows, city view","lighting":"soft morning light through silk, warm golden dawn, intimate atmosphere","style":"luxury morning editorial, intimate silk glamour photography","quality":"shot on Leica SL2, warm silk morning grade, portrait 2:3 vertical"},
    "corset_queen": {"tag":"Corset Queen","subject":"a powerful corset queen female model","body":"super glamour model, tiny waist, very wide round hips, maximum hourglass corset silhouette","outfit":"extreme waist-cinching corset, deep plunging neckline, dramatic hourglass shape, lace-up back","material":"rigid structured brocade corset, lace trim, bone structure visible, dramatic shape","environment":"Victorian dark boudoir, ornate mirror, dramatic drapes","lighting":"dramatic side light, corset shadow definition, powerful intimate atmosphere","style":"extreme corset editorial, power hourglass glamour photography","quality":"shot on Phase One XF IQ4, dramatic dark grade, portrait 2:3 vertical"},
    "bodycon_power": {"tag":"Bodycon Power","subject":"a commanding bodycon power female model","body":"hot glamour model, narrow cinched waist, wide round hips, every curve emphasized bodycon silhouette","outfit":"ultra-tight bodycon mini dress, second-skin fit, every curve perfectly outlined","material":"liquid stretch fabric, second-skin bodycon, ultra-fitted all over","environment":"luxury rooftop party, night city lights, glamour event","lighting":"dramatic event lighting, bodycon curve emphasis, night glamour glow","style":"bodycon power editorial, curve emphasis glamour photography","quality":"shot on Canon EOS R5, vibrant night grade, portrait 2:3 vertical"},
    "sheer_negligee": {"tag":"Sheer Negligee","subject":"a ethereal sheer negligee female model","body":"slim elegance model, delicate feminine curves, sheer-draped sensual presence","outfit":"floor-length sheer chiffon negligee, completely see-through, delicate lace trim, flowing","material":"ultra-sheer chiffon, transparent fabric, delicate lace edge, flowing layers","environment":"bedroom at dawn, soft natural light, ethereal morning atmosphere","lighting":"soft dawn natural light, sheer fabric glow, ethereal intimate atmosphere","style":"sheer negligee editorial, ethereal intimate glamour photography","quality":"shot on Hasselblad H6D, soft ethereal grade, portrait 2:3 vertical"},
    "boudoir_noir": {"tag":"Boudoir Noir","subject":"a mysterious boudoir noir female model","body":"luxury glamour model, defined curves, dark mysterious sensual presence","outfit":"dark boudoir lingerie set, black lace teddy, garter and stockings, noir atmosphere","material":"black lace teddy bodysuit, dark silk stockings, noir accessories","environment":"dark noir boudoir, low candlelight, mysterious shadow play","lighting":"dramatic low candlelight, noir shadow, mysterious intimate atmosphere","style":"boudoir noir editorial, dark intimate glamour photography","quality":"shot on Leica SL2, dark noir grade, portrait 2:3 vertical"},
    "wet_silk_gown": {"tag":"Wet Silk Gown","subject":"a dripping wet silk gown female model","body":"slim elegance model, every curve revealed through wet fabric, soaked glamour presence","outfit":"drenched silk evening gown completely soaked, clinging to every curve, wet fabric transparency","material":"soaked silk clinging fabric, wet transparency effect, water-drenched glamour","environment":"rain-soaked outdoor, dramatic wet atmosphere, puddle reflections","lighting":"dramatic wet light, water reflection, soaked fabric glow","style":"wet silk editorial, rain-soaked glamour photography","quality":"shot on Sony A7R V, dramatic wet grade, portrait 2:3 vertical"},
    "oil_goddess_gold": {"tag":"Oil Goddess Gold","subject":"a gleaming oil goddess gold female model","body":"athletic fitness model, every muscle and curve highlighted by oil, golden oiled presence","outfit":"minimal golden micro bikini, entire body covered in golden body oil, glistening everywhere","material":"golden body oil covering all skin, micro gold bikini, maximum golden gloss","environment":"dark studio, pure black backdrop, golden oil spotlight","lighting":"dramatic single spotlight on golden oiled skin, maximum shimmer, oil gleam","style":"golden oil body editorial, maximum gloss glamour photography","quality":"shot on Phase One XF IQ4, maximum golden oil grade, portrait 2:3 vertical"},
    "pool_wet_glam": {"tag":"Pool Wet Glam","subject":"a dripping pool wet glamour female model","body":"VS Angel body, toned flat abs, long legs, pool-soaked glamorous silhouette","outfit":"soaking wet white bikini clinging to body, just emerged from pool, dripping wet","material":"wet white bikini completely soaked, water droplets everywhere, pool wet effect","environment":"luxury infinity pool, tropical resort, sparkling water","lighting":"bright tropical pool light, water sparkle, wet skin shimmer","style":"pool wet glamour editorial, resort wet photography","quality":"shot on Canon EOS R5, bright tropical wet grade, portrait 2:3 vertical"},
    "rain_soaked_dress": {"tag":"Rain Soaked Dress","subject":"a rain soaked dress glamour female model","body":"slim elegance model, soaked dress clinging figure, rain-drenched sensual presence","outfit":"completely soaked white dress, rain-drenched fabric clinging to body, transparent when wet","material":"rain-soaked white fabric, wet transparency, clinging drenched dress","environment":"dramatic rainstorm, city street, rain puddles","lighting":"dramatic rain light, street lamp reflection on wet dress, rain atmosphere","style":"rain soaked dress editorial, wet glamour photography","quality":"shot on Sony A7R V, dramatic rain grade, portrait 2:3 vertical"},
    "sweat_glam": {"tag":"Sweat Glam","subject":"a gleaming sweat glamour athletic female model","body":"bikini competition model, extremely defined muscles, sweat-glistening athletic presence","outfit":"minimal athletic sports bra and shorts, entire body glistening with sweat, post-workout power","material":"minimal athletic wear soaked in sweat, glistening skin everywhere","environment":"dramatic gym, dark athletic studio, power atmosphere","lighting":"dramatic gym spotlight, sweat glisten emphasis, athletic power light","style":"sweat glamour editorial, athletic power photography","quality":"shot on Sony A7R V, dramatic athletic grade, portrait 2:3 vertical"},
    "micro_dress_only": {"tag":"Micro Dress Only","subject":"a ultra micro dress female model","body":"hot glamour model, narrow cinched waist, wide round hips, extreme micro dress hourglass","outfit":"ultra micro mini dress, barely covers hips, extreme short hemline, maximum leg exposure","material":"stretched metallic micro dress, ultra short barely-there coverage","environment":"luxury nightclub VIP, dramatic nightlife atmosphere","lighting":"dramatic nightclub light, micro dress shimmer, night glamour","style":"ultra micro dress editorial, extreme short glamour photography","quality":"shot on Canon EOS R5, vibrant nightclub grade, portrait 2:3 vertical"},
    "barely_covered": {"tag":"Barely Covered","subject":"a barely covered glamour female model","body":"slim elegance model, strategically barely covered curves, maximum exposure presence","outfit":"strategically placed minimal coverage, barely covered by fabric strips, artistic minimal","material":"minimal fabric strips barely covering, strategic placement only","environment":"dark artistic studio, minimal black backdrop, art photography","lighting":"dramatic artistic light, strategic shadow coverage, art photography","style":"barely covered artistic editorial, strategic minimal glamour photography","quality":"shot on Hasselblad H6D, dramatic artistic grade, portrait 2:3 vertical"},
    "deep_plunge_gown": {"tag":"Deep Plunge Gown","subject":"a extreme deep plunge gown female model","body":"luxury glamour model, defined waist, wide hips, dramatic plunge silhouette","outfit":"extreme deep plunge neckline gown to navel, dramatic V-cut, barely held by thin straps","material":"liquid satin extreme plunge gown, thin strap support, deep V to navel","environment":"red carpet premiere, dramatic event, luxury atmosphere","lighting":"red carpet dramatic light, plunge shadow, luxury event glow","style":"extreme plunge gown editorial, red carpet glamour photography","quality":"shot on Phase One XF IQ4, dramatic red carpet grade, portrait 2:3 vertical"},
    "backless_extreme": {"tag":"Backless Extreme","subject":"a extreme backless gown female model","body":"slim elegance model, graceful back fully exposed, extreme backless sensual presence","outfit":"extreme backless gown, entire back fully exposed to tailbone, minimal front coverage","material":"liquid backless gown, open back to tailbone, thin side straps only","environment":"luxury gala event, grand ballroom, dramatic architecture","lighting":"dramatic gala light, bare back shadow play, luxury atmosphere","style":"extreme backless editorial, bare back glamour photography","quality":"shot on Hasselblad H6D, elegant dramatic grade, portrait 2:3 vertical"},
    "one_strap_gown": {"tag":"One Strap Gown","subject":"a asymmetric one strap gown female model","body":"luxury glamour model, one shoulder bared, dramatic asymmetric sensual presence","outfit":"one shoulder asymmetric gown, single strap, one side fully bared, dramatic silhouette","material":"liquid satin one shoulder gown, dramatic asymmetric drape, bare shoulder side","environment":"luxury gala, grand venue, dramatic setting","lighting":"dramatic one-sided light, asymmetric shadow, elegant atmosphere","style":"one strap gown editorial, asymmetric glamour photography","quality":"shot on Leica SL2, elegant dramatic grade, portrait 2:3 vertical"},
    "latex_queen": {"tag":"Latex Queen","subject":"a powerful latex queen female model","body":"hot glamour model, narrow cinched waist, wide round hips, maximum latex hourglass silhouette","outfit":"full body latex catsuit, second-skin latex, every curve perfectly defined, latex queen","material":"glossy latex second-skin, high shine latex, perfectly form-fitting","environment":"dark power studio, dramatic black backdrop, latex power atmosphere","lighting":"hard dramatic studio light, latex high-gloss reflection, power atmosphere","style":"latex queen editorial, power glamour photography","quality":"shot on Phase One XF IQ4, high gloss latex grade, portrait 2:3 vertical"},
    "pvc_goddess": {"tag":"PVC Goddess","subject":"a futuristic PVC goddess female model","body":"slim elegance model, sleek curves in PVC, futuristic sensual presence","outfit":"futuristic clear PVC outfit, transparent vinyl, futuristic design with strategic coverage","material":"clear transparent PVC vinyl, futuristic design, see-through panels","environment":"futuristic nightclub, neon lights, cyber atmosphere","lighting":"neon cyberpunk light through PVC, transparent effect, futuristic glow","style":"PVC goddess editorial, futuristic glamour photography","quality":"shot on Sony A7R V, neon cyberpunk grade, portrait 2:3 vertical"},
    "leather_mistress": {"tag":"Leather Mistress","subject":"a commanding leather mistress female model","body":"athletic fitness model, powerful defined body, dominant leather power presence","outfit":"sleek leather bodysuit, leather harness details, commanding power outfit","material":"high-shine patent leather, structured harness, dominant leather accessories","environment":"dark power studio, dramatic leather atmosphere","lighting":"dramatic hard light on leather shine, power atmosphere, commanding glow","style":"leather mistress editorial, power dominance glamour photography","quality":"shot on Leica SL2, high contrast leather grade, portrait 2:3 vertical"},
    "crystal_mesh_goddess": {"tag":"Crystal Mesh Goddess","subject":"a dazzling crystal mesh goddess female model","body":"VS Angel body, toned flat abs, long legs, crystal-encrusted mesh silhouette","outfit":"crystal-encrusted mesh bodysuit, thousands of crystals on sheer mesh, maximum sparkle","material":"crystal-covered mesh fabric, diamond encrusted sheer, maximum sparkle coverage","environment":"luxury fashion show, dramatic runway, crystal light","lighting":"crystal sparkle explosion, diamond refraction light, maximum sparkle atmosphere","style":"crystal mesh editorial, maximum sparkle glamour photography","quality":"shot on Phase One XF IQ4, crystal sparkle grade, portrait 2:3 vertical"},
    "chain_mail_glam": {"tag":"Chain Mail Glam","subject":"a powerful chain mail glamour female model","body":"athletic fitness model, powerful toned body, metallic chain warrior goddess presence","outfit":"chainmail mini dress, metal ring armor fashion, warrior goddess glamour","material":"interlocking metal ring chainmail, warrior fashion fabric, metal link dress","environment":"dramatic dark studio, stone castle backdrop, warrior atmosphere","lighting":"dramatic metal light, chainmail reflection, warrior goddess atmosphere","style":"chain mail editorial, warrior glamour photography","quality":"shot on Phase One XF IQ4, cool metallic grade, portrait 2:3 vertical"},
    "pinup_classic": {"tag":"Pinup Classic","subject":"a classic 1950s pin-up glamour female model","body":"soft glamour model, classic hourglass figure, 1950s bombshell pin-up presence","outfit":"classic 1950s pin-up outfit, high-waist shorts or skirt, tied blouse, retro glamour","material":"cotton high-waist shorts, tied gingham blouse, vintage accessories","environment":"1950s Americana setting, vintage car, retro diner","lighting":"warm 1950s golden light, retro photography look, classic pin-up glow","style":"classic pin-up editorial, 1950s retro glamour photography","quality":"shot on Canon EOS R5, warm vintage grade, portrait 2:3 vertical"},
    "vargas_girl": {"tag":"Vargas Girl","subject":"a Alberto Vargas pin-up illustration style female model","body":"slim elegance model, Vargas elongated pin-up figure, dreamy illustration-like presence","outfit":"Vargas-style minimal elegant pin-up outfit, flowing chiffon, elegant lingerie-adjacent","material":"flowing chiffon, dreamy fabric, Vargas illustration aesthetic","environment":"dreamy illustrated backdrop, vintage Esquire illustration style","lighting":"soft dreamy illustration light, Vargas pastel atmosphere, dreamy glow","style":"Vargas girl pin-up editorial, illustration-style glamour photography","quality":"shot on Hasselblad H6D, soft dreamy grade, portrait 2:3 vertical"},
    "bombshell_retro": {"tag":"Bombshell Retro","subject":"a retro bombshell glamour female model","body":"super glamour model, tiny waist, very wide round hips, maximum hourglass classic bombshell","outfit":"classic bombshell outfit, tight sweater or cocktail dress, maximum retro sex appeal","material":"tight angora sweater or satin cocktail dress, retro bombshell styling","environment":"1950s Hollywood glamour, studio lighting, retro Hollywood backdrop","lighting":"classic Hollywood golden studio light, bombshell glamour, retro glow","style":"retro bombshell editorial, classic Hollywood glamour photography","quality":"shot on Hasselblad H6D, warm Hollywood grade, portrait 2:3 vertical"},
    "bunny_suit": {"tag":"Bunny Suit","subject":"a glamorous bunny suit female model","body":"VS Angel body, toned flat abs, long legs, bunny suit perfect hourglass","outfit":"classic bunny suit, strapless bodysuit with bunny ears, cuffs, collar and tail, fishnet stockings","material":"satin strapless bunny bodysuit, fishnet stockings, bunny accessories","environment":"luxury club setting, glamorous night atmosphere","lighting":"warm club spotlight, bunny glamour glow, luxury atmosphere","style":"bunny suit glamour editorial, classic club photography","quality":"shot on Canon EOS R5, warm club grade, portrait 2:3 vertical"},
    "playboy_glam": {"tag":"Playboy Glam","subject":"a iconic playboy glamour female model","body":"hot glamour model, dramatic hourglass figure, iconic playboy glamorous presence","outfit":"iconic playboy-inspired glamour, satin sheets, minimal coverage, classic glamour","material":"satin luxe, minimal strategic coverage, classic playboy aesthetic","environment":"luxury mansion boudoir, iconic playboy mansion aesthetic","lighting":"warm classic playboy mansion light, intimate luxury, glamour glow","style":"playboy glamour editorial, luxury intimate photography","quality":"shot on Hasselblad H6D, warm luxury grade, portrait 2:3 vertical"},
    # 💫 글래머 보강
    "plunge_gown": {"tag":"Plunge Gown","subject":"a dramatic plunge gown female model","body":"luxury glamour model, defined waist, wide hips, dramatic plunge runway silhouette","outfit":"extreme plunge neckline evening gown, ultra-deep V neckline, dramatic luxury fashion","material":"liquid satin extreme plunge gown, ultra-deep neckline, luxury fabric","environment":"Paris fashion week runway, dramatic fashion show","lighting":"dramatic runway spotlight, plunge shadow emphasis, fashion show glow","style":"extreme plunge editorial, high fashion glamour photography","quality":"shot on Phase One XF IQ4, dramatic runway grade, portrait 2:3 vertical"},
    "slit_maxi": {"tag":"Slit Maxi","subject":"a ultra high slit maxi gown female model","body":"slim elegance model, long legs through slit, floor-length slit goddess presence","outfit":"floor-length maxi gown with ultra-high thigh slit, entire leg exposed through dramatic slit","material":"liquid satin floor-length gown, extreme thigh slit, dramatic silhouette","environment":"luxury hotel grand staircase, dramatic architecture","lighting":"dramatic staircase light, slit leg emphasis, luxury atmosphere","style":"high slit maxi editorial, dramatic leg glamour photography","quality":"shot on Hasselblad H6D, elegant dramatic grade, portrait 2:3 vertical"},
    "cutout_bodysuit": {"tag":"Cutout Bodysuit","subject":"a strategic cutout bodysuit female model","body":"athletic fitness model, defined toned body, strategic cutout power presence","outfit":"bodysuit with strategic cutouts revealing skin, geometric cutout design, fashion-forward","material":"stretch fabric with precise geometric cutouts, structured bodysuit, strategic openings","environment":"avant-garde fashion studio, high fashion atmosphere","lighting":"dramatic studio light through cutouts, shadow play, high fashion glow","style":"cutout bodysuit editorial, avant-garde glamour photography","quality":"shot on Sony A7R V, high fashion grade, portrait 2:3 vertical"},
    "sheer_overlay": {"tag":"Sheer Overlay","subject":"a luxurious sheer overlay gown female model","body":"slim elegance model, silhouette visible through sheer overlay, ethereal glamour presence","outfit":"luxury gown with complete sheer overlay, silhouette visible through transparent layer, ethereal luxury","material":"sheer chiffon overlay on minimal lining, luxury transparent outer layer","environment":"luxury gala, crystal chandelier ballroom, elegant event","lighting":"soft gala chandelier light through sheer, ethereal glow, luxury atmosphere","style":"sheer overlay editorial, ethereal luxury glamour photography","quality":"shot on Phase One XF IQ4, soft ethereal grade, portrait 2:3 vertical"},
    "jeweled_bikini_top": {"tag":"Jeweled Bikini Top","subject":"a jeweled bikini top luxury female model","body":"hot glamour model, narrow cinched waist, wide round hips, jeweled top hourglass presence","outfit":"elaborate jeweled bikini top with tailored trousers, luxury jewel-encrusted fashion","material":"crystal and gemstone bikini top, luxury tailored wide-leg trousers, high fashion mix","environment":"luxury fashion editorial location, Cannes terrace, Monaco setting","lighting":"Mediterranean golden light, jewel sparkle, luxury fashion glow","style":"jeweled bikini top editorial, luxury fashion glamour photography","quality":"shot on Hasselblad H6D, golden luxury grade, portrait 2:3 vertical"},
    "golden_drape_goddess": {"tag":"Golden Drape Goddess","subject":"a golden drape goddess female model","body":"luxury glamour model, goddess curves, golden-draped divine presence","outfit":"golden fabric draped loosely across body, Greek goddess style, strategic golden drape","material":"metallic gold chiffon loosely draped, goddess-style strategic coverage","environment":"Greek temple backdrop, golden sunset Mediterranean, divine atmosphere","lighting":"golden sunset divine light, draped shadow play, goddess glow","style":"golden drape goddess editorial, Mediterranean divine glamour photography","quality":"shot on Phase One XF IQ4, golden divine grade, portrait 2:3 vertical"},
    "crystal_gown": {"tag":"Crystal Gown","subject":"a crystal encrusted gown female model","body":"slim elegance model, crystal-adorned silhouette, maximum sparkle presence","outfit":"full crystal encrusted evening gown, thousands of crystals head to toe, maximum luxury","material":"crystal-encrusted fabric, diamond and crystal embellishment throughout, maximum luxury","environment":"grand opera house, dramatic crystal chandelier, luxury event","lighting":"crystal chandelier explosion, maximum sparkle refraction, luxury glow","style":"crystal gown editorial, maximum luxury glamour photography","quality":"shot on Phase One XF IQ4, maximum crystal grade, portrait 2:3 vertical"},
    "feather_trim_mini": {"tag":"Feather Trim Mini","subject":"a feather trim mini dress female model","body":"slim elegance model, long legs below feather hem, playful glamour presence","outfit":"ultra-mini dress with dramatic feather trim hemline, feather-edged mini, luxury playful","material":"satin mini dress, dramatic marabou feather trim at hemline, luxury accessories","environment":"luxury nightclub, glamorous party atmosphere, VIP setting","lighting":"nightclub warm light, feather movement, playful glamour glow","style":"feather trim mini editorial, playful luxury glamour photography","quality":"shot on Canon EOS R5, warm playful grade, portrait 2:3 vertical"},
    # 🏖️ 비치 보강
    "thong_bikini": {"tag":"Thong Bikini","subject":"a daring thong bikini beach female model","body":"VS Angel body, toned flat abs, long legs, thong bikini perfect beach goddess","outfit":"minimal thong bikini, tiny triangle top, barely-there thong bottom, beach goddess","material":"minimal string thong bikini, sun-kissed skin, beach accessories","environment":"tropical private beach, crystal water, exclusive resort","lighting":"golden tropical sun, beach beauty light, sun-kissed glow","style":"thong bikini beach editorial, tropical resort glamour photography","quality":"shot on Canon EOS R5, golden tropical grade, portrait 2:3 vertical"},
    "micro_bikini_gold": {"tag":"Micro Bikini Gold","subject":"a golden micro bikini glamour female model","body":"athletic fitness model, defined toned body, golden micro bikini athletic glamour","outfit":"gold metallic micro bikini, tiny triangle top and minimal bottom, Sports Illustrated glamour","material":"metallic gold micro bikini, minimal coverage, maximum luxury","environment":"Maldives luxury beach, crystal turquoise water, exclusive resort","lighting":"golden hour tropical light, gold bikini shimmer, luxury beach glow","style":"gold micro bikini editorial, Sports Illustrated luxury photography","quality":"shot on Phase One XF IQ4, golden tropical grade, portrait 2:3 vertical"},
    "sarong_goddess": {"tag":"Sarong Goddess","subject":"a tropical sarong goddess female model","body":"luxury glamour model, curves draped in sarong, tropical island goddess presence","outfit":"barely-draped sarong wrap, tropical print, no top, goddess sarong style","material":"lightweight sarong fabric, loosely wrapped, tropical flower print","environment":"Bali tropical beach, temple backdrop, island paradise","lighting":"warm Bali tropical light, sarong fabric flow, island goddess glow","style":"sarong goddess editorial, tropical island glamour photography","quality":"shot on Hasselblad H6D, warm tropical grade, portrait 2:3 vertical"},
    "wet_bikini_pool": {"tag":"Wet Bikini Pool","subject":"a dripping wet pool bikini female model","body":"slim toned model, soaked bikini clinging figure, pool-drenched goddess presence","outfit":"completely wet bikini, just emerged from pool, water streaming down body","material":"soaked bikini fabric clinging, water droplets everywhere, pool wet effect","environment":"luxury infinity pool, blue water reflection, resort poolside","lighting":"bright pool light, water droplet sparkle, wet skin shimmer","style":"wet pool bikini editorial, luxury resort photography","quality":"shot on Canon EOS R5, bright pool grade, portrait 2:3 vertical"},
    "topless_editorial": {"tag":"Topless Editorial","subject":"a artistic topless editorial female model","body":"slim elegance model, natural artistic figure, high-art topless editorial presence","outfit":"topless high fashion editorial, minimal bottom coverage, artistic body positive fashion","material":"minimal bottom wear only, artistic body presentation, high fashion context","environment":"minimal art studio, high fashion editorial, artistic photography space","lighting":"dramatic artistic editorial light, shadow artistic coverage, high art atmosphere","style":"topless high fashion editorial, artistic body glamour photography","quality":"shot on Hasselblad H6D, artistic editorial grade, portrait 2:3 vertical"},
    "nude_beach_art": {"tag":"Nude Beach Art","subject":"a nude beach artistic female model","body":"slim elegance model, natural figure in nature, artistic nude beach presence","outfit":"tasteful artistic nude beach, natural body in sand and sea, nature art photography","material":"natural body, sand and sea elements, nature art context","environment":"secluded artistic nude beach, natural setting, art photography","lighting":"natural golden beach light, artistic shadow play, nature art glow","style":"nude beach art editorial, tasteful nature glamour photography","quality":"shot on Phase One XF IQ4, natural warm grade, portrait 2:3 vertical"},
    # ⚔️ 파워&엣지 보강
    "dominatrix_glam": {"tag":"Dominatrix Glam","subject":"a commanding dominatrix glamour female model","body":"athletic fitness model, powerful toned body, dominant commanding power presence","outfit":"dominatrix glamour outfit, structured leather corset, thigh-high boots, commanding accessories","material":"patent leather corset, thigh-high dominatrix boots, power accessories","environment":"dark power studio, dramatic leather atmosphere, commanding space","lighting":"hard dramatic power light, leather shine, commanding atmosphere","style":"dominatrix glamour editorial, power commanding photography","quality":"shot on Leica SL2, high contrast power grade, portrait 2:3 vertical"},
    "bondage_fashion": {"tag":"Bondage Fashion","subject":"a high fashion bondage editorial female model","body":"slim elegance model, strapped and bound fashion figure, avant-garde bondage presence","outfit":"high fashion bondage-inspired outfit, decorative rope harness, fashion editorial straps","material":"decorative rope harness, fashion bondage straps, avant-garde accessories","environment":"avant-garde fashion studio, high fashion editorial space","lighting":"dramatic fashion editorial light, strap shadow play, avant-garde atmosphere","style":"bondage fashion editorial, avant-garde glamour photography","quality":"shot on Hasselblad H6D, dramatic avant-garde grade, portrait 2:3 vertical"},
    "strappy_harness": {"tag":"Strappy Harness","subject":"a strappy harness fashion female model","body":"athletic fitness model, defined toned body, strappy harness athletic goddess presence","outfit":"elaborate strappy leather harness over minimal outfit, fashion harness accessories","material":"leather strappy harness, minimal base outfit, fashion-forward accessories","environment":"urban edge location, gritty fashion studio, edgy atmosphere","lighting":"dramatic edge lighting, strap shadow definition, urban power glow","style":"strappy harness editorial, edge fashion glamour photography","quality":"shot on Sony A7R V, dramatic urban grade, portrait 2:3 vertical"},
    "mesh_bodysuit": {"tag":"Mesh Bodysuit","subject":"a transparent mesh bodysuit female model","body":"hot glamour model, every curve visible through mesh, mesh goddess presence","outfit":"full transparent mesh bodysuit, completely see-through, every curve visible","material":"transparent mesh fabric bodysuit, complete see-through, minimal strategic coverage","environment":"dark power studio, dramatic backdrop, fashion power space","lighting":"dramatic studio light through mesh, shadow pattern, power atmosphere","style":"mesh bodysuit editorial, transparent power glamour photography","quality":"shot on Phase One XF IQ4, dramatic mesh grade, portrait 2:3 vertical"},
    "latex_catsuit": {"tag":"Latex Catsuit","subject":"a sleek latex catsuit female model","body":"slim elegance model, perfectly defined in latex, second-skin latex presence","outfit":"full body latex catsuit, head to toe latex, perfectly form-fitting second skin","material":"high-gloss latex full body catsuit, second-skin fit, maximum shine","environment":"dark sleek studio, pure black backdrop, latex power space","lighting":"hard single spotlight on latex shine, maximum gloss reflection, power glow","style":"latex catsuit editorial, maximum gloss power photography","quality":"shot on Leica SL2, maximum latex grade, portrait 2:3 vertical"},
    # 🔮 판타지&다크 보강
    "dark_succubus": {"tag":"Dark Succubus","subject":"a ultimate dark succubus female model","body":"super glamour model, tiny waist, very wide round hips, maximum demonic hourglass silhouette","outfit":"ultimate succubus costume, demonic wings, minimal dark coverage, maximum sensual demon presence","material":"glossy dark latex-look minimal coverage, massive dark wings, demonic accessories","environment":"darkest demonic realm, hellfire and shadow, ultimate demon atmosphere","lighting":"hellfire glow from all sides, maximum dark demonic atmosphere, infernal light","style":"dark succubus ultimate editorial, demonic goddess photography","quality":"shot on Phase One XF IQ4, dark infernal grade, portrait 2:3 vertical"},
    "vampire_seduction": {"tag":"Vampire Seduction","subject":"a seductive vampire seduction female model","body":"luxury glamour model, pale immortal curves, vampire seduction presence","outfit":"vampire seduction outfit, blood red minimal corset dress, fangs, immortal seductress","material":"blood red satin minimal corset dress, dark accessories, immortal jewelry","environment":"gothic castle seduction chamber, red candlelight, dark romance","lighting":"blood moon red through gothic window, seduction candlelight, immortal dark glow","style":"vampire seduction editorial, immortal dark romance photography","quality":"shot on Leica SL2, blood moon grade, portrait 2:3 vertical"},
    "witch_sensual": {"tag":"Witch Sensual","subject":"a sensual witch glamour female model","body":"slim elegance model, mystical sensual figure, powerful witch goddess presence","outfit":"sensual witch outfit, low-cut dark robe, revealing magical costume, witch glamour","material":"flowing dark velvet low-cut robe, magical accessories, sensual witch styling","environment":"mystical forest clearing, moonlight, magical atmosphere","lighting":"moonlight through trees, magical glow, sensual witch atmosphere","style":"sensual witch editorial, magical glamour photography","quality":"shot on Hasselblad H6D, mystical moonlight grade, portrait 2:3 vertical"},
    "dark_fairy_erotic": {"tag":"Dark Fairy Erotic","subject":"a dark erotic fairy female model","body":"slim elegance model, delicate yet dark fairy figure, seductive fairy presence","outfit":"dark erotic fairy costume, torn dark wings, minimal dark fairy dress, seductive fae","material":"torn dark fabric minimal fairy dress, dark iridescent wings, dark fae accessories","environment":"dark enchanted forest, dark magic atmosphere, corrupted fairy realm","lighting":"dark magical fairy light, corrupted forest atmosphere, dark fae glow","style":"dark erotic fairy editorial, seductive fae glamour photography","quality":"shot on Sony A7R V, dark enchanted grade, portrait 2:3 vertical"},
    "shadow_seductress": {"tag":"Shadow Seductress","subject":"a mysterious shadow seductress female model","body":"slim elegance model, half in shadow seductive figure, mysterious shadow presence","outfit":"shadow-merged minimal outfit, body half-consumed by shadow, dramatic chiaroscuro fashion","material":"dark minimal outfit merging with shadow, dramatic darkness, seductive shadow play","environment":"dark void studio, half-light half-shadow, mysterious atmosphere","lighting":"extreme chiaroscuro, half body in complete shadow, seductive mystery light","style":"shadow seductress editorial, chiaroscuro mystery photography","quality":"shot on Hasselblad H6D, extreme chiaroscuro grade, portrait 2:3 vertical"},
}

added = 0
skipped = 0
for name, data in new_presets.items():
    path = PRESETS_DIR / f"{name}.json"
    if path.exists():
        print(f"⏭️  skip: {name}")
        skipped += 1
    else:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"✅ added: {name}")
        added += 1

print(f"\n완료: {added}개 추가, {skipped}개 스킵")
print(f"총 프리셋: 516 → {516 + added}개")
