"""
add_new_presets_v11.py
신규 프리셋 40개 추가 — 기존 카테고리 보강

카테고리별:
💫 글래머·럭셔리 (4개): casino_royale, black_tie_gala, champagne_tower, fur_coat_only
🌿 자연·원소 (4개): volcanic_goddess, storm_lightning, deep_cave, tidal_wave
🌃 도시·나이트 (4개): tokyo_shibuya, paris_midnight, subway_editorial, penthouse_view
🎬 에디토리얼·무드 (4개): wet_glass, smoke_studio, infrared_beauty, grain_film
🏺 문명·신화 (4개): sumerian_queen, ming_empress, aztec_sun_goddess, celtic_warrior_queen
🔮 판타지·다크 (4개): witch_ritual, fae_queen, cursed_beauty, shadow_realm
⚔️ 파워·엣지 (4개): riot_goddess, punk_queen, steel_warrior, cage_fighter
🏖️ 비치·리조트 (4개): sunset_cruise, coral_diving, beach_bonfire_night, hammock_resort
🎭 퍼포먼스·댄스 (4개): ballet_noir, broadway_diva, street_dance, drag_glamour
✈️ 직업·라이프 (4개): barista_chic, gallery_curator, horse_racing, scuba_instructor

총 프리셋: 331 → 371개
"""

import json
from pathlib import Path

PRESETS_DIR = Path("presets")
PRESETS_DIR.mkdir(exist_ok=True)

new_presets = {
    "casino_royale": {"tag": "Casino Royale", "subject": "a seductive casino royale bond girl female model", "body": "VS Angel body, toned flat abs, long legs, curvaceous yet athletic silhouette", "outfit": "ultra-low plunging backless evening gown, thigh-high slit, diamond jewelry, casino glamour", "material": "liquid satin midnight blue gown, mirror-finish fabric, sparkling diamond accessories", "environment": "Monte Carlo casino grand hall, roulette tables, chandelier light, luxury interior", "lighting": "warm casino chandelier glow, dramatic spotlight, golden atmospheric shimmer", "style": "Bond girl casino royale editorial, luxury spy glamour fashion photography", "quality": "shot on Hasselblad H6D, cinematic teal and orange grade, portrait 2:3 vertical"},
    "black_tie_gala": {"tag": "Black Tie Gala", "subject": "a breathtaking black tie gala female model", "body": "luxury glamour model, defined waist, wide round hips, sophisticated voluptuous elegance", "outfit": "couture strapless black gown, extreme plunging neckline, thigh slit, opera gloves", "material": "heavy duchess satin, structured boning, jet black mirror finish", "environment": "grand opera house foyer, marble columns, crystal chandeliers, black tie crowd", "lighting": "crystal chandelier warm glow, dramatic uplighting, golden luxury atmosphere", "style": "black tie gala editorial, haute couture evening glamour photography", "quality": "shot on Phase One XF IQ4, warm golden luxury grade, portrait 2:3 vertical"},
    "champagne_tower": {"tag": "Champagne Tower", "subject": "a celebratory champagne tower female model", "body": "hot glamour model, narrow cinched waist, wide round hips, dramatic hourglass figure", "outfit": "gold sequin plunging mini dress, champagne pouring over body, drenched in bubbles", "material": "ultra-glossy gold iridescent sequins, champagne liquid glistening on skin", "environment": "luxury rooftop celebration, towering champagne pyramid, golden confetti rain", "lighting": "warm golden party light, champagne bubble bokeh, celebratory shimmer glow", "style": "champagne tower glamour editorial, luxury celebration fashion photography", "quality": "shot on Canon EOS R5, warm champagne gold grade, portrait 2:3 vertical"},
    "fur_coat_only": {"tag": "Fur Coat Only", "subject": "a smoldering fur coat only female model", "body": "slim elegance model, long graceful legs, sophisticated sensual presence", "outfit": "oversized luxury fur coat worn open, nothing underneath suggestion, bare legs, stiletto heels", "material": "ultra-plush faux fur coat, cream or black, bare skin contrast", "environment": "luxury hotel corridor or penthouse, minimal elegant backdrop", "lighting": "warm intimate hotel light, soft shadows, sophisticated moody glow", "style": "fur coat only minimalist glamour editorial, old Hollywood sensual fashion photography", "quality": "shot on Leica SL2, warm moody intimate grade, portrait 2:3 vertical"},
    "volcanic_goddess": {"tag": "Volcanic Goddess", "subject": "a fierce volcanic goddess female model", "body": "power fitness model, very muscular defined body, commanding powerful presence", "outfit": "molten lava-inspired bodysuit, volcanic rock jewelry, fire-red draped fabric", "material": "heat-distorted metallic red and black bodysuit, volcanic rock accessories", "environment": "active volcano edge, flowing lava rivers below, dramatic volcanic sky", "lighting": "intense lava glow, dramatic red-orange light from below, volcanic smoke atmosphere", "style": "volcanic goddess power editorial, elemental force fashion photography", "quality": "shot on Sony A7R V, fiery red dramatic grade, portrait 2:3 vertical"},
    "storm_lightning": {"tag": "Storm Lightning", "subject": "a electrifying storm lightning female model", "body": "athletic fitness model, defined toned body, electric powerful presence", "outfit": "sleek silver metallic bodysuit, hair dramatically wind-blown, lightning crackling around", "material": "chrome silver metallic bodysuit, static electricity effect on fabric", "environment": "open clifftop in lightning storm, dramatic storm clouds, electric atmosphere", "lighting": "lightning flash dramatic strobe, electric blue-white light, storm atmosphere", "style": "storm lightning power editorial, electric force fashion photography", "quality": "shot on Sony A7R V, dramatic electric blue-white grade, portrait 2:3 vertical"},
    "deep_cave": {"tag": "Deep Cave", "subject": "a mysterious deep cave female model", "body": "slim elegance model, graceful elongated figure, mysterious ethereal presence", "outfit": "crystal-encrusted sheer bodysuit, stalactite-inspired jewelry, underground goddess", "material": "sheer crystal mesh bodysuit, natural cave crystal accessories", "environment": "underground crystal cave, glowing stalactites, bioluminescent cave pool", "lighting": "ethereal bioluminescent cave glow, crystal reflections, mysterious blue-green light", "style": "deep cave goddess editorial, subterranean luxury fashion photography", "quality": "shot on Phase One XF IQ4, ethereal blue-green cave grade, portrait 2:3 vertical"},
    "tidal_wave": {"tag": "Tidal Wave", "subject": "a powerful tidal wave female model", "body": "sports glamour model, toned athletic body with curves, glistening wet skin", "outfit": "barely-there ocean blue bikini, massive tidal wave crashing behind, water spraying", "material": "minimal iridescent ocean blue swimwear, ocean water drenching body", "environment": "dramatic ocean shore, enormous tidal wave rising behind, spray and mist", "lighting": "dramatic ocean light through wave, deep blue-green water luminosity, power atmosphere", "style": "tidal wave power editorial, Sports Illustrated ocean force photography", "quality": "shot on Canon EOS R5, dramatic ocean blue grade, portrait 2:3 vertical"},
    "tokyo_shibuya": {"tag": "Tokyo Shibuya", "subject": "a captivating Tokyo Shibuya night female model", "body": "slim toned model, lean athletic build, edgy urban presence", "outfit": "sleek black mini dress, thigh-high boots, neon-reflective raincoat, street glamour", "material": "glossy patent leather mini dress, reflective raincoat, neon-wet street reflections", "environment": "Shibuya crossing Tokyo, massive neon billboards, rain-soaked crosswalk, night crowds", "lighting": "multi-colored neon reflections on wet pavement, Japanese billboard glow, rain bokeh", "style": "Tokyo Shibuya night editorial, urban neon glamour fashion photography", "quality": "shot on Sony A7R V, vibrant neon night grade, portrait 2:3 vertical"},
    "paris_midnight": {"tag": "Paris Midnight", "subject": "a smoldering Paris midnight female model", "body": "slim elegance model, long graceful legs, sophisticated Parisian sensual presence", "outfit": "plunging wrap dress, ultra-high slit, red lips, Parisian chic glamour", "material": "liquid silk wrap dress, deep burgundy or black, elegant French draping", "environment": "Paris midnight street, Eiffel Tower glowing in distance, cobblestones, brasserie lights", "lighting": "warm Parisian street lamp glow, Eiffel Tower ambient light, romantic night atmosphere", "style": "Paris midnight editorial, French luxury night glamour photography", "quality": "shot on Leica SL2, warm romantic Parisian grade, portrait 2:3 vertical"},
    "subway_editorial": {"tag": "Subway Editorial", "subject": "a fierce subway editorial female model", "body": "slim toned model, lean athletic build, edgy confident urban presence", "outfit": "couture power suit worn open, nothing underneath, platform boots, editorial edge", "material": "structured tailored blazer, high-gloss patent platform boots, minimal underneath", "environment": "empty late-night subway station, fluorescent industrial lighting, tile walls", "lighting": "harsh fluorescent subway light, dramatic industrial shadows, underground atmosphere", "style": "subway editorial fashion photography, underground urban luxury glamour", "quality": "shot on Sony A7R V, high contrast cool industrial grade, portrait 2:3 vertical"},
    "penthouse_view": {"tag": "Penthouse View", "subject": "a glamorous penthouse view female model", "body": "luxury glamour model, defined waist, wide round hips, sophisticated voluptuous elegance", "outfit": "sheer silk robe barely covering, floor-to-ceiling window backdrop, extreme luxury", "material": "gossamer silk robe, semi-transparent, city light reflections on fabric", "environment": "ultra-luxury penthouse, floor-to-ceiling windows, panoramic city skyline at night", "lighting": "city skyline ambient glow through glass, warm interior accent light, dramatic contrast", "style": "penthouse view ultra-luxury editorial, high-rise glamour fashion photography", "quality": "shot on Hasselblad H6D, warm luxury night grade, portrait 2:3 vertical"},
    "wet_glass": {"tag": "Wet Glass", "subject": "a sensual wet glass female model", "body": "slim elegance model, graceful silhouette, deeply sensual mysterious presence", "outfit": "minimal silk slip dress, pressed against rain-covered glass, silhouette visible", "material": "sheer wet silk slip, rain-beaded glass surface, skin silhouette effect", "environment": "behind rain-soaked floor-to-ceiling glass window, city lights blurred beyond", "lighting": "diffused city light through rain-covered glass, soft silhouette glow, intimate atmosphere", "style": "wet glass silhouette editorial, sensual atmospheric fashion photography", "quality": "shot on Leica SL2, soft moody rain-diffused grade, portrait 2:3 vertical"},
    "smoke_studio": {"tag": "Smoke Studio", "subject": "a smoldering smoke studio female model", "body": "athletic fitness model, defined toned muscles, powerful commanding presence", "outfit": "minimal metallic bodysuit, dramatic smoke swirling around body, studio power", "material": "chrome metallic second-skin bodysuit, dry ice smoke effects", "environment": "dark professional studio, dramatic dry ice smoke filling floor, black backdrop", "lighting": "hard dramatic strobe through smoke, rim lighting defining body, smoke diffused atmosphere", "style": "smoke studio power editorial, dramatic luxury fashion photography", "quality": "shot on Hasselblad H6D, dark dramatic moody grade, portrait 2:3 vertical"},
    "infrared_beauty": {"tag": "Infrared Beauty", "subject": "a otherworldly infrared beauty female model", "body": "slim elegance model, graceful elongated figure, ethereal otherworldly presence", "outfit": "white flowing dress transformed by infrared, surreal color shift, dreamlike fashion", "material": "lightweight white fabric glowing surreal in infrared, ethereal texture", "environment": "outdoor garden or forest transformed by infrared photography, white foliage", "lighting": "infrared converted light, surreal white-pink foliage glow, ethereal dreamlike", "style": "infrared beauty editorial, surreal atmospheric luxury fashion photography", "quality": "shot on modified infrared Canon EOS R5, surreal infrared color grade, portrait 2:3 vertical"},
    "grain_film": {"tag": "Grain Film", "subject": "a sultry grain film female model", "body": "soft glamour model, feminine gentle curves, vintage sultry presence", "outfit": "vintage lingerie slip, old Hollywood glamour, film grain texture throughout", "material": "vintage silk slip, aged fabric texture, analog film grain aesthetic", "environment": "vintage Hollywood boudoir, old mirror, classic vanity, period furniture", "lighting": "warm analog film light, heavy grain texture, vintage glamour atmosphere", "style": "grain film vintage editorial, old Hollywood glamour photography", "quality": "shot on analog 35mm film, heavy grain vintage warm grade, portrait 2:3 vertical"},
    "sumerian_queen": {"tag": "Sumerian Queen", "subject": "a majestic Sumerian queen female model", "body": "luxury glamour model, defined waist, wide round hips, ancient divine feminine power", "outfit": "Sumerian royal costume, layered lapis lazuli jewelry, gold headdress, draped textile", "material": "ancient Sumerian woven textile, heavy lapis lazuli and gold jewelry", "environment": "ancient Mesopotamian palace, cuneiform-carved stone columns, oil lamp firelight", "lighting": "warm ancient oil lamp glow, golden civilizational light, dramatic stone shadows", "style": "Sumerian queen editorial, ancient Mesopotamian luxury fashion photography", "quality": "shot on Phase One XF IQ4, warm ancient golden grade, portrait 2:3 vertical"},
    "ming_empress": {"tag": "Ming Empress", "subject": "a magnificent Ming dynasty empress female model", "body": "slim elegant model, graceful composed figure, imperial commanding presence", "outfit": "elaborate Ming dynasty phoenix robe, gold embroidered dragon motifs, imperial crown", "material": "heavy imperial silk brocade, gold thread embroidery, jade and pearl accessories", "environment": "Forbidden City imperial hall, red lacquered columns, golden imperial interior", "lighting": "warm imperial golden light, dramatic ceremonial atmosphere, red and gold tones", "style": "Ming empress editorial, imperial Chinese luxury fashion photography", "quality": "shot on Phase One XF IQ4, rich imperial red gold grade, portrait 2:3 vertical"},
    "aztec_sun_goddess": {"tag": "Aztec Sun Goddess", "subject": "a radiant Aztec sun goddess female model", "body": "athletic fitness model, powerful toned body, divine commanding presence", "outfit": "Aztec sun goddess ceremonial costume, gold sun disk headdress, bare midriff, jade jewelry", "material": "gold hammered sun disk, jade stone jewelry, woven Aztec textile panels", "environment": "Aztec pyramid summit, blazing sun overhead, sacrificial altar, jungle below", "lighting": "intense overhead sun, golden divine rays, dramatic Aztec ceremonial atmosphere", "style": "Aztec sun goddess editorial, Mesoamerican divine luxury fashion photography", "quality": "shot on Sony A7R V, intense golden sun grade, portrait 2:3 vertical"},
    "celtic_warrior_queen": {"tag": "Celtic Warrior Queen", "subject": "a fierce Celtic warrior queen female model", "body": "power fitness model, muscular defined body, fierce warrior commanding presence", "outfit": "Celtic warrior queen armor, bronze torque necklace, draped plaid, battle-ready glamour", "material": "hammered bronze armor pieces, rough-woven Celtic plaid, ancient warrior accessories", "environment": "misty Celtic highland battlefield, ancient standing stones, dramatic stormy sky", "lighting": "dramatic storm light, misty Celtic atmosphere, cold natural power light", "style": "Celtic warrior queen editorial, ancient warrior luxury fashion photography", "quality": "shot on Hasselblad H6D, cold dramatic Celtic grade, portrait 2:3 vertical"},
    "witch_ritual": {"tag": "Witch Ritual", "subject": "a seductive witch ritual female model", "body": "slim elegance model, graceful mysterious figure, darkly sensual powerful presence", "outfit": "flowing black ritual gown, deep plunging neckline, ceremonial accessories, candle wax", "material": "heavy black velvet ritual gown, dripping candle wax details, dark crystal jewelry", "environment": "dark ritual circle, floating candles, ancient grimoire, smoke and shadow", "lighting": "dramatic candle flame light, deep shadows, mysterious occult atmosphere", "style": "witch ritual dark editorial, occult luxury glamour fashion photography", "quality": "shot on Leica SL2, dark occult moody grade, portrait 2:3 vertical"},
    "fae_queen": {"tag": "Fae Queen", "subject": "a enchanting fae queen female model", "body": "slim elegance model, delicate ethereal figure, magical otherworldly sensual presence", "outfit": "gossamer fairy queen gown, iridescent wings, flower crown, barefoot elegance", "material": "sheer iridescent gossamer fabric, luminescent fairy wings, natural flower accessories", "environment": "enchanted forest clearing, bioluminescent mushrooms, fairy lights, magical mist", "lighting": "ethereal bioluminescent forest glow, magical sparkle light, dreamlike atmosphere", "style": "fae queen enchanted editorial, magical luxury fashion photography", "quality": "shot on Hasselblad H6D, ethereal magical forest grade, portrait 2:3 vertical"},
    "cursed_beauty": {"tag": "Cursed Beauty", "subject": "a hauntingly cursed beauty female model", "body": "soft glamour model, feminine curves, hauntingly beautiful dark presence", "outfit": "decaying ballgown glamour, crumbling rose petals, broken mirror accessories, gothic drama", "material": "distressed silk ballgown, aged lace, crumbling rose petal details", "environment": "abandoned baroque ballroom, crumbling chandeliers, overgrown vines, decay", "lighting": "dramatic decaying chandelier light, broken window rays, haunting atmosphere", "style": "cursed beauty dark editorial, gothic decay luxury fashion photography", "quality": "shot on Leica SL2, dark desaturated gothic grade, portrait 2:3 vertical"},
    "shadow_realm": {"tag": "Shadow Realm", "subject": "a mysterious shadow realm female model", "body": "slim elegance model, elongated silhouette, mysterious shadow-like presence", "outfit": "flowing shadow-black gown, semi-transparent, merging with darkness, minimal form", "material": "ultra-sheer black silk, shadow-absorbing matte fabric, darkness as material", "environment": "void-like shadow realm, floating dark particles, infinite darkness, shadow tendrils", "lighting": "single dramatic key light carving form from darkness, deep void atmosphere", "style": "shadow realm editorial, void darkness luxury fashion photography", "quality": "shot on Sony A7R V, extreme dark contrast void grade, portrait 2:3 vertical"},
    "riot_goddess": {"tag": "Riot Goddess", "subject": "a fierce riot goddess female model", "body": "athletic fitness model, defined toned body, rebellious powerful presence", "outfit": "torn fishnet top, destroyed denim micro shorts, combat boots, chain accessories", "material": "distressed fishnet, ripped denim, heavy chain jewelry, combat leather boots", "environment": "urban rooftop at night, graffiti walls, city rebellion atmosphere", "lighting": "harsh urban street light, dramatic shadows, edgy rebellious atmosphere", "style": "riot goddess editorial, rebellious urban luxury fashion photography", "quality": "shot on Sony A7R V, gritty high contrast urban grade, portrait 2:3 vertical"},
    "punk_queen": {"tag": "Punk Queen", "subject": "a electric punk queen female model", "body": "slim toned model, lean edgy figure, punk rock powerful commanding presence", "outfit": "studded leather corset, ripped fishnet, plaid micro skirt, platform boots, mohawk", "material": "studded patent leather, ripped fishnet, metallic stud accessories", "environment": "abandoned warehouse concert venue, graffiti walls, dramatic stage lighting", "lighting": "electric concert strobe light, harsh dramatic shadows, punk energy atmosphere", "style": "punk queen editorial, rock luxury glamour fashion photography", "quality": "shot on Sony A7R V, high contrast punk grade, portrait 2:3 vertical"},
    "steel_warrior": {"tag": "Steel Warrior", "subject": "a formidable steel warrior female model", "body": "power fitness model, very muscular defined body, powerful warrior commanding presence", "outfit": "sleek steel battle armor, form-fitting metallic bodysuit, warrior crown, bare arms", "material": "polished steel armor plates, chrome metallic bodysuit, warrior metal accessories", "environment": "futuristic battle arena, metallic industrial landscape, dramatic warrior setting", "lighting": "harsh industrial metallic light, dramatic rim lighting on armor, powerful atmosphere", "style": "steel warrior editorial, futuristic power luxury fashion photography", "quality": "shot on Phase One XF IQ4, cool steel metallic grade, portrait 2:3 vertical"},
    "cage_fighter": {"tag": "Cage Fighter", "subject": "a powerful cage fighter female model", "body": "bikini competition model, extremely defined muscles, shredded powerful physique", "outfit": "MMA sports bra and shorts, boxing gloves, athletic wrap, fighter glamour", "material": "athletic performance fabric, leather boxing gloves, athletic wrap tape", "environment": "dramatic MMA octagon cage, arena spotlights, fighter entrance atmosphere", "lighting": "dramatic arena spotlight, hard athletic light, fighter power atmosphere", "style": "cage fighter glamour editorial, athletic power luxury fashion photography", "quality": "shot on Sony A7R V, high contrast athletic grade, portrait 2:3 vertical"},
    "sunset_cruise": {"tag": "Sunset Cruise", "subject": "a radiant sunset cruise female model", "body": "VS Angel body, toned flat abs, long legs, golden bronzed curvaceous silhouette", "outfit": "barely-there gold metallic bikini, sunset wind in hair, luxury yacht deck pose", "material": "metallic gold micro bikini, sun-kissed bronzed oiled glistening skin", "environment": "luxury superyacht deck, Mediterranean sunset, golden horizon, ocean breeze", "lighting": "blazing golden hour sunset, warm ocean glow, magical twilight atmosphere", "style": "sunset cruise editorial, Mediterranean luxury yacht glamour photography", "quality": "shot on Hasselblad H6D, warm golden sunset grade, portrait 2:3 vertical"},
    "coral_diving": {"tag": "Coral Diving", "subject": "a breathtaking coral diving female model", "body": "slim fitness model, lean toned body, aquatic graceful presence", "outfit": "sleek scuba wetsuit worn half-down, coral reef surrounding, underwater glamour", "material": "neon-accented wetsuit, underwater aquatic accessories, coral reef environment", "environment": "crystal clear tropical reef, vibrant coral formations, tropical fish, underwater paradise", "lighting": "tropical underwater caustic light, turquoise water luminosity, coral color reflections", "style": "coral diving editorial, underwater tropical luxury fashion photography", "quality": "shot on underwater housing Canon EOS R5, vivid tropical underwater grade, portrait 2:3 vertical"},
    "beach_bonfire_night": {"tag": "Beach Bonfire Night", "subject": "a captivating beach bonfire night female model", "body": "hot glamour model, narrow cinched waist, bronzed curves, warm firelit presence", "outfit": "barely-there tribal print bikini, sarong wrapped low, bonfire glow on oiled skin", "material": "minimal tropical print bikini, sarong wrap, warm bonfire-lit bronzed skin", "environment": "secluded beach at night, large bonfire, ocean waves, tropical night sky, stars", "lighting": "warm flickering bonfire light, orange golden glow on skin, dark ocean backdrop", "style": "beach bonfire night editorial, tropical night glamour photography", "quality": "shot on Canon EOS R5, warm bonfire amber grade, portrait 2:3 vertical"},
    "hammock_resort": {"tag": "Hammock Resort", "subject": "a sensual hammock resort female model", "body": "soft glamour model, feminine gentle curves, languid sensual relaxed presence", "outfit": "barely-there string bikini, lazily draped in hammock, tropical flowers in hair", "material": "minimal string bikini, woven hammock texture, tropical flower accessories", "environment": "overwater bungalow hammock, crystal turquoise Maldives lagoon below, paradise", "lighting": "soft tropical golden afternoon light, turquoise water reflection glow, paradise atmosphere", "style": "hammock resort editorial, Maldives luxury leisure glamour photography", "quality": "shot on Hasselblad H6D, warm turquoise tropical grade, portrait 2:3 vertical"},
    "ballet_noir": {"tag": "Ballet Noir", "subject": "a dark ballet noir female model", "body": "ballerina physique, slender elongated figure, graceful yet dark powerful presence", "outfit": "black tutu, torn fishnet stockings, dark pointe shoes, dramatic dark ballet costume", "material": "black tulle tutu, distressed fishnet, worn leather pointe shoes", "environment": "dark abandoned theatre stage, single spotlight, dramatic shadows, dusty curtains", "lighting": "single harsh spotlight, deep theatrical shadows, dramatic noir atmosphere", "style": "ballet noir dark editorial, dark performance luxury fashion photography", "quality": "shot on Leica SL2, high contrast dark theatrical grade, portrait 2:3 vertical"},
    "broadway_diva": {"tag": "Broadway Diva", "subject": "a show-stopping Broadway diva female model", "body": "hot glamour model, dramatic hourglass figure, powerful stage commanding presence", "outfit": "spectacular Broadway showgirl costume, feather headdress, sequin corset, fishnet legs", "material": "iridescent sequin corset, dramatic feather headdress, rhinestone fishnet stockings", "environment": "grand Broadway stage, dramatic curtain backdrop, chorus line, stage lights", "lighting": "dramatic Broadway stage spotlight, rainbow follow spot, glamorous showbiz light", "style": "Broadway diva editorial, showbiz luxury glamour fashion photography", "quality": "shot on Canon EOS R5, warm Broadway stage grade, portrait 2:3 vertical"},
    "street_dance": {"tag": "Street Dance", "subject": "a electric street dance female model", "body": "slim fitness model, lean toned athletic body, dynamic energetic presence", "outfit": "crop top, high-waist shorts, chunky sneakers, streetwear glamour, attitude", "material": "athletic crop top, high-waist spandex shorts, limited edition sneakers", "environment": "urban street at night, neon signs, graffiti walls, street lamp light", "lighting": "urban street lamp light, neon color accents, dynamic urban atmosphere", "style": "street dance editorial, urban streetwear luxury fashion photography", "quality": "shot on Sony A7R V, vibrant urban night grade, portrait 2:3 vertical"},
    "drag_glamour": {"tag": "Drag Glamour", "subject": "a spectacular drag glamour female model", "body": "super glamour model, tiny waist, very wide round hips, maximum hourglass silhouette", "outfit": "over-the-top sequin gown, sky-high platform heels, dramatic wig, extreme glamour", "material": "maximum sequin full-body gown, rhinestone accessories, theatrical drag makeup", "environment": "drag show stage, theatrical lighting, glitter rain, spectacular backdrop", "lighting": "maximum theatrical drag stage light, glitter-filled spotlight, spectacular atmosphere", "style": "drag glamour editorial, maximalist theatrical luxury fashion photography", "quality": "shot on Canon EOS R5, vibrant maximalist stage grade, portrait 2:3 vertical"},
    "barista_chic": {"tag": "Barista Chic", "subject": "a captivating barista chic female model", "body": "slim toned model, lean athletic build, charming approachable yet sensual presence", "outfit": "fitted apron over minimal outfit, coffee glamour, casual chic editorial", "material": "fitted linen apron, minimal crop underneath, artisan coffee accessories", "environment": "luxury specialty coffee bar, espresso machine, warm cafe interior, morning light", "lighting": "warm morning cafe golden light, coffee steam atmosphere, intimate cozy glow", "style": "barista chic editorial, artisan luxury lifestyle fashion photography", "quality": "shot on Canon EOS R5, warm morning coffee grade, portrait 2:3 vertical"},
    "gallery_curator": {"tag": "Gallery Curator", "subject": "a sophisticated gallery curator female model", "body": "slim elegance model, graceful elongated figure, intellectual powerful presence", "outfit": "architectural power suit, open blazer, minimal underneath, gallery chic", "material": "structured tailored blazer, silk blouse minimal, clean luxury fashion", "environment": "contemporary art gallery white walls, large abstract artworks, minimal interior", "lighting": "clean gallery track lighting, art museum white light, sophisticated atmosphere", "style": "gallery curator editorial, art world luxury fashion photography", "quality": "shot on Hasselblad H6D, clean minimal gallery grade, portrait 2:3 vertical"},
    "horse_racing": {"tag": "Horse Racing", "subject": "a glamorous horse racing female model", "body": "slim elegance model, sophisticated figure, aristocratic glamorous presence", "outfit": "sculptural fascinator hat, tailored racing dress, thigh slit, Ascot glamour", "material": "structured silk racing day dress, architectural fascinator, leather racing gloves", "environment": "Royal Ascot racecourse, green turf, racing crowd, champagne enclosure", "lighting": "bright English summer daylight, champagne enclosure atmosphere, prestigious glamour", "style": "horse racing Ascot editorial, aristocratic luxury fashion photography", "quality": "shot on Hasselblad H6D, bright English summer grade, portrait 2:3 vertical"},
    "scuba_instructor": {"tag": "Scuba Instructor", "subject": "a alluring scuba instructor female model", "body": "slim fitness model, lean toned athletic body, confident aquatic presence", "outfit": "form-fitting wetsuit worn half-unzipped, scuba mask pushed up, tank on back", "material": "neoprene wetsuit, scuba diving equipment, marine-grade accessories", "environment": "tropical dive boat deck, crystal ocean below, diving destination paradise", "lighting": "bright tropical sun, ocean glitter light reflection, aquatic paradise atmosphere", "style": "scuba instructor editorial, aquatic luxury lifestyle fashion photography", "quality": "shot on Canon EOS R5, vivid tropical marine grade, portrait 2:3 vertical"},
}

added = 0
skipped = 0
for name, data in new_presets.items():
    path = PRESETS_DIR / f"{name}.json"
    if path.exists():
        print(f"⏭️  skip: {name}")
        skipped += 1
    else:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"✅ added: {name}")
        added += 1

print(f"\n완료: {added}개 추가, {skipped}개 스킵")
print(f"총 프리셋: 331 → {331 + added}개")