"""
add_new_presets_v17.py
부족 카테고리 보강 39개

🎭 퍼포먼스 & 댄스 (+8개)
  belly_dance_glam, lap_dance_glam, striptease_art, pole_dance_power,
  samba_carnival, hula_goddess, jazz_dance_glam, kathak_dance

👘 전통 & 문화의상 (+10개)
  hanfu_goddess, cheongsam_slit, kebaya_java, dashiki_glam, kaftan_sheer,
  flamenco_dress, dirndl_glam, hanbok_modern, ao_dai_glamour, saree_draped_sensual

🌸 계절 & 테마 (+8개)
  halloween_glam, christmas_boudoir, new_year_glam, sakura_night_glam,
  summer_solstice_glam, autumn_gold_sensual, snow_queen_erotic, monsoon_goddess

🏺 문명 & 신화 (+8개)
  aphrodite_glam, artemis_huntress, freya_norse, kali_goddess,
  isis_egypt, lakshmi_goddess, oshun_yoruba, morgan_le_fay

🎬 에디토리얼 & 무드 (+5개)
  noir_femme_fatale, film_noir_glam, dreamy_soft_focus, shadow_art_nude, wet_editorial

총 프리셋: 566 → 605개
"""

import json
from pathlib import Path

PRESETS_DIR = Path("presets")
PRESETS_DIR.mkdir(exist_ok=True)

new_presets = {
    "belly_dance_glam": {"tag":"Belly Dance Glam","subject":"a sensual belly dance glamour female model","body":"hot glamour model, narrow cinched waist, wide round hips, undulating belly dance goddess presence","outfit":"elaborate belly dance costume, jeweled bra top, hip scarf with coins, flowing harem pants, coin belt","material":"gold coin hip scarf, jeweled bra top, sheer harem pants, layered flowing fabric","environment":"exotic Middle Eastern palace, low candlelight, silk cushions","lighting":"warm golden candlelight, coin shimmer, exotic sensual atmosphere","style":"belly dance glamour editorial, exotic sensual dance photography","quality":"shot on Phase One XF IQ4, warm golden exotic grade, portrait 2:3 vertical"},
    "lap_dance_glam": {"tag":"Lap Dance Glam","subject":"a seductive lap dance glamour female model","body":"VS Angel body, toned flat abs, long legs, lap dance seductive glamour presence","outfit":"seductive club dancer outfit, minimal sequin bodysuit, thigh-high boots, sultry accessories","material":"sequin stretch minimal bodysuit, patent thigh-high boots, sultry accessories","environment":"VIP nightclub private booth, low intimate lighting, luxury club","lighting":"intimate low club light, sequin shimmer, seductive atmosphere","style":"lap dance glamour editorial, seductive club photography","quality":"shot on Canon EOS R5, intimate club grade, portrait 2:3 vertical"},
    "striptease_art": {"tag":"Striptease Art","subject":"a artistic striptease female model","body":"slim elegance model, graceful artistic figure, burlesque striptease art presence","outfit":"burlesque striptease artistic costume, gloves being removed, corset partially unlaced, artistic reveal","material":"satin gloves, corset partially open, burlesque artistic elements","environment":"classic burlesque theatre stage, spotlight, vintage red curtain","lighting":"classic burlesque spotlight, theatrical atmosphere, vintage glamour light","style":"artistic striptease burlesque editorial, classic glamour photography","quality":"shot on Hasselblad H6D, warm theatrical grade, portrait 2:3 vertical"},
    "pole_dance_power": {"tag":"Pole Dance Power","subject":"a powerful pole dance glamour female model","body":"bikini competition model, extremely defined muscles, athletic pole dancer power presence","outfit":"pole dance performance outfit, minimal athletic wear, chrome pole, athletic power glamour","material":"minimal stretch performance wear, chrome pole prop, athletic accessories","environment":"dark pole dance studio, dramatic spotlight on chrome pole","lighting":"dramatic single spotlight, chrome pole reflection, athletic power atmosphere","style":"pole dance power editorial, athletic glamour photography","quality":"shot on Sony A7R V, dramatic chrome grade, portrait 2:3 vertical"},
    "samba_carnival": {"tag":"Samba Carnival","subject":"a spectacular samba carnival female model","body":"hot glamour model, narrow cinched waist, wide round hips, samba goddess explosive presence","outfit":"Rio samba carnival costume, elaborate feather headdress, sequin bikini, samba accessories","material":"massive feather headdress, crystal sequin bikini, colorful feather body accessories","environment":"Rio Sambadrome parade, carnival crowd, spectacular float","lighting":"carnival parade spotlight, sequin explosion, samba festival atmosphere","style":"samba carnival glamour editorial, Brazilian festival photography","quality":"shot on Canon EOS R5, vibrant carnival grade, portrait 2:3 vertical"},
    "hula_goddess": {"tag":"Hula Goddess","subject":"a graceful hula goddess female model","body":"soft glamour model, feminine gentle curves, hula goddess flowing presence","outfit":"traditional hula grass skirt, flower lei, floral top, barefoot island goddess","material":"natural grass skirt, tropical flower lei, floral fabric top","environment":"Hawaiian sunset beach, volcanic landscape, tropical paradise","lighting":"Hawaiian golden sunset, tropical flower bokeh, island goddess glow","style":"hula goddess editorial, Hawaiian island glamour photography","quality":"shot on Phase One XF IQ4, warm Hawaiian grade, portrait 2:3 vertical"},
    "jazz_dance_glam": {"tag":"Jazz Dance Glam","subject":"a electric jazz dance glamour female model","body":"athletic fitness model, defined toned body, jazz dancer electric glamour presence","outfit":"jazz dance performance costume, sequin leotard, fishnet stockings, character shoes","material":"sequin stretch leotard, fishnet stockings, jazz character shoes","environment":"jazz age nightclub stage, big band atmosphere, vintage spotlight","lighting":"vintage stage spotlight, jazz age warm light, performance atmosphere","style":"jazz dance glamour editorial, jazz age photography","quality":"shot on Hasselblad H6D, warm jazz age grade, portrait 2:3 vertical"},
    "kathak_dance": {"tag":"Kathak Dance","subject":"a elegant kathak dance glamour female model","body":"slim elegance model, graceful Indian classical figure, kathak spinning goddess presence","outfit":"kathak classical dance costume, ghagra choli, ankle bells, classical Indian jewelry","material":"embroidered silk ghagra, classical choli top, ghungroo ankle bells, Indian jewelry","environment":"Mughal palace courtyard, classical Indian performance atmosphere","lighting":"warm Mughal palace lamp light, classical dance atmosphere, Indian golden glow","style":"kathak dance glamour editorial, Indian classical dance photography","quality":"shot on Phase One XF IQ4, warm Indian grade, portrait 2:3 vertical"},
    "hanfu_goddess": {"tag":"Hanfu Goddess","subject":"a ethereal hanfu goddess female model","body":"slim elegance model, graceful Chinese classical figure, hanfu flowing goddess presence","outfit":"Tang dynasty hanfu, flowing silk ruqun, long ribbon sleeves, classical Chinese goddess","material":"flowing silk hanfu fabric, long ribbon sleeves, classical jade accessories","environment":"Chinese classical garden, lotus pond, Tang dynasty atmosphere","lighting":"soft classical Chinese garden light, lotus bokeh, ethereal goddess glow","style":"hanfu goddess editorial, Tang dynasty glamour photography","quality":"shot on Hasselblad H6D, soft classical Chinese grade, portrait 2:3 vertical"},
    "cheongsam_slit": {"tag":"Cheongsam Slit","subject":"a seductive cheongsam slit female model","body":"slim elegance model, graceful curves in cheongsam, extreme slit sensual presence","outfit":"ultra-high slit cheongsam, side slit to hip, mandarin collar, form-fitting Chinese dress","material":"silk cheongsam with extreme high slit, mandarin collar, frog button closure","environment":"Shanghai Art Deco interior, 1930s glamour, Chinese vintage atmosphere","lighting":"warm Art Deco Shanghai light, 1930s glamour, vintage Chinese glow","style":"cheongsam slit glamour editorial, Shanghai vintage photography","quality":"shot on Leica SL2, warm Art Deco grade, portrait 2:3 vertical"},
    "kebaya_java": {"tag":"Kebaya Java","subject":"a elegant kebaya Javanese female model","body":"slim elegance model, graceful Southeast Asian figure, Javanese kebaya refined presence","outfit":"Javanese kebaya, sheer lace kebaya top, batik sarong, traditional Javanese accessories","material":"sheer embroidered kebaya lace, batik fabric sarong, traditional gold accessories","environment":"Javanese royal kraton palace, traditional Indonesian atmosphere","lighting":"warm Javanese palace light, batik shadow, traditional Indonesian glow","style":"kebaya Javanese editorial, Indonesian cultural glamour photography","quality":"shot on Phase One XF IQ4, warm Indonesian grade, portrait 2:3 vertical"},
    "dashiki_glam": {"tag":"Dashiki Glam","subject":"a powerful dashiki glamour female model","body":"athletic fitness model, powerful toned body, West African dashiki goddess presence","outfit":"West African dashiki glamour, bold print off-shoulder dress, African jewelry, head wrap","material":"bold Ankara print dashiki fabric, African gold jewelry, gele head wrap","environment":"West African vibrant market, Lagos urban glamour, African modern city","lighting":"bright West African daylight, Ankara print vibrancy, modern African glow","style":"dashiki glamour editorial, West African modern photography","quality":"shot on Canon EOS R5, vibrant African grade, portrait 2:3 vertical"},
    "kaftan_sheer": {"tag":"Kaftan Sheer","subject":"a luxurious sheer kaftan female model","body":"luxury glamour model, curves visible through sheer kaftan, Middle Eastern goddess presence","outfit":"sheer luxury kaftan, transparent embroidered fabric, minimal underneath, Middle Eastern glamour","material":"sheer embroidered silk kaftan, transparent luxury fabric, gold thread embroidery","environment":"Moroccan luxury riad, courtyard fountain, Middle Eastern luxury atmosphere","lighting":"warm Moroccan afternoon light through sheer fabric, riad courtyard glow","style":"sheer kaftan glamour editorial, Middle Eastern luxury photography","quality":"shot on Hasselblad H6D, warm Moroccan grade, portrait 2:3 vertical"},
    "flamenco_dress": {"tag":"Flamenco Dress","subject":"a fierce flamenco dress female model","body":"hot glamour model, narrow waist, wide dramatic hips, flamenco goddess passionate presence","outfit":"dramatic flamenco dress, ruffled layers, deep red and black, rose in hair, dramatic pose","material":"ruffled silk taffeta flamenco layers, deep red black fabric, passionate accessories","environment":"Seville flamenco tablao, dramatic Spanish atmosphere, passionate performance","lighting":"dramatic Spanish spotlight, passionate dance atmosphere, flamenco fire glow","style":"flamenco dress glamour editorial, Spanish passionate photography","quality":"shot on Sony A7R V, dramatic Spanish grade, portrait 2:3 vertical"},
    "dirndl_glam": {"tag":"Dirndl Glam","subject":"a playful dirndl glamour female model","body":"soft glamour model, feminine generous curves, Bavarian dirndl playful glamour presence","outfit":"glamorous Bavarian dirndl, low-cut bodice, full skirt, apron, Oktoberfest glamour","material":"traditional dirndl with plunging neckline, full gathered skirt, lace apron","environment":"Bavarian Oktoberfest beer tent, Alpine mountains backdrop, festive atmosphere","lighting":"warm Bavarian beer tent light, Oktoberfest festive glow, Alpine warm atmosphere","style":"dirndl glamour editorial, Bavarian festive photography","quality":"shot on Canon EOS R5, warm Bavarian grade, portrait 2:3 vertical"},
    "hanbok_modern": {"tag":"Hanbok Modern","subject":"a contemporary modern hanbok female model","body":"slim elegance model, graceful Korean figure, modern hanbok fusion elegant presence","outfit":"modern reinterpreted hanbok, contemporary fusion design, short hemline, exposed shoulder","material":"modern silk hanbok fabric, contemporary fusion design, minimal traditional elements","environment":"Seoul modern gallery, Korean contemporary art space, modern urban backdrop","lighting":"clean modern gallery light, contemporary Korean atmosphere, elegant modern glow","style":"modern hanbok editorial, Korean contemporary fashion photography","quality":"shot on Hasselblad H6D, clean modern Korean grade, portrait 2:3 vertical"},
    "ao_dai_glamour": {"tag":"Ao Dai Glamour","subject":"a sensual ao dai glamour female model","body":"slim elegance model, graceful Vietnamese figure, ao dai sensual refined presence","outfit":"form-fitting Vietnamese ao dai, high neck, side slits revealing legs, sheer fabric","material":"sheer silk ao dai, form-fitting cut, high mandarin collar, side slit","environment":"Hoi An ancient town, lantern festival atmosphere, Vietnamese heritage","lighting":"warm Vietnamese lantern light, heritage atmosphere, ao dai elegance glow","style":"ao dai glamour editorial, Vietnamese heritage photography","quality":"shot on Phase One XF IQ4, warm Vietnamese grade, portrait 2:3 vertical"},
    "saree_draped_sensual": {"tag":"Saree Draped Sensual","subject":"a sensually draped saree female model","body":"luxury glamour model, curves beautifully draped, Indian goddess sensual saree presence","outfit":"sensually draped silk saree, exposed midriff, low hip drape, elaborate blouse, Indian glamour","material":"silk saree sensually draped, embroidered choli blouse, gold jewelry, low hip wrap","environment":"Rajasthani palace rooftop, golden sunset, Indian luxury atmosphere","lighting":"golden Rajasthan sunset, palace atmosphere, Indian goddess glow","style":"saree sensual editorial, Indian palace glamour photography","quality":"shot on Hasselblad H6D, warm golden Indian grade, portrait 2:3 vertical"},
    "halloween_glam": {"tag":"Halloween Glam","subject":"a seductive halloween glamour female model","body":"hot glamour model, narrow cinched waist, wide round hips, halloween seductive goddess presence","outfit":"sexy halloween costume glamour, devil horns, minimal dark costume, fishnet stockings, maximum glamour","material":"minimal dark costume fabric, fishnet stockings, devil accessories, halloween glamour","environment":"halloween haunted mansion, jack-o-lantern glow, spooky luxury atmosphere","lighting":"jack-o-lantern orange glow, halloween atmosphere, seductive dark light","style":"halloween glamour editorial, seductive holiday photography","quality":"shot on Canon EOS R5, orange halloween grade, portrait 2:3 vertical"},
    "christmas_boudoir": {"tag":"Christmas Boudoir","subject":"a festive christmas boudoir female model","body":"luxury glamour model, defined curves, christmas boudoir sensual festive presence","outfit":"santa boudoir costume, red velvet minimal corset, white fur trim, stockings, christmas accessories","material":"red velvet minimal santa costume, white fur trim, holiday stockings, festive accessories","environment":"luxury christmas boudoir, christmas tree glow, fireplace, festive intimate setting","lighting":"warm christmas fireplace glow, christmas tree light, intimate festive atmosphere","style":"christmas boudoir glamour editorial, festive intimate photography","quality":"shot on Leica SL2, warm christmas grade, portrait 2:3 vertical"},
    "new_year_glam": {"tag":"New Year Glam","subject":"a dazzling new year glamour female model","body":"slim elegance model, sparkling glitter figure, new year countdown goddess presence","outfit":"new year countdown glamour, gold sequin mini dress, glitter everywhere, champagne, party accessories","material":"gold sequin mini dress, glitter body coverage, festive party accessories","environment":"Times Square new year countdown, fireworks, confetti explosion","lighting":"firework explosion light, confetti atmosphere, new year sparkle glow","style":"new year glamour editorial, countdown celebration photography","quality":"shot on Sony A7R V, gold glitter grade, portrait 2:3 vertical"},
    "sakura_night_glam": {"tag":"Sakura Night Glam","subject":"a ethereal sakura night glamour female model","body":"slim elegance model, delicate figure under cherry blossoms, sakura night goddess presence","outfit":"cherry blossom themed glamour, pink silk dress, sakura accessories, ethereal night glamour","material":"pink silk dress, sakura flower accessories, ethereal sheer overlay","environment":"Tokyo cherry blossom night, illuminated sakura trees, Japanese night festival","lighting":"sakura lantern night light, cherry blossom bokeh, ethereal Japanese night glow","style":"sakura night glamour editorial, Japanese night photography","quality":"shot on Hasselblad H6D, soft sakura night grade, portrait 2:3 vertical"},
    "summer_solstice_glam": {"tag":"Summer Solstice Glam","subject":"a radiant summer solstice glamour female model","body":"athletic fitness model, sun-kissed toned body, summer solstice goddess radiant presence","outfit":"summer solstice festival glamour, floral wreath crown, minimal summer dress, festival goddess","material":"floral crown, flowing minimal festival dress, natural summer accessories","environment":"summer solstice festival, Stonehenge golden sunrise, midsummer celebration","lighting":"summer solstice golden sunrise, stone circle atmosphere, midsummer goddess glow","style":"summer solstice glamour editorial, midsummer goddess photography","quality":"shot on Phase One XF IQ4, golden solstice grade, portrait 2:3 vertical"},
    "autumn_gold_sensual": {"tag":"Autumn Gold Sensual","subject":"a sensual autumn gold glamour female model","body":"luxury glamour model, curves wrapped in autumn colors, golden autumn sensual presence","outfit":"autumn sensual glamour, burnt orange silk dress, autumn leaf accessories, golden fall fashion","material":"burnt orange silk dress, autumn leaf accessories, warm golden fabric","environment":"autumn forest at golden hour, falling leaves, rich fall colors","lighting":"golden autumn hour light, falling leaf bokeh, warm sensual fall atmosphere","style":"autumn gold sensual editorial, fall glamour photography","quality":"shot on Leica SL2, warm autumn gold grade, portrait 2:3 vertical"},
    "snow_queen_erotic": {"tag":"Snow Queen Erotic","subject":"a seductive snow queen erotic female model","body":"slim elegance model, pale ice queen figure, snow queen erotic frozen presence","outfit":"erotic snow queen costume, minimal white crystal outfit, ice crown, sheer frozen elements","material":"minimal crystal white fabric, ice crown accessories, sheer frozen elements","environment":"dark ice palace, black ice formations, frozen erotic realm","lighting":"cold blue ice glow, frozen erotic atmosphere, snow queen dark light","style":"snow queen erotic editorial, frozen dark glamour photography","quality":"shot on Phase One XF IQ4, cold ice blue grade, portrait 2:3 vertical"},
    "monsoon_goddess": {"tag":"Monsoon Goddess","subject":"a drenched monsoon goddess female model","body":"slim elegance model, soaked saree clinging figure, monsoon goddess sensual presence","outfit":"monsoon rain goddess, drenched traditional outfit clinging to body, rain-soaked glamour","material":"rain-soaked silk clinging fabric, monsoon wet effect, transparent when wet","environment":"Indian monsoon rainstorm, ancient temple backdrop, dramatic rain","lighting":"monsoon dramatic rain light, temple backdrop, rain goddess sensual glow","style":"monsoon goddess editorial, rain-soaked glamour photography","quality":"shot on Sony A7R V, dramatic monsoon grade, portrait 2:3 vertical"},
    "aphrodite_glam": {"tag":"Aphrodite Glam","subject":"a divine Aphrodite goddess glamour female model","body":"luxury glamour model, divine goddess curves, Aphrodite love beauty goddess presence","outfit":"Aphrodite goddess costume, draped white marble fabric, golden laurel crown, divine accessories","material":"draped white fabric, golden laurel crown, divine Greek goddess accessories","environment":"Greek marble temple of Aphrodite, rose petals, Mediterranean divine atmosphere","lighting":"golden Mediterranean divine light, rose petal bokeh, goddess of love glow","style":"Aphrodite glamour editorial, Greek goddess photography","quality":"shot on Phase One XF IQ4, golden divine grade, portrait 2:3 vertical"},
    "artemis_huntress": {"tag":"Artemis Huntress","subject":"a powerful Artemis huntress goddess female model","body":"athletic fitness model, powerful toned body, Artemis moon huntress goddess presence","outfit":"Artemis huntress costume, short chiton, bow and arrow, moon crown, athletic goddess","material":"short white chiton, silver moon accessories, bow and arrow, huntress elements","environment":"ancient Greek forest under full moon, hunting goddess realm","lighting":"silver full moonlight, forest atmosphere, huntress goddess glow","style":"Artemis huntress editorial, moon goddess photography","quality":"shot on Sony A7R V, silver moonlight grade, portrait 2:3 vertical"},
    "freya_norse": {"tag":"Freya Norse","subject":"a magnificent Freya Norse goddess female model","body":"powerful glamour model, Viking goddess curves, Freya love war goddess presence","outfit":"Freya Norse goddess costume, fur-trimmed warrior dress, Brisingamen necklace, Viking accessories","material":"fur-trimmed Norse dress, Brisingamen necklace, Viking gold accessories","environment":"Norse realm Asgard, Northern Lights, Viking divine atmosphere","lighting":"Northern Lights aurora glow, Norse divine atmosphere, Freya warrior goddess light","style":"Freya Norse editorial, Norse mythology glamour photography","quality":"shot on Hasselblad H6D, aurora Norse grade, portrait 2:3 vertical"},
    "kali_goddess": {"tag":"Kali Goddess","subject":"a fierce Kali Hindu goddess female model","body":"power fitness model, muscular defined body, Kali destroyer goddess fierce presence","outfit":"Kali Hindu goddess costume, dark blue skin paint, skull necklace, fierce warrior goddess","material":"dark blue body paint, skull garland, Kali goddess accessories, warrior elements","environment":"Hindu cremation ground, dark goddess realm, Kali divine atmosphere","lighting":"dramatic dark divine light, Kali fierce atmosphere, destroyer goddess glow","style":"Kali goddess editorial, Hindu mythology glamour photography","quality":"shot on Phase One XF IQ4, dramatic dark grade, portrait 2:3 vertical"},
    "isis_egypt": {"tag":"Isis Egypt","subject":"a divine Isis Egyptian goddess female model","body":"slim elegance model, Egyptian goddess figure, Isis divine magic presence","outfit":"Isis Egyptian goddess costume, white linen pleated dress, wings spread, ankh, Egyptian crown","material":"white pleated linen, divine Isis wings, Egyptian gold accessories, ankh","environment":"ancient Egyptian temple of Isis, Nile backdrop, divine Egyptian atmosphere","lighting":"golden Egyptian divine light, Nile atmosphere, Isis goddess glow","style":"Isis Egypt editorial, Egyptian goddess photography","quality":"shot on Phase One XF IQ4, golden Egyptian grade, portrait 2:3 vertical"},
    "lakshmi_goddess": {"tag":"Lakshmi Goddess","subject":"a radiant Lakshmi Hindu goddess female model","body":"luxury glamour model, divine Indian goddess curves, Lakshmi wealth beauty goddess presence","outfit":"Lakshmi goddess costume, gold silk saree, lotus flowers, gold coins shower, divine jewelry","material":"gold silk saree, lotus accessories, divine gold jewelry, wealth symbols","environment":"Hindu temple of Lakshmi, lotus pond, divine golden atmosphere","lighting":"divine golden temple light, lotus bokeh, Lakshmi goddess radiant glow","style":"Lakshmi goddess editorial, Hindu goddess photography","quality":"shot on Hasselblad H6D, divine golden grade, portrait 2:3 vertical"},
    "oshun_yoruba": {"tag":"Oshun Yoruba","subject":"a magnificent Oshun Yoruba goddess female model","body":"hot glamour model, sensual curves, Oshun love river goddess radiant presence","outfit":"Oshun Yoruba goddess costume, yellow gold flowing dress, honey accessories, river goddess elements","material":"yellow gold silk flowing dress, honey and amber accessories, river goddess elements","environment":"sacred Oshun river, yellow and gold atmosphere, Yoruba divine realm","lighting":"golden river light, Oshun divine atmosphere, love goddess radiant glow","style":"Oshun Yoruba editorial, African goddess photography","quality":"shot on Phase One XF IQ4, golden river grade, portrait 2:3 vertical"},
    "morgan_le_fay": {"tag":"Morgan Le Fay","subject":"a mysterious Morgan Le Fay sorceress female model","body":"slim elegance model, mysterious Celtic figure, Morgan le Fay dark sorceress presence","outfit":"Morgan le Fay Celtic sorceress costume, dark medieval gown, magical staff, Avalon mist","material":"dark silk medieval gown, Celtic magical accessories, sorceress staff","environment":"Isle of Avalon mist, Celtic magical realm, Arthurian dark atmosphere","lighting":"Avalon mist light, Celtic dark atmosphere, sorceress mysterious glow","style":"Morgan le Fay editorial, Celtic mythology glamour photography","quality":"shot on Leica SL2, dark Celtic grade, portrait 2:3 vertical"},
    "noir_femme_fatale": {"tag":"Noir Femme Fatale","subject":"a iconic noir femme fatale female model","body":"slim elegance model, deadly curves, film noir femme fatale dangerous presence","outfit":"classic femme fatale outfit, sleek noir dress, red lips, cigarette holder, dangerous accessories","material":"sleek black satin dress, classic noir accessories, dangerous glamour styling","environment":"1940s film noir rain-soaked street, detective agency, shadow play","lighting":"classic film noir shadow lighting, venetian blind shadows, femme fatale dramatic light","style":"noir femme fatale editorial, classic film noir photography","quality":"shot on Leica SL2, high contrast noir grade, portrait 2:3 vertical"},
    "film_noir_glam": {"tag":"Film Noir Glam","subject":"a glamorous film noir female model","body":"luxury glamour model, 1940s Hollywood curves, film noir glamour deadly presence","outfit":"1940s Hollywood noir glamour, bias-cut satin dress, veronica lake hair, cigarette","material":"bias-cut satin dress, classic 1940s accessories, Hollywood noir styling","environment":"1940s Hollywood noir backlot, rain-slicked street, neon bar signs","lighting":"classic noir low key lighting, hard shadow contrast, neon sign glow","style":"film noir glamour editorial, classic Hollywood photography","quality":"shot on Hasselblad H6D, classic noir grade, portrait 2:3 vertical"},
    "dreamy_soft_focus": {"tag":"Dreamy Soft Focus","subject":"a ethereal dreamy soft focus female model","body":"slim elegance model, ethereal dreamy figure, soft focus goddess presence","outfit":"flowing ethereal minimal dress, dreamy soft styling, barely-there glamour, gossamer fabric","material":"gossamer sheer fabric, flowing minimal dress, dreamy soft accessories","environment":"dreamy flower field, soft bokeh everywhere, ethereal dreamscape","lighting":"soft diffused golden light, maximum bokeh, dreamy ethereal atmosphere","style":"dreamy soft focus editorial, ethereal glamour photography","quality":"shot on Hasselblad H6D, maximum soft focus grade, portrait 2:3 vertical"},
    "shadow_art_nude": {"tag":"Shadow Art Nude","subject":"a artistic shadow art nude female model","body":"slim elegance model, silhouette through shadow, artistic nude shadow presence","outfit":"artistic shadow play, body revealed only through dramatic shadow patterns, minimal coverage","material":"shadow and light only coverage, artistic body shadow play, minimal fabric","environment":"minimal art studio, dramatic shadow pattern light, artistic photography","lighting":"extreme chiaroscuro, shadow pattern covering body, artistic nude light","style":"shadow art nude editorial, artistic shadow glamour photography","quality":"shot on Phase One XF IQ4, extreme shadow art grade, portrait 2:3 vertical"},
    "wet_editorial": {"tag":"Wet Editorial","subject":"a drenched wet editorial female model","body":"slim elegance model, soaked figure, high fashion wet editorial presence","outfit":"high fashion wet editorial look, drenched designer outfit clinging to body, fashion-forward","material":"soaked high fashion fabric clinging, wet transparency, editorial wet styling","environment":"minimal high fashion studio, water pouring, editorial wet atmosphere","lighting":"dramatic studio strobe on wet fabric, water drop freeze, editorial light","style":"wet editorial high fashion, avant-garde wet photography","quality":"shot on Sony A7R V, dramatic wet editorial grade, portrait 2:3 vertical"},
}

added = 0
skipped = 0
for name, data in new_presets.items():
    path = PRESETS_DIR / f"{name}.json"
    if path.exists():
        print(f"⏭️  skip: {name}")
        skipped += 1
    else:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"✅ added: {name}")
        added += 1

print(f"\n완료: {added}개 추가, {skipped}개 스킵")
print(f"총 프리셋: 566 → {566 + added}개")
