import json
from pathlib import Path

PRESETS_DIR = Path(r"C:\Dev\LumineX\presets")

presets = [
    ("machu_picchu_cloud", {"tag":"Machu Picchu Cloud","subject":"a woman at the lost city of the Incas","body":"full body shot","outfit":"minimal flowing fabric, wind movement","material":"sheer lightweight fabric","environment":"Machu Picchu, Peru, ancient Inca citadel perched on Andean mountain ridge, dramatic cloud sea below, terraced stone architecture, llamas grazing on emerald grass, misty Andes peaks surrounding, sacred lost city atmosphere","lighting":"dramatic morning mist light, golden rays piercing cloud layer, ancient stone warmth","style":"lost civilization editorial, Inca wonder photography, above the clouds","quality":"shot on Hasselblad H6D, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("chichen_itza_pyramid", {"tag":"Chichen Itza Pyramid","subject":"a woman at the great Maya pyramid","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Chichen Itza, Mexico, El Castillo pyramid rising 30 meters from jungle floor, precise geometric steps on all four sides, surrounding jungle canopy, ancient Maya astronomical precision, sacred Mesoamerican atmosphere","lighting":"dramatic equatorial sunlight, deep shadows on pyramid steps, golden stone warmth","style":"ancient Maya editorial, archaeological wonder photography","quality":"shot on Canon EOS R5, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("colosseum_dusk", {"tag":"Colosseum Dusk","subject":"a woman at the ancient Roman Colosseum","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Colosseum, Rome Italy, ancient amphitheater arches glowing at dusk, travertine limestone facade, underground hypogeum visible, warm amber city lights, 2000 year old engineering marvel, eternal city atmosphere","lighting":"golden dusk light on ancient stone, warm amber glow, dramatic arch shadows","style":"eternal city editorial, ancient Rome photography, golden hour","quality":"shot on Sony A7R V, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("alhambra_palace", {"tag":"Alhambra Palace","subject":"a woman in the Nasrid palace of Alhambra","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Alhambra palace, Granada Spain, Court of Lions with intricate muqarnas ceiling, geometric tilework covering every surface, central fountain with lion sculptures, reflecting pool, Islamic geometric art perfection, Sierra Nevada visible","lighting":"soft filtered light through intricate carved screens, warm golden Islamic interior glow","style":"Islamic art editorial, Moorish palace photography, geometric perfection","quality":"shot on Hasselblad H6D, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("borobudur_dawn", {"tag":"Borobudur Dawn","subject":"a woman at the Buddhist mandala temple","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Borobudur temple, Java Indonesia, massive Buddhist mandala rising in terraces, hundreds of bell-shaped stupas, Mount Merapi volcano in background, pre-dawn mist, sunrise light breaking over volcanic horizon, spiritual Buddhist atmosphere","lighting":"pre-dawn volcanic horizon glow, misty golden sunrise, spiritual amber atmosphere","style":"Buddhist wonder editorial, volcanic island photography, spiritual dawn","quality":"shot on Canon EOS R5, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("karnak_temple", {"tag":"Karnak Temple","subject":"a woman among the ancient Egyptian forest of columns","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Karnak Temple complex, Luxor Egypt, Great Hypostyle Hall with 134 massive sandstone columns, hieroglyphs covering every surface, dramatic scale dwarfing human figures, sacred lake, ancient Egyptian grandeur beyond imagination","lighting":"harsh Egyptian sunlight through column gaps, dramatic shaft light, ancient stone warmth","style":"ancient Egypt editorial, pharaonic wonder photography","quality":"shot on Sony A7R V, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("mont_saint_michel", {"tag":"Mont Saint-Michel","subject":"a woman at the island abbey of Mont Saint-Michel","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Mont Saint-Michel, Normandy France, medieval abbey rising dramatically from tidal flat island, surrounding sea at low tide reveals vast sand bay, Gothic spire piercing misty sky, ancient village clinging to rock, ethereal island fortress","lighting":"dramatic tidal flat reflection, misty Normandy light, medieval stone golden glow","style":"medieval wonder editorial, French heritage photography","quality":"shot on Hasselblad H6D, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("sigiriya_rock", {"tag":"Sigiriya Rock","subject":"a woman atop the ancient rock fortress of Sigiriya","body":"full body shot","outfit":"minimal flowing fabric, tropical wind","material":"sheer lightweight fabric","environment":"Sigiriya Lion Rock, Sri Lanka, ancient palace ruins atop sheer 200m volcanic rock, surrounding jungle stretching to horizon, ancient frescoes on rock face, water gardens below, tropical mist, ancient Sri Lankan kingdom atmosphere","lighting":"tropical golden hour, dramatic rock shadow, lush jungle light","style":"ancient kingdom editorial, tropical archaeology photography","quality":"shot on Canon EOS R5, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("angkor_thom_faces", {"tag":"Angkor Thom Faces","subject":"a woman among the giant stone faces of Bayon","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Bayon temple, Angkor Thom Cambodia, 216 giant serene stone faces carved on 54 towers, ancient moss-covered stone, jungle trees reclaiming walls, mysterious smiling Khmer faces in every direction, ancient Buddhist kingdom","lighting":"diffused jungle light, mysterious stone face shadows, ancient moss warmth","style":"mysterious ancient editorial, Khmer face photography, jungle archaeology","quality":"shot on Sony A7R V, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("teotihuacan_pyramid", {"tag":"Teotihuacan Pyramid","subject":"a woman atop the Pyramid of the Sun","body":"full body shot","outfit":"minimal flowing fabric, wind movement","material":"sheer lightweight fabric","environment":"Teotihuacan, Mexico, Pyramid of the Sun rising 65 meters, Avenue of the Dead stretching below, Pyramid of the Moon in distance, ancient Mesoamerican city grid visible from summit, volcanic mountains horizon, sacred pre-Aztec atmosphere","lighting":"dramatic Mexican highland sun, vast scale dramatic shadows, ancient stone warmth","style":"pre-Aztec wonder editorial, Mesoamerican pyramid photography","quality":"shot on Hasselblad H6D, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("gobekli_tepe", {"tag":"Göbekli Tepe","subject":"a woman among the world's oldest temple pillars","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Göbekli Tepe, Turkey, world's oldest known temple 12000 years old, T-shaped limestone pillars carved with animals, circular enclosures, ancient hilltop site, Anatolian plains stretching to horizon, prehistoric mystery","lighting":"dramatic Anatolian sunlight, deep shadow in ancient stone circles, prehistoric atmosphere","style":"prehistoric mystery editorial, ancient humanity photography","quality":"shot on Canon EOS R5, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("palmyra_colonnade", {"tag":"Palmyra Colonnade","subject":"a woman among the Roman desert colonnade of Palmyra","body":"full body shot","outfit":"minimal flowing fabric, desert wind","material":"sheer lightweight fabric","environment":"Palmyra, Syria, ancient Roman colonnaded street stretching through desert, Corinthian columns rising from sand, Temple of Bel ruins, dramatic desert landscape, ancient Silk Road city, golden stone ruins at sunset","lighting":"golden desert sunset on Roman columns, dramatic long shadows, ancient stone warmth","style":"desert ruins editorial, Silk Road archaeology photography","quality":"shot on Sony A7R V, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("zhangjiajie_avatar", {"tag":"Zhangjiajie Avatar","subject":"a woman among the floating Avatar mountains","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Zhangjiajie National Forest, China, towering sandstone pillar mountains rising vertically through cloud sea, lush subtropical forest on sheer cliff tops, glass bridge between pillars, misty Avatar landscape, otherworldly scale","lighting":"dramatic cloud sea light, misty pillar shadows, ethereal mountain atmosphere","style":"Avatar landscape editorial, floating mountain photography, otherworldly China","quality":"shot on Hasselblad H6D, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("pamukkale_white", {"tag":"Pamukkale White","subject":"a woman on the white calcium terraces of Pamukkale","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer white fabric","environment":"Pamukkale, Turkey, snow-white calcium carbonate terraces cascading down hillside, turquoise thermal pools on each terrace, cotton castle landscape, ancient Hierapolis ruins above, surreal all-white mineral landscape","lighting":"bright Turkish sun on white terraces, turquoise water reflection, pure white ground glow","style":"mineral wonder editorial, cotton castle photography, surreal white","quality":"shot on Canon EOS R5, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("plitvice_cascade", {"tag":"Plitvice Cascade","subject":"a woman at the emerald waterfall staircase of Plitvice","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Plitvice Lakes, Croatia, sixteen turquoise lakes connected by cascading waterfalls, wooden boardwalks over crystal water, lush beech and fir forest, travertine barriers creating natural pools, UNESCO wonder, emerald paradise","lighting":"soft forest filtered light, turquoise water glow, natural emerald reflection","style":"natural paradise editorial, Croatian wonder photography","quality":"shot on Sony A7R V, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("frozen_baikal", {"tag":"Frozen Baikal","subject":"a woman on the transparent frozen Lake Baikal","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer fabric","environment":"Lake Baikal, Siberia Russia, world's deepest lake frozen solid, perfectly transparent blue ice stretching to horizon, dramatic crack patterns in ice, Siberian mountains in distance, subzero clarity, ancient ice formations","lighting":"cold Siberian blue light, ice crack shadow patterns, pristine frozen atmosphere","style":"Siberian ice editorial, frozen wonder photography, crystal clarity","quality":"shot on Hasselblad H6D, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("rainbow_mountain", {"tag":"Rainbow Mountain","subject":"a woman on the rainbow-striped Vinicunca mountain","body":"full body shot","outfit":"minimal flowing fabric, high altitude wind","material":"sheer lightweight fabric","environment":"Vinicunca Rainbow Mountain, Peru, 5000m altitude Andean peak with vivid mineral color stripes of red, yellow, green, purple and turquoise, vast Andean landscape, alpacas grazing, dramatic high altitude sky","lighting":"dramatic high altitude Andean light, vivid mineral colors, thin air clarity","style":"Andean wonder editorial, rainbow mountain photography","quality":"shot on Canon EOS R5, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("wisteria_tunnel", {"tag":"Wisteria Tunnel","subject":"a woman walking through a magical wisteria tunnel","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Kawachi Wisteria Garden, Fukuoka Japan, tunnel of cascading purple and white wisteria flowers overhead, dappled purple light filtering through flower canopy, wooden trellis structure, 150 year old wisteria vines, magical purple atmosphere","lighting":"purple filtered light through wisteria canopy, dappled floral shadows, magical soft glow","style":"Japanese garden editorial, wisteria wonder photography","quality":"shot on Sony A7R V, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("torres_del_paine", {"tag":"Torres del Paine","subject":"a woman before the granite towers of Patagonia","body":"full body shot","outfit":"minimal flowing fabric, Patagonian wind","material":"sheer lightweight fabric","environment":"Torres del Paine, Chilean Patagonia, three dramatic granite towers rising 2800m, turquoise glacial lake reflection, guanaco grazing on steppe, dramatic Patagonian sky, glaciers and ice fields, untouched wilderness","lighting":"dramatic Patagonian light, granite tower alpenglow, glacial lake reflection","style":"Patagonian wilderness editorial, granite tower photography","quality":"shot on Hasselblad H6D, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("ha_long_bay", {"tag":"Ha Long Bay","subject":"a woman among the limestone karst islands of Ha Long Bay","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Ha Long Bay, Vietnam, thousands of limestone karst pillars rising from emerald sea, morning mist between islands, traditional junk boats, hidden caves and lagoons, UNESCO world heritage, ethereal seascape","lighting":"misty morning light between limestone karsts, emerald water reflection, ethereal fog atmosphere","style":"Vietnamese seascape editorial, karst wonder photography","quality":"shot on Canon EOS R5, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("kelimutu_crater", {"tag":"Kelimutu Crater","subject":"a woman at the three-colored volcanic crater lakes","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Kelimutu volcano, Flores Indonesia, three crater lakes each different color — one turquoise, one black, one red-brown — volcanic mineral chemistry, sacred Flores ancestor spirit lakes, otherworldly volcanic summit","lighting":"dramatic volcanic summit light, three-color lake reflection, otherworldly mineral glow","style":"volcanic wonder editorial, three color lake photography","quality":"shot on Sony A7R V, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("victoria_falls", {"tag":"Victoria Falls","subject":"a woman at the thundering Victoria Falls","body":"full body shot","outfit":"minimal flowing fabric, mist","material":"sheer wet fabric","environment":"Victoria Falls, Zimbabwe/Zambia, world's largest waterfall curtain 1700m wide, thundering water creating permanent rainbow mist cloud, spray forest, Zambezi River gorge, Devil's Pool edge, smoke that thunders atmosphere","lighting":"dramatic mist rainbow light, thundering water spray, natural prismatic glow","style":"African wonder editorial, Victoria Falls photography, rainbow mist","quality":"shot on Canon EOS R5, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("fairy_pools", {"tag":"Fairy Pools","subject":"a woman at the magical fairy pools of Isle of Skye","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Fairy Pools, Isle of Skye Scotland, crystal clear turquoise natural pools and waterfalls, dramatic Cuillin mountain backdrop, ancient basalt rock, wild Scottish Highland atmosphere, magical hidden valley","lighting":"dramatic Scottish Highland light, turquoise pool reflection, moody mountain atmosphere","style":"Scottish Highland editorial, fairy pool photography, magical wilderness","quality":"shot on Hasselblad H6D, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("tunnel_of_love", {"tag":"Tunnel of Love","subject":"a woman in the enchanted green railway tunnel","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Tunnel of Love, Klevan Ukraine, magical railway track enclosed by dense arching green tree canopy, sunlight filtering through leaves creating green cathedral effect, romantic natural tunnel stretching into distance, summer green paradise","lighting":"dappled green filtered sunlight, natural leaf cathedral glow, romantic green atmosphere","style":"romantic nature editorial, green tunnel photography","quality":"shot on Sony A7R V, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("chocolate_hills", {"tag":"Chocolate Hills","subject":"a woman among the mysterious Chocolate Hills","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Chocolate Hills, Bohol Philippines, over 1200 perfectly conical grass-covered hills stretching to horizon, dry season turns hills chocolate brown, symmetrical dome shapes of geological mystery, tropical blue sky, otherworldly landscape","lighting":"tropical Philippine sun, chocolate brown hill shadows, dramatic horizon scale","style":"geological mystery editorial, Philippine wonder photography","quality":"shot on Canon EOS R5, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("santorini_sunset", {"tag":"Santorini Sunset","subject":"a woman overlooking the Santorini caldera at sunset","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Santorini, Greece, iconic blue-domed white church on cliff edge, caldera sea view, Aegean sunset turning sky orange and pink, whitewashed Cycladic architecture cascading down volcanic cliff, Oia village, Mediterranean paradise","lighting":"dramatic Aegean sunset, golden orange-pink sky, white architecture warm glow, caldera reflection","style":"Mediterranean editorial, Santorini sunset photography, Greek island luxury","quality":"shot on Hasselblad H6D, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("cappadocia_balloons", {"tag":"Cappadocia Balloons","subject":"a woman among the fairy chimneys of Cappadocia at dawn","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Cappadocia, Turkey, hundreds of colorful hot air balloons floating over fairy chimney rock formations at dawn, rose valley tuff cones, ancient cave dwellings, pink and orange sunrise sky, magical Anatolian landscape","lighting":"magical dawn balloon glow, pink-orange sunrise, fairy chimney long shadows","style":"magical balloon editorial, Cappadocia dawn photography","quality":"shot on Canon EOS R5, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("chefchaouen_blue", {"tag":"Chefchaouen Blue","subject":"a woman in the blue streets of Chefchaouen","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Chefchaouen, Morocco, entire medina painted in shades of blue and white, narrow winding alleyways, blue-painted walls and stairs, potted flowers, Rif Mountains backdrop, magical monochromatic blue world","lighting":"soft Moroccan blue shadow, dappled alley light, blue wall reflection glow","style":"Moroccan blue editorial, Chefchaouen photography, monochromatic wonder","quality":"shot on Sony A7R V, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("hallstatt_lake", {"tag":"Hallstatt Lake","subject":"a woman at the fairy tale lakeside village of Hallstatt","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Hallstatt, Austria, picturesque Alpine village reflected in mirror-still lake, colorful historic houses on lake shore, dramatic Dachstein mountains backdrop, morning mist, church spire reflection, most photographed village in the world","lighting":"perfect mirror lake reflection, Alpine morning mist, soft golden hour glow","style":"Alpine fairy tale editorial, Hallstatt reflection photography","quality":"shot on Hasselblad H6D, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("shirakawa_snow", {"tag":"Shirakawa Snow","subject":"a woman in the snow-covered gasshō-zukuri village","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Shirakawa-go, Japan, UNESCO traditional gasshō-zukuri farmhouses with steep thatched roofs under heavy snow, winter illumination, mountain valley setting, smoke rising from farmhouses, magical winter Japanese village","lighting":"soft winter snow light, warm farmhouse window glow, blue hour snow reflection","style":"Japanese winter editorial, UNESCO village photography, snow paradise","quality":"shot on Canon EOS R5, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("positano_cliff", {"tag":"Positano Cliff","subject":"a woman overlooking the cliffside village of Positano","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Positano, Amalfi Coast Italy, pastel-colored buildings cascading dramatically down steep cliffs to Mediterranean sea, terracotta rooftops, lemon trees, colorful beach umbrellas below, dramatic Italian coastal atmosphere","lighting":"Mediterranean golden hour, pastel building warm glow, azure sea reflection","style":"Amalfi Coast editorial, Italian cliff village photography","quality":"shot on Sony A7R V, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("bruges_canal", {"tag":"Bruges Canal","subject":"a woman along the medieval canals of Bruges","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Bruges, Belgium, perfectly preserved medieval city with Gothic buildings reflected in still canals, stone bridges, cobblestone streets, swans on water, medieval guild houses, Venice of the North atmosphere","lighting":"soft Belgian light, canal reflection, medieval stone warmth, golden hour glow","style":"medieval canal editorial, Bruges reflection photography","quality":"shot on Hasselblad H6D, ultra-sharp, 8K, stunning, realistic proportions"}),
    ("cinque_terre_harbor", {"tag":"Cinque Terre Harbor","subject":"a woman in the colorful cliffside harbor villages of Cinque Terre","body":"full body shot","outfit":"minimal flowing fabric","material":"sheer lightweight fabric","environment":"Cinque Terre, Italian Riviera, five colorful fishing villages clinging to dramatic sea cliffs, pastel buildings in yellow, orange, pink and green, terraced vineyards on cliffs, turquoise Ligurian Sea, UNESCO coastal wonder","lighting":"Mediterranean golden light, colorful building warm glow, sea reflection","style":"Italian Riviera editorial, Cinque Terre photography","quality":"shot on Canon EOS R5, ultra-sharp, 8K, stunning, realistic proportions"}),
]

for filename, data in presets:
    path = PRESETS_DIR / f"{filename}.json"
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"저장: {filename}.json")

print(f"\n✅ 총 {len(presets)}개 완료!")
