# -*- coding: utf-8 -*-
"""
generate_new_category_jsons.py
Dark Fantasy / Bioluminescence / Spider Silk / Vortex 프리셋 JSON 생성
실행: python preset_builders/generate_new_category_jsons.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PRESETS_DIR = ROOT / "presets"
sys.path.insert(0, str(ROOT))

PRESETS = {
    # ──────────────────────────────────────────────
    # 👑 Body × Dark Fantasy Glamour
    # ──────────────────────────────────────────────
    "dark_super_glamour_succubus": ("👑 Body × Dark Fantasy Glamour", "Professional fashion photograph, full body shot. Model: supreme hourglass succubus queen, impossibly cinched waist, maximum curves with demonic elegance — dark fantasy ultimate feminine power. Body: spectacular extreme hourglass, porcelain-alabaster skin with subtle dark vein patterns, voluminous black waves with dark energy edges, expression dark-seductive-commanding. Wearing: minimal black micro string bikini with dark jewel embellishments — black bat wing silhouette emerging from back, black stiletto thigh-high platform boots 6-inch heel with dark crystal encrusting, black diamond choker with blood ruby center. Environment: dark gothic throne room, obsidian pillars, dark candles, midnight atmosphere, dark fantasy architecture. Lighting: dark candle amber + blood-red atmosphere, porcelain skin with dark vein glow, dramatic gothic chiaroscuro. Style: super glamour dark fantasy succubus editorial. Shot on Hasselblad X2D, gothic dark grade, portrait 2:3 vertical."),
    "dark_bbw_earth_witch": ("👑 Body × Dark Fantasy Glamour", "Professional fashion photograph, full body shot. Model: supreme BBW earth witch goddess, magnificent full figure commanding earth magic — full power earth sorceress. Body: supremely full magnificent figure, deep mahogany earth skin, massive natural locs entwined with living vines and moss, expression ancient-powerful. Wearing: minimal dark green earth micro dress with vine embellishments — living vines and roots rising from ground and wrapping around magnificent figure, dark earth platform boots 5-inch heel in root-covered ground, bone and crystal choker. Environment: ancient dark forest clearing, massive old-growth trees, bioluminescent mushrooms, earth magic atmosphere, roots responding to figure. Lighting: bioluminescent blue-green from mushrooms + warm earth amber from ground roots, mahogany skin in witch-forest light. Style: BBW dark fantasy earth witch editorial. Shot on Phase One XF IQ4, earth magic grade, portrait 2:3 vertical."),
    "dark_amazon_valkyrie": ("👑 Body × Dark Fantasy Glamour", "Professional fashion photograph, full body shot. Model: 185cm amazon valkyrie warrior goddess, towering powerful physique in dark Norse warrior aesthetic — ultimate dark fantasy warrior female. Body: extreme tall powerful physique, pale Norse skin, severe warrior braid with dark metal beads, expression battle-fierce. Wearing: minimal dark steel micro scale armor bikini — dark Norse warrior minimal armor, dark steel thigh-high platform warrior boots 6-inch heel, dark metal armband cuffs, dark Norse choker. Accessories: dark raven perched on raised arm. Environment: dark Norse battlefield at twilight, fallen warriors below, Valhalla clouds above, dark Norse mythology atmosphere. Lighting: twilight blue-purple from dark Norse sky, steel armor catching dying light, pale skin in valkyrie twilight. Style: amazon dark fantasy valkyrie editorial. Shot on Hasselblad X2D, Norse dark grade, portrait 2:3 vertical."),
    "dark_miniature_shadow_fairy": ("👑 Body × Dark Fantasy Glamour", "Professional fashion photograph, full body shot. Model: petite miniature shadow fairy, ultra-tiny figure with massive shadow wings — scale contrast between tiny body and enormous dark wings. Body: ultra-petite compact figure, dark alabaster skin, dark hair with shadow dust, expression mischievous-dark. Wearing: minimal black micro fairy dress barely there — massive shadow wings extending 3x body width behind tiny figure, black platform stiletto fairy boots 4-inch, dark crystal ear cuffs, shadow dust crown. Environment: dark enchanted forest, dark glowing mushrooms, shadow atmosphere, dark fairy realm, night forest. Lighting: dark bioluminescent glow from mushrooms, shadow wings absorbing light creating dark halo, tiny figure luminous in dark forest. Style: miniature dark fantasy shadow fairy editorial. Shot on Phase One XF IQ4, dark fairy grade, portrait 2:3 vertical."),
    "dark_bust_queen_vampire": ("👑 Body × Dark Fantasy Glamour", "Professional fashion photograph, full body shot. Model: legendary bust vampire queen, legendary figure with immortal dark elegance — dark fantasy ultimate feminine power. Body: legendary bust physique, porcelain-pale vampire skin, dark auburn waves, expression cold-immortal-dangerous. Wearing: minimal deep crimson micro corset — vampire queen minimal with crimson silk cape beginning behind, crimson patent thigh-high platform boots 5-inch heel, blood ruby choker, dark crimson lips. Environment: gothic castle interior, stone walls, dark candelabras, blood moon through arched window, bat silhouettes. Lighting: blood moon red through window + candelabra warm amber, pale vampire skin in blood moon light, crimson silk catching candlelight. Style: bust queen dark fantasy vampire editorial. Shot on Hasselblad X2D, vampire gothic grade, portrait 2:3 vertical."),
    "dark_latina_blood_moon": ("👑 Body × Dark Fantasy Glamour", "Professional fashion photograph, full body shot. Model: Colombian blood moon goddess, extreme hourglass commanding lunar blood magic — dark celestial feminine power. Body: extreme Colombian hourglass, warm bronze skin lit in blood moon red, dark waves with lunar energy edges, expression lunar-commanding. Wearing: minimal deep crimson micro string bikini — blood moon energy rising from ground around dramatic figure, crimson gold thigh-high platform boots 6-inch heel in blood moon field, lunar crescent choker. Environment: open dark field, full blood moon dominating sky, blood moon casting red light on everything, dark forest behind. Lighting: blood moon red from above, dramatic red-crimson on warm bronze skin, blood moon atmosphere total. Style: Colombian dark fantasy blood moon editorial. Shot on Phase One XF IQ4, blood moon grade, portrait 2:3 vertical."),
    "dark_vs_angel_fallen_angel": ("👑 Body × Dark Fantasy Glamour", "Professional fashion photograph, full body shot. Model: VS perfect fallen angel, flawless figure with broken dark wings — dark fantasy fallen beauty. Body: VS perfect hourglass, alabaster skin with dark veining, platinum waves with dark tips, expression fallen-sorrowful-beautiful. Wearing: minimal tattered white micro lace bikini — fallen angel minimal torn couture, one dark broken wing dragging, white platform stiletto boots 5-inch heel, broken dark halo crown above, dark crystal tears at eyes. Environment: dark gothic cathedral, broken stone, dark sky through broken windows, falling ash, fallen angel realm. Lighting: broken cathedral cold light + dark ash atmosphere, alabaster skin in fallen beauty light, dramatic broken cathedral space. Style: VS angel dark fantasy fallen angel editorial. Shot on Hasselblad X2D, fallen angel grade, portrait 2:3 vertical."),
    "dark_black_glamour_void_queen": ("👑 Body × Dark Fantasy Glamour", "Professional fashion photograph, full body shot. Model: extreme black glamour void queen, maximum ebony figure commanding absolute darkness — dark fantasy cosmic void ruler. Body: spectacular jet-black hourglass, deep ebony skin absorbing all light, voluminous natural coils with void edges, expression void-commanding. Wearing: minimal galaxy micro string bikini — void energy emanating from jet figure, darkness swirling around magnificent curves, gold thigh-high platform stiletto boots 6-inch heel in void space, obsidian choker with void gem. Environment: cosmic void throne, darkness with distant star points, void energy, cosmic dark fantasy realm. Lighting: minimal star point light from void, jet skin as void itself, pure void atmosphere, stars edge-lighting black. Style: black glamour dark fantasy void queen editorial. Shot on Phase One XF IQ4, void dark grade, portrait 2:3 vertical."),
    "dark_hot_glamour_dark_siren": ("👑 Body × Dark Fantasy Glamour", "Professional fashion photograph, full body shot. Model: hot glamour dark siren, dramatic cinched-waist curves with dark ocean power — dark fantasy ocean temptress. Body: dramatic hot glamour hourglass, sea-glass skin with bioluminescent undertones, dark waves with sea foam edges, expression siren-beckoning. Wearing: minimal deep ocean-black micro string bikini with bioluminescent details — dark ocean water rising around dramatic figure, dark tentacle elements from ocean below, black platform stiletto boots 5-inch heel in dark surf, bioluminescent choker. Environment: dark ocean cliff at midnight, bioluminescent waves below, dark sea, siren rock, midnight ocean atmosphere. Lighting: bioluminescent blue from ocean below + moon silver from above, sea-glass skin in midnight ocean light, dark siren atmosphere. Style: hot glamour dark fantasy siren editorial. Shot on Hasselblad X2D, dark siren grade, portrait 2:3 vertical."),
    "dark_brazil_jungle_goddess": ("👑 Body × Dark Fantasy Glamour", "Professional fashion photograph, full body shot. Model: Brazilian dark jungle goddess, maximum dramatic hip ratio commanding dark jungle power — dark fantasy jungle queen. Body: extreme Brazilian hip physique, rich deep terra-cotta skin, voluminous dark waves with jaguar patterns, expression jungle-commanding. Wearing: minimal dark jaguar print micro string bikini — dark jungle vines and creatures responding to generous curves, jaguar markings beginning on skin, dark platform wedge boots 5-inch heel in dark jungle floor, dark bone choker with jaguar claw. Environment: deep dark jungle, bioluminescent plants, dark canopy, jaguar shadows, dark jungle atmosphere, primal energy. Lighting: dark jungle bioluminescent green + amber torchlight, deep skin in dark jungle shadow-light, primal dark atmosphere. Style: Brazilian dark fantasy jungle goddess editorial. Shot on Phase One XF IQ4, dark jungle grade, portrait 2:3 vertical."),
    "dark_supermodel_ice_witch": ("👑 Body × Dark Fantasy Glamour", "Professional fashion photograph, full body shot. Model: 185cm+ supermodel ice witch, extreme tall figure commanding dark winter magic — dark fantasy ice sorceress. Body: extreme tall supermodel physique, ice-white skin with frost patterns, severe white-silver updo with ice crystals, expression cold-magical. Wearing: minimal white ice micro bandeau + micro skirt with frost details — dark ice formations rising from ground around tall figure, ice tendrils conforming to tall silhouette, clear ice platform stiletto mules 6-inch heel, ice crown, frost choker. Environment: dark winter forest, dead dark trees with ice, dark sky, ice magic atmosphere, winter dark fantasy. Lighting: cold blue-white ice magic glow from formations + dark winter atmosphere, ice-white skin in dark winter light, ice magic dramatic. Style: supermodel dark fantasy ice witch editorial. Shot on Hasselblad X2D, ice witch grade, portrait 2:3 vertical."),
    "dark_powerlifter_war_goddess": ("👑 Body × Dark Fantasy Glamour", "Professional fashion photograph, full body shot. Model: powerlifter dark war goddess, extreme defined musculature commanding battlefield dark power — dark fantasy ultimate warrior. Body: extreme powerlifter physique, defined everywhere, dark bronze-iron skin, severe warrior braid with dark war beads, expression battle-commanding. Wearing: minimal dark battle-worn micro armor breastplate + micro shorts — dark war energy around iron figure, battlefield dark atmosphere, matte black combat platform boots 5-inch heel on dark stone, dark iron armband cuffs, dark war choker. Environment: dark fantasy battlefield, dark sky, dark energy, fallen dark armies, war goddess domain, dark fantasy war realm. Lighting: dark battlefield fire from below + dark sky, iron skin in battle fire light, dark war goddess atmosphere. Shot on Phase One XF IQ4, dark war grade, portrait 2:3 vertical."),

    # ──────────────────────────────────────────────
    # 🌊 Bioluminescence Glamour
    # ──────────────────────────────────────────────
    "bio_amazon_anglerfish_lure": ("🌊 Bioluminescence Glamour", "Professional fashion photograph, full body shot. Model: 185cm amazon deep sea goddess, towering powerful physique with single anglerfish bioluminescent lure hovering above head — deep ocean darkness creating scale contrast. Body: extreme tall powerful physique, deep indigo-tinted skin, natural afro with bioluminescent blue tips, expression deep-sea-commanding. Wearing: minimal deep navy micro string bikini with bioluminescent trim — deep sea darkness around towering figure, single blue-white lure orb hovering 30cm above, navy chrome thigh-high platform stiletto boots 6-inch heel, bioluminescent choker. Environment: absolute deep ocean darkness, occasional deep sea creature lights, total black water, anglerfish atmosphere. Lighting: single lure orb blue-white + scattered deep sea creature bioluminescence, indigo skin in deep ocean bioluminescent dark. Style: amazon bioluminescence deep sea editorial. Shot on Hasselblad X2D, deep sea grade, portrait 2:3 vertical."),
    "bio_plus_size_jellyfish_bloom": ("🌊 Bioluminescence Glamour", "Professional fashion photograph, full body shot. Model: magnificent BBW jellyfish bloom goddess, full magnificent figure commanding ocean of bioluminescent jellyfish — surrounded by hundreds of glowing jellyfish. Body: supremely full magnificent figure, deep ocean-blue tinted skin, voluminous natural locs with jellyfish-trail bioluminescence. Wearing: minimal deep blue micro string bikini with jellyfish pattern — hundreds of bioluminescent jellyfish surrounding full magnificent figure, tentacles trailing around curves, navy patent thigh-high platform boots 5-inch heel with jellyfish at base, no jewelry — jellyfish crown. Environment: open dark ocean, jellyfish bloom filling entire frame, figure at bloom center, total bioluminescent atmosphere. Lighting: multi-jellyfish bioluminescent blue-purple from all around, magnificent figure in total jellyfish glow, ocean dark. Style: BBW bioluminescence jellyfish bloom editorial. Shot on Phase One XF IQ4, jellyfish grade, portrait 2:3 vertical."),
    "bio_petite_firefly_swarm": ("🌊 Bioluminescence Glamour", "Professional fashion photograph, full body shot. Model: petite miniature firefly goddess, ultra-tiny figure commanding massive firefly swarm — thousands of fireflies creating maximum scale contrast with tiny figure. Body: ultra-petite compact figure, warm olive skin, dark hair with firefly light in waves, expression wonder-commanding. Wearing: minimal white micro summer dress — massive firefly swarm of thousands surrounding tiny figure, creating living light constellation far larger than tiny body, white platform wedge boots 4-inch heel in summer field, no jewelry — fireflies are the crown. Environment: summer meadow at deep twilight, massive firefly swarm surrounding tiny figure, firefly lights reflecting in dew, summer night. Lighting: thousands of firefly warm amber-green from all positions, tiny figure lit by own firefly constellation, summer magic light. Style: petite bioluminescence firefly swarm editorial, scale goddess. Shot on Hasselblad X2D, firefly grade, portrait 2:3 vertical."),
    "bio_curvy_deep_sea_coral": ("🌊 Bioluminescence Glamour", "Professional fashion photograph, full body shot. Model: hot glamour deep sea coral goddess, dramatic cinched-waist curves surrounded by bioluminescent coral reef — deep sea coral ecosystem responding to her curves. Body: dramatic hot glamour hourglass, deep sea blue-tinted warm skin, dark waves with coral-bioluminescent streaks. Wearing: minimal coral-pink micro string bikini — bioluminescent coral rising and conforming around dramatic curves, coral tentacles creating natural reef-dress silhouette, coral patent thigh-high platform boots 5-inch heel, coral-pink choker. Environment: deep sea coral reef, bioluminescent coral filling frame, deep blue water, reef ecosystem, underwater atmosphere. Lighting: multi-coral bioluminescent pink-orange-green from all reef positions, warm skin in coral reef bioluminescent light, underwater depth. Style: hot glamour bioluminescence coral reef editorial. Shot on Phase One XF IQ4, coral reef grade, portrait 2:3 vertical."),
    "bio_athletic_comb_jelly_rainbow": ("🌊 Bioluminescence Glamour", "Professional fashion photograph, full body shot. Model: amazon athletic comb jelly goddess, towering powerful physique surrounded by comb jellies creating rainbow iridescent light show — comb jelly prismatic display around athletic figure. Body: extreme tall powerful physique, clear pale skin capturing rainbow comb jelly reflections, natural afro with rainbow comb jelly light in hair, expression ocean-powerful. Wearing: minimal transparent micro string bikini capturing rainbow light — comb jellies surrounding tall athletic figure, rainbow iridescence from comb jelly cilia playing over athletic physique, clear platform stiletto boots 6-inch heel, no jewelry — comb jelly rainbow is everything. Environment: dark ocean, comb jellies of all sizes surrounding figure, full rainbow spectrum iridescence, total comb jelly atmosphere. Lighting: full rainbow comb jelly iridescence from all positions, clear skin as rainbow canvas, total iridescent light show. Style: amazon bioluminescence comb jelly editorial. Shot on Hasselblad X2D, comb jelly rainbow grade, portrait 2:3 vertical."),
    "bio_supermodel_sea_sparkle": ("🌊 Bioluminescence Glamour", "Professional fashion photograph, full body shot. Model: 185cm+ supermodel sea sparkle goddess, extreme tall figure standing in bioluminescent waves — each wave breaking in blue fire at her feet. Body: extreme tall supermodel physique, night-sky dark skin, sleek dark hair with sea-sparkle blue in waves, expression oceanic-commanding. Wearing: minimal navy micro string bikini — bioluminescent breaking waves creating blue fire at feet and rising around extreme tall figure, navy chrome thigh-high platform stiletto boots 6-inch heel in bioluminescent surf, sea-glass choker. Environment: dark beach at night, bioluminescent waves breaking in electric blue fire, sea sparkle filling beach, ocean dark behind. Lighting: bioluminescent wave blue from breaking waves below, night sky dark above, dark skin in electric blue sea-fire light. Style: supermodel bioluminescence sea sparkle editorial. Shot on Phase One XF IQ4, sea sparkle grade, portrait 2:3 vertical."),
    "bio_bbw_giant_squid_ink": ("🌊 Bioluminescence Glamour", "Professional fashion photograph, full body shot. Model: magnificent BBW deep sea ink goddess, full magnificent figure in giant squid ink cloud — bioluminescent ink creating living dark galaxy around full figure. Body: supremely full magnificent figure, deep ebony skin, voluminous natural locs with ink-cloud tendrils, expression deep-sea-queen. Wearing: minimal black micro string bikini — giant squid bioluminescent ink cloud surrounding full figure, ink tendrils trailing around magnificent curves, black patent thigh-high platform boots 5-inch heel in ink cloud, dark choker. Environment: deep ocean, bioluminescent ink cloud filling frame, deep sea darkness, ink galaxy atmosphere. Lighting: bioluminescent ink blue-purple glow from ink cloud surrounding figure, ebony skin in ink-cloud galaxy light. Style: BBW bioluminescence giant squid editorial. Shot on Hasselblad X2D, deep sea ink grade, portrait 2:3 vertical."),
    "bio_latina_dinoflagellate": ("🌊 Bioluminescence Glamour", "Professional fashion photograph, full body shot. Model: Colombian extreme hourglass dinoflagellate goddess, dramatic curves commanding electric blue bioluminescent wave — dinoflagellate blue fire in breaking surf. Body: extreme Colombian hourglass, warm bronze-copper skin soaked in surf, dark waves with blue dinoflagellate light. Wearing: minimal navy micro string bikini soaked in luminescent surf — bioluminescent blue dinoflagellate fire rising from breaking waves around dramatic figure, navy gold thigh-high platform boots 6-inch heel in blue-fire surf, no jewelry — blue fire is the jewelry. Environment: dark beach at night, bioluminescent blue waves breaking around figure, electric blue fire surf, dinoflagellate atmosphere. Lighting: electric blue dinoflagellate fire from breaking surf, warm bronze skin in electric blue contrast, dramatic ocean dark behind. Style: Colombian bioluminescence dinoflagellate editorial. Shot on Phase One XF IQ4, electric blue grade, portrait 2:3 vertical."),
    "bio_bust_queen_abyss_glow": ("🌊 Bioluminescence Glamour", "Professional fashion photograph, full body shot. Model: legendary bust abyss glow goddess, legendary figure in absolute deep ocean abyss — surrounded by deepest ocean bioluminescent organisms. Body: legendary bust physique, deep sea pale skin with subtle bioluminescent undertone, dark hair, expression abyss-commanding. Wearing: minimal deep blue micro corset — abyss organisms creating bioluminescent corona around legendary figure, deep sea creature lights orbiting from all distances, deep blue thigh-high platform boots 5-inch heel, bioluminescent choker. Environment: absolute ocean abyss, deepest ocean darkness, scattered abyss organism lights, complete abyss atmosphere, depth pressure visible. Lighting: scattered abyss organism bioluminescence from all distances, pale skin as only natural light source in abyss, bioluminescent corona. Style: bust queen bioluminescence abyss editorial. Shot on Hasselblad X2D, abyss grade, portrait 2:3 vertical."),
    "bio_black_glamour_viper_fish": ("🌊 Bioluminescence Glamour", "Professional fashion photograph, full body shot. Model: extreme black glamour viperfish goddess, maximum ebony figure surrounded by deep sea viperfish bioluminescent light lines — photophore light lines creating geometry around jet figure. Body: spectacular jet-black hourglass, deepest ebony skin, voluminous natural coils, expression deep-sea-predator. Wearing: minimal black micro string bikini — viperfish photophore light lines creating geometric bioluminescent pattern around jet figure, lines running parallel to curves, black patent thigh-high platform boots 6-inch heel, photophore-pattern choker. Environment: complete deep sea darkness, viperfish photophore lines creating geometric light architecture, absolute abyss. Lighting: viperfish photophore line bioluminescent blue-white geometric patterns only, jet skin as absolute darkness between light lines, predator atmosphere. Style: black glamour bioluminescence viperfish editorial. Shot on Phase One XF IQ4, deep predator grade, portrait 2:3 vertical."),
    "bio_vs_angel_crystal_medusa": ("🌊 Bioluminescence Glamour", "Professional fashion photograph, full body shot. Model: VS perfect angel crystal medusa goddess, flawless figure with crystal medusa trailing behind — bioluminescent crystal medusa as living couture veil. Body: VS perfect hourglass, translucent pale skin, platinum waves, expression ethereal-commanding. Wearing: minimal white micro lace bikini — massive crystal medusa trailing behind perfect figure, medusa bell forming living couture cape, white platform stiletto boots 5-inch heel, crystal medusa tentacle jewelry. Environment: dark ocean, single massive crystal medusa behind figure, translucent medusa illuminating surrounding water, medusa-goddess symbiosis. Lighting: crystal medusa bioluminescent blue-white from medusa behind, pale skin translucent in medusa glow, perfect figure as medusa goddess. Style: VS angel bioluminescence crystal medusa editorial. Shot on Hasselblad X2D, crystal medusa grade, portrait 2:3 vertical."),
    "bio_powerlifter_hydrothermal": ("🌊 Bioluminescence Glamour", "Professional fashion photograph, full body shot. Model: powerlifter hydrothermal vent goddess, extreme defined musculature at hydrothermal vent — vent tube worms and chemosynthetic bioluminescence around iron figure. Body: extreme powerlifter physique, defined everywhere, deep-sea bronze skin, severe warrior braid, expression vent-commanding. Wearing: minimal matte black micro sports bra + micro shorts — hydrothermal vent tube worms and bioluminescent vent organisms surrounding iron figure, vent energy rising from below, matte black combat boots 5-inch heel at vent base, iron cuffs. Environment: deep ocean hydrothermal vent field, superheated vent rising, tube worm colonies, vent ecosystem, absolute deep sea. Lighting: hydrothermal vent bioluminescent and thermal glow from below, iron skin in vent thermal light, absolute ocean floor. Style: powerlifter bioluminescence hydrothermal editorial. Shot on Phase One XF IQ4, hydrothermal grade, portrait 2:3 vertical."),

    # ──────────────────────────────────────────────
    # 🕸️ Spider Silk Glamour
    # ──────────────────────────────────────────────
    "silk_amazon_web_cathedral": ("🕸️ Spider Silk Glamour", "Professional fashion photograph, full body shot. Model: 185cm amazon web cathedral goddess, towering powerful physique at center of massive spider web cathedral — web architecture matching her towering scale. Body: extreme tall powerful physique, copper skin, natural afro, expression web-commanding. Wearing: minimal silver micro string bikini — massive spider web cathedral structure filling full frame, web strands 1-5mm diameter forming gothic arch architecture, silver chrome thigh-high platform stiletto boots 6-inch heel at web cathedral base, silver web armband. Environment: dark space, massive web cathedral surrounding towering figure, web architecture spanning floor to ceiling, dew on strands catching light. Lighting: side spotlight, web strands creating silver light-line architecture, copper skin glowing through web frame. Style: amazon spider silk web cathedral editorial. Shot on Hasselblad X2D, web cathedral grade, portrait 2:3 vertical."),
    "silk_bbw_cocoon_emergence": ("🕸️ Spider Silk Glamour", "Professional fashion photograph, full body shot. Model: magnificent BBW cocoon emergence goddess, full magnificent figure emerging from massive spider silk cocoon — emergence moment, silk splitting to reveal magnificent figure. Body: supremely full magnificent figure, deep mahogany skin, voluminous locs emerging from silk strands. Wearing: minimal white silk micro dress with cocoon remnants — white spider silk cocoon splitting apart as full figure emerges, silk strands trailing from magnificent curves, white patent thigh-high platform boots 5-inch heel at emergence base, silk-wrapped jewelry. Environment: dark space, massive white cocoon splitting, silk strands catching light as figure emerges, emergence atmosphere. Lighting: warm overhead spot, splitting cocoon silk catching light, mahogany skin emerging luminous from white silk. Style: BBW spider silk cocoon emergence editorial. Shot on Phase One XF IQ4, cocoon grade, portrait 2:3 vertical."),
    "silk_petite_dew_drop_web": ("🕸️ Spider Silk Glamour", "Professional fashion photograph, full body shot. Model: petite miniature dew drop web goddess, ultra-tiny figure among massive dew-covered web — web strands towering over tiny figure creating maximum scale contrast. Body: ultra-petite compact figure, dewy pale skin, dark hair with dew drops, expression wonder-among-giants. Wearing: minimal white micro bikini — massive dew-drop spider web surrounding tiny figure, each dew drop reflecting tiny goddess figure, white platform wedge boots 4-inch heel on web strand, dew drop ear jewelry. Environment: dawn garden, massive dew-covered spider web filling frame, tiny figure among enormous web architecture, dawn light on dew drops. Lighting: dawn side light, dew drops catching light as thousand crystal spheres, tiny figure luminous among giant web. Style: petite spider silk dew drop editorial, scale goddess. Shot on Hasselblad X2D, dew drop grade, portrait 2:3 vertical."),
    "silk_curvy_golden_silk_gown": ("🕸️ Spider Silk Glamour", "Professional fashion photograph, full body shot. Model: hot glamour golden silk web gown goddess, dramatic cinched-waist curves draped in real golden spider silk — golden orb-weaver silk naturally conforming to dramatic curves. Body: dramatic hot glamour hourglass, warm caramel skin, dark waves with golden silk threads caught. Wearing: minimal gold micro string bikini — golden spider silk (real gold color) draping naturally over dramatic curves as living gown, silk conforming to every curve naturally, caramel gold stiletto thigh-high platform boots 5-inch heel, gold web choker. Environment: dark opulent studio, golden silk web forming natural gown architecture around curves, individual silk strands visible, silk catching light as liquid gold. Lighting: warm gold key, golden silk strands catching as liquid gold lines, caramel skin warm through golden silk gown. Style: hot glamour spider silk golden gown editorial. Shot on Phase One XF IQ4, golden silk grade, portrait 2:3 vertical."),
    "silk_athletic_web_armor": ("🕸️ Spider Silk Glamour", "Professional fashion photograph, full body shot. Model: amazon athletic web armor goddess, towering powerful physique armored in spider silk — silk forming precision athletic armor over powerful figure. Body: extreme tall powerful physique, bronze-copper oiled skin, severe high bun, expression warrior-silk. Wearing: minimal black micro sports bra + micro shorts — spider silk forming precision geometric web armor over athletic figure, silk panels conforming to muscle definition, black chrome thigh-high platform stiletto boots 6-inch heel with web armoring, silver web cuff armor. Environment: dark precision studio, web armor catching directional light as silver line-work over bronze figure. Lighting: hard directional light, web armor catching as precise silver lines over bronze skin, web armor precision. Style: amazon spider silk web armor editorial. Shot on Hasselblad X2D, web armor grade, portrait 2:3 vertical."),
    "silk_supermodel_spiral_web": ("🕸️ Spider Silk Glamour", "Professional fashion photograph, full body shot. Model: 185cm+ supermodel spiral web goddess, extreme tall figure at center of massive spiral web — orb-weaver spiral web scaled to towering figure. Body: extreme tall supermodel physique, alabaster skin, severe fashion updo, cheekbones. Wearing: minimal white micro bandeau + micro thong — massive orb-weaver spiral web surrounding extreme tall figure, web spiral centered on figure, each silk strand visible, alabaster platform stiletto mules 6-inch heel at web center, geometric ear cuff. Environment: dark space, massive perfect orb-weaver spiral web filling full frame, figure at web center, web architecture perfect. Lighting: side spot, spiral web catching as perfect silver geometry, alabaster skin at geometric web center. Style: supermodel spider silk spiral web editorial. Shot on Phase One XF IQ4, spiral web grade, portrait 2:3 vertical."),
    "silk_bbw_funnel_web_throne": ("🕸️ Spider Silk Glamour", "Professional fashion photograph, full body shot. Model: magnificent BBW funnel web throne goddess, full magnificent figure seated on massive funnel web throne — web architecture becoming throne for full goddess figure. Body: supremely full magnificent figure, deep ebony skin, natural locs, expression web-queen-enthroned. Wearing: minimal black micro dress — massive funnel web throne of spider silk surrounding and supporting full figure, web architecture as throne, web backing as living headpiece, black patent thigh-high platform boots 5-inch heel on web floor, web crown. Environment: dark space, massive funnel web throne filling frame, figure enthroned in web architecture, web queen domain. Lighting: dramatic side lighting, web throne catching light as silver architecture, ebony skin on web throne. Style: BBW spider silk funnel web throne editorial. Shot on Phase One XF IQ4, web throne grade, portrait 2:3 vertical."),
    "silk_latina_web_veil": ("🕸️ Spider Silk Glamour", "Professional fashion photograph, full body shot. Model: Colombian extreme hourglass web veil goddess, dramatic curves draped in massive spider web veil — web as ultimate bridal editorial veil. Body: extreme Colombian hourglass, warm bronze skin, dark waves with web drops, expression web-bride-fierce. Wearing: minimal white micro string bikini — massive spider web veil trailing from head to floor behind dramatic figure, web veil with morning dew catching light, white gold stiletto thigh-high platform boots 6-inch heel, web tiara crown. Environment: dark romantic studio, massive web veil filling frame, web catching light behind dramatic figure, romance of silk and curves. Lighting: warm romantic side light, web veil catching as luminous silver behind curves, bronze skin warm against silver web veil. Style: Colombian spider silk web veil editorial. Shot on Hasselblad X2D, web veil grade, portrait 2:3 vertical."),
    "silk_bust_queen_orb_web": ("🕸️ Spider Silk Glamour", "Professional fashion photograph, full body shot. Model: legendary bust orb web goddess, legendary figure at center of perfect orb web — web framing legendary proportions. Body: legendary bust physique, cream skin, auburn waves with web strands caught, expression web-centered. Wearing: minimal cream micro corset — perfect orb web surrounding legendary figure, web strands radiating from figure as center point, web framing legendary bust proportions, cream patent thigh-high platform boots 5-inch heel at web center, crystal web choker. Environment: dark studio, perfect orb web filling frame, figure at geometric web center, web architecture perfect. Lighting: warm side spot, web catching as geometric silver lines, cream skin luminous at web center. Style: bust queen spider silk orb web editorial. Shot on Phase One XF IQ4, orb web grade, portrait 2:3 vertical."),
    "silk_black_glamour_black_widow": ("🕸️ Spider Silk Glamour", "Professional fashion photograph, full body shot. Model: extreme black glamour black widow goddess, maximum ebony figure in black widow web — darkest silk web matching jet skin creating ultimate dark editorial. Body: spectacular jet-black hourglass, deepest ebony skin, voluminous natural coils, expression black-widow-predator. Wearing: minimal all-black micro string bikini with red hourglass jewel at waist — black widow web surrounding jet figure, web architecture in absolute black, single red hourglass jewel the only color, black patent thigh-high platform boots 6-inch heel, black widow web choker with ruby. Environment: absolute dark studio, black widow web in darkness, only red jewel catching light, predator atmosphere. Lighting: dramatic hard spot on ruby red hourglass jewel only, jet skin absorbing everything, red jewel as sole light source in black web. Style: black glamour black widow spider silk editorial. Shot on Hasselblad X2D, black widow grade, portrait 2:3 vertical."),
    "silk_vs_angel_dewdrop_cathedral": ("🕸️ Spider Silk Glamour", "Professional fashion photograph, full body shot. Model: VS perfect angel dew drop cathedral goddess, flawless figure in massive dew-cathedral web — angel among crystalline dew architecture. Body: VS perfect hourglass, golden skin, beach waves with dew drops, expression angelic-ethereal. Wearing: minimal white micro lace bikini — massive dew-covered web cathedral surrounding perfect angel figure, each dew drop a crystal sphere, white platform stiletto boots 5-inch heel at cathedral center, dew drop pearl jewelry. Environment: dawn garden, massive dew-cathedral web in morning light, golden morning light through web architecture, angel in dew cathedral. Lighting: morning golden side light, dew drops as crystal sphere constellation, golden skin in dawn dew-cathedral light. Style: VS angel spider silk dew cathedral editorial. Shot on Phase One XF IQ4, dew cathedral grade, portrait 2:3 vertical."),
    "silk_powerlifter_web_cage": ("🕸️ Spider Silk Glamour", "Professional fashion photograph, full body shot. Model: powerlifter web cage goddess, extreme defined musculature in silk web cage — web architecture containing iron power. Body: extreme powerlifter physique, defined everywhere, bronze-iron skin, severe warrior braid, expression iron-caged. Wearing: minimal matte black micro sports bra + micro shorts — thick spider silk web cage surrounding iron figure, web bars 5-10mm diameter, cage structure, web cage becoming display of iron physique, matte black combat boots 5-inch heel in cage, iron cuffs against cage wall. Environment: dark industrial space, web cage filling frame, iron figure displayed in web cage structure, power and web contrast. Lighting: hard industrial light, web cage bars casting shadow lines over iron physique, bronze skin in cage shadow-light. Style: powerlifter spider silk web cage editorial. Shot on Hasselblad X2D, web cage grade, portrait 2:3 vertical."),

    # ──────────────────────────────────────────────
    # 🌪️ Vortex & Tornado Glamour (재작성 버전)
    # ──────────────────────────────────────────────
    "vortex_amazon_fire_tornado": ("🌪️ Vortex & Tornado Glamour", "Professional fashion photograph, full body shot. Model: 185cm amazon goddess, extreme tall powerful physique, bronze-copper oiled skin gleaming in fire light, natural afro with fire-energy edges, lips parted, expression smoldering-commanding. Wearing: deep red metallic micro string bikini, fire-scorched lace-up gladiator sandal heels 4-inch at tornado base. Active fire tornado rising 3x her height surrounding her towering figure, fire walls whirling in perfect vortex. Environment: dark volcanic open space, fire vortex filling full frame, ember sparks orbiting figure. Lighting: fire tornado orange-red from all vortex positions, bronze skin blazing in fire glow, dramatic volcanic chiaroscuro. Style: amazon fire tornado glamour editorial, dangerous sensual power. Shot on Phase One XF IQ4, fire grade, portrait 2:3 vertical."),
    "vortex_bbw_water_cyclone": ("🌪️ Vortex & Tornado Glamour", "Professional fashion photograph, full body shot. Model: super BBW goddess, supremely full magnificent figure, deep mahogany skin soaked in cyclone spray, voluminous natural locs whipping in cyclone wind, expression cyclone-queen. Wearing: deep blue micro string bikini soaked transparent against full magnificent curves, bare feet in cyclone surf, gold ankle chain. Massive water cyclone rising from ocean around full figure, water walls curving around magnificent curves. Environment: open dark ocean, water vortex room surrounding figure, seafoam swirling at feet. Lighting: silver-blue ocean light through cyclone walls, water droplets catching light against mahogany skin, dramatic storm sky. Style: BBW water cyclone glamour editorial, full figure commanding ocean. Shot on Hasselblad X2D, storm grade, portrait 2:3 vertical."),
    "vortex_petite_sand_devil": ("🌪️ Vortex & Tornado Glamour", "Professional fashion photograph, full body shot. Model: miniature petite goddess, ultra-tiny compact figure, warm golden sand skin, dark hair total wind-chaos, expression fierce-tiny. Wearing: desert gold micro string bikini barely there, lace-up ankle boots 3-inch heel at sand vortex axis. Massive sand devil vortex 10x her height rising from desert around ultra-tiny figure — maximum scale contrast. Environment: desert floor, scorching sand vortex surrounding tiny goddess, desert horizon stretching beyond, mirage heat visible. Lighting: desert golden hour filtering through sand vortex, tiny figure warm amber in sand-filtered light, epic scale contrast. Style: petite sand devil scale glamour editorial, tiny figure commanding vast desert force. Shot on Phase One XF IQ4, desert grade, portrait 2:3 vertical."),
    "vortex_curvy_rose_tornado": ("🌪️ Vortex & Tornado Glamour", "Professional fashion photograph, full body shot. Model: hot glamour goddess, dramatic extreme cinched-waist hourglass, warm caramel skin, dark waves cascading in rose petal wind, expression sultry-rose-center. Wearing: deep rose ultra-sheer micro slip dress clinging to every curve, strappy rose gold stiletto sandals 4-inch heel at rose vortex center. Thousands of red and pink rose petals in perfect tornado formation surrounding dramatic hourglass figure. Environment: dark romantic space, rose petal tornado filling full frame, petals tracing her curves as they spiral. Lighting: warm rose-gold from petal catch-light, caramel skin glowing through rose-filtered tornado light, romantic sensual atmosphere. Style: hot glamour rose tornado editorial, curves commanding romance. Shot on Hasselblad X2D, rose grade, portrait 2:3 vertical."),
    "vortex_athletic_lightning_vortex": ("🌪️ Vortex & Tornado Glamour", "Professional fashion photograph, full body shot. Model: VS angel athletic goddess, flawless toned physique, golden skin with electric corona, platinum waves with lightning-charged edges, expression electric-fierce. Wearing: silver metallic micro sports bra + micro thong, clear lucite mule heels 5-inch at vortex base. Plasma lightning forming perfect spiral vortex around athletic flawless figure, electric arcs dancing over toned skin. Environment: dark storm space, lightning vortex reaching all frame edges, ozone atmosphere. Lighting: plasma blue-white lightning from all arc positions, golden skin in electric strobe light, electric vortex dramatic. Style: VS angel lightning vortex glamour editorial, electric beauty. Shot on Phase One XF IQ4, lightning grade, portrait 2:3 vertical."),
    "vortex_supermodel_galaxy_spiral": ("🌪️ Vortex & Tornado Glamour", "Professional fashion photograph, full body shot. Model: 185cm+ supermodel tall goddess, impossibly long legs, deep space dark skin, sleek silver hair, razor cheekbones, expression cosmic cold-editorial. Wearing: galaxy iridescent micro string bikini shifting colors, barefoot in starfield, constellation anklet only. Galaxy spiral vortex surrounding extreme tall figure, stars and nebulae in perfect Fibonacci spiral formation, figure as galactic axis. Environment: infinite cosmic void, galaxy spiral filling frame, nebula colors shifting around tall silhouette. Lighting: galaxy starlight + nebula purple-blue glow from spiral positions, dark skin as void center, stars edge-lighting tall silhouette. Style: supermodel galaxy spiral editorial, cosmic haute couture. Shot on Hasselblad X2D, cosmic grade, portrait 2:3 vertical."),
    "vortex_bbw_cloud_column": ("🌪️ Vortex & Tornado Glamour", "Professional fashion photograph, full body shot. Model: Colombian extreme hourglass BBW goddess, spectacular full figure with dramatic waist definition, storm-dark skin, voluminous natural locs in storm wind, expression storm-queen-fierce. Wearing: storm grey wet micro string bikini clinging to spectacular curves, knee-high lace-up storm boots 4-inch heel at cloud column base. Massive cumulonimbus cloud column rising from her figure to sky, lightning flashing in cloud walls around spectacular curves. Environment: open storm field, cloud column vortex rising to sky, lightning illuminating from within cloud walls. Lighting: dramatic storm chiaroscuro, lightning flash from cloud column, storm-dark skin in electric storm light. Style: Colombian BBW storm cloud glamour editorial, full curves commanding storm. Shot on Phase One XF IQ4, storm grade, portrait 2:3 vertical."),
    "vortex_latina_petal_whirlwind": ("🌪️ Vortex & Tornado Glamour", "Professional fashion photograph, full body shot. Model: Colombian extreme hourglass goddess, sculpted maximum curves with dramatic hip-to-waist ratio, warm bronze skin, voluminous dark waves in petal wind, expression sensual-vortex-commanding. Wearing: tropical micro string bikini in hot pink and gold, strappy wedge sandals 4-inch heel at whirlwind center. Massive tropical flower petal whirlwind — hibiscus, bougainvillea, plumeria — swirling around dramatic Colombian curves, petals tracing her silhouette. Environment: dark tropical space, tropical petal whirlwind filling frame, petals in perfect vortex. Lighting: warm tropical amber from petal catch-light, bronze skin warm through tropical petal-filtered light, sensual whirlwind drama. Shot on Hasselblad X2D, tropical grade, portrait 2:3 vertical."),
    "vortex_bust_queen_aurora_vortex": ("🌪️ Vortex & Tornado Glamour", "Professional fashion photograph, full body shot. Model: legendary bust queen goddess, impossibly full legendary bust with cinched waist, pale arctic skin luminous in aurora light, dark waves in aurora wind, expression aurora-commanding-seductive. Wearing: aurora iridescent micro corset barely containing legendary proportions, clear crystal mule heels 5-inch at aurora center. Aurora borealis forming perfect spiral vortex around legendary figure, green-purple-blue aurora conforming to her legendary silhouette. Environment: arctic dark space, aurora vortex filling frame, aurora colors shifting around legendary proportions. Lighting: aurora green-purple-blue from all vortex positions, pale skin translucent in aurora color shifts, legendary bust lit in aurora glow. Style: bust queen aurora vortex glamour editorial. Shot on Phase One XF IQ4, aurora grade, portrait 2:3 vertical."),
    "vortex_black_glamour_void_spiral": ("🌪️ Vortex & Tornado Glamour", "Professional fashion photograph, full body shot. Model: extreme black glamour goddess, spectacular jet-black hourglass, deepest ebony skin absorbing all light, voluminous natural coils with void-star edges, expression void-queen-dangerous. Wearing: galaxy micro string bikini with gold constellation details, gold stiletto ankle strap sandals 5-inch heel at void center. Cosmic void spiral forming around jet figure, stars orbiting in perfect Fibonacci spiral, darkness and star points in vortex formation. Environment: cosmic void, void spiral filling frame, stars in perfect spiral orbit around jet figure. Lighting: star constellation point-light only, jet ebony skin as void center, stars edge-lighting black curves in gold. Style: black glamour void spiral editorial, cosmic dark goddess. Shot on Hasselblad X2D, void grade, portrait 2:3 vertical."),
    "vortex_vs_angel_snow_vortex": ("🌪️ Vortex & Tornado Glamour", "Professional fashion photograph, full body shot. Model: VS perfect angel goddess, flawless hourglass, snow-pale luminous skin, platinum waves in snow crystal wind, expression winter-angel-fierce. Wearing: white micro lace triangle bikini, white satin mary jane heels 4-inch at snow vortex center. Massive snow crystal vortex surrounding perfect angel figure, individual snowflakes visible in perfect vortex formation, snow crystals catching light around perfect curves. Environment: dark winter space, snow crystal vortex filling frame, snowflakes in perfect vortex formation. Lighting: winter white-blue from snow crystal catch-light, pale skin luminous against dark vortex, snow crystals creating sparkle corona around angel figure. Style: VS angel snow vortex glamour editorial, icy beauty. Shot on Phase One XF IQ4, snow grade, portrait 2:3 vertical."),
    "vortex_powerlifter_magma_vortex": ("🌪️ Vortex & Tornado Glamour", "Professional fashion photograph, full body shot. Model: powerlifter goddess, extreme defined musculature with feminine power, volcanic bronze-iron skin gleaming in magma light, severe warrior braid, expression magma-commanding-dangerous. Wearing: matte black micro sports bra + micro shorts, iron-reinforced combat ankle boots 3-inch heel at magma vortex base, iron wrist cuffs glowing in magma heat. Magma vortex rising in perfect spiral around iron figure, molten rock in spiral formation, heat distortion visible around defined physique. Environment: volcanic space, magma vortex filling frame, molten rock spiral around iron figure. Lighting: magma orange-red from all vortex positions, iron skin blazing in magma spiral light, volcanic heat atmosphere. Style: powerlifter magma vortex glamour editorial, iron beauty commanding volcano. Shot on Phase One XF IQ4, magma grade, portrait 2:3 vertical."),
}

# ── 실행 ─────────────────────────────────────────────────────

created = []
skipped = []
errors = []

for pid, (cat, prompt) in PRESETS.items():
    json_path = PRESETS_DIR / f"{pid}.json"
    if json_path.exists():
        skipped.append(pid)
        continue
    try:
        data = {"id": pid, "prompt": prompt, "category": cat}
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        created.append(pid)
        print(f"  OK: {pid}")
    except Exception as e:
        errors.append((pid, str(e)))
        print(f"  ERR: {pid} - {e}")

print(f"\n{'='*50}")
print(f"생성: {len(created)}개 / 스킵: {len(skipped)}개 / 오류: {len(errors)}개")
