# -*- coding: utf-8 -*-
"""
core/sss_tier.py 생성 스크립트
- 아카이브된 SSS_TIER, SS_TIER 데이터에서
- 실제 presets/*.json 에 존재하는 키만 필터링해서 저장
"""
import os, glob, ast

# 실제 존재하는 프리셋 키
existing = set(
    os.path.basename(p).replace('.json', '')
    for p in glob.glob('presets/*.json')
)
print(f"실제 프리셋: {len(existing)}개")

# ── SSS_TIER 원본 데이터 ──
SSS_RAW = {
    # Spa & Wet
    "amalfi_cliff_storm", "bali_rain_wet", "bangkok_monsoon_silk",
    "bhutan_himalaya_pool", "blue_lagoon_silica", "cape_town_atlantic_storm",
    "champagne_bubble_bath", "chocolate_spa_drip", "costa_rica_jungle_pool",
    "dubai_rooftop_storm", "gold_leaf_spa", "greek_sea_emergence",
    "greenland_glacier_pool", "hammam_marble_glam", "honey_drip_spa",
    "hot_spring_nude_editorial", "japan_snow_onsen", "kuala_lumpur_monsoon",
    "lagoon_surface_break", "lisbon_rain_tiles", "monaco_wet_silk",
    "morocco_riad_pool", "mud_spa_clay", "mumbai_monsoon_sari",
    "new_york_rooftop_rain", "new_zealand_geyser", "niagara_mist_goddess",
    "oil_massage_table", "pamukkale_travertine", "rio_corcovado_storm",
    "rose_petal_bath", "ryokan_hinoki_bath", "salt_scrub_steam",
    "santorini_aegean_storm", "venice_acqua_alta", "yunoko_bamboo_onsen",
    "maldives_bikini_editorial",
    # Minimal Cover
    "body_chain_only_glam", "flower_body_only", "rope_art_editorial",
    "ribbon_wrap_glam", "crystal_body_cover", "seaweed_coral_body",
    # Sci-Fi & Biopunk
    "metamorphosis_editorial", "virus_pattern_body", "spine_tech_implant",
    "neural_lace_crown", "jellyfish_bloom_float", "carnivorous_plant_trap",
    "coral_organism_absorption", "petri_dish_giant_macro",
    "gene_sequencer_data_skin", "specimen_amber_suspended",
    "alien_host_glam", "toxic_spore_cloud", "mutation_bloom",
    "prosthetic_art", "cyborg_partial_reveal", "symbiote_second_skin",
    "mycelium_web_consumed", "abyssal_pressure_glam",
    "quarantine_protocol_breach", "clean_room_latex_protocol",
    "cryo_emergence_wet", "synthetic_skin_tear", "infection_glam",
    "exoskeleton_stripped",
    # Mirror & Reflection
    "liquid_metal_pool", "chrome_sphere_world", "crystal_cave_skin_facets",
    "glass_box_all_angles", "flooded_temple_mirror", "mercury_lake_reflection",
    "hall_of_mirrors_glam", "mirrored_skyscraper_facade", "foil_room_crush",
    "supercar_chrome_reflect", "polished_obsidian_floor", "soap_bubble_dome",
    "window_rain_double", "prism_light_body_split", "rain_puddle_city_invert",
    "salt_flat_sky_merge", "broken_mirror_multiplied", "venetian_mirror_boudoir",
    "infinity_mirror_goddess", "two_way_mirror_watcher",
    "morning_dew_skin_reflection", "infinity_pool_edge_reflect",
    "cheval_mirror_reveal", "obsidian_mirror_ritual",
    # QUAD/QUINT/HEXA/OCTET
    "quad_four_ages_bodypaint", "quad_four_classical_elements_klimt",
    "quad_four_seasons_night_bodypaint", "quint_five_senses_bodypaint",
    "quint_five_worlds_bodypaint", "quint_five_elements_wuxing_bodypaint",
    "hexa_rainbow_spectrum_bodypaint", "quad_four_civilizations_bodypaint",
    "quad_four_gemstones_bodypaint", "quad_cmyk_bodypaint",
    "quad_four_metals_bodypaint", "quint_five_mythologies_bodypaint",
    "quint_five_oceans_deep_bodypaint", "quint_five_sacred_colors_bodypaint",
    "hexa_six_chakras_bodypaint", "octet_planets_solar_bodypaint",
    # Night/Slip/Animal/Theatrical
    "club_vip_neon_goddess", "club_rooftop_citylight", "micro_sequin_club",
    "rooftop_micro_night", "silk_slip_dawn_hotel", "satin_slip_vanity_noir",
    "satin_slip_micro", "leopard_power_editorial", "leopard_micro_studio",
    "snake_micro_marble", "snakeskin_latex_glam",
    "gyeongbokgung_night_couture", "bukchon_rain_editorial",
    "namsan_tower_dusk", "dongdaemun_neon_rain", "haeinsa_temple_dawn",
    "jeju_volcanic_coast", "fushimi_inari_crimson", "arashiyama_bamboo_mist",
    "osaka_dotonbori_neon", "mount_fuji_dawn_silk", "japanese_garden_autumn",
    "kabukiza_backstage_glam", "forbidden_city_golden_hour",
    "li_river_karst_mist", "shanghai_bund_noir", "zhangjiajie_cloud_forest",
    "west_lake_lotus_dawn", "bali_tanah_lot_sunset", "hoi_an_lantern_rain",
    "bangkok_wat_arun_gold", "singapore_marina_bay_night",
    "luang_prabang_monk_dawn", "rice_terrace_banaue_mist",
    "opera_house_goddess", "venetian_carnival_palazzo", "flamenco_tablao_fire",
    "broadway_red_curtain", "scottish_castle_mist", "sahara_dune_queen",
    "ballet_stage_noir",
    # Minimal Object Cover (feather etc)
    "feather_body_cover", "mushroom_moss_cover", "butterfly_swarm_cover",
    "seashell_body_cover", "silver_chain_mirror_room", "desert_sand_sculpture",
    "ice_crystal_gown", "autumn_leaves_cover", "trio_inside_outside_bodypaint",
    "quad_fashion_capitals_bodypaint",
    # Hot/Sexy
    "champagne_pour_body", "wine_pour_body", "milk_pour_body",
    "honey_pour_body", "gold_paint_body", "hot_tub_goddess", "foam_bath_goddess",
    "pasties_editorial", "body_tape_art", "wrap_sarong_nude", "ribbon_only",
    "desert_heat_nude", "jungle_wet_goddess", "steam_room_goddess",
    "volcanic_heat_body", "liquid_latex_drip", "silver_foil_body",
    "holographic_latex", "mirror_latex", "private_pool_villa",
    "rooftop_pool_night", "penthouse_pool", "yacht_sunset_glam",
    "casino_vip_glam", "limo_glam", "bed_editorial", "floor_editorial",
    "chair_editorial", "door_frame_glam", "staircase_glam", "elevator_glam",
    # Environment Merge
    "trio_bodypaint_latex_frame", "trio_bodypaint_gown_frame",
    "trio_bodypaint_leather_frame", "trio_animal_bodypaint_latex",
    "trio_klimt_bodypaint_gold_gown", "trio_galaxy_bodypaint_chrome",
    "duo_bodypaint_latex", "duo_bodypaint_gown", "duo_bodypaint_leather",
    "duo_bodypaint_gold_dress", "duo_animal_bodypaint_latex",
    "duo_klimt_bodypaint_gown", "duo_galaxy_bodypaint_chrome",
    "trio_latex_bodypaint_center", "trio_gown_bodypaint_center",
    "trio_leather_bodypaint_center", "trio_bikini_bodypaint_center",
    "trio_sheer_bodypaint_center", "trio_chrome_bodypaint_center",
    "invisible_dress", "neon_latex", "paint_pour_goddess", "neon_paint_pour",
    "shower_goddess", "rain_soaked_nude", "waterfall_nude",
    "ocean_nude_editorial", "steam_bath_goddess",
    # Performance G3/G4
    "opera_night", "christmas_glamour", "ballet_noir", "broadway_diva",
    "street_dance", "drag_glamour", "ribbon_goddess", "petal_storm",
    # Anime
    "anime_jp_90s_retro", "anime_jp_80s_citypop", "anime_jp_modern_glossy",
    "anime_jp_shoujo_soft", "anime_jp_shounen_action", "anime_jp_seinen_gritty",
    "anime_jp_makoto_watercolor", "anime_jp_ghibli_soft", "anime_jp_gekiga_noir",
    "anime_jp_pinup_retro", "anime_kr_webtoon_glossy", "anime_kr_romance_soft",
    "anime_kr_action_manhwa", "anime_kr_lezhin_mature", "anime_kr_pastel_dream",
    "anime_kr_lofi_chill", "anime_kr_noir_mature", "anime_cn_donghua_xianxia",
    "anime_cn_guofeng_ink", "anime_cn_modern_donghua", "anime_cn_palace_drama",
    "anime_us_cartoon_bold", "anime_us_comic_ink", "anime_us_pixar_stylized",
    "anime_us_disney_classic", "anime_us_pinup_classic", "anime_us_badgirl_comic",
    "anime_eu_ligne_claire", "anime_eu_graphic_novel", "anime_eu_erotic_bd",
    "anime_noir_silhouette",
    # Hot & Sexy
    "bodycon_power", "boudoir_noir", "wet_silk_gown", "oil_goddess_gold",
    "rain_soaked_dress", "micro_dress_only", "deep_plunge_gown",
    "backless_extreme", "one_strap_gown", "pinup_classic", "vargas_girl",
    "bombshell_retro", "playboy_glam", "lingerie_noir", "barely_there",
    "wet_look_goddess", "micro_bikini_gold", "sarong_goddess", "nude_beach_art",
    "aqua_bikini", "golden_summer", "riviera_heat", "snow_queen_erotic",
    "autumn_gold_sensual", "christmas_boudoir", "summer_solstice_glam",
    "latex_queen", "pvc_goddess", "leather_mistress", "crystal_mesh_goddess",
    "chain_mail_glam", "fishnet_goddess", "lace_bodysuit", "satin_slip",
    "velvet_corset", "body_chain_only", "strappy_dress", "cut_out_swimsuit",
    "monokini_goddess", "champagne_drip", "neon_bodysuit", "bikini_top_only",
    "white_linen_sheer", "oil_drip_body", "yoga_pants_glam", "halter_glam",
    "wet_editorial", "pool_edge_wet", "ocean_wave_body", "penthouse_bath",
    "silk_sheets_morning", "spa_private_steam", "bar_counter_glam",
    "after_party_suite", "tennis_short_dress", "dressing_room_mirror",
    "vip_booth_neon",
    # Cultural Bodypaint v28
    "kabuki_bodypaint", "joseon_bodypaint", "tibetan_bodypaint",
    "byzantine_bodypaint", "mayan_bodypaint", "geisha_bodypaint",
    "ming_bodypaint", "thai_bodypaint", "ottoman_bodypaint",
    "flamenco_bodypaint", "sumerian_bodypaint", "maori_bodypaint",
    "balinese_bodypaint", "persian_bodypaint", "mughal_bodypaint",
    "hopi_bodypaint", "haida_bodypaint", "polynesian_bodypaint",
    "korean_shaman_bodypaint", "noh_bodypaint", "hanbok_bodypaint",
    "tang_dynasty_bodypaint", "moroccan_bodypaint", "batik_bodypaint",
    "ikat_bodypaint", "dirndl_bodypaint", "ninja_bodypaint",
    "kebaya_bodypaint", "scottish_bodypaint", "voodoo_bodypaint",
    "scythian_bodypaint", "olmec_bodypaint", "odalisque_bodypaint",
    "harem_bodypaint", "shaman_bodypaint", "kimono_bodypaint",
    "samurai_bodypaint", "geisha_white_bodypaint", "hanfu_bodypaint",
    "qipao_bodypaint", "cheongsam_bodypaint", "gisaeng_bodypaint",
    "hanbok_modern_bodypaint", "ao_dai_bodypaint", "zulu_bodypaint",
    "kente_bodypaint", "dashiki_bodypaint", "belly_bodypaint",
    # Anime & Glamour
    "kunoichi_glam", "samurai_bride", "oni_warrior", "cosmic_warrior_glam",
    "dragon_princess", "dark_sorceress_glam", "neon_android", "android_2b",
    "vampire_seductress", "vampirella_dark", "manhwa_villainess",
    "dark_elsa", "anime_battle_angel", "poison_ivy_vines", "storm_goddess",
    "jessica_rabbit_glam", "barbarella_retro",
    # City & Night
    "monaco_nights", "candlelight_noir", "jazz_club", "noir_ballet",
    "brutalist_glam", "new_year_countdown", "emerald_city", "tokyo_shibuya",
    "paris_midnight", "penthouse_view", "palacio_de_sal", "chefchaouen_blue",
    "hallstatt_lake", "shirakawa_snow", "azure_nights", "blue_hour_goddess",
    "jazz_age", "disco_goddess", "urban_vanguard", "music_festival",
    "subway_editorial", "santorini_sunset", "cappadocia_balloons",
    # Elemental Goddess
    "uyuni_wet_silk", "maldives_underwater", "bioluminescent_bay",
    "rainbow_falls_goddess", "trolltunga_edge", "zhangjiajie_cloud",
    "cliff_wind_sheer", "skydive_editorial", "hot_air_balloon_glam",
    "wave_barrel_goddess", "glacier_melt_goddess", "sahara_mirage",
    "salt_flat_body", "salar_atacama_flamingo", "pamukkale_goddess",
    "red_canyon_goddess", "lava_field_latex", "solar_flare_goddess",
    "aurora_bare", "antarctica_ice_glam", "meteor_shower_glam",
    "ice_cave_blue", "antelope_light_sheer", "waitomo_glow_body",
    "coral_reef_sheer", "black_sea_midnight",
    # Power & Edge
    "valkyrie_storm", "fencer_noir", "martial_arts", "boxing_glamour",
    "cage_fighter", "biker_glam", "riot_goddess", "punk_queen",
    "steel_warrior", "power_suit", "shadow_play", "power_curve",
    "sculpted_power", "shadow_queen", "bioluminescence", "bioluminescent",
    # Duo/Trio Bodypaint
    "duo_aurora_bodypaint", "duo_ocean_bodypaint", "duo_golden_desert_bodypaint",
    "duo_cyberpunk_bodypaint", "duo_jungle_tribal_bodypaint",
    "duo_latex_color_block", "duo_latex_storm_opposites", "duo_dark_latex_power",
    "duo_flamenco_latex_fusion", "duo_smoke_noir", "duo_infinity_pool_contrast",
    "duo_pool_bodypaint_micro", "duo_wet_glass_divide", "duo_bodypaint_vs_latex",
    "duo_fire_and_ice", "duo_angel_devil", "duo_chrome_future",
    "duo_skeleton_bloom_bodypaint", "duo_odalisque_gisaeng_bodypaint",
    "trio_stone_bronze_iron_bodypaint", "trio_past_present_future_bodypaint",
    "trio_sunrise_sunset_moonrise_bodypaint",
    "trio_lightning_ocean_earthquake_bodypaint",
    "trio_sand_ice_magma_bodypaint", "trio_sky_earth_underground_bodypaint",
    "trio_fog_rain_snow_bodypaint", "trio_primary_colors_bodypaint",
    "trio_black_white_gray_bodypaint", "trio_gold_silver_bronze_bodypaint",
    "trio_infrared_visible_uv_bodypaint",
    "trio_creator_preserver_destroyer_bodypaint", "trio_fate_three_bodypaint",
    "trio_medusa_sphinx_hydra_bodypaint", "trio_creation_of_adam_bodypaint",
    "trio_east_west_south_bodypaint", "trio_viking_samurai_spartan_bodypaint",
    "trio_nile_amazon_yangtze_bodypaint", "trio_rome_babylon_aztec_bodypaint",
    "trio_fear_anger_joy_bodypaint", "trio_order_chaos_void_bodypaint",
    "trio_id_ego_superego_bodypaint", "trio_thesis_antithesis_synthesis_bodypaint",
    # Performance & Dance
    "flamenco_queen", "tango_passion", "ribbon_dance", "aerial_silk",
    "kathak_dance", "hula_goddess", "circus_performer", "fire_dancer",
    "masquerade_ball", "samba_carnival", "jazz_dance_glam",
    # Atmosphere & Particle
    "smoke_machine_club", "dry_ice_floor", "cigarette_smoke_noir",
    "incense_smoke_ritual", "smoke_color_holi", "fog_forest_mystery",
    "gold_dust_pour", "holi_powder_explosion", "chalk_dust_sport",
    "flour_dust_studio", "pigment_powder_art", "feather_explosion",
    "black_feather_dark", "petal_storm_indoor", "cherry_blossom_burst",
    "dried_flower_cascade", "glitter_rain_studio", "gold_confetti_burst",
    "silver_glitter_body", "neon_particle_club", "bubble_floating_studio",
    "sparkler_night_glam", "fire_poi_dance", "ember_glow_dark",
    "firework_silhouette", "autumn_leaves_burst", "snow_indoor_studio",
    "dandelion_blow", "firefly_night_field", "seed_pod_floating",
    # Erotic & Fetish
    "latex_venom", "latex_catsuit", "latex_catsuit_red", "pvc_transparent_full",
    "latex_hood_full", "latex_transparent", "vinyl_goddess", "rubber_goddess",
    "chrome_vixen", "chain_goddess", "savage_leather", "leather_bodysuit",
    "chrome_bodysuit", "mirror_dress", "liquid_metal_body",
    "bondage_fashion", "strappy_harness", "harness_only", "rope_bondage_art",
    "suspension_art", "tape_bondage", "metal_bondage", "mesh_bodysuit",
    "bodystocking", "fishnet_bodysuit", "transparent_dress", "sheer_catsuit",
    "catsuit_zipper", "dominatrix_glam", "dominatrix_full_armor",
    "dominatrix_red", "goddess_throne", "pole_art", "burlesque", "showgirl",
    "candy_rave", "lap_dance_glam", "lap_dance_extreme", "striptease_art",
    "pole_dance_power", "pole_dance_extreme", "midnight_bath",
    "belly_dance_glam", "dark_succubus", "vampire_seduction", "witch_sensual",
    "dark_fairy_erotic", "shadow_seductress", "succubus_full",
    "dark_angel_fallen", "alien_queen_body", "fire_goddess",
    "secretary_after_hours", "nurse_sensual", "maid_sensual",
    "teacher_after_class", "doctor_sensual", "police_dominatrix",
    "stewardess_dark", "oil_goddess", "micro_thong_only", "fetish_boots_only",
    "corset_stockings",
    # Fantasy & Dark
    "dark_mermaid", "vampire_queen", "angel_fallen", "moon_goddess",
    "demon_goddess", "forest_witch", "pastel_fairy", "medusa_queen",
    "halloween_queen", "hologram_ghost", "glitch_beauty", "void_emergence",
    "void_glamour", "void_secret", "crystal_goddess", "toxic_bloom",
    "zombie_apocalypse", "dark_academia", "gothic_romance",
    "double_exposure_dark", "double_exposure_ethereal", "oil_slick_noir",
    "witch_ritual", "fae_queen", "cursed_beauty", "shadow_realm",
    # Silhouette
    "silhouette_spotlight_smoke", "silhouette_spotlight_latex",
    "silhouette_spotlight_heels", "silhouette_spotlight_hair",
    "silhouette_spotlight_dance", "silhouette_spotlight_chair",
    "silhouette_spotlight_back", "silhouette_spotlight_pole",
    "silhouette_window_city", "silhouette_window_rain",
    "silhouette_window_sheer", "silhouette_doorway_light",
    "silhouette_window_sunset", "silhouette_window_neon",
    "silhouette_neon_pink", "silhouette_neon_blue", "silhouette_neon_red",
    "silhouette_neon_purple", "silhouette_neon_multicolor",
    "silhouette_sunset_beach", "silhouette_sunset_cliff",
    "silhouette_moonlight", "silhouette_aurora",
    "silhouette_pool_underwater", "silhouette_pool_edge",
    "silhouette_bath_candle", "silhouette_rain_wet", "silhouette_fire_dark",
    "silhouette_candle_boudoir", "silhouette_smoke_studio",
    # Wet & Gloss
    "pool_surface_break", "pool_underwater_up", "pool_edge_dripping",
    "infinity_pool_wet", "hot_spring_steam", "jacuzzi_bubbles",
    "rain_window_inside", "rain_street_soaked", "rain_studio_dramatic",
    "monsoon_body", "rain_car_window", "oil_pour_studio", "oil_drip_back",
    "honey_drip_body", "chocolate_pour_gloss", "gloss_lips_drip",
    "chrome_gloss_body", "sweat_studio_light", "heat_mirage_sweat",
    "sauna_steam_body", "condensation_skin", "ice_melt_drip",
    "dew_morning_body", "frost_breath_cold", "waterfall_direct",
    "wave_crash_body", "wet_silk_minimal", "bubble_bath_gloss",
    "milk_bath_petals",
    # Korean History
    "silla_queen_gold", "baekje_lotus_queen", "gojoseon_shaman_queen",
    "gaya_iron_goddess", "ancient_mural_goddess", "goryeo_empress_silk",
    "goryeo_gisaeng_glam", "goryeo_celadon_goddess",
    "goryeo_buddhist_temptress", "goryeo_court_dancer",
    "goryeo_night_gisaeng", "mongol_goryeo_queen", "joseon_queen_slit",
    "joseon_consort_sheer", "crown_princess_latex", "joseon_court_dancer",
    "joseon_painter_nude", "hwajeon_court_lady", "damo_warrior",
    "joseon_night_queen", "joseon_concubine_red", "changdeok_moonlight",
    "gyeongbokgung_geisha", "gisaeng_joseon_sheer", "gisaeng_red_lantern",
    "gisaeng_sword_dance", "gisaeng_rain_dance", "gisaeng_black_silk",
    "wonhyang_legend", "hwang_jini_glam", "gisaeng_fan_dance",
    "gisaeng_pipa_night", "pyongyang_gisaeng", "gumiho_latex",
    "gumiho_red_moon", "samshin_goddess_glam", "dragon_daughter_sea",
    "imoogi_seduction", "dokkaebi_girl", "seonnyeo_descent",
    "haenyeo_mermaid", "baeksa_serpent", "chamsuri_ghost",
    "taoist_fairy_korea", "nine_tail_dominatrix", "dano_festival_glam",
    "ganggangsullae_night", "mudang_fire_ritual", "mudang_trance_glam",
    "namsadang_acrobat", "jeju_shaman_sea", "korean_harvest_goddess",
    "joseon_female_assassin", "goryeo_archer_queen", "silla_female_hwarang",
    "joseon_damo_noir", "tiger_huntress_korea", "wonhyang_warrior",
    "goguryeo_fire_warrior", "joseon_spy_sheer", "joseon_modern_fusion",
    "gisaeng_cyberpunk", "hanbok_latex_queen", "joseon_noir",
    "gisaeng_opium_den", "korean_vamp_modern", "hanbok_wet_editorial",
    "joseon_boudoir",
    # Multi Body Paint (G1~G6)
    "duo_fire_and_ice_bodypaint", "duo_day_and_night_bodypaint",
    "duo_bloom_and_void_bodypaint", "duo_gold_and_shadow_bodypaint",
    "duo_ocean_and_desert_bodypaint", "duo_circuit_and_nature_bodypaint",
    "trio_rgb_trinity_bodypaint", "trio_predator_prey_apex_bodypaint",
    "trio_ink_gold_chrome_bodypaint", "trio_season_trinity_bodypaint",
    "duo_butterfly_split_bodypaint", "duo_yin_yang_merge_bodypaint",
    "duo_world_map_bodypaint", "duo_galaxy_split_bodypaint",
    "duo_wave_hokusai_bodypaint", "trio_triptych_klimt_bodypaint",
    "trio_phoenix_rising_bodypaint", "trio_world_tree_bodypaint",
    "trio_ocean_depth_bodypaint", "trio_aurora_spectrum_bodypaint",
    "trio_cosmic_creation_bodypaint", "duo_east_and_west_bodypaint",
    "duo_macro_and_micro_bodypaint", "duo_ancient_and_future_bodypaint",
    "duo_poison_and_medicine_bodypaint", "duo_deep_sea_bodypaint",
    "trio_sun_moon_star_bodypaint", "trio_three_oceans_bodypaint",
    "trio_three_civilizations_bodypaint", "trio_fire_water_earth_bodypaint",
    "trio_three_big_cats_bodypaint", "duo_dna_helix_bodypaint",
    "duo_solar_eclipse_bodypaint", "duo_human_shadow_bodypaint",
    "duo_tiger_split_bodypaint", "duo_starry_night_split_bodypaint",
    "duo_peacock_split_bodypaint", "trio_last_supper_bodypaint",
    "trio_rainbow_arc_bodypaint", "trio_milky_way_panorama_bodypaint",
    "trio_coral_reef_zones_bodypaint", "trio_poles_and_equator_bodypaint",
    "duo_earth_hemisphere_bodypaint", "duo_day_city_night_city_bodypaint",
    "duo_volcano_glacier_bodypaint", "duo_storm_eye_bodypaint",
    "duo_aurora_milkyway_bodypaint", "duo_coral_abyss_bodypaint",
    "duo_tree_root_bodypaint", "duo_eagle_serpent_bodypaint",
    "duo_wolf_moon_bodypaint", "duo_butterfly_cocoon_bodypaint",
    "duo_dragon_phoenix_bodypaint", "duo_lion_zebra_bodypaint",
    "duo_spider_web_bodypaint", "duo_mona_lisa_split_bodypaint",
    "duo_birth_venus_split_bodypaint", "duo_yin_yang_koi_bodypaint",
    "duo_chess_board_bodypaint", "duo_android_human_bodypaint",
    "duo_black_hole_star_bodypaint", "duo_past_future_city_bodypaint",
    "duo_virus_antibody_bodypaint", "duo_matrix_reality_bodypaint",
    "duo_crystal_lava_bodypaint", "duo_ink_wash_split_bodypaint",
    "trio_ancient_medieval_modern_bodypaint", "trio_birth_life_death_bodypaint",
    "trio_seed_tree_ash_bodypaint", "trio_micro_human_macro_bodypaint",
    "trio_jungle_desert_tundra_bodypaint", "trio_heaven_earth_hell_bodypaint",
    "trio_valkyrie_siren_medea_bodypaint", "trio_amazon_sahara_arctic_bodypaint",
    "trio_love_war_peace_bodypaint",
    # Duo Glamour
    "duo_infinity_pool_contrast", "duo_pool_bodypaint_micro",
    "duo_wet_glass_divide", "duo_bodypaint_vs_latex", "duo_ocean_bodypaint",
    "duo_golden_desert_bodypaint", "duo_aurora_bodypaint",
    "duo_cyberpunk_bodypaint", "duo_latex_color_block",
    "duo_latex_storm_opposites", "duo_dark_latex_power",
    "duo_flamenco_latex_fusion", "duo_smoke_noir", "duo_versailles_latex_gold",
    "duo_champagne_gala", "duo_casino_power", "duo_fire_and_ice",
    "duo_angel_devil", "duo_chrome_future", "duo_sunset_silhouette",
    "duo_desert_minimal", "duo_kpop_stage", "duo_penthouse_power",
    "duo_rain_neon_soaked", "duo_jungle_tribal_bodypaint", "duo_monaco_yacht",
    "duo_villa_italy", "duo_ice_bath_contrast",
    # Career & Lifestyle
    "flight_attendant", "pilot_glamour", "yacht_captain", "private_jet",
    "helipad", "hotel_concierge", "lawyer_power", "architect_chic",
    "casino_dealer", "gallery_curator", "golf_glam", "tennis_luxe",
    "tennis_referee", "tennis_champion", "f1_grid_girl", "equestrian_glam",
    "horse_racing", "yoga_goddess", "cheerleader", "ballet_prima",
    "gymnastics_editorial", "figure_skater", "carnival_rio", "luxury_shopping",
    # Ruins & Civilization
    "positano_cliff", "bruges_canal", "colosseum_dusk", "alhambra_palace",
    "mont_saint_michel", "sigiriya_rock", "angkor_thom_faces",
    "teotihuacan_pyramid", "palmyra_colonnade",
    # Locations
    "cenote_sacred", "tikal_skyrise", "angkor_dawn", "waitomo_glow",
    "marble_caves_water", "bagan_balloon", "tigers_nest_cliff",
    "sheikh_zayed_dawn", "livraria_lello_staircase", "namib_star_desert",
    "ellora_rock_temple",
    # Editorial
    "backlit_silk", "mirror_room", "eclipse_body", "plasma_aura",
    "molten_chrome", "mercury_pool", "snowflake_skin", "noir_femme_fatale",
    # Season & Theme
    "halloween_glam", "new_year_glam", "sakura_night_glam", "greenhouse_eden",
    # Pop & Kawaii
    "harajuku_doll", "cherry_pop", "hime_gyaru", "decora_kei", "lolita_gothic",
    "space_babe", "arcade_queen", "virtual_idol", "kdrama_villain_queen",
    "bubble_tea", "doll_house",
}

# ── SS_TIER 원본 데이터 ──
SS_RAW = {
    # QUAD/QUINT/HEXA SS
    "quad_four_seasons_bodypaint", "quad_four_elements_bodypaint",
    "quad_four_directions_bodypaint", "quad_four_seasons_klimt_bodypaint",
    "quad_rgba_spectrum_bodypaint", "quint_five_continents_bodypaint",
    "quint_five_elements_asia_bodypaint", "quint_rainbow_five_bodypaint",
    "quint_five_oceans_bodypaint", "quad_four_goddesses_bodypaint",
    "quad_lunar_phases_bodypaint", "quint_five_dance_cultures_bodypaint",
    # Multi bodypaint G5/G6
    "duo_klimt_tree_bodypaint",
    # Hot/Sexy SS
    "painted_jeans", "sauna_nude_editorial", "chrome_paint_body",
    "invisible_dress", "neon_latex",
    # Performance SS
    "pop_art_glamour",
    # Anime SS
    "anime_jp_ecchi_glossy", "anime_swordmistress", "anime_mecha_pilot",
    "anime_shrine_maiden", "anime_galaxy_idol", "anime_cyber_ninja",
    # Bodypaint SS
    "bioluminescent_ink", "galaxy_skin", "klimt_gold_body", "half_statue",
    "vangogh_body", "dali_surreal", "munch_scream", "ash_phoenix",
    "lichtenstein_dot", "warhol_pop", "mondrian_body", "lace_body_paint",
    "jewelry_trompe_loeil", "klimt_silver", "botticelli_venus",
    "liquid_gold_drip", "mermaid_scales", "tiger_stripes_body",
    "mantis_shrimp", "phoenix_rising", "jellyfish_glow", "panther_black",
    "octopus_ink", "snow_leopard", "scarab_beetle", "atlas_moth",
    "eagle_wings", "butterfly_monarch", "arctic_fox",
    "degas_dancer", "toulouse_lautrec", "waterhouse_nymph",
    "takashi_murakami", "yayoi_kusama", "keith_haring_body",
    "dancheong_body", "najeonchilgi_body", "goryeo_celadon_body",
    "minhwa_body", "korean_tiger_body", "silla_crown_body",
    "najeon_abalone", "giraffe_pattern", "zebra_stripes", "dragon_scales_red",
    "alma_tadema", "gauguin_tropics", "melting_chocolate",
    "parrot_tropical", "boa_constrictor", "king_cobra_hood",
    "cheetah_speed", "bird_of_paradise", "owl_feather", "crocodile_skin",
    "phoenix_jujakk", "cheongnyong_dragon", "korean_dragon_body",
    "haetae_guardian", "coral_reef_body", "galaxy_nebula_body",
    "islamic_geometric_body", "aztec_calendar_body", "stained_glass_body",
    "mushroom_forest_body", "hieroglyph_body", "mexico_flag_body",
    "ocelot_wild", "ndebele_pattern", "celtic_knot_body", "greek_mosaic_body",
    "ocean_depth_body", "weather_map_body", "bauhaus_body", "wolf_grey",
    "transparent_dress", "sheer_catsuit", "chrome_bodysuit", "mirror_dress",
    "suspension_art", "dominatrix_full_armor", "goddess_throne",
    "doctor_sensual", "police_dominatrix", "pole_dance_extreme",
    "fire_goddess", "succubus_full", "dark_angel_fallen", "alien_queen_body",
    "body_paint_nude", "cabaret_star", "vampire_seduction", "witch_sensual",
    "latex_venom", "unicorn_opal",
    "body_paint_watercolor_free", "body_paint_metallic_free",
    "body_paint_impasto", "body_paint_airbrush", "body_paint_monochrome",
    "body_paint_earth_tones", "body_paint_jewel_tones",
    "body_paint_iridescent_free", "body_paint_geometric_free",
    "body_paint_organic_flow", "body_paint_surreal_free",
    "body_paint_glitter_free",
    # Luxury SS
    "black_mirror", "noir_opulence", "velvet_darkness", "luxury_noir",
    "lace_noir", "midnight_couture", "velvet_serpent", "golden_oil",
    "golden_nude", "gold_temptress", "golden_hour_editorial",
    "platinum_elite", "ivory_silk", "pearl_essence", "velvet_gold",
    "diamond_couture", "runway_power", "red_carpet", "red_temptress",
    "crimson_gown", "opera_glam", "silver_screen", "crystal_gown",
    "baroque_glam", "feather_cascade", "feather_trim_mini", "cobweb_drape",
    "petal_goddess", "goddess_draped", "sheer_overlay", "champagne_mist",
    "couture_heat", "casino_royale", "black_tie_gala", "champagne_tower",
    "plunge_gown", "slit_maxi", "cutout_bodysuit", "jeweled_bikini_top",
    "golden_drape_goddess", "penthouse_glam", "serpentine_dress",
    # Power & Edge SS
    "shadow_play", "power_suit", "shadow_queen", "punk_queen",
    # Elemental SS
    "uyuni_wet_silk", "aurora_bare", "antelope_light_sheer", "lava_field_latex",
    "niagara_wet_editorial", "thunderstorm_wet", "cave_waterfall_goddess",
    "desert_heat_body", "volcano_edge_glam", "bonfire_editorial",
    "eruption_silhouette", "amazon_river_goddess", "iceland_hot_spring",
    "northern_lights_body", "dead_sea_goddess", "socotra_alien_glam",
    "deep_jungle_goddess", "monsoon_goddess",
    # Location SS
    "son_doong_jungle", "petra_rose", "danxia_rainbow", "dead_vlei_ghost",
    "lake_natron", "socotra_alien", "richat_eye", "derinkuyu_underground",
    "naoshima_art_island", "cinque_terre_harbor", "karnak_temple",
    "chichen_itza_pyramid", "gobekli_tepe",
    # Beach SS
    "summer_beach", "surfer_goddess", "pool_goddess", "poolside_noir",
    "glass_floor", "glass_house", "ski_chalet", "beach_bonfire",
    "balcony_goddess", "coral_diving", "beach_bonfire_night",
    "hammock_resort", "infinity_pool", "scuba_goddess", "spa_noir",
    "sunset_cruise",
    # Pop & Kawaii SS
    "y2k_fairy", "pink_champagne", "cotton_candy", "angel_baby",
    "idol_stage", "kitty_glam", "strawberry_milk", "neon_kawaii",
    "fairy_kei", "gyaru_glam", "kogal_style", "maid_glamour", "visual_kei",
    "disco_barbie", "bubblegum_pop", "rainbow_rave", "glitter_bomb",
    "tokimeki_pop", "kpop_girl_crush", "hallyu_goddess",
    "kdrama_chaebol_heir", "gangnam_luxury_glam", "harajuku_doll",
    # Season SS
    "cherry_blossom", "lavender_field", "spring_rain", "tulip_field",
    "autumn_forest", "sunflower_field", "tropical_night", "first_snow",
    "golden_autumn", "midsummer_heat", "rainy_season", "harvest_moon",
    "winter_solstice", "cherry_blossom_night", "tropical_monsoon",
    "halloween_glam", "new_year_glam", "sakura_night_glam", "monsoon_goddess",
    # Editorial SS
    "silhouette_only", "back_beauty", "collarbone_focus", "neck_elegance",
    "long_legs_focus", "light_driven", "mirror_goddess", "chrome_skin",
    "neon_body", "molten_chrome", "mercury_rising", "titanium_body",
    "80s_power", "y2k_chrome", "bohemian_paris", "origami_couture",
    "wet_glass", "smoke_studio", "infrared_beauty", "grain_film",
    "dreamy_soft_focus", "film_noir_glam",
    # Nature SS
    "lava_flow", "heat_shimmer", "solar_flare", "desert_mirage",
    "ocean_surge", "waterfall_goddess", "water_reflection", "liquid_gold_pour",
    "ice_palace", "ice_refraction", "frozen_latex", "blizzard_queen",
    "arctic_minimal", "frozen_baikal", "sandstorm_veil", "desert_oracle",
    "desert_sand_glam", "smoke_veil", "mist_goddess", "storm_couture",
    "storm_lightning", "lightning_body", "zero_gravity", "winter_forest",
    "cliff_edge", "deep_cave", "dawn_awakening", "liquid_mirror",
    "aurora_drape", "aurora_spirit", "prism_light", "shattered_glass",
    "dead_vlei_ghost", "danxia_rainbow", "socotra_alien", "lake_natron",
    "zhangjiajie_avatar", "pamukkale_white", "plitvice_cascade",
    "rainbow_mountain", "kelimutu_crater", "victoria_falls",
    "wisteria_tunnel", "torres_del_paine", "ha_long_bay", "fairy_pools",
    "tunnel_of_love", "chocolate_hills", "volcanic_goddess", "tidal_wave",
    "rain_soaked", "mist_vanguard", "tropical_storm",
    # Hot/Sexy SS
    "lingerie_goddess", "silk_robe_only", "corset_queen", "sheer_negligee",
    "pool_wet_glam", "sweat_glam", "barely_covered", "bunny_suit",
    "elite_lingerie", "barely_there", "thong_bikini", "wet_bikini_pool",
    "topless_editorial",
    # Cultural Bodypaint SS
    "sari_bodypaint", "yoruba_bodypaint", "maiko_bodypaint",
    # Korean History SS
    "silla_dancing_girl", "goguryeo_warrior_queen", "silla_hwarang_girl",
    "three_kingdoms_spy", "dongye_tribal_queen", "goryeo_haenyeo_silk",
    "joseon_merchant_woman", "gisaeng_haiku_bath", "gisaeng_mirror_boudoir",
    "haenyeo_wet_glam",
    # Multi Bodypaint SS
    "duo_fire_and_ice_bodypaint", "duo_day_and_night_bodypaint",
    "duo_bloom_and_void_bodypaint", "duo_gold_and_shadow_bodypaint",
    "duo_ocean_and_desert_bodypaint", "duo_circuit_and_nature_bodypaint",
    "duo_east_and_west_bodypaint", "duo_macro_and_micro_bodypaint",
    "duo_ancient_and_future_bodypaint", "duo_poison_and_medicine_bodypaint",
    "duo_deep_sea_bodypaint", "trio_rgb_trinity_bodypaint",
    "trio_past_present_future_bodypaint", "trio_predator_prey_apex_bodypaint",
    "trio_ink_gold_chrome_bodypaint", "trio_season_trinity_bodypaint",
    "trio_sun_moon_star_bodypaint", "trio_three_oceans_bodypaint",
    "trio_three_civilizations_bodypaint", "trio_fire_water_earth_bodypaint",
    "trio_three_big_cats_bodypaint", "duo_butterfly_split_bodypaint",
    "duo_yin_yang_merge_bodypaint", "duo_world_map_bodypaint",
    "duo_klimt_tree_bodypaint", "duo_galaxy_split_bodypaint",
    "duo_wave_hokusai_bodypaint", "duo_dna_helix_bodypaint",
    "duo_solar_eclipse_bodypaint", "duo_human_shadow_bodypaint",
    "duo_tiger_split_bodypaint", "duo_starry_night_split_bodypaint",
    "duo_peacock_split_bodypaint", "trio_triptych_klimt_bodypaint",
    "trio_phoenix_rising_bodypaint", "trio_world_tree_bodypaint",
    "trio_ocean_depth_bodypaint", "trio_aurora_spectrum_bodypaint",
    "trio_cosmic_creation_bodypaint", "trio_last_supper_bodypaint",
    "trio_rainbow_arc_bodypaint", "trio_milky_way_panorama_bodypaint",
    "trio_coral_reef_zones_bodypaint", "trio_creation_of_adam_bodypaint",
    "trio_poles_and_equator_bodypaint",
    # Environment Merge SS
    "merge_butterfly_fabric", "merge_floral_wallpaper", "merge_leopard_fabric",
    "merge_mandala_carpet", "merge_toile_pattern", "merge_tartan_plaid",
    "merge_salt_flat_sky", "merge_autumn_leaves_floor", "merge_coral_reef_water",
    "merge_sand_dunes", "merge_moss_stone_ground", "merge_clockwork_gears",
    "merge_marble_column_wall", "merge_islamic_tile_wall",
    "merge_stained_glass_window", "merge_circuit_board", "merge_klimt_gold_mural",
    "merge_vangogh_starry", "merge_ukiyo_wave_print", "merge_mondrian_grid",
    "merge_pollock_splatter", "merge_byzantine_mosaic",
    # Career SS
    "cruise_hostess", "yacht_club", "nurse_glamour", "sommelier",
    "wine_tasting", "barista_chic", "golf_caddie", "fitness_power",
    "scuba_instructor", "archery_goddess",
}

# 필터링: 실제 존재하는 키만
SSS_TIER = SSS_RAW & existing
SS_TIER = (SS_RAW & existing) - SSS_TIER  # SSS와 겹치면 SSS 우선

print(f"SSS_TIER: {len(SSS_TIER)}개 (원본 {len(SSS_RAW)}개 중)")
print(f"SS_TIER: {len(SS_TIER)}개 (원본 {len(SS_RAW)}개 중)")

# 파일 생성
content = f'''# -*- coding: utf-8 -*-
"""
LumineX SSS / SS 티어 목록
dashboard.py 에서 import: from core.sss_tier import SSS_TIER, SS_TIER
"""

SSS_TIER = {{
{chr(10).join(f'    "{k}",' for k in sorted(SSS_TIER))}
}}

SS_TIER = {{
{chr(10).join(f'    "{k}",' for k in sorted(SS_TIER))}
}}
'''

try:
    ast.parse(content)
    open('core/sss_tier.py', 'w', encoding='utf-8').write(content)
    print(f"\ncore/sss_tier.py 생성 완료!")
except SyntaxError as e:
    print(f"SyntaxError: {e}")
