import json, os

PRESETS_DIR = "presets"
os.makedirs(PRESETS_DIR, exist_ok=True)

PRESETS = {

    # ── H 신규 (H-017 ~ H-030) ──────────────────────────────

    "irezumi_dragon_wisteria_milf_budapest": {
        "key": "irezumi_dragon_wisteria_milf_budapest",
        "label": "DRAGON WISTERIA MILF BUDAPEST",
        "category": "🐉 Irezumi Motif H",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 40s commanding mature goddess, hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs so enormously thick each leg fills impossible width, long voluminous auburn hair with gold highlights in dramatic loose waves to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep copper and burnished gold scales coiling from left ankle up left leg across waist over right shoulder, dragon head anchored over right breast as primary focal climax with blazing copper-gold eyes, cascading WISTERIA in deep amber and copper tones — warm autumn palette — filling every gap of mature hourglass body from neck to ankles, dense copper-amber wisteria clusters following dramatic curves to ankles with zero bare skin, warm copper-gold tone composition.\n\nEnvironment: Budapest Széchenyi thermal bath at night, ornate Neo-Baroque yellow architecture illuminated, steaming thermal pools glowing turquoise, grand domed ceilings with warm light, elegant European grandeur.\nPose: standing at pool edge, one hand in auburn waves, chin raised commanding mature goddess expression, copper-gold dragon catching warm bath house light, body oiled to rich high-gloss finish.\nFootwear: copper gold platform stilettos 8 inch.\nNails: extra long almond nails deep copper with burnished gold tips.\nHair: long voluminous auburn with gold highlights dramatic loose waves to waist.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_bbw_cape_town": {
        "key": "irezumi_dragon_wisteria_bbw_cape_town",
        "label": "DRAGON WISTERIA BBW CAPE TOWN",
        "category": "🐉 Irezumi Motif H",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 40s commanding goddess, BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust full and projecting forward, hips flaring to wide maximum, thighs full and heavy, waist defined creating dramatic curves, bubble butt projecting rearward in generous volume, long sleek black hair with vivid violet highlights in dramatic low side braid to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep violet and black scales coiling from left ankle up left leg across generous hips over right shoulder, dragon head anchored over right breast as primary focal climax with blazing violet eyes, cascading WISTERIA in deep violet and magenta filling every gap of BBW body from neck to ankles, dense violet wisteria clusters following generous hip curve and thighs to ankles with zero bare skin.\n\nEnvironment: Cape Town Table Mountain at sunset, dramatic flat-topped mountain silhouette against orange-pink sky, Cape Peninsula coast below, fynbos wildflowers in foreground, warm African golden hour light.\nPose: 3/4 angle showing full BBW silhouette against mountain, one hand on dramatically flared hip, head turned toward mountain with commanding expression, violet braid cascading over one shoulder, body oiled to high-gloss finish.\nFootwear: deep violet platform stilettos 8 inch.\nNails: extra long coffin nails deep violet with magenta tips.\nHair: long sleek black with vivid violet highlights dramatic low side braid to waist.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_superbbw_rio": {
        "key": "irezumi_dragon_wisteria_superbbw_rio",
        "label": "DRAGON WISTERIA SUPERBBW RIO",
        "category": "🐉 Irezumi Motif H",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid-30s commanding goddess, super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips so impossibly wide filling the entire frame, thighs each wider than most bodies, bubble butt projecting rearward to absolute maximum, waist defined creating dramatic contrast, micro braids in deep violet to mid-back — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in electric violet and indigo scales coiling from right ankle up right thigh across enormous hips over left shoulder, dragon head anchored over left breast as primary focal climax with blazing violet-white eyes, cascading WISTERIA in deep violet and electric indigo filling every gap of super BBW body from neck to ankles, dense violet wisteria clusters following every impossible curve to ankles with zero bare skin.\n\nEnvironment: Rio de Janeiro Carnival night, Sambadrome parade in full explosion behind her, massive floats glowing in gold and violet, samba dancers in feathered costumes, fireworks bursting overhead.\nPose: 3/4 rear angle showing full super BBW silhouette, bubble butt projecting toward camera, head turned over shoulder with fierce goddess expression, micro braids cascading down, one hand on impossibly wide hip, body oiled to extreme high-gloss finish.\nFootwear: deep violet platform stilettos 8 inch.\nNails: extra long square nails electric violet with indigo tips.\nHair: micro braids deep violet to mid-back.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_muscular_tokyo": {
        "key": "irezumi_dragon_wisteria_muscular_tokyo",
        "label": "DRAGON WISTERIA MUSCULAR TOKYO",
        "category": "🐉 Irezumi Motif H",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 20s warrior goddess, extreme muscular physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — biceps so massively defined impossible for human anatomy, shoulders so broad and powerful filling the frame, abs carved like obsidian stone, quads and glutes of impossible density and size, waist nevertheless dramatically narrow, natural black hair in tight warrior knot — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in gunmetal silver and cold white scales coiling from left ankle up left leg across carved abs over right shoulder, dragon head anchored over right breast as primary focal climax with blazing silver-ice eyes, cascading WISTERIA in pale lavender and cold white filling every gap of extreme muscular body from neck to ankles, delicate white wisteria tendrils following every carved muscle line to ankles.\n\nEnvironment: Tokyo Shinjuku neon night, towering neon kanji signs in electric blue and white, rain-slicked streets reflecting neon, massive urban energy.\nPose: double bicep pose facing camera, both arms raised showing impossible muscle peaks, chin down warrior expression, every muscle group in full flex, body oiled to wet-chrome high-gloss finish.\nFootwear: white chrome platform boots to knee.\nNails: extra long stiletto nails chrome silver with ice-blue tips.\nHair: natural black tight warrior knot.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_hourglass_marrakech": {
        "key": "irezumi_dragon_wisteria_hourglass_marrakech",
        "label": "DRAGON WISTERIA HOURGLASS MARRAKECH",
        "category": "🐉 Irezumi Motif H",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 50s timeless goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust projecting forward in impossible volume, waist cinched to absolute minimum, hips flaring to maximum impossible width, thighs thick and powerful, long natural silver locs to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in burnished gold and terracotta scales coiling from right ankle up right thigh across cinched waist over left shoulder, dragon head anchored over left breast as primary focal climax with blazing amber-gold eyes, cascading WISTERIA in warm saffron and deep terracotta filling every gap of extreme hourglass body from neck to ankles, dense amber wisteria clusters following dramatic hourglass silhouette to ankles with zero bare skin.\n\nEnvironment: Marrakech Djemaa el-Fna at golden hour, ancient medina walls glowing amber, spice market stalls in deep orange and saffron, Atlas Mountains silhouette at dusk, lanterns beginning to glow.\nPose: full frontal commanding stance, both hands raised cupping natural silver locs, chin raised elder goddess expression, full hourglass silhouette center frame, gold dragon catching Moroccan golden hour light, body oiled to warm amber high-gloss finish.\nFootwear: burnished gold platform stilettos 8 inch with ankle wrap.\nNails: extra long coffin nails burnished gold with terracotta tips.\nHair: long natural silver locs to waist.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_runway_seoul": {
        "key": "irezumi_dragon_wisteria_runway_seoul",
        "label": "DRAGON WISTERIA RUNWAY SEOUL",
        "category": "🐉 Irezumi Motif H",
        "tier": "SS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 20s high fashion goddess, extreme runway slim physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — impossibly elongated legs filling the full frame height, flat angular torso, sharp hip bones projecting outward, impossibly long neck, razor cheekbones, waist-length bone-straight black hair with blunt fringe — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in jet black and deep charcoal scales coiling from left ankle up endless left leg across flat angular torso over right shoulder, dragon head anchored over right breast as primary focal climax with blazing onyx-black eyes barely visible on void skin, cascading WISTERIA in deep charcoal and midnight purple filling every gap of runway body from neck to ankles, ultra-fine dark wisteria tendrils following every angular line of endless legs to ankles.\n\nEnvironment: Seoul Dongdaemun Design Plaza at night, Zaha Hadid futuristic curves illuminated in white and silver, reflection pools below, Seoul skyline glittering.\nPose: editorial high fashion walking stride, impossibly long legs in motion, arms barely moving, face forward cold high-fashion gaze, DDP architecture curving behind, body oiled to subtle matte-satin finish.\nFootwear: jet black platform stilettos 9 inch architectural heel.\nNails: extra long ballerina nails jet black with charcoal tips.\nHair: waist-length bone-straight black with blunt fringe.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_petite_kyoto": {
        "key": "irezumi_dragon_wisteria_petite_kyoto",
        "label": "DRAGON WISTERIA PETITE KYOTO",
        "category": "🐉 Irezumi Motif H",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid-20s fierce petite goddess, petite powerhouse physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — 155cm frame so intensely muscular every proportion defies belief, thick powerful thighs on short frame, full bust disproportionately large for petite frame, waist dramatically narrow, compact bubble butt, natural black afro puff enormous and dramatic — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep crimson and scarlet scales coiling from right ankle up short powerful right leg across disproportionately full bust over left shoulder, dragon head anchored over left breast as primary focal climax with blazing crimson eyes, cascading WISTERIA in deep crimson and magenta filling every gap of petite powerhouse body from neck to ankles, dense crimson wisteria clusters following every compact powerful curve to ankles with zero bare skin.\n\nEnvironment: Kyoto Fushimi Inari-taisha at dawn, thousands of vermillion torii gates receding into mist, moss and stone lanterns, cherry blossoms falling in first morning light.\nPose: standing in torii gate frame, full body visible through vermillion gate, arms crossed commanding expression, natural afro puff enormous against torii red, crimson dragon catching dawn light, body oiled to high-gloss finish.\nFootwear: deep crimson platform stilettos 8 inch.\nNails: extra long round nails deep crimson with scarlet tips.\nHair: natural black afro puff enormous dramatic.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_mature_bbw_istanbul": {
        "key": "irezumi_dragon_wisteria_mature_bbw_istanbul",
        "label": "DRAGON WISTERIA MATURE BBW ISTANBUL",
        "category": "🐉 Irezumi Motif H",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 60s magnificent elder goddess, mature BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust full and heavy projecting forward, wide generous hips of mature fullness, thighs thick and commanding, decades of magnificence in every curve, full silver afro enormous and regal — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in royal purple and deep gold scales coiling from left ankle up left leg across generous mature hips over right shoulder, dragon head anchored over right breast as primary focal climax with blazing royal-purple eyes, cascading WISTERIA in deep royal purple and antique gold filling every gap of mature BBW body from neck to ankles, dense royal wisteria clusters following every full mature curve to ankles with zero bare skin.\n\nEnvironment: Istanbul Hagia Sophia interior at night, ancient Byzantine mosaics glowing in candlelight, towering Ottoman arches, massive central dome above, centuries of empire in every stone.\nPose: full frontal elder goddess stance, full silver afro enormous against Byzantine gold, both hands open at sides palms forward elder blessing pose, dragon coiling across mature BBW curves in full display, regal expression of absolute authority, body oiled to warm high-gloss finish.\nFootwear: royal purple platform stilettos 7 inch.\nNails: extra long round nails royal purple with antique gold tips.\nHair: full silver afro enormous and regal.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_athletic_void": {
        "key": "irezumi_dragon_wisteria_athletic_void",
        "label": "DRAGON WISTERIA ATHLETIC VOID",
        "category": "🐉 Irezumi Motif H",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 20s apex predator goddess, athletic hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — lean muscle everywhere but feminine curves dominant, full round bubble butt of impossible projection, powerful thick thighs, defined abs visible, full bust projecting forward, shoulders broad and powerful, natural black locs loose to shoulders — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in pure white and ice-blue scales coiling from right ankle up right leg across powerful abs over left shoulder, dragon head anchored over left breast as primary focal climax with blazing ice-white eyes maximum contrast on void skin, cascading WISTERIA in pure white and pale ice-blue filling every gap of athletic hourglass body from neck to ankles, ultra-fine white wisteria tendrils following every athletic curve and muscle line to ankles.\n\nPose: kneeling one knee down, right knee on ground left leg bent power stance, both arms raised overhead hands clasped, full body displayed from knee to crown, bubble butt visible in profile, ice-white dragon catching single cold spotlight.\nFootwear: ice-white platform stilettos 8 inch.\nNails: extra long stiletto nails ice-white with pale blue tips.\nHair: natural black locs loose to shoulders.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single cold white overhead spotlight. Pattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_superbbw_void": {
        "key": "irezumi_dragon_wisteria_superbbw_void",
        "label": "DRAGON WISTERIA SUPERBBW VOID",
        "category": "🐉 Irezumi Motif H",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid-30s apex goddess, super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips so impossibly wide they dominate the entire frame edge to edge, thighs each wider than most human torsos, bubble butt projecting rearward to absolute maximum impossible volume, waist still dramatically defined creating extreme hourglass despite BBW scale, natural black hair in massive crown twist updo — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in blazing electric gold and white scales coiling from right ankle up right thigh across impossibly wide hips over left shoulder, dragon head anchored over left breast as primary focal climax with blazing gold-white eyes maximum contrast, cascading WISTERIA in pure gold and cream white filling every gap of super BBW body from neck to ankles, dense gold wisteria clusters following every impossible extreme curve to ankles with zero bare skin.\n\nPose: side profile stance, full super BBW silhouette in pure profile showing maximum hip-to-waist ratio, one arm raised touching crown twist updo, chin raised commanding expression, bubble butt projecting rearward maximum, bust projecting forward maximum, gold dragon catching single spotlight in pure profile display, body oiled to extreme high-gloss finish.\nFootwear: gold platform stilettos 8 inch.\nNails: extra long coffin nails electric gold with cream tips.\nHair: natural black massive crown twist updo.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single cold white spotlight from side catching full BBW silhouette profile. Pattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_bbw_dubai": {
        "key": "irezumi_dragon_wisteria_bbw_dubai",
        "label": "DRAGON WISTERIA BBW DUBAI",
        "category": "🐉 Irezumi Motif H",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 30s commanding goddess, BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust full and projecting forward in impossible volume, hips flaring to extreme maximum width, thighs massively thick and powerful, bubble butt of generous impossible projection, waist defined creating dramatic curves, long sleek jet black hair with rose gold highlights in high dramatic ponytail — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in rose gold and champagne scales coiling from left ankle up left leg across generous hips over right shoulder, dragon head anchored over right breast as primary focal climax with blazing rose gold eyes, cascading WISTERIA in blush rose and champagne gold filling every gap of BBW body from neck to ankles.\n\nEnvironment: Dubai Burj Khalifa at night, tower soaring into darkness above, Dubai Fountain illuminated below in blue and gold, Downtown Dubai skyline glittering.\nPose: full frontal commanding stance, both hands on dramatically wide hips, chin raised goddess expression, rose-gold dragon catching tower light, Burj Khalifa soaring directly behind as crown, body oiled to rich high-gloss finish.\nFootwear: rose gold platform stilettos 8 inch.\nNails: extra long almond nails rose gold with champagne tips.\nHair: long sleek jet black with rose gold highlights high dramatic ponytail.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_hourglass_santorini": {
        "key": "irezumi_dragon_wisteria_hourglass_santorini",
        "label": "DRAGON WISTERIA HOURGLASS SANTORINI",
        "category": "🐉 Irezumi Motif H",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 40s timeless goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs enormously thick, voluminous silver-white natural hair in loose goddess waves to shoulders — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep cobalt blue and Aegean white scales coiling from right ankle up right leg across cinched waist over left shoulder, dragon head anchored over left breast as primary focal climax with blazing cobalt-blue eyes, cascading WISTERIA in deep Aegean blue and pure white filling every gap of extreme hourglass body from neck to ankles, dense cobalt wisteria clusters following dramatic hourglass silhouette to ankles.\n\nEnvironment: Santorini caldera at sunset, iconic white-domed blue churches on cliff edge, Aegean Sea burning orange below, Oia village cascading down volcanic cliffs, cyclamen flowers in foreground.\nPose: standing at caldera edge, arms open wide embracing the sunset view, chin raised eyes closed ecstatic expression, full hourglass silhouette against Aegean sunset, cobalt-blue dragon catching last golden light, silver-white hair catching sunset breeze, body oiled to warm satin high-gloss finish.\nFootwear: cobalt blue platform stilettos 8 inch.\nNails: extra long square nails cobalt blue with white tips.\nHair: voluminous silver-white natural hair loose goddess waves to shoulders.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_athletic_new_york": {
        "key": "irezumi_dragon_wisteria_athletic_new_york",
        "label": "DRAGON WISTERIA ATHLETIC NEW YORK",
        "category": "🐉 Irezumi Motif H",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 20s power goddess, athletic BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — thick powerful thighs of maximum density, full round bubble butt of impossible projection, defined abs visible beneath full curves, broad powerful shoulders, full bust projecting forward, natural black afro enormous and commanding — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep forest green and jade scales coiling from left ankle up left leg across powerful abs over right shoulder, dragon head anchored over right breast as primary focal climax with blazing jade-green eyes, cascading WISTERIA in deep emerald and jade green filling every gap of athletic BBW body from neck to ankles.\n\nEnvironment: New York City Brooklyn Bridge at blue hour, suspension cables framing shot, Manhattan skyline glittering beyond East River, city lights beginning to ignite.\nPose: walking stride toward camera, powerful thighs in motion, arms relaxed at sides, direct confident gaze into lens, natural afro enormous against bridge cables, body oiled to high-gloss finish.\nFootwear: deep emerald platform stilettos 8 inch.\nNails: extra long round nails deep emerald with jade tips.\nHair: natural black afro enormous and commanding.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_dragon_wisteria_mature_hourglass_void": {
        "key": "irezumi_dragon_wisteria_mature_hourglass_void",
        "label": "DRAGON WISTERIA MATURE HOURGLASS VOID",
        "category": "🐉 Irezumi Motif H",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid-50s magnificent elder goddess, mature extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust overwhelmingly full and projecting forward defying gravity, waist cinched dramatic despite mature fullness, hips of absolute maximum mature width, thighs enormously thick and commanding, full silver natural afro enormous cathedral-like crown — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in pure silver and ice-white scales coiling from right ankle up right leg across mature hourglass curves over left shoulder, dragon head anchored over left breast as primary focal climax with blazing silver-white eyes maximum contrast on void skin, cascading WISTERIA in pure white and pale silver filling every gap of mature hourglass body from neck to ankles, ultra-fine silver-white wisteria tendrils following every mature curve to ankles.\n\nPose: seated on invisible surface one leg extended forward, full mature hourglass silhouette in seated display, both hands resting on wide hips, chin raised elder goddess expression of absolute authority, full silver afro cathedral crown, silver dragon catching single cold spotlight, white wisteria glowing against void skin, body oiled to pearl high-gloss finish.\nFootwear: silver chrome platform stilettos 8 inch.\nNails: extra long stiletto nails pure silver with ice-white tips.\nHair: full silver natural afro enormous cathedral crown.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single cold white overhead spotlight. Pattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    # ── I 모티프 (skull+chrysanthemum) ──────────────────────

    "irezumi_skull_chrysanthemum_black_glam_void": {
        "key": "irezumi_skull_chrysanthemum_black_glam_void",
        "label": "SKULL CHRYSANTHEMUM BLACK GLAM VOID",
        "category": "💀 Irezumi Motif I",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid-20s fierce goddess, Black glamour hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs enormously thick, natural black hair voluminous afro crown — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax, jaw wide and commanding, eye sockets blazing cold white light, fine white ink detail throughout, surrounded by explosively blooming CHRYSANTHEMUMS in pure white and pale cream radiating outward from skull across entire bust, cascading white chrysanthemum petals filling every gap of hourglass body from neck to ankles, maximum white-on-void contrast composition.\n\nPose: full frontal power stance, feet wide apart, both fists clenched at sides, chin down intense direct gaze into lens, full hourglass silhouette dead center frame, white skull center chest blazing against void skin, body oiled to extreme wet high-gloss finish.\nFootwear: white chrome platform stilettos 9 inch.\nNails: extra long stiletto nails pure white with chrome tips.\nHair: natural black voluminous afro crown maximum size.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single cold white overhead spotlight maximum contrast white tattoo on void skin. Pattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_aurora_nordic": {
        "key": "irezumi_skull_chrysanthemum_aurora_nordic",
        "label": "SKULL CHRYSANTHEMUM AURORA NORDIC",
        "category": "💀 Irezumi Motif I",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 20s warrior goddess, extreme athletic hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — lean powerful muscle everywhere, full round bubble butt of impossible projection, thick powerful thighs, defined abs, full bust projecting forward, long platinum silver locs to mid-back — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax with blazing aurora-green eye sockets, surrounded by explosively blooming CHRYSANTHEMUMS in deep emerald green and silver radiating outward from skull across athletic bust, cascading emerald chrysanthemum petals filling every gap of athletic body from neck to ankles, dense green-silver chrysanthemum fields following every muscle line and curve to ankles with zero bare skin.\n\nEnvironment: Iceland glacial landscape at night, Aurora Borealis in full explosion overhead, curtains of emerald green and violet dancing across black sky, glacial ice blue beneath feet, volcanic mountain silhouette.\nPose: standing on glacier edge, arms raised overhead crossed at wrists, chin raised eyes closed ecstatic expression, full athletic silhouette against aurora explosion, emerald skull catching aurora light, platinum locs catching green aurora glow, body oiled to ice-gloss finish.\nFootwear: silver chrome platform stilettos 8 inch.\nNails: extra long stiletto nails emerald green with silver tips.\nHair: long platinum silver locs to mid-back.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_bbw_versailles": {
        "key": "irezumi_skull_chrysanthemum_bbw_versailles",
        "label": "SKULL CHRYSANTHEMUM BBW VERSAILLES",
        "category": "💀 Irezumi Motif I",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 40s commanding goddess, BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust full and projecting forward in impossible volume, hips flaring to extreme maximum width, thighs massively thick and powerful, bubble butt of generous projection, waist defined creating dramatic curves, long sleek black hair with deep crimson highlights in dramatic updo — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax with blazing crimson-gold eye sockets, surrounded by explosively blooming CHRYSANTHEMUMS in deep crimson and antique gold radiating outward from skull across BBW bust, cascading crimson-gold chrysanthemum petals filling every gap of BBW body from neck to ankles.\n\nEnvironment: Hall of Mirrors Versailles, gilded baroque grandeur in full blaze, crystal chandeliers above blazing gold, gilded mirror frames reflecting infinity.\nPose: standing center hall, one hand raised touching dramatic updo, chin raised commanding expression, crimson skull catching chandelier gold light, full BBW silhouette framed by mirror infinity, body oiled to warm high-gloss finish.\nFootwear: deep crimson platform stilettos 8 inch with gold detail.\nNails: extra long coffin nails deep crimson with antique gold tips.\nHair: long sleek black with deep crimson highlights dramatic updo.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_runway_void": {
        "key": "irezumi_skull_chrysanthemum_runway_void",
        "label": "SKULL CHRYSANTHEMUM RUNWAY VOID",
        "category": "💀 Irezumi Motif I",
        "tier": "SS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 20s high fashion goddess, extreme runway slim physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — impossibly elongated legs filling full frame height, flat angular torso, sharp hip bones projecting outward, impossibly long neck, razor cheekbones, bone-straight jet black hair severe blunt cut to jaw — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax with blazing gold eye sockets maximum contrast on void skin, surrounded by explosively blooming CHRYSANTHEMUMS in burnished gold and deep amber radiating outward from skull following angular torso lines, cascading gold chrysanthemum petals filling every gap of runway body from neck to ankles.\n\nPose: high fashion editorial seated on invisible surface, one leg extended forward crossed over other, both hands resting on extended knee, spine perfectly upright, chin raised cold high-fashion expression, gold skull center chest blazing, body oiled to subtle satin finish.\nFootwear: gold architectural platform stilettos 10 inch.\nNails: extra long ballerina nails burnished gold with amber tips.\nHair: bone-straight jet black severe blunt cut to jaw.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single cold gold spotlight from above. Pattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_hourglass_istanbul": {
        "key": "irezumi_skull_chrysanthemum_hourglass_istanbul",
        "label": "SKULL CHRYSANTHEMUM HOURGLASS ISTANBUL",
        "category": "💀 Irezumi Motif I",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid-40s timeless goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs enormously thick, voluminous natural silver-white hair in dramatic loose goddess waves to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax with blazing deep violet eye sockets, surrounded by explosively blooming CHRYSANTHEMUMS in deep violet and antique gold radiating outward from skull across hourglass bust, cascading violet-gold chrysanthemum petals filling every gap of extreme hourglass body from neck to ankles.\n\nEnvironment: Istanbul Bosphorus at night, historic Ottoman mosques illuminated on both shores, Bosphorus Bridge lit in violet and gold above, minarets piercing night sky.\nPose: standing at waterfront, both hands cupping silver-white waves lifting hair dramatically, chin raised goddess expression, full hourglass silhouette against Bosphorus night, violet skull catching bridge light, body oiled to warm high-gloss finish.\nFootwear: deep violet platform stilettos 8 inch with gold trim.\nNails: extra long almond nails deep violet with antique gold tips.\nHair: voluminous natural silver-white dramatic loose goddess waves to waist.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_superbbw_void": {
        "key": "irezumi_skull_chrysanthemum_superbbw_void",
        "label": "SKULL CHRYSANTHEMUM SUPERBBW VOID",
        "category": "💀 Irezumi Motif I",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid-30s commanding goddess, super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips so impossibly wide dominating entire frame edge to edge, thighs each wider than most human torsos, bubble butt projecting rearward to absolute maximum volume, waist defined creating extreme contrast, voluminous natural black hair in massive afro crown — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on back upper torso as primary focal climax visible in rear view, jaw wide and commanding, eye sockets blazing cold white light, surrounded by explosively blooming CHRYSANTHEMUMS in pure white and cream radiating outward from skull across entire back, cascading white chrysanthemum petals filling every gap of super BBW body from neck to ankles — dense white chrysanthemum fields following every impossible extreme curve.\n\nPose: full rear 3/4 angle, bubble butt projecting toward camera at maximum impossible volume, head turned over shoulder with fierce goddess expression, natural afro crown enormous, one hand on impossibly wide hip, white skull visible on upper back, white chrysanthemums cascading down full rear silhouette to ankles, body oiled to extreme high-gloss finish.\nFootwear: white platform stilettos 8 inch.\nNails: extra long coffin nails pure white with cream tips.\nHair: voluminous natural black massive afro crown.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single cold white spotlight from above. Pattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_hourglass_tokyo": {
        "key": "irezumi_skull_chrysanthemum_hourglass_tokyo",
        "label": "SKULL CHRYSANTHEMUM HOURGLASS TOKYO",
        "category": "💀 Irezumi Motif I",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 30s fierce goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs enormously thick, long sleek black hair with electric red highlights in sharp blunt cut to collarbone — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax with blazing crimson eye sockets, surrounded by explosively blooming CHRYSANTHEMUMS in deep crimson and scarlet radiating outward from skull across entire hourglass bust, cascading crimson chrysanthemum petals filling every gap of extreme hourglass body from neck to ankles.\n\nEnvironment: Tokyo Shibuya crossing at night, massive neon screens blazing red and white above, thousands of crossing pedestrians below, rain-slicked streets reflecting crimson neon.\nPose: standing center crossing, full frontal commanding stance, both hands on dramatically wide hips, chin raised fierce expression, crimson skull catching Shibuya neon light, body oiled to wet high-gloss finish.\nFootwear: deep crimson platform stilettos 9 inch.\nNails: extra long stiletto nails deep crimson with scarlet tips.\nHair: long sleek black with electric red highlights sharp blunt cut to collarbone.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_mature_bbw_paris": {
        "key": "irezumi_skull_chrysanthemum_mature_bbw_paris",
        "label": "SKULL CHRYSANTHEMUM MATURE BBW PARIS",
        "category": "💀 Irezumi Motif I",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 60s magnificent elder goddess, mature BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust full and heavy projecting forward in mature fullness, wide generous hips of absolute maximum width, thighs thick and commanding, full silver natural afro enormous and regal — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax with blazing gold eye sockets, surrounded by explosively blooming CHRYSANTHEMUMS in antique gold and champagne radiating outward from skull across mature BBW bust, cascading gold chrysanthemum petals filling every gap of mature BBW body from neck to ankles.\n\nEnvironment: Paris Eiffel Tower at night, iron tower fully illuminated in gold, Champ de Mars below, Paris skyline glittering, warm golden Parisian night light.\nPose: full frontal elder goddess stance, both arms raised open wide embracing Paris night, full silver afro enormous against gold tower, chin raised expression of absolute authority, gold skull catching tower light, body oiled to warm high-gloss finish.\nFootwear: antique gold platform stilettos 7 inch.\nNails: extra long round nails antique gold with champagne tips.\nHair: full silver natural afro enormous and regal.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_athletic_void": {
        "key": "irezumi_skull_chrysanthemum_athletic_void",
        "label": "SKULL CHRYSANTHEMUM ATHLETIC VOID",
        "category": "💀 Irezumi Motif I",
        "tier": "SS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 20s warrior goddess, extreme muscular athletic physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — biceps massively defined impossible for human anatomy, shoulders broad and powerful, abs carved like obsidian, quads and glutes of impossible density, full round bubble butt projecting rearward, waist dramatically narrow, natural black locs loose to mid-back — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax with blazing electric blue eye sockets maximum contrast on void skin, surrounded by explosively blooming CHRYSANTHEMUMS in electric blue and ice white radiating outward from skull following every carved muscle line across torso, cascading electric blue chrysanthemum petals filling every gap of muscular body from neck to ankles.\n\nPose: side profile walking stride, powerful muscular legs in motion, arms relaxed at sides, profile showing full muscle definition, skull visible on chest in profile, electric blue chrysanthemums cascading down muscle lines, body oiled to wet-chrome high-gloss finish.\nFootwear: electric blue platform stilettos 8 inch.\nNails: extra long stiletto nails electric blue with ice-white tips.\nHair: natural black locs loose to mid-back.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single cold blue-white spotlight. Pattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_hourglass_mexico": {
        "key": "irezumi_skull_chrysanthemum_hourglass_mexico",
        "label": "SKULL CHRYSANTHEMUM HOURGLASS MEXICO",
        "category": "💀 Irezumi Motif I",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 40s timeless goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs enormously thick and powerful, long voluminous black hair with vivid violet highlights in dramatic loose waves to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax with blazing violet eye sockets, surrounded by explosively blooming CHRYSANTHEMUMS in deep violet and magenta radiating outward from skull across hourglass bust, cascading violet chrysanthemum petals filling every gap of extreme hourglass body from neck to ankles.\n\nEnvironment: Mexico City Dia de los Muertos festival at night, streets ablaze with marigold orange and violet decorations, sugar skull altars glowing with candles, papel picado banners overhead in violet and gold, crowds in elaborate face paint below.\nPose: standing on festival altar steps, both hands raised holding enormous marigold flowers at either side, chin raised goddess expression, violet skull echoing festival sugar skulls, violet-highlight waves cascading down, full hourglass silhouette lit by candle and festival light, body oiled to warm high-gloss finish.\nFootwear: deep violet platform stilettos 8 inch with gold studs.\nNails: extra long coffin nails deep violet with magenta tips.\nHair: long voluminous black with vivid violet highlights dramatic loose waves to waist.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_superbbw_void2": {
        "key": "irezumi_skull_chrysanthemum_superbbw_void2",
        "label": "SKULL CHRYSANTHEMUM SUPERBBW VOID 2",
        "category": "💀 Irezumi Motif I",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 40s apex goddess, super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips so impossibly wide filling entire frame edge to edge, thighs each wider than most human torsos, bubble butt projecting rearward absolute maximum volume, waist dramatically defined creating extreme hourglass despite BBW scale, long sleek black hair with blazing gold highlights in dramatic side-swept waves to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax, each eye socket blazing electric gold, jaw wide commanding open, surrounded by explosively blooming CHRYSANTHEMUMS in blazing gold and deep amber radiating from skull across impossibly massive bust, cascading gold chrysanthemum petals filling every gap of super BBW body from neck to ankles.\n\nPose: full frontal stance feet wide apart, both hands on impossibly wide hips elbows flared outward maximizing silhouette width, chin down fierce direct gaze into lens, full super BBW silhouette dominating frame edge to edge, gold skull center chest blazing, body oiled to extreme wet high-gloss finish.\nFootwear: gold platform stilettos 9 inch.\nNails: extra long square nails blazing gold with amber tips.\nHair: long sleek black with blazing gold highlights dramatic side-swept waves to waist.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single cold white overhead spotlight. Pattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_superbbw_dubai": {
        "key": "irezumi_skull_chrysanthemum_superbbw_dubai",
        "label": "SKULL CHRYSANTHEMUM SUPERBBW DUBAI",
        "category": "💀 Irezumi Motif I",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid-30s commanding goddess, super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips so impossibly wide dominating entire frame, thighs each wider than most human torsos, bubble butt projecting rearward to absolute maximum, waist still defined creating extreme contrast, voluminous natural black hair in enormous goddess updo with gold pins — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax with blazing rose-gold eye sockets, surrounded by explosively blooming CHRYSANTHEMUMS in rose gold and champagne radiating outward from skull across super BBW bust, cascading rose-gold chrysanthemum petals filling every gap of super BBW body from neck to ankles.\n\nEnvironment: Dubai Palm Jumeirah at night, Atlantis hotel blazing in gold behind, Persian Gulf glittering below, Dubai skyline golden horizon.\nPose: 3/4 rear angle, bubble butt projecting toward camera maximum impossible volume, head turned over shoulder with fierce goddess expression, enormous updo dramatic against Dubai gold skyline, one hand raised touching gold pins in updo, body oiled to extreme high-gloss finish.\nFootwear: rose gold platform stilettos 9 inch.\nNails: extra long coffin nails rose gold with champagne tips.\nHair: voluminous natural black enormous goddess updo with gold pins.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_superbbw_kyoto": {
        "key": "irezumi_skull_chrysanthemum_superbbw_kyoto",
        "label": "SKULL CHRYSANTHEMUM SUPERBBW KYOTO",
        "category": "💀 Irezumi Motif I",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 30s fierce goddess, super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips so impossibly wide they dominate the entire frame, thighs each wider than most human torsos, bubble butt projecting rearward to absolute maximum volume, waist defined creating dramatic contrast at impossible scale, natural black hair in massive twisted crown updo with crimson lacquer pins — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax with blazing deep crimson eye sockets, surrounded by explosively blooming CHRYSANTHEMUMS in deep crimson and vermillion radiating outward from skull across super BBW bust, cascading crimson chrysanthemum petals filling every gap of super BBW body from neck to ankles.\n\nEnvironment: Kyoto Arashiyama bamboo grove at dawn, towering green bamboo shafts filtering first pink dawn light, stone path through bamboo, mist rising from ground.\nPose: full frontal commanding stance, both hands raised pressing palms flat against two bamboo shafts at either side, chin raised fierce expression, full super BBW silhouette between bamboo shafts, crimson skull catching dawn pink light, massive crown updo at bamboo height, body oiled to high-gloss finish.\nFootwear: deep crimson platform stilettos 8 inch with lacquer finish.\nNails: extra long round nails deep crimson with vermillion tips.\nHair: natural black massive twisted crown updo with crimson lacquer pins.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_superbbw_marrakech": {
        "key": "irezumi_skull_chrysanthemum_superbbw_marrakech",
        "label": "SKULL CHRYSANTHEMUM SUPERBBW MARRAKECH",
        "category": "💀 Irezumi Motif I",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid-40s magnificent goddess, super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips so impossibly wide filling the entire frame, thighs each wider than most human torsos, bubble butt projecting rearward to absolute maximum impossible volume, waist defined at impossible scale creating dramatic contrast, long natural silver locs to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL centered on chest as primary focal climax with blazing deep amber eye sockets, surrounded by explosively blooming CHRYSANTHEMUMS in deep burnt amber and terracotta radiating outward from skull across super BBW bust, cascading amber-terracotta chrysanthemum petals filling every gap of super BBW body from neck to ankles.\n\nEnvironment: Marrakech Djemaa el-Fna at golden hour, ancient medina walls glowing deep amber, spice market stalls blazing orange and saffron, Atlas Mountains silhouette at dusk.\nPose: side profile, full super BBW silhouette in pure profile showing maximum hip-to-waist ratio and maximum bubble butt projection, both arms raised lifting silver locs dramatically overhead, chin raised goddess expression, amber skull catching Moroccan golden hour light, body oiled to warm amber high-gloss finish.\nFootwear: burnt amber platform stilettos 8 inch with gold ankle wrap.\nNails: extra long stiletto nails burnt amber with terracotta tips.\nHair: long natural silver locs to waist.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_gold_void": {
        "key": "irezumi_skull_chrysanthemum_gold_void",
        "label": "SKULL CHRYSANTHEMUM GOLD VOID",
        "category": "💀 Irezumi Motif I",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid-40s magnificent goddess, TRUE super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE — massive pendulous belly hanging heavy with generous natural fat folds and deep rolls, belly projecting forward as dominant central volume, deep navel buried in soft flesh, thick side rolls, arms heavy and thick, enormous bust resting on belly shelf, hips enormously wide, thighs massively thick — NO cinched waist, full authentic super BBW proportions, long natural black locs to mid-back — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL riding center of enormous belly as primary focal climax, skull jaw following natural belly fold line, eye sockets blazing electric gold, surrounded by explosively blooming CHRYSANTHEMUMS in blazing gold and deep amber radiating from skull across belly folds, side rolls, and enormous bust, cascading gold chrysanthemum petals filling every gap of super BBW body from neck to ankles.\n\nPose: 3/4 front angle, body turned slightly showing belly volume in dramatic 3/4 perspective, right hand resting flat on top of belly shelf fingers spread, left arm hanging at side, chin raised fierce goddess expression, body oiled to extreme high-gloss finish.\nFootwear: gold platform stilettos 7 inch wide-fit.\nNails: extra long coffin nails blazing gold with amber tips.\nHair: long natural black locs to mid-back.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single warm gold spotlight from above. Pattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_crimson_void": {
        "key": "irezumi_skull_chrysanthemum_crimson_void",
        "label": "SKULL CHRYSANTHEMUM CRIMSON VOID",
        "category": "💀 Irezumi Motif I",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 30s fierce goddess, TRUE super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE — massive pendulous belly hanging heavy with generous natural fat folds, belly projecting forward dominant central volume, deep navel buried in soft belly flesh, thick side rolls visible at flanks, arms heavy and thick, enormous bust resting on belly shelf, hips enormously wide flaring outward, thighs massively thick — NO cinched waist, full authentic super BBW body where belly dominates, voluminous natural black afro enormous crown — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL riding center of enormous belly as primary focal climax, eye sockets blazing deep crimson fire, skull rendered in vivid crimson ink following natural belly curve and fold, surrounded by explosively blooming CHRYSANTHEMUMS in deep crimson and scarlet radiating from skull across belly rolls, thick arms, side rolls, and enormous bust, cascading crimson chrysanthemum petals filling every gap from neck to ankles.\n\nPose: pure 90 degree side profile, full super BBW silhouette in absolute side view, belly projecting forward maximum, bubble butt projecting rearward maximum simultaneously, arms relaxed at sides, chin raised profile goddess expression, crimson skull riding belly curve visible in dramatic profile, enormous afro crown in profile, body oiled to extreme high-gloss finish.\nFootwear: deep crimson platform stilettos 7 inch wide-fit.\nNails: extra long stiletto nails deep crimson with scarlet tips.\nHair: voluminous natural black afro enormous crown.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single cold side spotlight catching full BBW silhouette profile. Pattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_violet_istanbul": {
        "key": "irezumi_skull_chrysanthemum_violet_istanbul",
        "label": "SKULL CHRYSANTHEMUM VIOLET ISTANBUL",
        "category": "💀 Irezumi Motif I",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 50s elder goddess, TRUE super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE — massive pendulous belly hanging heavy with generous natural fat folds and rolls, belly the dominant central volume of entire composition, deep navel buried in soft flesh, thick side rolls, arms heavy and thick, enormous bust resting fully on belly shelf, hips enormously wide, thighs massively thick — NO cinched waist, full authentic super BBW where belly is queen, long silver-white natural hair in dramatic loose waves to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL riding center of enormous belly as primary focal climax, eye sockets blazing deep violet, skull following natural belly fold, surrounded by explosively blooming CHRYSANTHEMUMS in deep violet and antique gold radiating from skull across belly folds, side rolls, enormous bust, cascading violet-gold chrysanthemum petals filling every gap from neck to ankles.\n\nEnvironment: Istanbul Bosphorus waterfront at night, Ortakoy mosque illuminated in gold behind, Bosphorus Bridge glowing violet above, ancient Ottoman architecture reflecting in dark water.\nPose: 3/4 rear angle, belly visible projecting at side in 3/4 view, bubble butt dominant in rear 3/4, head turned over shoulder with elder goddess expression, silver-white waves cascading down, one hand on enormously wide hip, body oiled to warm high-gloss finish.\nFootwear: deep violet platform stilettos 7 inch wide-fit.\nNails: extra long almond nails deep violet with gold tips.\nHair: long silver-white natural hair dramatic loose waves to waist.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_copper_marrakech": {
        "key": "irezumi_skull_chrysanthemum_copper_marrakech",
        "label": "SKULL CHRYSANTHEMUM COPPER MARRAKECH",
        "category": "💀 Irezumi Motif I",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid-40s commanding goddess, TRUE super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE — massive pendulous belly hanging heavy with generous natural fat folds, belly projecting forward as dominant volume, deep navel buried in soft flesh, thick side rolls, arms heavy and thick, enormous bust resting on belly shelf, hips enormously wide, thighs massively thick — NO cinched waist, full authentic super BBW proportions, long natural silver locs to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL riding center of enormous belly as primary focal climax, eye sockets blazing burnished copper-amber, surrounded by explosively blooming CHRYSANTHEMUMS in burnished copper and deep terracotta radiating from skull across belly folds and rolls, cascading copper chrysanthemum petals filling every gap from neck to ankles.\n\nEnvironment: Marrakech rooftop terrace at golden hour, ancient medina rooftops cascading below in amber, Atlas Mountains glowing copper at dusk, warm Moroccan lanterns beginning to glow.\nPose: seated on low Moroccan pouf, legs slightly apart both feet flat, hands resting on thighs palms down, belly hanging heavy forward between thighs in seated volume, chin raised commanding expression, full super BBW seated silhouette, copper skull center belly catching golden hour light, body oiled to warm amber high-gloss finish.\nFootwear: burnished copper platform mules wide-fit.\nNails: extra long round nails burnished copper with terracotta tips.\nHair: long natural silver locs to waist.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_white_void": {
        "key": "irezumi_skull_chrysanthemum_white_void",
        "label": "SKULL CHRYSANTHEMUM WHITE VOID",
        "category": "💀 Irezumi Motif I",
        "tier": "SS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 40s apex goddess, TRUE super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE — massive pendulous belly hanging heavy with generous natural fat folds and deep rolls, belly the undeniable dominant central volume, deep navel buried in soft belly flesh, thick side rolls and flank rolls, arms heavy and thick, enormous bust resting fully on belly shelf, hips enormously wide, thighs massively thick pressing together — NO cinched waist, full authentic super BBW body, natural black hair in massive braided updo crown — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL riding center of enormous belly as primary focal climax, eye sockets blazing pure ice-white maximum contrast, skull rendered in pure white ink following natural belly curve and fold, surrounded by explosively blooming CHRYSANTHEMUMS in pure white and pale silver radiating from skull across belly folds, enormous bust, cascading white chrysanthemum petals filling every gap from neck to ankles.\n\nPose: kneeling, both knees on ground sitting back on heels, body upright, belly hanging heavy forward in kneeling position, both hands raised above head palms together prayer position, chin raised eyes closed serene goddess expression, white skull riding belly curve, massive braided updo crown, body oiled to extreme pearl high-gloss finish.\nFootwear: none, bare feet in kneeling position.\nNails: extra long stiletto nails pure white with silver tips.\nHair: natural black massive braided updo crown.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single cold white overhead spotlight. Pattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_folds_void_side": {
        "key": "irezumi_skull_chrysanthemum_folds_void_side",
        "label": "SKULL CHRYSANTHEMUM FOLDS VOID SIDE",
        "category": "💀 Irezumi Motif I",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 40s apex goddess, TRUE super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE — massive pendulous belly with natural fat rolls and skin folds, lower belly apron fold hanging heavy, mid-belly fold crease line visible, natural fat rolls at waist sides, arms heavy and thick, enormous bust resting on belly shelf, bubble butt projecting maximum rearward, thighs massively thick — NO smooth pregnancy belly, authentic super BBW with visible fold lines, voluminous natural black afro enormous — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL on belly visible in side profile, eye sockets blazing electric gold, CHRYSANTHEMUMS in blazing gold and amber following fold lines in side profile view, cascading gold chrysanthemum filling every gap neck to ankles.\n\nPose: pure 90 degree side profile, full super BBW silhouette in absolute side view, belly projecting forward maximum, bubble butt projecting rearward maximum, arms relaxed, chin raised profile goddess expression, enormous afro in profile, body oiled to extreme high-gloss finish.\nFootwear: gold platform stilettos 7 inch wide-fit.\nNails: extra long stiletto nails blazing gold.\nHair: voluminous natural black afro enormous.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single cold hard sidelight from front-left catching fold ridge highlights. Pattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "irezumi_skull_chrysanthemum_folds_istanbul": {
        "key": "irezumi_skull_chrysanthemum_folds_istanbul",
        "label": "SKULL CHRYSANTHEMUM FOLDS ISTANBUL",
        "category": "💀 Irezumi Motif I",
        "tier": "SSS",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 50s elder goddess, TRUE super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE — soft pendulous belly with natural fat rolls and skin folds, lower belly apron fold drooping naturally, mid-belly horizontal fold crease clearly defined, love handle rolls at flanks, arms heavy and thick, enormous bust resting on belly shelf, hips enormously wide, thighs massively thick — NO smooth single volume, authentic super BBW belly, long silver-white natural hair dramatic waves to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: skull+chrysanthemum full body composition — massive SKULL riding center belly fold as primary focal climax, eye sockets blazing deep violet, CHRYSANTHEMUMS in deep violet and antique gold following fold crease lines, cascading violet-gold chrysanthemum filling every gap neck to ankles.\n\nEnvironment: Istanbul Hagia Sophia interior at night, massive Byzantine dome above blazing with golden candlelight, ancient stone columns, warm gold candlelight washing across entire scene.\nPose: 3/4 front angle, body slightly turned showing belly in 3/4 perspective, both arms raised lifting silver-white waves dramatically overhead, chin raised elder goddess expression, pendulous belly hanging forward in 3/4 view, warm Hagia Sophia dome light catching belly, body oiled to warm high-gloss finish.\nFootwear: deep violet platform stilettos 7 inch wide-fit with gold trim.\nNails: extra long almond nails deep violet with antique gold tips.\nHair: long silver-white natural hair dramatic waves to waist.\n\nPattern density MAXIMUM — EVERY inch neck to ankle. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

}

# JSON 파일 생성
for key, data in PRESETS.items():
    path = os.path.join(PRESETS_DIR, f"{key}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"✅ {path}")

print(f"\n총 {len(PRESETS)}개 JSON 생성 완료")
