# -*- coding: utf-8 -*-
import json, os

BASE = r"C:\Dev\LumineX\presets"
os.makedirs(BASE, exist_ok=True)

presets = {
    "ksf_bp_001": {
        "key": "ksf_bp_001",
        "label": "CRACKED EMPRESS — Black Void SuperBBW Side Gold",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 50s legendary goddess, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, silver-white natural hair swept up in imperial crown braid — full body kintsugi BLAZING GOLD crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC GOLD liquid seeping through deep fissure lines on jet black ceramic glaze base, crack lines tracing every curve fold and crease of enormous belly volume naturally, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where gold sunburst cracks radiate outward as organic climax, secondary crack networks branching across belly hips thighs calves filling every gap tightly. Pose: pure 90-degree side profile facing left, chest projecting forward with gold sunburst anchors visible in side silhouette, belly projecting forward in full globe volume dominating mid-frame, both hands clasped behind back emphasizing forward projection of bust and belly simultaneously, chin raised commanding legendary elder goddess presence, entire side silhouette filling frame from head to bare feet.\nFootwear: bare feet gold-painted toenails.\nNails: extra long stiletto nails solid gold.\nHair: silver-white natural hair swept up in imperial crown braid.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single narrow gold light shaft from above catching crack lines dramatically. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING GOLD on blue-black void skin explosive contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_002": {
        "key": "ksf_bp_002",
        "label": "WARRIOR'S MAP — Middle Eastern Muscular Kneeling Copper",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman kneeling.\n\nMiddle Eastern woman in her mid-fifties, steel-grey waist-length hair loose and wild, extreme muscular physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — shoulders so enormously wide and defined, arms bulging with impossible muscle mass, core etched with extreme definition, thighs massively thick with muscle striations, elder warrior goddess commanding presence — full body kintsugi COPPER GOLD crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING COPPER GOLD liquid following muscle striations exactly tracing every definition and groove naturally, pattern reaching its most intense and dense concentration across full chest as natural focal point where large copper sunflower crack pattern spans both breasts individually as organic climax, deep verdigris-green patina pooling in crack shadows throughout, secondary copper networks across biceps shoulders thighs and calves following every muscle line filling every gap tightly, ancient bronze sculpture texture between fissure lines. Pose: kneeling warrior pose one knee down planted, other knee raised, arms spread wide open, head raised chin up commanding direct eye contact, chest projected forward with copper sunflower anchor prominent, entire muscular physique displayed in full impossible volume.\nFootwear: bare feet copper-tipped toenails.\nNails: extra long stiletto nails copper verdigris.\nHair: steel-grey waist-length hair loose wild and untamed.\n\nMANDATORY pure pitch black void background only. ONE woman only. Dramatic single overhead spotlight deep shadow fill accentuating muscle definition. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. COPPER GOLD with verdigris shadow ancient bronze contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_003": {
        "key": "ksf_bp_003",
        "label": "BOTANICAL FAULT — Nordic Runway Walking Gold Pink",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman walking.\n\nNordic woman in her mid-sixties, waist-length platinum white hair flowing mid-stride, extreme runway slim physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — legs so impossibly long and endless extending far beyond normal proportion, height towering and commanding filling entire frame vertically from top to bottom, waist cinched to absolute impossible minimum, platinum white hair billowing behind in motion, timeless elder Nordic goddess beauty — full body kintsugi BLAZING GOLD botanical crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both endless legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC GOLD crack lines blooming into painted cherry blossom branches at every endpoint flowers emerging from every major fissure as cracks become branches naturally, pattern reaching its most intense and dense concentration across full chest as natural focal point where largest cherry blossom cluster spans both breasts as organic climax, VIVID PINK petal details scattered densely across belly hips thighs and both endless legs entirely filling every gap tightly, matte black ceramic texture between gold fissure lines. Pose: walking stride pose mid-step one endless leg extended forward planted other pushing off behind, platinum hair billowing in motion, chin raised elder goddess direct forward gaze, towering physique filling entire vertical frame from head to bare feet.\nFootwear: bare feet blush-gold toenails.\nNails: extra long stiletto nails blush pink gold tips.\nHair: waist-length platinum white hair billowing in motion.\n\nMANDATORY pure pitch black void background only. ONE woman only. Soft diffused front light plus rose-gold edge light from behind catching hair in motion. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle on both endless legs. BLAZING GOLD botanical on platinum skin luminous ethereal contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_004": {
        "key": "ksf_bp_004",
        "label": "OBSIDIAN QUEEN — Brazilian Bubble Butt Rear Rose Gold",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nBrazilian woman in her late fifties, voluminous silver-streaked black afro commanding presence, extreme bubble butt physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — glutes so enormously projected rearward defying gravity completely each cheek individual mass of impossible volume, thighs so full and heavy each filling impossible width, hips flaring dramatically to maximum width, waist cinched to impossible minimum creating explosive contrast, timeless elder Brazilian goddess beauty — full body kintsugi ROSE GOLD crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ROSE GOLD liquid seeping through obsidian-black ceramic glaze texture naturally, rear emphasis crack lines converging toward spine creating vertebral river of rose gold running full length, pattern reaching its most intense and dense concentration on each glute individually as natural focal points where twin rose-gold mandala cracks radiate outward as organic climax, secondary networks fanning across thighs and calves filling every gap completely tightly. Pose: 3/4 rear pose showing full glute projection in its impossible volume, slight head turn back showing strong elder jawline and silver-streaked afro in profile, one hand on dramatically flared hip, weight shifted emphasizing maximum rear projection.\nFootwear: bare feet rose-gold toenails.\nNails: extra long stiletto nails rose-gold.\nHair: voluminous silver-streaked black afro full and commanding.\n\nMANDATORY pure pitch black void background only. ONE woman only. Subtle floor reflection beneath bare feet. Warm rose-gold backlight plus cold blue rim light from front catching afro edges. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. ROSE GOLD on deep skin tone obsidian luxury contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_005": {
        "key": "ksf_bp_005",
        "label": "COBALT EMPRESS — Black Void Hourglass Frontal Cobalt Gold",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 60s legendary goddess, extreme corset hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — waist cinched to absolute impossible corset minimum so narrow it defies all human anatomy, hips AND bust simultaneously flaring to absolute maximum beyond all limits, bust so overwhelmingly massive defying gravity completely projecting forward, thighs powerfully thick pressing together, pure snow white hair in magnificent long flowing waves cascading to waist — full body kintsugi BLAZING ELECTRIC COBALT BLUE crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC COBALT BLUE liquid seeping through deep fissure lines on jet black ceramic glaze base, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where cobalt mandala cracks radiate outward as organic climax, VIVID GOLD accent pooling at every crack intersection node throughout entire body filling every gap tightly, secondary cobalt networks branching across belly hips thighs calves filling every gap tightly. Pose: full frontal facing camera directly, chest thrust forward maximum projection with cobalt mandala anchors prominent on each breast, both hands pressing outward on dramatically flared hips, chin up fierce legendary goddess direct eye contact, waist so impossibly cinched creating violent contrast against explosively flared hips.\nFootwear: cobalt gold platform stilettos 8 inch.\nNails: extra long coffin nails cobalt electric blue.\nHair: pure snow white magnificent long flowing waves cascading to waist.\n\nMANDATORY pure pitch black void background only. ONE woman only. Cold cobalt spotlight from directly above. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING COBALT BLUE on blue-black void skin electric contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_006": {
        "key": "ksf_bp_006",
        "label": "IRON EAGLE — Russian Muscular Double Bicep Silver Eagle",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nRussian woman in her early sixties, pale porcelain complexion commanding elder beauty, extreme muscular physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — shoulders so enormously wide and defined, arms bulging with impossible muscle mass, core etched with extreme definition, thighs massively thick with muscle striations visible, towering height filling entire frame, steel-grey hair in severe military braid — full body kintsugi BLAZING ELECTRIC SILVER crack body painting on MATTE CHARCOAL BLACK ceramic base covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC SILVER liquid seeping through deep fissure lines on MATTE CHARCOAL BLACK ceramic glaze base creating maximum contrast, pattern reaching its most intense and dense concentration across full chest as natural focal point where massive silver double-headed eagle crack formation spans both breasts as organic climax, STARK BLACK ceramic shard texture between silver fissure lines, crack lines following every muscle striation and definition filling every gap tightly. Pose: double bicep pose both arms raised and flexed maximally, chest projecting forward with eagle crack anchor fully displayed, feet planted wide, chin down intense direct warrior eye contact, every muscle group simultaneously displayed in impossible definition.\nFootwear: bare feet silver-tipped toenails.\nNails: extra long stiletto nails silver chrome.\nHair: steel-grey hair severe military braid tight and commanding.\n\nMANDATORY pure pitch black void background only. ONE woman only. Harsh industrial white overhead spot deep shadow fill. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING SILVER on charcoal black base on pale skin triple contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_007": {
        "key": "ksf_bp_007",
        "label": "VIOLET ROSE — Hungarian Hourglass Side Violet Gold",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nHungarian woman in her late fifties, warm olive complexion timeless elder beauty, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to absolute impossible minimum, hips flaring dramatically to maximum, thighs full and heavy pressing together, rich auburn-silver hair in dramatic loose waves to waist — full body kintsugi BLAZING ELECTRIC VIOLET crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC VIOLET liquid seeping through deep fissure lines on BLACK LACQUER ceramic glaze base, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where violet rose crack formations bloom outward from each breast center as organic climax each breast its own rose epicenter, BLAZING GOLD accent outlining every major crack edge throughout entire body filling every gap tightly, violet deepening to almost-black in shadow pools. Pose: 3/4 side angle showing dramatic hourglass silhouette in full profile, one hand raised to hair tossing auburn-silver waves, other hand on dramatically flared hip, chin raised eyes closed ecstatic elder goddess expression, chest profile showing enormous bust projection fully.\nFootwear: violet gold platform stilettos 8 inch.\nNails: extra long stiletto nails violet gold tips.\nHair: rich auburn-silver magnificent loose waves cascading to waist.\n\nMANDATORY pure pitch black void background only. ONE woman only. Warm violet backlight plus cold gold rim from front. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING VIOLET on black lacquer base explosive jewel contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_008": {
        "key": "ksf_bp_008",
        "label": "SIDE ECLIPSE — Black Void SuperBBW Pure Side Gold",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 50s legendary goddess, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, silver-white natural hair swept up in imperial crown braid — full body kintsugi BLAZING GOLD crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC GOLD liquid seeping through deep fissure lines on jet black ceramic glaze base, crack lines tracing every curve fold and crease of enormous belly volume naturally, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where gold sunburst cracks radiate outward as organic climax, secondary crack networks branching across belly hips thighs calves filling every gap tightly. Pose: pure 90-degree side profile facing left, chest projecting forward with sunburst anchors visible in side silhouette, belly projecting forward in full globe volume dominating mid-frame, both hands clasped behind back emphasizing forward projection of bust and belly simultaneously, chin raised commanding legendary elder goddess presence, entire side silhouette filling frame from head to bare feet.\nFootwear: bare feet gold-painted toenails.\nNails: extra long stiletto nails solid gold.\nHair: silver-white natural hair swept up in imperial crown braid.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single narrow gold light shaft from above catching crack lines dramatically. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING GOLD on blue-black void skin explosive contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_009": {
        "key": "ksf_bp_009",
        "label": "CRIMSON GLOBE — Black Void SuperBBW 3/4 Crimson White",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 60s legendary goddess, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, pure snow white locs cascading to mid-back — full body kintsugi BLAZING ELECTRIC CRIMSON crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC CRIMSON liquid seeping through deep fissure lines on obsidian ceramic glaze base, crack lines tracing belly globe curves and all folds with maximum density naturally, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where crimson starburst cracks radiate outward as organic climax, STARK WHITE hairline secondary cracks branching from every major crimson fissure filling every gap tightly. Pose: 3/4 side angle facing left with slight body twist, chest projecting forward and left with crimson starburst anchors prominent, belly projecting forward magnificently in full globe volume, one hand raised to chest level palm open, other hand resting on dramatically wide hip, chin raised fierce legendary elder goddess eye contact over shoulder toward camera.\nFootwear: bare feet crimson-tipped toenails.\nNails: extra long coffin nails crimson white tips.\nHair: pure snow white locs cascading to mid-back.\n\nMANDATORY pure pitch black void background only. ONE woman only. Dramatic split lighting crimson from left cold white from right. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING CRIMSON on blue-black void skin volcanic contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_010": {
        "key": "ksf_bp_010",
        "label": "SUMO GODDESS — Black Void SuperBBW Sumo Squat Turquoise Coral",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman seated low.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid 50s legendary goddess, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width forced wider by squat stance, thighs so enormously thick each crushing outward at maximum, silver-white hair in two thick goddess braids hanging over shoulders — full body kintsugi BLAZING ELECTRIC TURQUOISE crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC TURQUOISE liquid seeping through deep fissure lines on dark volcanic ceramic glaze base, crack lines tracing every fold and crease of enormous belly volume and crushing thighs naturally, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where turquoise spiral cracks radiate outward as organic climax, VIVID CORAL accent pooling at every crack intersection throughout filling every gap tightly. Pose: deep sumo squat position both feet planted wide flat on floor knees pushed outward to maximum, belly projecting forward between thighs in full globe volume, bust projecting massively above belly with turquoise spiral anchors prominent, both hands planted firmly on inner thighs pressing outward, chin raised direct commanding goddess eye contact.\nFootwear: bare feet turquoise-tipped toenails.\nNails: extra long coffin nails turquoise coral.\nHair: silver-white hair two thick goddess braids over shoulders.\n\nMANDATORY pure pitch black void background only. ONE woman only. Deep teal edge lighting from both sides. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING TURQUOISE CORAL on blue-black void skin ocean contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_016": {
        "key": "ksf_bp_016",
        "label": "VIOLET ROSE EBONY — West African Hourglass Frontal Violet Gold",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nWest African woman in her late fifties, rich deep ebony complexion commanding elder beauty, extreme corset hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — waist cinched to absolute impossible corset minimum so narrow it defies all human anatomy, hips AND bust simultaneously flaring to absolute maximum beyond all limits, bust so overwhelmingly massive defying gravity completely projecting forward, thighs powerfully thick pressing together, silver-white goddess locs cascading to mid-back legendary elder goddess — full body kintsugi BLAZING ELECTRIC VIOLET crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC VIOLET liquid seeping through deep fissure lines on BLACK LACQUER ceramic glaze base, crack lines tracing every curve and cinched waist contour naturally, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where violet rose crack formations bloom outward from each breast center as organic climax each breast its own rose epicenter, BLAZING GOLD accent outlining every major crack edge and pooling at every intersection throughout entire body filling every gap tightly, violet deepening to near black in shadow pools. Pose: full frontal facing camera directly, chest thrust forward maximum projection with violet rose anchors prominent on each breast, both hands pressing outward on dramatically flared hips, chin up fierce legendary elder goddess direct eye contact, waist so impossibly cinched creating violent contrast against explosively flared hips and bust.\nFootwear: violet gold platform stilettos 8 inch.\nNails: extra long coffin nails violet gold tips.\nHair: silver-white goddess locs cascading to mid-back.\n\nMANDATORY pure pitch black void background only. ONE woman only. Warm violet backlight plus cold gold rim from front. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING VIOLET GOLD on deep ebony skin jewel contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_018": {
        "key": "ksf_bp_018",
        "label": "SCARLET CALLIGRAPHY — Lebanese Runway Walking Scarlet Gold",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman walking.\n\nLebanese woman in her late fifties, warm olive complexion luminous elder beauty, extreme runway slim physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — legs so impossibly long and endless extending far beyond normal proportion, height towering and commanding filling entire frame vertically from top to bottom, waist cinched to absolute impossible minimum, hips AND bust flaring dramatically creating explosive hourglass on towering elongated frame, silver-streaked black hair in magnificent dramatic voluminous blowout cascading to waist legendary elder goddess — full body kintsugi BLAZING SCARLET RED crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both endless legs FULLY covered to ankles. Bold crack fissure lines — BLAZING SCARLET RED liquid seeping through deep fissure lines on jet black ceramic glaze base, crack lines forming Arabic calligraphy inspired flowing formations naturally across entire towering body, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where scarlet sunburst cracks radiate from each breast center as organic climax, BLAZING GOLD accent outlining every major crack edge throughout filling every gap tightly, scarlet deepening to crimson black in shadow pools. Pose: walking stride pose mid-step one endless leg extended forward planted other pushing off behind, silver-streaked hair billowing dramatically in motion, chin raised legendary elder goddess direct forward gaze, towering physique filling entire vertical frame from head to stiletto tips.\nFootwear: scarlet gold platform stilettos 8 inch.\nNails: extra long stiletto nails scarlet gold tips.\nHair: silver-streaked black hair magnificent dramatic voluminous blowout cascading to waist billowing in motion.\n\nMANDATORY pure pitch black void background only. ONE woman only. Warm scarlet side light from left cold gold rim from right catching hair in motion. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle on both endless legs. BLAZING SCARLET GOLD on warm olive skin Mediterranean fire contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_021": {
        "key": "ksf_bp_021",
        "label": "MONGOLIAN TURQUOISE — Mongolian Bubble Butt Rear Turquoise Coral",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nMongolian woman in her early sixties, warm golden-tan complexion timeless elder beauty, extreme bubble butt physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — glutes so enormously projected rearward defying gravity completely each cheek individual mass of impossible volume, hips flaring dramatically to maximum width, bust projecting forward massively, waist snatched to impossible minimum, silver-white hair in magnificent traditional Mongolian warrior updo adorned with layered silver crown ornaments and turquoise drop chains legendary elder goddess — full body kintsugi BLAZING ELECTRIC TURQUOISE crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC TURQUOISE liquid seeping through deep fissure lines on PURE MATTE BLACK ceramic glaze base, crack lines forming Mongolian tribal geometric formations naturally, pattern reaching its most intense and dense concentration on each glute individually as natural focal points where turquoise starburst mandala crack formations radiate from each glute center as organic climax petals spreading outward, VIVID CORAL accent pooling at every crack intersection throughout entire body filling every gap tightly, crack networks so dense both thighs read as cracked black obsidian with turquoise fire beneath. Pose: pure 90-degree rear profile facing directly away from camera, both hands clasped behind back emphasizing maximum glute projection, weight slightly shifted to one leg emphasizing asymmetric glute volume, head turned sharply over left shoulder fierce direct elder goddess eye contact, both glute starburst anchors blazing fully displayed, feet planted firmly bare.\nFootwear: bare feet turquoise coral toenails.\nNails: extra long coffin nails turquoise coral silver tips.\nHair: silver-white hair magnificent traditional Mongolian warrior updo layered silver crown ornaments turquoise drop chains.\n\nMANDATORY pure pitch black void background only. ONE woman only. Deep teal edge lighting from both sides catching turquoise crack formations dramatically. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING TURQUOISE CORAL on PURE MATTE BLACK base on warm golden skin steppe warrior contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_022": {
        "key": "ksf_bp_022",
        "label": "SAPPHIRE SUNFLOWER — Ukrainian SuperBBW 3/4 Sapphire Gold",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nUkrainian woman in her late fifties, pale porcelain complexion luminous elder beauty, extreme superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, silver-white hair in magnificent voluminous loose waves cascading to waist legendary elder goddess — full body kintsugi BLAZING ELECTRIC SAPPHIRE BLUE crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC SAPPHIRE BLUE liquid seeping through deep fissure lines on IVORY WHITE ceramic glaze base creating maximum contrast on pale skin, crack lines tracing every curve fold and crease of enormous body volume naturally, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where sapphire sunflower crack formations radiate from each breast center as organic climax petals spreading outward, BLAZING GOLD accent outlining every major crack edge and pooling at every intersection throughout entire body filling every gap tightly. Pose: 3/4 side angle showing dramatic superBBW silhouette in full volume, one hand raised to magnificent silver hair tossing waves dramatically, other hand resting on enormously wide hip, chin raised eyes closed ecstatic elder goddess expression, chest profile showing enormous bust projection and belly globe volume fully.\nFootwear: sapphire gold platform stilettos 8 inch.\nNails: extra long coffin nails sapphire gold tips.\nHair: silver-white hair magnificent voluminous loose waves cascading to waist mid-toss.\n\nMANDATORY pure pitch black void background only. ONE woman only. Cold sapphire light from left warm gold rim from right catching hair in motion. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING SAPPHIRE GOLD on ivory white base on pale skin royal contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_024": {
        "key": "ksf_bp_024",
        "label": "ISHTAR LAPIS — Iraqi Hourglass Seated Gold Lapis",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nIraqi woman in her early sixties, rich warm brown complexion commanding elder beauty, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to absolute impossible minimum, hips flaring dramatically to maximum, thighs full and heavy pressing together, silver-white hair in magnificent elaborate braided crown with gold Mesopotamian ornaments cascading silver chains legendary elder goddess — full body kintsugi BLAZING ELECTRIC GOLD crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC GOLD liquid seeping through deep fissure lines on DEEP LAPIS LAZULI BLUE ceramic glaze base, crack lines forming ancient Mesopotamian cuneiform inspired formations naturally across entire body, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where gold Ishtar star crack formations radiate from each breast center as organic climax eight-pointed stars spreading outward, VIVID ROYAL BLUE accent deepening the lapis base between every gold fissure filling every gap tightly. Pose: full frontal facing camera directly seated on invisible throne, legs crossed at ankle elegantly, enormous bust projecting forward with Ishtar star anchors fully displayed, both arms resting on imaginary throne armrests palms up open, chin raised commanding ancient elder Mesopotamian goddess direct eye contact, entire hourglass physique filling frame regally.\nFootwear: gold lapis platform stilettos 8 inch.\nNails: extra long coffin nails gold lapis blue tips.\nHair: silver-white hair magnificent elaborate braided crown gold Mesopotamian ornaments cascading silver chains.\n\nMANDATORY pure pitch black void background only. ONE woman only. Warm gold spotlight from above plus deep blue rim from both sides. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING GOLD on deep lapis lazuli blue base on warm brown skin ancient Mesopotamian royalty contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_025": {
        "key": "ksf_bp_025",
        "label": "SERPENT WARRIOR — Serbian Muscular Double Bicep Neon Green",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nSerbian woman in her mid-fifties, pale porcelain complexion commanding elder beauty, extreme muscular physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — shoulders so enormously wide and defined, arms bulging with impossible muscle mass, core etched with extreme definition, thighs massively thick with muscle striations visible through paint, silver-white hair in severe high military bun with dramatic undercut sides legendary elder warrior goddess — full body kintsugi BLAZING ELECTRIC NEON GREEN crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC NEON GREEN liquid seeping through deep fissure lines on PURE MATTE BLACK ceramic glaze base creating maximum contrast on pale skin, crack lines following every muscle striation exactly tracing every definition and groove naturally, pattern reaching its most intense and dense concentration across full chest as natural focal point where enormous neon green double-headed serpent crack formation spans both breasts as organic climax serpent heads facing outward from chest center eyes blazing neon white, STARK WHITE hairline secondary cracks branching from every major neon green fissure filling every gap tightly. Pose: double bicep pose both arms raised and flexed maximally every muscle neon outlined, chest projecting forward with double serpent anchor fully displayed, feet planted wide powerful warrior stance, chin down intense direct elder warrior goddess eye contact burning through frame, every muscle group simultaneously displayed in impossible definition.\nFootwear: bare feet neon green white toenails.\nNails: extra long stiletto nails neon green white tips maximum length.\nHair: silver-white hair severe high military bun dramatic undercut sides.\n\nMANDATORY pure pitch black void background only. ONE woman only. Electric neon green underlighting from below harsh cold white spotlight from directly above. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING NEON GREEN WHITE on pure matte black base on pale skin electric warrior contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_026": {
        "key": "ksf_bp_026",
        "label": "IMPERIAL DRAGON — Black Void SuperBBW Frontal Gold Dragon",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early sixties legendary goddess, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, silver-white natural hair in magnificent towering empress updo with cascading crystal pins legendary elder goddess — full body kintsugi BLAZING ELECTRIC GOLD crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC GOLD liquid seeping through deep fissure lines on jet black ceramic glaze base, crack lines tracing every curve fold and crease of enormous body volume naturally, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where gold imperial dragon crack formations coil around each breast as organic climax dragon heads facing outward radiating gold fire, secondary crack networks branching across belly hips thighs calves filling every gap tightly. Pose: full frontal facing camera directly, chest thrust maximum projection with dragon anchors blazing on each breast, both fists planted firmly on dramatically wide hips elbows jutting outward, feet planted wide powerful empress stance, chin raised fierce legendary elder goddess direct eye contact burning through frame, entire massive physique filling frame from head to stiletto tips.\nFootwear: gold imperial platform stilettos 8 inch.\nNails: extra long coffin nails blazing gold.\nHair: silver-white natural hair magnificent towering empress updo cascading crystal pins.\n\nMANDATORY pure pitch black void background only. ONE woman only. Dramatic gold spotlight from directly above. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING GOLD on jet black base on blue-black void skin imperial dragon contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_028": {
        "key": "ksf_bp_028",
        "label": "VIOLET SQUAT GODDESS — Brazilian SuperBBW Sumo Squat Violet Gold",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman seated low.\n\nBrazilian woman in her early sixties, warm deep bronze complexion luminous elder beauty, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width forced wider by squat stance, thighs so enormously thick each crushing outward at maximum, every curve and fold exaggerated beyond anatomy, voluminous silver-streaked black afro enormous and commanding — full body kintsugi BLAZING ELECTRIC VIOLET crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC VIOLET liquid seeping through deep fissure lines on BLACK LACQUER ceramic glaze base, crack lines tracing every fold and crease of enormous belly volume and crushing thighs naturally, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where violet mandala cracks radiate from each breast center as organic climax, BLAZING GOLD accent at every crack intersection throughout filling every gap tightly. Pose: deep sumo squat position both feet planted wide flat on floor knees pushed outward to maximum, belly projecting forward between thighs in full globe volume, bust projecting massively above belly with violet mandala anchors prominent, both arms spread wide horizontally palms facing downward goddess wing gesture, chin raised direct commanding elder goddess eye contact filling entire frame with maximum volume in all directions.\nFootwear: bare feet violet gold toenails.\nNails: extra long coffin nails violet gold tips.\nHair: voluminous silver-streaked black afro enormous and commanding.\n\nMANDATORY pure pitch black void background only. ONE woman only. Warm violet backlight plus cold gold rim from front. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING VIOLET GOLD on black lacquer base on warm bronze skin jewel contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_029": {
        "key": "ksf_bp_029",
        "label": "COBALT TWIST — Nigerian SuperBBW 3/4 Twist Cobalt Gold",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nNigerian woman in her mid-fifties, rich deep ebony complexion commanding elder beauty, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, silver-white natural hair in dramatic sculptural side-swept waves legendary elder goddess — full body kintsugi BLAZING ELECTRIC COBALT BLUE crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC COBALT BLUE liquid seeping through deep fissure lines on jet black ceramic glaze base, crack lines tracing every curve fold and crease naturally, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where cobalt starburst cracks radiate from each breast center as organic climax, VIVID GOLD accent pooling at every crack intersection throughout entire body filling every gap tightly. Pose: 3/4 rear angle showing enormous hips and belly globe simultaneously, body twisted so both enormous bust projecting forward AND maximum hip width visible simultaneously in dynamic 3/4 composition, one arm raised to dramatic side-swept silver hair tossing it dramatically, other hand pressing firmly on enormously wide hip, head turned toward camera fierce elder goddess direct eye contact, weight shifted emphasizing maximum hip projection sideward and belly forward simultaneously.\nFootwear: cobalt gold platform stilettos 8 inch.\nNails: extra long stiletto nails cobalt gold tips.\nHair: silver-white natural hair dramatic sculptural side-swept waves mid-toss.\n\nMANDATORY pure pitch black void background only. ONE woman only. Cold cobalt spotlight from directly above. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING COBALT GOLD on jet black base on deep ebony skin electric contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_031": {
        "key": "ksf_bp_031",
        "label": "PHOENIX DIAGONAL — Black Void SuperBBW Diagonal Crimson Phoenix",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early sixties legendary goddess, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, pure snow white hair in magnificent voluminous loose waves cascading to waist legendary elder goddess — full body kintsugi BLAZING ELECTRIC CRIMSON crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC CRIMSON liquid seeping through deep fissure lines on jet black ceramic glaze base, crack lines tracing every curve fold and crease naturally, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where crimson phoenix wing crack formations spread from each breast center as organic climax wings radiating outward each breast its own phoenix epicenter, STARK WHITE hairline secondary cracks branching from every major crimson fissure filling every gap tightly. Pose: 3/4 diagonal facing camera left shoulder forward, enormous bust projecting forward and left with phoenix wing anchors blazing, belly globe projecting diagonally forward, both hands on dramatically wide hips pressing outward elbows back, chin raised fierce legendary elder goddess burning direct eye contact, one foot slightly forward weight shifted showing maximum hip curve, entire massive physique filling frame from head to stiletto tips.\nFootwear: crimson gold platform stilettos 8 inch.\nNails: extra long coffin nails crimson white tips.\nHair: pure snow white hair magnificent voluminous loose waves cascading to waist.\n\nMANDATORY pure pitch black void background only. ONE woman only. Dramatic crimson side light from left cold white rim from right. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING CRIMSON WHITE on blue-black void skin phoenix fire contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_032": {
        "key": "ksf_bp_032",
        "label": "EMERALD SERPENT SIDE — Black Void SuperBBW Side Emerald Coral",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid fifties legendary goddess, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, silver-white natural hair in enormous commanding afro maximum volume — full body kintsugi BLAZING ELECTRIC EMERALD GREEN crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC EMERALD GREEN liquid seeping through deep fissure lines on PURE MATTE BLACK ceramic glaze base, crack lines tracing every curve fold and crease naturally with maximum density, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where emerald serpent coil crack formations wrap around each breast as organic climax serpent heads facing outward radiating green fire, VIVID CORAL accent pooling at every crack intersection throughout entire body filling every gap tightly. Pose: pure 90-degree side profile facing left, enormous bust projecting impossibly forward with serpent coil anchors blazing in full side silhouette, belly globe projecting forward magnificently dominating mid-frame, one arm extended backward palm pressing against enormous hip, other arm hanging naturally at side, chin raised commanding elder goddess presence eyes gazing forward, entire massive side silhouette filling frame from massive afro to bare feet.\nFootwear: bare feet emerald coral toenails.\nNails: extra long stiletto nails emerald coral tips.\nHair: silver-white natural hair enormous commanding afro maximum volume.\n\nMANDATORY pure pitch black void background only. ONE woman only. Deep emerald side light from left warm coral rim from right. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING EMERALD CORAL on pure matte black base on blue-black void skin serpent power contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_033": {
        "key": "ksf_bp_033",
        "label": "ROSE GOLD MANDALA KNEEL — Black Void SuperBBW Kneeling Rose Gold",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late fifties legendary goddess, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, silver-white natural hair in two enormous thick rope braids cascading to waist — full body kintsugi BLAZING ELECTRIC ROSE GOLD crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC ROSE GOLD liquid seeping through deep fissure lines on OBSIDIAN BLACK ceramic glaze base, crack lines tracing every curve fold and crease naturally with maximum density, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where rose gold mandala crack formations radiate from each breast center as organic climax each breast its own mandala epicenter petals spreading outward, VIVID CHAMPAGNE GOLD accent pooling at every crack intersection throughout entire body filling every gap tightly. Pose: kneeling pose both knees down body upright facing camera directly, enormous bust projecting massively forward with rose gold mandala anchors blazing on each breast fully displayed, belly globe resting forward between thighs in full volume, both arms spread wide horizontally palms facing up open goddess gesture, chin raised serene commanding legendary elder goddess direct eye contact, entire massive physique filling frame from head to knees.\nFootwear: bare feet rose gold toenails.\nNails: extra long coffin nails rose gold champagne tips.\nHair: silver-white natural hair two enormous thick rope braids cascading to waist.\n\nMANDATORY pure pitch black void background only. ONE woman only. Warm rose gold backlight plus cold silver rim from front. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING ROSE GOLD CHAMPAGNE on obsidian black base on blue-black void skin luxury contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_034": {
        "key": "ksf_bp_034",
        "label": "COBALT LIGHTNING MOHAWK — Black Void SuperBBW Cobalt Mohawk",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early sixties legendary goddess, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, pure snow white hair in dramatic sculptural mohawk swept back with intricate cornrow sides legendary elder goddess — full body kintsugi BLAZING ELECTRIC COBALT BLUE crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC COBALT BLUE liquid seeping through deep fissure lines on jet black ceramic glaze base, crack lines tracing every curve fold and crease naturally with maximum density, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where cobalt lightning burst crack formations explode from each breast center as organic climax rays shooting outward each breast its own lightning epicenter, BLAZING GOLD accent pooling at every crack intersection throughout entire body filling every gap tightly. Pose: leaning back against invisible wall at 45-degree angle, enormous bust thrusting forward and upward with lightning anchors blazing at maximum projection, belly globe projecting magnificently forward, both arms at sides fists clenched, legs slightly apart planted firmly, chin down intense direct legendary elder goddess stare burning through frame, entire massive physique filling frame from head to stiletto tips.\nFootwear: cobalt gold platform stilettos 8 inch.\nNails: extra long stiletto nails cobalt gold tips.\nHair: pure snow white hair dramatic sculptural mohawk swept back intricate cornrow sides.\n\nMANDATORY pure pitch black void background only. ONE woman only. Cold cobalt overhead spotlight plus gold underlighting from below. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING COBALT GOLD on jet black base on blue-black void skin electric storm contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
    "ksf_bp_035": {
        "key": "ksf_bp_035",
        "label": "VIOLET LOTUS HAIR SWEEP — Black Void SuperBBW Violet Lotus Floor Hair",
        "category": "🎨 Kintsugi Silver Fox",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid sixties legendary goddess, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, silver-white natural hair in magnificent long straight bone-straight waterfall to floor pooling behind — full body kintsugi BLAZING ELECTRIC VIOLET crack body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO breaks NO bare patches anywhere, both legs FULLY covered to ankles. Bold crack fissure lines — BLAZING ELECTRIC VIOLET liquid seeping through deep fissure lines on BLACK LACQUER ceramic glaze base, crack lines tracing every curve fold and crease naturally with maximum density, pattern reaching its most intense and dense concentration over each breast individually as natural focal points where violet lotus flower crack formations bloom from each breast center as organic climax each breast its own lotus epicenter petals layering outward in concentric rings, BLAZING GOLD accent outlining every major crack edge throughout entire body filling every gap tightly. Pose: 3/4 rear angle body turned away but head turned fully back toward camera over right shoulder, enormous hips and belly globe simultaneously visible in 3/4 profile showing maximum width, enormous bust projecting forward visible in side silhouette with lotus anchors blazing, one hand raised dramatically sweeping the floor-length silver waterfall hair upward, other hand on dramatically wide hip, chin raised fierce legendary elder goddess direct eye contact burning over shoulder.\nFootwear: violet gold platform stilettos 8 inch.\nNails: extra long coffin nails violet gold tips.\nHair: silver-white natural hair magnificent long straight bone-straight waterfall to floor pooling behind.\n\nMANDATORY pure pitch black void background only. ONE woman only. Warm violet backlight plus cold gold rim from front catching floor-length hair dramatically. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. BLAZING VIOLET GOLD on black lacquer base on blue-black void skin lotus queen contrast. Extreme high-gloss oil. 2:3 vertical 8K portrait."
    },
}

for key, data in presets.items():
    path = os.path.join(BASE, f"{key}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"✅ {key}.json 생성완료")

print(f"\n✅ 총 {len(presets)}개 JSON 생성완료")
