# -*- coding: utf-8 -*-
import json, os

BASE = r"C:\Dev\LumineX\presets"
os.makedirs(BASE, exist_ok=True)

presets = {
"cb_001": {
    "key": "cb_001",
    "label": "BIOMECH COBALT",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 50s legendary goddess, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, silver-white natural hair in imperial crown braid — full body biomechanical body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO bare patches anywhere, both legs FULLY covered to ankles.\n\nBIOMECH SYSTEM: H.R. Giger-inspired organic machine fusion — exposed chrome pistons and hydraulic cylinders painted at hip joints and knee joints, ribbed metallic tubing coiling across belly volume like serpentine power conduits, circuit board micro-detail etched across chest with each breast individually featuring a glowing reactor core radiating outward as organic focal climax, vertebral spine replaced by visible chrome servo column running full back length, shoulder joints exposed as ball-and-socket chrome machinery, entire surface rendered in cold steel grey with electric COBALT BLUE glowing accents at every mechanical joint and circuit node, skin-to-machine transition zones densely detailed where organic flesh merges seamlessly into cold metal surface.\n\nPose: powerful frontal stance, legs shoulder-width apart, both arms slightly raised showing forearm mechanical plating, chin raised commanding cyborg goddess presence, chest reactor cores facing forward as primary focal points.\nFootwear: chrome platform boots knee-high.\nNails: extra long stiletto nails chrome cobalt.\nHair: silver-white natural hair imperial crown braid.\n\nMANDATORY pure pitch black void background only. ONE woman only. Cold industrial blue light from above, electric cobalt rim light from sides catching chrome surface details. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. CHROME COBALT on blue-black void skin cold machine contrast. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_002": {
    "key": "cb_002",
    "label": "STEAMPUNK GOLD",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nNigerian woman in her late 50s, THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, belly projecting forward in full magnificent globe volume, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, silver-white afro commanding elder goddess presence — full body biomechanical body painting covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION, pattern so densely packed it reads as second skin, NO gaps NO bare patches anywhere, both legs FULLY covered to ankles.\n\nBIOMECH SYSTEM: organic-machine fusion in BLAZING GOLD and COPPER tones — exposed brass gear mechanisms painted at every major joint, golden chain-link conduits running from shoulders across enormous bust volume with each breast individually featuring a massive golden gear formation as primary focal climax teeth radiating outward, copper pipe ribbing wrapping belly globe in industrial corset structure, riveted bronze plating overlapping across hips and thighs like ancient mechanical armor, spine rendered as visible golden rack-and-pinion column, skin surface transitioning from organic flesh to burnished copper sheet metal in seamlessly detailed zones, warm amber glow emanating from every joint gap and gear tooth gap as internal power source.\n\nPose: pure 90-degree side profile facing left, chest projecting forward with golden gear anchors visible in side silhouette, belly globe projecting forward dominating mid-frame, one hand raised showing forearm copper plating, chin raised commanding mechanical goddess presence.\nFootwear: bare feet gold-copper toenails.\nNails: extra long stiletto nails gold copper tips.\nHair: silver-white afro full commanding elder presence.\n\nMANDATORY pure pitch black void background only. ONE woman only. Warm amber light from above catching copper and gold surface, cold blue rim from right creating metal sheen contrast. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. GOLD COPPER BRASS on blue-black void skin industrial luxury contrast. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_003": {
    "key": "cb_003",
    "label": "BIOMECH CRIMSON EMPRESS",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 40s commanding goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs so enormously thick each leg fills impossible width, silver-white natural hair in severe imperial updo — Body fully painted with H.R. Giger-inspired organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: deep obsidian black organic base with BLAZING ELECTRIC CRIMSON mechanical network — exposed hydraulic pistons at hip joints and knee joints painted crimson-chrome, ribbed crimson tubing coiling across waist like power conduits, each breast individually featuring a BLAZING CRIMSON reactor core burst as primary focal climax with mechanical tendrils radiating outward in all directions, vertebral spine replaced by visible crimson servo column running full back length, shoulder joints rendered as exposed ball-and-socket crimson machinery, forearms plated with crimson-chrome segmented armor panels, thighs featuring hydraulic shock absorber columns, entire surface dense with micro-etched circuit detail in crimson on obsidian, skin-to-machine transition zones where organic flesh merges into crimson metal seamlessly.\n\nPose: powerful frontal stance legs slightly apart, both arms raised at sides showing forearm crimson plating, chin raised eyes closed commanding cyborg empress presence, chest reactor cores facing forward as primary focal points.\nFootwear: crimson chrome platform boots knee-high.\nNails: extra long stiletto nails chrome crimson.\nHair: silver-white natural hair severe imperial updo.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Cold industrial blue light from above, BLAZING ELECTRIC CRIMSON rim light from sides catching chrome plating, reactor core burst points glowing crimson. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_004": {
    "key": "cb_004",
    "label": "BIOMECH GOLD WARRIOR",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nBrazilian woman in her early 40s, rich warm bronze complexion commanding beauty, muscular athletic physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — shoulders impossibly broad and powerful, arms so densely muscled, each breast massive sitting high on sculpted chest, glutes powerfully rounded, thighs and calves so heavily muscled filling impossible width, long vivid gold-highlighted black hair in fierce warrior braids cascading to mid-back — Body fully painted with organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: warm bronze organic base with BLAZING 24K GOLD mechanical network — exposed brass gear mechanisms at every major joint, golden chain-link power conduits running from shoulders across chest, each breast individually featuring a massive BLAZING GOLD gear formation as primary focal climax with gear teeth radiating outward as organic climax, copper pipe ribbing wrapping torso in industrial corset structure, riveted bronze plating overlapping across hips and thighs like ancient mechanical armor, spine rendered as visible golden rack-and-pinion column running full length, forearms plated with segmented gold-bronze armor, thighs featuring interlocking bronze plate segments, warm amber glow emanating from every joint gap and gear tooth gap as internal power source, organic flesh merging into gold metal in seamlessly detailed transition zones.\n\nPose: powerful double bicep pose 3/4 angle, both arms raised showing extreme muscular definition and forearm bronze plating, chin raised fierce warrior goddess expression, gold gear chest anchors visible as primary focal points.\nFootwear: gold platform combat boots ankle-high.\nNails: extra long coffin nails brushed gold.\nHair: long vivid gold-highlighted black hair fierce warrior braids to mid-back.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Warm amber light from above catching brass and gold surface, cold blue rim from sides creating metal contrast, gear burst focal points glowing warm gold. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_005": {
    "key": "cb_005",
    "label": "BIOMECH EMERALD QUEEN",
    "category": "🦾 Cyborg/Biomech",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nIndian woman in her late 30s, warm golden-olive complexion commanding beauty, extreme superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, NO pregnancy — pure fat superBBW body composition only, voluminous jet black hair with emerald green tips in enormous loose waves to waist — Body fully painted with organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: deep obsidian black organic base with BLAZING ELECTRIC EMERALD GREEN mechanical network — exposed chrome pistons at hip joints glowing emerald, ribbed emerald tubing coiling across enormous body volume like serpentine power conduits following every curve, each breast individually featuring a BLAZING EMERALD reactor core burst as primary focal climax with mechanical circuit patterns radiating outward, vertebral spine replaced by emerald servo column, shoulder joints rendered as emerald ball-and-socket machinery, forearms plated with emerald-chrome segmented panels, thighs featuring hydraulic columns following enormous volume, micro-etched circuit detail in emerald on obsidian covering every surface, skin-to-machine transition zones seamlessly detailed across all curves and folds.\n\nPose: pure 90-degree side profile facing left, bust projecting forward in full massive volume dominating upper frame, hips and thighs filling impossible width in side silhouette, one arm raised showing forearm emerald plating, chin raised commanding cyborg queen presence.\nFootwear: emerald chrome platform stilettos 8 inch.\nNails: extra long stiletto nails emerald chrome.\nHair: voluminous jet black hair with emerald green tips enormous loose waves to waist.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Cold industrial blue from above, BLAZING ELECTRIC EMERALD rim light catching chrome plating, reactor core glowing emerald. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_006": {
    "key": "cb_006",
    "label": "BIOMECH VIOLET GODDESS",
    "category": "🦾 Cyborg/Biomech",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nCongolese woman in her late 30s, THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, extreme superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, NO pregnancy — pure fat superBBW body composition only, voluminous silver-white natural afro enormous and commanding — Body fully painted with H.R. Giger-inspired organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: deep obsidian black organic base with BLAZING ELECTRIC VIOLET mechanical network — exposed hydraulic pistons at hip joints and knee joints painted violet-chrome, ribbed violet tubing coiling across enormous body volume like power conduits following every curve, each breast individually featuring a BLAZING VIOLET reactor core burst as primary focal climax with mechanical circuit tendrils radiating outward, vertebral spine replaced by violet servo column, shoulder joints as violet ball-and-socket machinery, forearms plated with violet-chrome segmented armor following enormous arm volume, thighs featuring hydraulic shock absorber columns tracing enormous volume, entire surface dense with micro-etched violet circuit detail on obsidian, violet green glow emanating from every joint and circuit node.\n\nPose: pure 90-degree side profile facing left, bust projecting forward in full massive volume, hips and thighs filling impossible width in side silhouette, one arm raised showing forearm violet plating, chin raised commanding goddess presence.\nFootwear: violet chrome platform stilettos 8 inch.\nNails: extra long coffin nails chrome violet.\nHair: voluminous silver-white natural afro enormous and commanding.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Cold industrial blue from above, BLAZING ELECTRIC VIOLET rim light catching chrome plating, reactor cores glowing violet. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_007": {
    "key": "cb_007",
    "label": "BIOMECH ROSE GOLD QUEEN",
    "category": "🦾 Cyborg/Biomech",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nLebanese woman in her early 40s, warm honey complexion commanding beauty, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs so enormously thick each leg fills impossible width, long sleek jet black hair with rose gold highlights cascading in loose waves to waist — Body fully painted with organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: warm ivory organic base with BLAZING ROSE GOLD mechanical network — exposed rose gold gear mechanisms at every major joint, rose gold chain-link power conduits running from shoulders across chest, each breast individually featuring a massive BLAZING ROSE GOLD gear formation as primary focal climax with delicate gear teeth and rose petal hybrid formations radiating outward, ribbed rose gold tubing wrapping waist in elegant mechanical corset structure, riveted rose gold plating overlapping across hips and thighs like ornate mechanical armor, spine rendered as rose gold rack-and-pinion column, forearms plated with segmented rose gold panels, warm rose-amber glow emanating from every joint gap as internal power source, organic flesh merging into rose gold metal in seamlessly detailed transition zones.\n\nPose: elegant walking stride 3/4 angle, one leg crossing in front of other, arms in natural confident swing showing forearm rose gold plating, chin raised commanding beauty.\nFootwear: rose gold platform stilettos 8 inch.\nNails: extra long stiletto nails rose gold chrome.\nHair: long sleek jet black hair with rose gold highlights loose waves to waist.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Warm rose gold light from above catching gear surfaces, cold blue rim from sides creating metal contrast, gear burst focal points glowing warm rose-gold. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_008": {
    "key": "cb_008",
    "label": "BIOMECH ARCTIC WARRIOR",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nRussian woman in her late 30s, pale ice complexion commanding nordic beauty, muscular athletic physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — shoulders impossibly broad and powerful, arms so densely muscled, each breast massive sitting high on sculpted chest, glutes powerfully rounded, thighs and calves so heavily muscled filling impossible width, platinum blonde hair in severe military braid — Body fully painted with organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: pale arctic white organic base with BLAZING ELECTRIC ICE BLUE mechanical network — exposed chrome pistons at every joint glowing ice blue, ribbed ice blue crystalline tubing coiling across chest like frozen power conduits, each breast individually featuring a BLAZING ICE BLUE reactor core burst as primary focal climax with crystalline mechanical arms radiating outward like frozen circuit snowflakes, vertebral spine replaced by visible ice blue cryo-column running full back length, shoulder joints rendered as exposed chrome ball-and-socket cryo-machinery, forearms plated with ice blue crystalline armor panels, thighs featuring cryo-hydraulic columns, entire surface dense with ice blue micro-circuit frost patterns on arctic white base, skin-to-machine transition zones where pale flesh merges into ice-chrome machinery seamlessly.\n\nPose: powerful rear-facing double bicep pose, head turned sharply over shoulder showing fierce expression and severe military braid, both arms raised showing extreme muscular definition and forearm ice blue plating, cryo-column spine visible as primary rear focal point.\nFootwear: ice blue chrome platform boots knee-high.\nNails: extra long stiletto nails ice blue chrome.\nHair: platinum blonde severe military braid.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Cold arctic blue light from above catching ice chrome surface, white cryo rim from sides, reactor core burst points glowing ice blue. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_009": {
    "key": "cb_009",
    "label": "BIOMECH COPPER AMAZON",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nWest African woman in her mid 30s, THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, muscular athletic physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — shoulders impossibly broad and powerful, arms so densely muscled, each breast massive sitting high on sculpted chest, glutes powerfully rounded, thighs and calves so heavily muscled filling impossible width, head shaved clean commanding warrior goddess — Body fully painted with organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH base with BLAZING ELECTRIC COPPER mechanical network — exposed copper pistons at every joint gleaming warm amber, dense copper chain-link conduits running across broad shoulders and chest, each breast individually featuring a BLAZING COPPER gear burst as primary focal climax with brass cog teeth radiating outward, ribbed copper tubing wrapping torso like ancient warrior harness, riveted copper plate armor overlapping across hips and thighs following muscular volume, spine rendered as copper vertebral column with exposed amber glow joints, forearms plated with dense copper segmented battle armor, thighs featuring hydraulic copper columns following extreme muscular definition, warm amber-copper glow emanating from every joint and gear gap, entire surface micro-etched with ancient tribal-meets-machine circuit patterns in copper on void black.\n\nPose: powerful kneeling pose on one knee, back straight, both arms raised in dramatic V showing extreme bicep peaks and forearm copper plating, chin raised fierce shaved-head warrior goddess expression.\nFootwear: copper platform combat boots ankle-high.\nNails: extra long stiletto nails brushed copper.\nHair: head shaved clean.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Warm amber-copper light from above catching all metal surfaces, cold blue rim from sides creating dark contrast, gear burst and joint glow points blazing copper. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_010": {
    "key": "cb_010",
    "label": "BIOMECH SILVER RUNWAY",
    "category": "🦾 Cyborg/Biomech",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nEthiopian woman in her late 20s, warm deep mahogany complexion commanding beauty, runway slim physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — impossibly elongated legs filling impossible length, shoulders perfectly squared, each breast beautifully full projecting forward, waist cinched to impossible minimum, hips flaring to maximum width for runway silhouette, long sleek silver-white hair in dramatic center-part cascading straight to hips — Body fully painted with H.R. Giger-inspired organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: deep warm mahogany organic base with BLAZING MIRROR CHROME SILVER mechanical network — ultra-reflective chrome pistons at every joint creating mirror surface, delicate chrome wire-frame conduits tracing elongated body lines from shoulders to ankles, each breast individually featuring a chrome mirror lens flare burst as primary focal climax with ultra-fine mechanical tendrils radiating outward, spine rendered as chrome vertebral column visible from front as sternum plate, forearms plated with ultra-thin chrome segmented panels, impossibly long legs featuring delicate chrome circuit line work following every muscle, chrome surface so reflective it mirrors surrounding darkness creating infinite depth, entire surface covered with ultra-fine chrome micro-circuit etching on mahogany base.\n\nPose: elegant runway walking stride, one leg crossing in front of other creating maximum silhouette length, arms in natural confident swing showing forearm chrome plating, chin raised eyes forward commanding runway cyborg goddess presence.\nFootwear: mirror chrome platform stilettos 10 inch.\nNails: extra long coffin nails mirror chrome.\nHair: long sleek silver-white hair dramatic center-part cascading straight to hips.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Cold silver spotlight from above catching chrome mirror surfaces, blue rim from sides, chrome surfaces reflecting void darkness. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss mirror finish. 2:3 vertical 8K portrait."
},
"cb_011": {
    "key": "cb_011",
    "label": "BIOMECH OBSIDIAN EMPRESS",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nIraqi woman in her early 40s, deep olive complexion commanding beauty, extreme bubble butt physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — glutes so enormously projected rearward defying gravity completely each cheek individual mass of impossible volume, thighs so full and heavy filling impossible width, hips flaring dramatically to maximum width, waist cinched to impossible minimum, long voluminous jet black hair with electric white highlights in enormous loose curls cascading to waist — Body fully painted with H.R. Giger-inspired organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: deep obsidian black organic base with BLAZING ELECTRIC WHITE SILVER mechanical network — exposed white chrome pistons at hip joints and knee joints, dense white circuit network covering entire surface like living lightning frozen in obsidian, each breast individually featuring a BLAZING WHITE reactor core burst as primary focal climax with electric circuit tendrils radiating outward, glutes individually featuring twin white mechanical mandala formations as primary rear focal climax with circuit patterns radiating across full volume, spine rendered as white vertebral servo column visible from rear, shoulder joints as white chrome ball-and-socket machinery, forearms plated with obsidian-white segmented armor, thighs featuring white hydraulic columns following enormous bubble butt volume, pure white electric glow emanating from every circuit node and joint gap on obsidian surface.\n\nPose: 3/4 rear angle showing full glute projection in impossible volume, head turned sharply over shoulder with commanding expression, one hand on dramatically flared hip, electric white highlights in loose curls catching light dramatically.\nFootwear: obsidian black platform stilettos 8 inch with white chrome sole.\nNails: extra long almond nails obsidian black with silver tips.\nHair: long voluminous jet black hair with electric white highlights enormous loose curls to waist.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Zero ambient light merging obsidian base with background, cold electric white spotlight catching circuit network, glute mandala and reactor cores blazing white. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_012": {
    "key": "cb_012",
    "label": "BIOMECH SOLAR TITAN",
    "category": "🦾 Cyborg/Biomech",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nUgandan woman in her mid 30s, THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, extreme superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, NO pregnancy — pure fat superBBW body composition only, voluminous natural 4C afro with gold tips enormous and commanding — Body fully painted with H.R. Giger-inspired organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH base with BLAZING ELECTRIC SOLAR GOLD mechanical network — exposed solar gold pistons at every joint radiating warm amber light, dense solar corona chain-link conduits running across enormous bust, each breast individually featuring a BLAZING SOLAR CORONA reactor burst as primary focal climax with plasma loop tendrils radiating outward, vertebral spine replaced by gold solar column with plasma glow joints, shoulder joints as gold solar ball-and-socket machinery, forearms plated with solar gold segmented armor following enormous volume, thighs featuring solar hydraulic columns, entire surface dense with solar circuit micro-etching in blazing gold on void black, warm plasma glow at every joint and gear intersection.\n\nPose: 3/4 rear angle showing full superBBW glute and hip projection in impossible volume, head turned back showing strong jawline and gold-tipped afro, one hand on dramatically wide hip, weight shifted showing maximum hip and thigh volume.\nFootwear: solar gold platform stilettos 8 inch.\nNails: extra long stiletto nails blazing gold.\nHair: voluminous natural 4C afro with gold tips enormous and commanding.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Blazing solar gold light from above catching all metal surfaces, cold blue rim from sides creating void contrast, solar corona burst points glowing blazing gold. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_013": {
    "key": "cb_013",
    "label": "BIOMECH NEON PINK GODDESS",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nColombian woman in her late 20s, warm honey-olive complexion radiant youth, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs so enormously thick each leg fills impossible width, long vivid hot pink hair with black roots in high dramatic ponytail to waist — Body fully painted with H.R. Giger-inspired organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: deep obsidian black organic base with BLAZING ELECTRIC HOT PINK mechanical network — exposed hot pink chrome pistons at hip joints and knee joints, dense neon pink circuit board patterns covering entire surface, each breast individually featuring a BLAZING HOT PINK reactor core burst as primary focal climax with neon circuit tendrils radiating outward, ribbed neon pink tubing coiling across waist as mechanical corset, riveted pink chrome plating overlapping across hips creating mechanical armor, vertebral spine replaced by neon pink servo column, forearms plated with hot pink segmented panels, thighs featuring neon pink hydraulic columns, entire surface dense with neon pink micro-circuit etching on obsidian, hot pink glow emanating from every joint and circuit node creating UV effect.\n\nPose: powerful frontal stance, both hands on dramatically wide hips showing full hourglass silhouette, chin raised commanding young goddess expression, chest reactor cores facing forward as primary focal points, hot pink ponytail cascading dramatically over one shoulder.\nFootwear: neon pink platform stilettos 8 inch.\nNails: extra long coffin nails neon pink chrome.\nHair: long vivid hot pink hair with black roots high dramatic ponytail to waist.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. UV blacklight from above making neon pink circuit network blaze, cold blue rim from sides, reactor core burst points glowing hot pink. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_014": {
    "key": "cb_014",
    "label": "BIOMECH BRONZE AMAZON",
    "category": "🦾 Cyborg/Biomech",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nKenyan woman in her early 40s, rich warm ebony complexion commanding beauty, muscular athletic physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — shoulders impossibly broad and powerful, arms so densely muscled, each breast massive sitting high on sculpted chest, glutes powerfully rounded, thighs and calves so heavily muscled filling impossible width, long goddess locs with bronze tips cascading to mid-back — Body fully painted with organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: rich warm ebony organic base with BLAZING ANTIQUE BRONZE mechanical network — exposed antique bronze pistons at every joint with aged patina texture, dense bronze chain armor conduits running across broad powerful shoulders, each breast individually featuring a massive BLAZING BRONZE gear formation as primary focal climax with aged cog teeth and verdigris accent radiating outward, ancient carved bronze plating overlapping across torso in layered armor structure, riveted bronze battle plates across hips and thighs following muscular volume, spine rendered as bronze vertebral battle column, forearms plated with dense ancient bronze battle armor, thighs featuring bronze hydraulic war columns, warm copper-amber-green patina glow emanating from every joint and gear gap, entire surface micro-etched with ancient African warrior symbols meets machine circuit in antique bronze on ebony.\n\nPose: powerful walking stride 3/4 angle, one leg forward, arms in natural commanding swing showing forearm bronze battle armor, chin raised fierce warrior goddess expression, bronze-tipped locs cascading dramatically.\nFootwear: antique bronze platform combat boots ankle-high.\nNails: extra long stiletto nails antique bronze.\nHair: long goddess locs with bronze tips cascading to mid-back.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Warm amber-bronze light from above catching patina surfaces, cold blue rim from sides, gear burst focal points glowing warm bronze-green. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_015": {
    "key": "cb_015",
    "label": "BIOMECH PEARL EMPRESS",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nJapanese woman in her late 40s, cool porcelain complexion commanding beauty, extreme bubble butt physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — glutes so enormously projected rearward defying gravity completely each cheek individual mass of impossible volume, thighs so full and heavy filling impossible width, hips flaring dramatically to maximum width, waist cinched to impossible minimum, voluminous jet black hair with pearl white highlights in enormous elegant updo — Body fully painted with organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: cool porcelain ivory organic base with BLAZING IRIDESCENT PEARL mechanical network — exposed pearl-chrome pistons at every joint shifting between white pink and gold in light, delicate pearl gear mechanisms at every joint with mother-of-pearl iridescent surface, each breast individually featuring a BLAZING PEARL reactor core burst as primary focal climax with iridescent mechanical tendrils radiating outward like pearl nautilus arms, glutes individually featuring twin pearl mandala mechanical formations as primary rear focal climax with iridescent circuit patterns radiating across full volume, spine rendered as pearl servo column visible from rear, forearms plated with iridescent pearl segmented panels, thighs featuring pearl hydraulic columns following enormous bubble butt volume, entire surface dense with pearl iridescent micro-circuit patterns on ivory base shifting color with light angle.\n\nPose: 3/4 rear angle showing full glute projection in impossible volume, head turned elegantly over shoulder with serene commanding expression, one hand raised to elaborate pearl updo, weight shifted maximizing impossible rear projection.\nFootwear: pearl white platform stilettos 8 inch.\nNails: extra long almond nails pearl white chrome.\nHair: voluminous jet black hair with pearl white highlights enormous elegant updo.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Soft iridescent white light from above catching pearl surfaces, cold blue rim from sides, pearl reactor cores and glute mandalas glowing iridescent. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss iridescent finish. 2:3 vertical 8K portrait."
},
"cb_016": {
    "key": "cb_016",
    "label": "BIOMECH JADE TITAN",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTanzanian woman in her mid 30s, THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, extreme superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward each breast an enormous independent globe of impossible weight and volume, hips expanding to absolute maximum width filling the entire frame, thighs so enormously thick each leg fills impossible width pressing together under their own massive weight, body rolls and folds layered and exaggerated beyond anatomy, NO pregnancy — pure fat superBBW body composition only, voluminous silver-white natural afro with jade green tips enormous and commanding — Body fully painted with H.R. Giger-inspired organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH base with BLAZING ELECTRIC JADE GREEN mechanical network — exposed jade chrome pistons at every joint following enormous body volume, dense jade circuit board patterns covering entire surface tracing every roll fold and curve, each breast individually featuring a BLAZING JADE reactor core burst as primary focal climax with mechanical tendrils radiating outward, vertebral spine replaced by jade servo column, shoulder joints as jade ball-and-socket machinery, forearms plated with jade chrome segmented armor following enormous arm volume, thighs and hips featuring jade hydraulic columns tracing impossible volume, entire surface dense with jade micro-circuit etching on void black, jade green glow emanating from every joint and circuit node.\n\nPose: 3/4 rear angle, both hands on dramatically wide hips, head turned back showing strong jawline and jade-tipped afro, weight shifted showing maximum hip and thigh volume from rear.\nFootwear: jade chrome platform stilettos 8 inch.\nNails: extra long coffin nails jade chrome.\nHair: voluminous silver-white natural afro with jade green tips enormous and commanding.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Cold jade green light from above, blue rim from sides, jade reactor cores glowing blazing jade. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_017": {
    "key": "cb_017",
    "label": "BIOMECH RUBY EMPRESS",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nNigerian woman in her early 40s, THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, extreme superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward each breast an enormous independent globe of impossible weight, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width pressing together under their own massive weight, body rolls and folds layered across entire torso exaggerated beyond anatomy, NO pregnancy — pure fat superBBW body composition only, long silver-white locs with ruby red tips cascading to waist — Body fully painted with H.R. Giger-inspired organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere — MAXIMUM DENSITY biomech coverage leaving ZERO exposed skin:\n\nBIOMECH SYSTEM: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH base with BLAZING ELECTRIC RUBY RED mechanical network — exposed ruby chrome pistons at EVERY joint following enormous body volume, ULTRA-DENSE ruby circuit board patterns covering EVERY inch of surface with NO gaps NO breaks NO exposed skin areas, every body roll and fold covered in dense ruby circuit micro-etching, each breast individually featuring a BLAZING RUBY reactor core burst as primary focal climax with blood-red mechanical tendrils radiating outward filling every inch of breast surface, vertebral spine replaced by ruby servo column with red glow joints, shoulder joints as ruby ball-and-socket machinery, forearms plated with DENSE ruby chrome segmented armor following enormous arm volume, thighs featuring DENSE ruby hydraulic columns and circuit plating covering every inch, entire surface saturated with ruby micro-circuit etching on void black — circuit density so high it reads as solid ruby on black, deep ruby-red glow at EVERY joint node and circuit intersection.\n\nPose: pure 90-degree side profile facing left, bust projecting forward in full massive volume each breast enormous independent globe, hips and thighs filling impossible width in full side silhouette, one arm raised elegantly showing dense ruby arm plating, chin raised commanding superBBW goddess presence.\nFootwear: ruby chrome platform stilettos 8 inch.\nNails: extra long stiletto nails ruby chrome.\nHair: long silver-white locs with ruby red tips cascading to waist.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Blazing ruby-red light from above, cold blue rim from sides, ruby reactor cores glowing blazing red. Pattern density ABSOLUTE MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_018": {
    "key": "cb_018",
    "label": "BIOMECH TEAL QUEEN",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nGhanaian woman in her late 30s, THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, extreme superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward each breast an enormous independent globe of impossible weight and volume, hips expanding to absolute maximum width filling entire frame, thighs so enormously thick each leg fills impossible width, body rolls and folds layered and exaggerated beyond anatomy across entire torso, NO pregnancy — pure fat superBBW body composition only, massive crown braid updo with teal chrome threads interwoven commanding empress presence — Body fully painted with H.R. Giger-inspired organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH base with BLAZING ELECTRIC TEAL mechanical network — exposed teal chrome pistons at every joint following enormous body volume and rolls, dense teal circuit board patterns covering entire surface tracing every roll fold and curve, each breast individually featuring a BLAZING TEAL reactor core burst as primary focal climax with electric teal mechanical tendrils radiating outward, vertebral spine replaced by teal servo column, shoulder joints as teal chrome ball-and-socket machinery, forearms plated with teal chrome segmented armor following enormous arm volume, thighs and hips featuring teal hydraulic columns tracing impossible volume, entire surface dense with teal micro-circuit etching on void black, blazing electric teal glow at every joint and circuit node.\n\nPose: frontal facing camera, both arms slightly raised to sides showing full superBBW silhouette — enormous bust projecting forward, massive hips filling frame, thighs pressing together under their own weight, chin raised commanding empress goddess presence, teal crown updo as mechanical crown.\nFootwear: teal chrome platform stilettos 8 inch.\nNails: extra long coffin nails teal chrome.\nHair: massive crown braid updo with teal chrome threads interwoven.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Cold electric teal light from above, blue rim from sides, teal reactor cores glowing blazing teal. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_019": {
    "key": "cb_019",
    "label": "BIOMECH OBSIDIAN PHOENIX",
    "category": "🦾 Cyborg/Biomech",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nBrazilian woman in her late 30s, rich warm bronze complexion commanding beauty, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs so enormously thick each leg fills impossible width, long vivid crimson hair with black roots in enormous loose waves cascading to waist — Body fully painted with H.R. Giger-inspired organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: deep obsidian black organic base with BLAZING CRIMSON-ORANGE PHOENIX mechanical network — exposed phoenix-wing shaped hydraulic panels at shoulder joints spreading dramatically, dense crimson-orange flame circuit patterns covering entire surface, each breast individually featuring a BLAZING PHOENIX reactor core burst as primary focal climax with phoenix flame mechanical tendrils radiating outward like wings, vertebral spine replaced by phoenix tail feather servo column in crimson-orange, forearms plated with phoenix scale segmented armor, thighs featuring flame hydraulic columns, entire surface dense with crimson-orange flame micro-circuit etching on obsidian, blazing crimson-orange phoenix glow at every joint and circuit node creating living flame effect on dark surface.\n\nPose: powerful kneeling pose on one knee, back straight, both arms raised dramatically to sides showing phoenix wing shoulder panels, chin raised fierce phoenix goddess expression, crimson waves cascading dramatically over one shoulder.\nFootwear: obsidian black platform boots ankle-high with crimson sole.\nNails: extra long almond nails obsidian black with crimson tips.\nHair: long vivid crimson hair with black roots enormous loose waves to waist.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Blazing crimson-orange from above creating phoenix fire effect, cold blue rim from sides, phoenix reactor cores and wing panels glowing blazing crimson-orange. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
"cb_020": {
    "key": "cb_020",
    "label": "BIOMECH MIDNIGHT WARRIOR",
    "category": "🦾 Cyborg/Biomech",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nMoroccan woman in her early 40s, warm golden-olive complexion commanding beauty, muscular athletic physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — shoulders impossibly broad and powerful, arms so densely muscled, each breast massive sitting high on sculpted chest, glutes powerfully rounded, thighs and calves so heavily muscled filling impossible width, long sleek jet black hair with electric blue underlights in severe high bun — Body fully painted with H.R. Giger-inspired organic-machine fusion body paint covering EVERY single inch of skin from neck to ankle WITHOUT EXCEPTION — NO bare skin anywhere:\n\nBIOMECH SYSTEM: deep midnight navy organic base with BLAZING ELECTRIC MIDNIGHT BLUE mechanical network — exposed midnight blue chrome pistons at every joint blazing electric blue, dense midnight circuit board patterns covering entire surface with electric blue node points, each breast individually featuring a BLAZING MIDNIGHT BLUE reactor core burst as primary focal climax with electric circuit tendrils radiating outward, vertebral spine replaced by midnight blue servo column with electric node joints, shoulder joints as midnight chrome ball-and-socket machinery, forearms plated with midnight blue segmented battle armor following muscular definition, thighs featuring midnight hydraulic war columns, entire surface dense with midnight blue micro-circuit etching on navy base, electric midnight blue glow emanating from every joint and circuit node.\n\nPose: powerful rear-facing double bicep pose, head turned sharply over shoulder showing fierce expression and electric-underlit high bun, both arms raised showing extreme muscular definition and forearm midnight armor, glutes powerfully defined from rear, midnight servo spine column visible as primary rear focal point.\nFootwear: midnight blue chrome platform boots knee-high.\nNails: extra long stiletto nails midnight blue chrome.\nHair: long sleek jet black hair with electric blue underlights severe high bun.\n\nMANDATORY PURE PITCH BLACK VOID BACKGROUND ONLY. ONE woman only. Cold midnight blue light from above, electric blue rim from sides, reactor cores and joint nodes blazing midnight blue. Pattern density MAXIMUM — zero bare skin anywhere from neck to ankle. Extreme high-gloss metallic finish. 2:3 vertical 8K portrait."
},
}

for key, data in presets.items():
    path = os.path.join(BASE, f"{key}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"✅ {key}.json 생성완료")

print(f"🎉 Cyborg/Biomech JSON 총 {len(presets)}개 생성완료")
