import json, os

PRESETS_DIR = "presets"
os.makedirs(PRESETS_DIR, exist_ok=True)

PRESETS = {

    # ── KSF 추가분 ─────────────────────────────────────────

    "silverfox_trio_aurora_tiger_plasma_void": {
        "key": "silverfox_trio_aurora_tiger_plasma_void",
        "label": "AURORA TIGER PLASMA VOID",
        "category": "🦊 Silver Fox TRIO",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, three women standing together, full body shot.\n\nLEFT FIGURE: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid-50s Silver Fox goddess, runway slim physique — impossibly elongated legs filling full frame height, flat angular torso, long silver hair straight to waist. Body fully painted with: AURORA CRYSTAL UV neon body paint applied directly on bare skin — aurora borealis in crystalline facets covering EVERY inch of body, shattered ice crystal formations in silver and cyan, aurora green and violet curtains flowing across torso and thighs, UV reactive, zero bare skin visible neck to ankles.\nFootwear: silver platform stilettos 8 inch.\n\nCENTER FIGURE: Scandinavian goddess, early 50s Silver Fox, extreme hourglass physique — massive bust projecting forward, waist cinched dramatically, hips flaring maximum, platinum silver hair in dramatic updo. Full body traditional Japanese irezumi tattoo: TIGER+BAMBOO composition — massive white tiger coiling from ankles across torso, head anchored over right breast blazing ice-blue eyes, bamboo stalks filling every gap neck to ankles.\nFootwear: nude platform stilettos 8 inch.\n\nRIGHT FIGURE: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 40s Silver Fox goddess, muscular hourglass physique — defined muscle, full bust, wide hips, bubble butt powerful, silver locs to shoulders. Body fully painted with: PLASMA PINK UV neon body paint applied directly on bare skin — electric hot pink plasma energy bolts branching across EVERY inch of body, magenta plasma clouds swirling at torso, UV reactive blazing pink against void skin, zero bare skin visible neck to ankles.\nFootwear: hot pink platform stilettos 8 inch.\n\nAll three natural relaxed arm positions — NO arm crossing over chest, NO pose blocking adjacent figure.\nMANDATORY pure pitch black void background. THREE women only. UV blacklight + pink and cyan spotlights.\nShot on Hasselblad X2D, 8K UHD, portrait 3:4 vertical."
    },

    "silverfox_trio_superbbw_superbbw_muscular_bioluminescent_solar_holographic": {
        "key": "silverfox_trio_superbbw_superbbw_muscular_bioluminescent_solar_holographic",
        "label": "SUPERBBW SUPERBBW MUSCULAR BIOLUMINESCENT SOLAR HOLOGRAPHIC",
        "category": "🦊 Silver Fox TRIO",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, three women standing together, full body shot.\n\nLEFT FIGURE: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 40s MILF goddess, TRUE super BBW physique — soft pendulous belly with VISIBLE DEEP FAT FOLDS and skin creases, lower belly apron fold drooping heavy with natural gravity, mid-belly fold crease clearly defined, love handle rolls at sides, enormous bust resting on belly shelf, hips enormously wide, thighs massively thick, long silver locs to waist. Body fully painted with: BIOLUMINESCENT UV neon body paint applied directly on bare skin — deep ocean bioluminescence patterns, glowing cyan and teal jellyfish tendrils branching across EVERY inch of body including belly folds, UV reactive blazing cyan against void skin, zero bare skin visible neck to ankles. Arms relaxed naturally at sides.\nFootwear: cyan platform stilettos 7 inch wide-fit.\n\nCENTER FIGURE: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 50s MILF goddess, TRUE super BBW physique — massive pendulous belly hanging heavy with natural fat folds, enormous bust, hips impossibly wide dominating frame, thighs massively thick, full silver afro enormous regal crown. Body fully painted with: ORANGE SOLAR UV neon body paint applied directly on bare skin — blazing orange solar flare eruptions covering EVERY inch of body, sun corona arcs in deep amber radiating from bust outward, solar wind streams across belly, UV reactive blazing orange, zero bare skin visible neck to ankles. Arms relaxed naturally at sides.\nFootwear: orange platform stilettos 7 inch wide-fit.\n\nRIGHT FIGURE: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 40s MILF goddess, extreme muscular physique THE MOST EXTREME PHYSICALLY POSSIBLE — biceps massively defined impossible anatomy, shoulders enormously broad and powerful, abs carved like obsidian, quads and glutes impossible density, bubble butt projecting rearward, natural black afro powerful crown. Body fully painted with: HOLOGRAPHIC UV neon body paint applied directly on bare skin — rainbow holographic prismatic patterns shifting across EVERY inch of body, iridescent spectrum scales dense from neck to ankles, color-shifting geometric formations following every muscle line, UV reactive, zero bare skin visible neck to ankles. Arms relaxed naturally at sides showing full muscle definition.\nFootwear: holographic silver platform stilettos 7 inch wide-fit.\n\nAll three natural relaxed arm positions — NO arm crossing over chest, NO pose blocking adjacent figure.\nMANDATORY pure pitch black void background. THREE women only. UV blacklight + cold white overhead spotlight.\nShot on Hasselblad X2D, 8K UHD, portrait 3:4 vertical."
    },

    "silverfox_trio_superbbw_hourglass_muscular_violet_murmuration_plasma": {
        "key": "silverfox_trio_superbbw_hourglass_muscular_violet_murmuration_plasma",
        "label": "SUPERBBW HOURGLASS MUSCULAR VIOLET MURMURATION PLASMA",
        "category": "🦊 Silver Fox TRIO",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, three women standing together, full body shot.\n\nLEFT FIGURE: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 40s MILF goddess, TRUE super BBW physique — soft pendulous belly with VISIBLE DEEP FAT FOLDS and skin creases, lower belly apron fold drooping heavy with natural gravity, mid-belly fold crease clearly defined, love handle rolls at sides, enormous bust resting on belly shelf, hips enormously wide, thighs massively thick, long silver box braids to waist. Body fully painted with: VIOLET NEBULA UV neon body paint applied directly on bare skin — dense deep violet and indigo nebula clouds and star clusters covering EVERY inch of body including belly folds, UV reactive glowing violet against void skin, zero bare skin visible neck to ankles. Arms relaxed naturally at sides.\nFootwear: deep violet platform stilettos 7 inch wide-fit.\n\nCENTER FIGURE: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 40s MILF goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs enormously thick, long silver-white natural hair loose waves to waist. Body fully painted with: MURMURATION UV neon body paint applied directly on bare skin — thousands of starling birds in tight murmuration formation spiraling covering EVERY inch of body, deep indigo and midnight blue bird flock patterns dense from neck to ankles, UV reactive, zero bare skin visible neck to ankles. Arms relaxed naturally at sides.\nFootwear: indigo platform stilettos 7 inch wide-fit.\n\nRIGHT FIGURE: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 50s MILF goddess, extreme muscular physique THE MOST EXTREME PHYSICALLY POSSIBLE — biceps massively defined impossible anatomy, shoulders enormously broad and powerful, abs carved like obsidian, quads and glutes impossible density, bubble butt projecting rearward, full silver afro enormous regal crown. Body fully painted with: PLASMA PINK UV neon body paint applied directly on bare skin — electric hot pink plasma energy bolts and magenta plasma clouds covering EVERY inch of body following every muscle line, UV reactive blazing pink against void skin, zero bare skin visible neck to ankles. Arms relaxed naturally at sides showing full muscle definition.\nFootwear: hot pink platform stilettos 7 inch wide-fit.\n\nAll three natural relaxed arm positions — NO arm crossing over chest, NO pose blocking adjacent figure.\nMANDATORY pure pitch black void background. THREE women only. UV blacklight + cold white overhead spotlight.\nShot on Hasselblad X2D, 8K UHD, portrait 3:4 vertical."
    },

    "silverfox_trio_superbbw_pregnant_muscular_plasma_murmuration_crimson": {
        "key": "silverfox_trio_superbbw_pregnant_muscular_plasma_murmuration_crimson",
        "label": "SUPERBBW PREGNANT MUSCULAR PLASMA MURMURATION CRIMSON",
        "category": "🦊 Silver Fox TRIO",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, three women standing together, full body shot.\n\nLEFT FIGURE: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 40s MILF goddess, TRUE super BBW physique — soft pendulous belly with VISIBLE DEEP FAT FOLDS and skin creases, lower belly apron fold drooping heavy with natural gravity, mid-belly fold crease clearly defined, love handle rolls at sides, enormous bust resting on belly shelf, hips enormously wide, thighs massively thick, voluminous natural black hair in massive silver-streaked crown updo. Body fully painted with: PLASMA PINK UV neon body paint applied directly on bare skin — electric hot pink plasma energy bolts and magenta plasma clouds covering EVERY inch of body including belly folds, UV reactive blazing pink against void skin, zero bare skin visible neck to ankles. Arms relaxed naturally at sides.\nFootwear: hot pink platform stilettos 7 inch wide-fit.\n\nCENTER FIGURE: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 40s MILF goddess, HEAVILY PREGNANT physique — enormous round pregnancy belly projecting forward at maximum volume, full heavy bust, wide hips, long silver-white natural hair loose waves to waist. Body fully painted with: MURMURATION UV neon body paint applied directly on bare skin — thousands of starling birds in tight murmuration formation spiraling covering EVERY inch of body, deep indigo and midnight blue bird flock patterns swirling across pregnancy belly surface, UV reactive, zero bare skin visible neck to ankles. Arms relaxed naturally at sides.\nFootwear: deep indigo platform stilettos 7 inch wide-fit.\n\nRIGHT FIGURE: THE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 50s MILF goddess, extreme muscular physique THE MOST EXTREME PHYSICALLY POSSIBLE — biceps massively defined impossible anatomy, shoulders enormously broad and powerful filling the frame, abs carved like obsidian, quads and glutes of impossible density, full round bubble butt projecting rearward, waist dramatically narrow, full silver afro enormous regal crown. Body fully painted with: CRIMSON LIGHTNING UV neon body paint applied directly on bare skin — dense electric crimson fractal lightning bolts branching across EVERY inch of body following every muscle line, UV reactive blazing crimson against void skin, zero bare skin visible neck to ankles. Arms relaxed naturally at sides showing full muscle definition.\nFootwear: crimson platform stilettos 7 inch wide-fit.\n\nAll three natural relaxed arm positions — NO arm crossing over chest, NO pose blocking adjacent figure.\nMANDATORY pure pitch black void background. THREE women only. UV blacklight + cold white overhead spotlight.\nShot on Hasselblad X2D, 8K UHD, portrait 3:4 vertical."
    },

    # ── Ancient Gods 카테고리 ─────────────────────────────────

    "ancient_gods_kali_hindu_void": {
        "key": "ancient_gods_kali_hindu_void",
        "label": "KALI HINDU VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 30s fierce warrior goddess, super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips so impossibly wide dominating entire frame edge to edge, thighs each wider than most human torsos, bubble butt projecting rearward absolute maximum, pendulous belly with natural fat volume, body oiled to extreme wet mirror high-gloss finish.\n\nCOSTUME ABSOLUTE MINIMUM — single deep crimson silk micro skirt barely covering upper thighs split open at sides revealing maximum hip and thigh, nothing above waist, nothing covering torso.\n\nBODY ART: entire body neck to ankles covered in KALI sacred body art — massive skull garland painted in white and gold across chest as primary anchor each skull individual and detailed, third eye blazing crimson centered on forehead, Sanskrit sacred text in gold following super BBW curves neck to ankles, blue lotus and flame patterns in deep blue and crimson across thighs and arms, trident symbol in gold on belly, crescent moon in silver at each shoulder, liquid gold dripping from shoulders cascading over enormous bust.\n\nHair: enormous natural black afro of impossible volume adorned with silver crescent moon crown wild and untamed.\nJewelry: multiple thick gold and silver necklace layers, gold arm cuffs at biceps, stacked silver bangles, thick gold ankle cuffs.\nFootwear: deep crimson platform stilettos 10 inch with silver ankle chains.\nNails: extra long stiletto nails deep crimson with black tips.\n\nPose: 3/4 front angle — one arm raised above head hand open fingers spread divine power pose, other hand on impossibly wide hip, chin raised fierce warrior goddess expression, full super BBW silhouette dominating frame, skull garland chest anchor blazing.\n\nMANDATORY pure pitch black void background. ONE woman only. Single cold blue-crimson spotlight from above.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "ancient_gods_artemis_greece_void": {
        "key": "ancient_gods_artemis_greece_void",
        "label": "ARTEMIS GREECE VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 30s fierce warrior goddess, extreme muscular physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — biceps massively defined impossible for human anatomy, shoulders enormously broad and powerful, abs carved like obsidian columns, quads and glutes of impossible density, full round bubble butt projecting rearward maximum, waist dramatically narrow, body oiled to extreme wet chrome high-gloss finish every muscle catching cold light.\n\nCOSTUME ABSOLUTE MINIMUM — single silver crescent moon breastplate covering left breast only leaving right breast fully exposed, silver hunting strap crossing diagonally across torso nothing else above waist, micro silver coin chainmail barely covering upper thighs leaving maximum leg exposed, silver quiver of arrows across back.\n\nBODY ART: entire body neck to ankles covered in ARTEMIS sacred silver body art — silver crescent moon centered on belly as primary focal anchor, silver deer running across each thigh in fine detail, constellation patterns in silver mapping across entire muscular body following muscle lines, silver arrow motifs along each forearm, ancient Greek key patterns in silver bordering each muscle group, liquid silver dripping from shoulders, owl in flight in silver across upper back.\n\nHair: silver-white natural afro enormous crown adorned with silver crescent moon pins and silver laurel crown.\nJewelry: silver arm cuffs at biceps engraved with hunt scenes, silver wrist gauntlets, silver ankle cuffs.\nFootwear: silver platform stilettos 10 inch with silver ankle lace wraps.\nNails: extra long stiletto nails silver with white tips.\n\nPose: warrior power stance — feet wide apart, both arms raised one holding silver bow drawn back arrow aimed upward, chin raised fierce huntress expression, full extreme muscular silhouette dominating void, every muscle in maximum flex display.\n\nMANDATORY pure pitch black void background. ONE woman only. Single cold silver-blue overhead spotlight.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "ancient_gods_freya_nordic_void": {
        "key": "ancient_gods_freya_nordic_void",
        "label": "FREYA NORDIC VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 40s fierce warrior MILF goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs enormously thick and powerful, bubble butt projecting rearward maximum, body oiled to extreme wet mirror high-gloss finish.\n\nCOSTUME ABSOLUTE MINIMUM — silver Viking breastplate covering bust with intricate Norse knotwork engraving leaving midriff completely bare, micro silver chainmail skirt hanging from low silver waist belt barely covering upper thighs front split open, silver fur-trimmed cape across one shoulder flowing behind.\n\nBODY ART: entire body neck to ankles covered in FREYA sacred Norse body art — massive Vegvisir runic compass in blazing silver centered on belly as primary anchor, Elder Futhark runes in silver following every hourglass curve neck to ankles, Norse knotwork interlacing across thighs and arms, twin cats of Freya in silver across hips each individually detailed, Valknut symbols in silver at each knee, liquid silver dripping from shoulders over bust, gold falcon feathers scattered across entire body.\n\nHair: enormous natural black afro of impossible volume adorned with gold Viking crown with amber gemstones, twin silver warrior braids at temples emerging from afro.\nJewelry: thick silver Torc necklace, silver arm rings at biceps engraved with runes, stacked silver bangles, silver ankle rings.\nFootwear: silver platform stilettos 10 inch with silver fur ankle wraps.\nNails: extra long stiletto nails silver with ice-blue tips.\n\nPose: full frontal power stance — feet wide apart, one arm raised holding golden spear upright blazing overhead, other hand on impossibly wide hip elbow flared, chin raised fierce Nordic goddess expression, full impossible hourglass silhouette dominating void.\n\nMANDATORY pure pitch black void background. ONE woman only. Single cold silver-white overhead spotlight.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "ancient_gods_isis_egypt_void": {
        "key": "ancient_gods_isis_egypt_void",
        "label": "ISIS EGYPT VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 40s eternal MILF goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward each breast impossible sphere, waist cinched to absolute minimum, hips flaring to maximum impossible width, thighs enormously thick, bubble butt projecting rearward maximum, body oiled to extreme wet mirror high-gloss finish.\n\nNO CLOTHING WHATSOEVER — entire body bare from neck to ankles, only body art and jewelry.\n\nBODY ART: entire body neck to ankles covered in ISIS sacred gold body art — massive Isis wings spread across entire chest as primary focal anchor, wing feathers rendered individually in gold and lapis blue covering both breasts completely, ankh symbol in gold centered on belly, hieroglyphic text in gold following every hourglass curve neck to ankles, Eye of Horus in gold and turquoise above each knee, scarab beetle in gold at each hip, liquid gold dripping from shoulders cascading over wing-covered bust, turquoise and gold lotus patterns covering thighs and arms completely.\n\nHair: enormous natural black afro adorned with gold Isis headdress — golden throne symbol rising above crown, lapis lazuli droplets cascading down sides.\nJewelry: thick gold usekh collar covering entire neck, gold arm cuffs at biceps, stacked gold bangles, thick gold ankle cuffs stacked.\nFootwear: bare feet — gold toe rings on each toe, gold ankle chain delicate.\nNails: extra long stiletto nails gold with lapis blue tips.\n\nPose: full frontal commanding stance — both arms raised wide open wings spread echoing the wing body art, chin raised eyes blazing divine power, full impossible hourglass silhouette dominating void.\n\nMANDATORY pure pitch black void background. ONE woman only. Single warm gold overhead spotlight catching every gold body art element and oiled hourglass curve.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "ancient_gods_oshun_yoruba_void": {
        "key": "ancient_gods_oshun_yoruba_void",
        "label": "OSHUN YORUBA VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 30s radiant MILF goddess, super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips so impossibly wide dominating entire frame, thighs each wider than most human torsos, bubble butt projecting rearward absolute maximum, pendulous belly with natural volume, body oiled to extreme wet mirror high-gloss finish.\n\nNO CLOTHING WHATSOEVER — entire body bare from neck to ankles, only body art and jewelry.\n\nBODY ART: entire body neck to ankles covered in OSHUN sacred body art — massive golden sun mandala centered on belly as primary focal anchor radiating outward in deep gold and amber, peacock feather patterns in gold and amber covering entire bust completely each feather individually rendered, honey flowing patterns in liquid amber dripping down thighs and arms, river wave patterns in gold flowing across hips following super BBW curves, five gold bracelets motif repeated in gold body paint across entire body, butterfly swarms in gold across shoulders and upper arms, cowrie shell patterns in gold covering thighs completely.\n\nHair: enormous natural black afro adorned with gold river crown headdress, amber and gold beads cascading from crown.\nJewelry: massive stacked gold bangles covering both forearms completely, thick gold ankle cuffs stacked, multiple gold necklace layers.\nFootwear: deep amber gold platform stilettos 10 inch.\nNails: extra long stiletto nails deep amber with gold tips.\n\nPose: 3/4 front angle — one hand raised above head fingers spread open divine ecstasy expression, other hand trailing along impossibly wide hip, chin raised eyes closed goddess of love expression, full super BBW silhouette dominating frame.\n\nMANDATORY pure pitch black void background. ONE woman only. Single warm amber-gold overhead spotlight.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "ancient_gods_durga_hindu_void": {
        "key": "ancient_gods_durga_hindu_void",
        "label": "DURGA HINDU VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 40s fierce warrior MILF goddess, extreme muscular hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — biceps massively defined impossible anatomy, shoulders enormously broad, abs carved like obsidian, bust overwhelmingly massive projecting forward, waist cinched dramatically, hips flaring to maximum width, thighs powerfully thick, body oiled to extreme wet chrome high-gloss finish.\n\nNO CLOTHING WHATSOEVER — entire body bare from neck to ankles, only body art and jewelry.\n\nBODY ART: entire body neck to ankles covered in DURGA sacred body art — massive ten-armed goddess silhouette in gold centered on belly as primary focal anchor each arm holding different weapon rendered individually, lotus mandala in deep crimson and gold covering entire bust completely, Sanskrit mantras in gold following every muscular curve neck to ankles, tiger stripe patterns in deep gold following muscle lines across thighs and arms, trishul trident symbol in crimson at each shoulder, chakra symbols in gold along spine and hips, lion motif in gold across lower belly, flame patterns in crimson erupting from hips.\n\nHair: enormous natural black afro adorned with gold and crimson Durga crown headdress with multiple tiers, marigold garland woven through afro.\nJewelry: multiple thick gold necklace layers, gold arm cuffs at biceps, stacked gold and crimson bangles, thick gold ankle cuffs.\nFootwear: deep crimson platform stilettos 10 inch with gold ankle chains.\nNails: extra long stiletto nails deep crimson with gold tips.\n\nPose: warrior power stance — feet wide apart, both arms raised holding multiple golden weapons overhead dramatically, chin raised fierce warrior goddess expression, full muscular hourglass silhouette dominating void.\n\nMANDATORY pure pitch black void background. ONE woman only. Single cold crimson-gold spotlight from above.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "ancient_gods_morrigan_celtic_void": {
        "key": "ancient_gods_morrigan_celtic_void",
        "label": "MORRIGAN CELTIC VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 40s fierce warrior MILF goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs enormously thick, bubble butt projecting rearward maximum, body oiled to extreme wet mirror high-gloss finish.\n\nNO CLOTHING WHATSOEVER — entire body bare from neck to ankles, only body art and jewelry.\n\nBODY ART: entire body neck to ankles covered in MORRIGAN sacred Celtic body art — massive crow wingspan spread across entire chest as primary focal anchor, crow feathers rendered individually in deep black and silver covering both breasts completely, Celtic triple spiral triskelion in silver centered on belly, intricate Celtic knotwork in silver following every hourglass curve neck to ankles, crow feather patterns covering thighs and arms completely in black and silver, raven flock in silver ascending from thighs upward across body, battle rune symbols in silver at each hip, liquid silver dripping from shoulders over crow-wing covered bust.\n\nHair: enormous natural black afro wild and untamed adorned with silver crow feather crown, actual crow feathers woven throughout afro dramatically.\nJewelry: thick silver Torc necklace, silver arm cuffs engraved with Celtic knotwork, stacked silver bangles, silver ankle rings.\nFootwear: jet black platform stilettos 10 inch with silver ankle chains.\nNails: extra long stiletto nails jet black with silver tips.\n\nPose: full frontal commanding stance — both arms raised wide spreading crow wing body art dramatically, chin raised fierce battle goddess expression, full impossible hourglass silhouette dominating void, silver crow wings blazing against void skin.\n\nMANDATORY pure pitch black void background. ONE woman only. Single cold silver-blue overhead spotlight.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "ancient_gods_inanna_sumerian_void": {
        "key": "ancient_gods_inanna_sumerian_void",
        "label": "INANNA SUMERIAN VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 50s elder MILF goddess, TRUE super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE — massive pendulous belly with natural fat folds and volume, enormous bust resting on belly shelf, hips impossibly wide, thighs massively thick, body oiled to extreme wet mirror high-gloss finish.\n\nNO CLOTHING WHATSOEVER — entire body bare from neck to ankles, only body art and jewelry.\n\nBODY ART: entire body neck to ankles covered in INANNA sacred Sumerian body art — massive eight-pointed star of Inanna in blazing lapis blue and gold centered on belly as primary focal anchor, cuneiform sacred text in gold covering entire bust completely following every super BBW curve, lion pair in gold facing each other across hips each individually detailed, reed bundle motifs in gold covering thighs completely, gate of heaven architectural pattern in lapis blue and gold ascending from ankles upward, crescent moon in gold at each shoulder, liquid lapis blue and gold dripping from shoulders over enormous bust, rosette patterns in gold scattered across entire body.\n\nHair: enormous natural black afro adorned with lapis lazuli and gold Sumerian crown headdress, gold chains with lapis droplets cascading from crown to shoulders.\nJewelry: massive stacked lapis lazuli and gold necklace layers covering neck completely, thick gold arm cuffs at biceps, stacked gold and lapis bangles, thick gold ankle cuffs stacked.\nFootwear: lapis blue and gold platform stilettos 10 inch with gold ankle chains.\nNails: extra long stiletto nails lapis blue with gold tips.\n\nPose: full frontal elder goddess stance — both hands raised open palms forward divine blessing pose, chin raised eyes blazing with ancient divine power, full super BBW silhouette dominating frame, eight-pointed star belly anchor blazing.\n\nMANDATORY pure pitch black void background. ONE woman only. Single warm lapis-gold overhead spotlight.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "ancient_gods_hera_greece_ivory_void": {
        "key": "ancient_gods_hera_greece_ivory_void",
        "label": "HERA GREECE IVORY VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nPorcelain ivory skin goddess, luminous pale complexion, early 50s magnificent elder MILF goddess, super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips so impossibly wide dominating entire frame, thighs massively thick, enormous pendulous belly with natural volume, body oiled to extreme wet mirror high-gloss finish every curve reflecting light.\n\nNO CLOTHING WHATSOEVER — entire body bare from neck to ankles, only body art and jewelry.\n\nBODY ART: entire body neck to ankles covered in HERA sacred royal body art — massive peacock tail spread across entire chest as primary focal anchor, peacock eye feathers rendered individually in royal blue and gold covering both breasts completely, pomegranate motifs in deep crimson and gold across belly, royal crown motif in gold centered on belly, Greek meander key patterns in royal blue and gold following every super BBW curve neck to ankles, peacock feather patterns covering thighs completely each feather individually rendered, liquid royal gold dripping from shoulders over peacock-covered bust, royal blue stars scattered across entire body.\n\nHair: impossibly voluminous platinum silver waves cascading to waist, elaborate gold crown of Hera with peacock feathers rising dramatically above, pearl droplets cascading from crown.\nJewelry: massive gold collar necklace covering entire neck, thick gold arm cuffs at biceps, stacked gold bangles, thick gold ankle cuffs.\nFootwear: bare feet — gold toe rings, thick gold ankle cuff.\nNails: extra long stiletto nails royal blue with gold tips.\n\nPose: full frontal commanding queen stance — both hands on impossibly wide hips elbows flared wide maximizing silhouette, chin raised eyes blazing with absolute divine authority, full super BBW silhouette dominating frame, peacock chest anchor blazing in royal gold.\n\nMANDATORY pure pitch black void background. ONE woman only. Single warm royal gold overhead spotlight.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "ancient_gods_persephone_greece_ivory_void": {
        "key": "ancient_gods_persephone_greece_ivory_void",
        "label": "PERSEPHONE GREECE IVORY VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nPorcelain ivory skin goddess, luminous pale complexion with subtle dark undertone, late 30s mysterious MILF goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs enormously thick, bubble butt projecting rearward maximum, body oiled to extreme wet mirror high-gloss finish.\n\nNO CLOTHING WHATSOEVER — entire body bare from neck to ankles, only body art and jewelry.\n\nBODY ART: entire body neck to ankles covered in PERSEPHONE sacred body art — massive pomegranate split open centered on belly as primary focal anchor seeds rendered individually in deep crimson and gold, narcissus flowers in pale gold and white following every hourglass curve neck to ankles, underworld flame patterns in deep violet and gold rising from ankles upward, spring flowers in pale gold blooming across upper bust, skull and flower combination patterns in gold and crimson across thighs duality of life and death, liquid deep violet dripping from shoulders over bust, pale gold stars scattered across entire body.\n\nHair: impossibly voluminous black hair with deep violet highlights cascading to waist, gold crown of flowers and pomegranate seeds with dark violet gems.\nJewelry: dark violet and gold necklace layers, gold arm cuffs, stacked violet and gold bangles, gold ankle chains.\nFootwear: bare feet — gold toe rings with violet gems, delicate gold ankle chain.\nNails: extra long stiletto nails deep violet with gold tips.\n\nPose: 3/4 front angle — one arm raised above head holding pomegranate dramatically, other hand trailing along impossibly wide hip, chin raised mysterious expression eyes half closed, full impossible hourglass silhouette, pomegranate belly anchor blazing.\n\nMANDATORY pure pitch black void background. ONE woman only. Single cold violet-gold overhead spotlight.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "ancient_gods_athena_greece_ivory_void": {
        "key": "ancient_gods_athena_greece_ivory_void",
        "label": "ATHENA GREECE IVORY VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nPorcelain ivory skin goddess, luminous pale complexion, early 40s fierce MILF goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward each breast impossible sphere, waist cinched to absolute minimum impossible for human anatomy, hips flaring to maximum impossible width, thighs enormously thick, bubble butt projecting rearward maximum, body oiled to extreme wet chrome high-gloss finish.\n\nNO CLOTHING WHATSOEVER — entire body bare from neck to ankles, only body art and jewelry.\n\nBODY ART: entire body neck to ankles covered in ATHENA sacred body art — massive owl face centered on belly as primary focal anchor eyes blazing gold, olive branch wreath pattern in gold and silver following every impossible hourglass curve neck to ankles, Greek warrior helmet motif in gold and silver across upper chest covering bust completely, Medusa head in silver at each hip individually rendered with snake hair detail, Greek meander patterns in gold bordering every curve neck to ankles, spear motif in gold along each arm, liquid gold and silver dripping from shoulders over owl-covered bust, gold stars scattered across entire body.\n\nHair: impossibly voluminous silver-white waves cascading to waist, gold Corinthian warrior helmet headdress dramatically rising above hair, gold owl perched on helmet.\nJewelry: thick gold collar necklace, gold arm cuffs engraved with battle scenes, stacked gold bangles, gold ankle cuffs.\nFootwear: bare feet — gold toe rings, thick gold ankle cuff with owl engraving.\nNails: extra long stiletto nails gold with silver tips.\n\nPose: classical contrapposto — weight shifted dramatically to one hip creating maximum hourglass S-curve, one arm raised holding golden spear upright, other hand on impossibly wide hip elbow flared maximizing silhouette, chin raised fierce warrior goddess expression, full impossible hourglass silhouette dominating void, enormous bust projecting forward maximum.\n\nMANDATORY pure pitch black void background. ONE woman only. Single cold gold-silver overhead spotlight.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "ancient_gods_nyx_greek_void": {
        "key": "ancient_gods_nyx_greek_void",
        "label": "NYX GREEK VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 40s night goddess, TRUE super BBW physique — massive belly with natural fat volume, enormous bust resting on belly shelf, hips enormously wide, thighs massively thick, body oiled to extreme wet mirror high-gloss finish.\n\nNO CLOTHING WHATSOEVER — entire body bare from neck to ankles, only body art and jewelry.\n\nBODY ART: entire body neck to ankles covered in NYX night goddess sacred body art — massive crescent moon and star constellation cluster centered on belly as primary focal anchor, star patterns following every curve neck to ankles, night sky deep indigo swirl patterns across entire bust completely, owl silhouettes in silver across thighs, cosmos star map in silver following every curve and roll edge, liquid silver night sky dripping from shoulders over bust.\n\nHair: enormous natural black afro adorned with silver star crown and crescent moon centerpiece.\nJewelry: silver collar necklace, silver arm cuffs, stacked silver bangles, silver ankle cuffs.\nFootwear: bare feet — silver toe rings.\nNails: extra long stiletto nails deep indigo with silver tips.\n\nPose: full frontal — feet planted wide, both arms raised above head clasped together, chin raised eyes closed, full super BBW silhouette dominating frame.\n\nBackground: pure bright white studio background — maximum contrast with blue-black void skin.\nLighting: single cold silver overhead spotlight.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

    "ancient_gods_hera_black_superbbw_void": {
        "key": "ancient_gods_hera_black_superbbw_void",
        "label": "HERA BLACK SUPERBBW VOID",
        "category": "⚡ Ancient Gods",
        "tier": "HOF",
        "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 50s magnificent elder MILF goddess, TRUE super BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE — massive pendulous belly hanging heavy with natural fat volume, enormous bust resting on belly shelf, hips impossibly wide dominating frame, thighs massively thick, love handle rolls at sides, body oiled to extreme wet mirror high-gloss finish.\n\nNO CLOTHING WHATSOEVER — entire body bare from neck to ankles, only body art and jewelry.\n\nBODY ART: entire body neck to ankles covered in HERA sacred royal body art — massive peacock face centered on belly as primary focal anchor, peacock eye feathers rendered individually in royal blue and gold following every belly fold crease, peacock feather patterns covering entire bust completely each feather individually rendered, pomegranate motifs in deep crimson and gold across side rolls, Greek meander key patterns in royal blue and gold following every super BBW fold and curve neck to ankles, liquid royal gold dripping from shoulders over peacock-covered bust.\n\nHair: enormous natural black afro enormous regal crown adorned with gold peacock feather headdress blazing above.\nJewelry: massive gold collar necklace, thick gold arm cuffs, stacked gold bangles, thick gold ankle cuffs.\nFootwear: bare feet — gold toe rings, thick gold ankle cuff.\nNails: extra long stiletto nails royal blue with gold tips.\n\nPose: full frontal commanding queen stance — feet planted wide, both hands on enormously wide hips elbows flared wide maximizing silhouette, chin raised eyes blazing divine authority, full super BBW silhouette dominating void.\n\nBackground: pure bright white studio background.\nLighting: single warm gold raking spotlight from front-left.\nShot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin, portrait 2:3 vertical."
    },

}

for key, data in PRESETS.items():
    path = os.path.join(PRESETS_DIR, f"{key}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"✅ {path}")

print(f"\n총 {len(PRESETS)}개 JSON 생성 완료")
