# -*- coding: utf-8 -*-
import json, os

BASE = r"C:\Dev\LumineX\presets"
os.makedirs(BASE, exist_ok=True)

presets = {
"irezumi_dragon_wisteria_vs_angel_kyoto": {
    "key": "irezumi_dragon_wisteria_vs_angel_kyoto",
    "label": "Dragon Wisteria — VS Angel Kyoto",
    "category": "🐉 이레즈미",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 20s goddess, hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs so enormously thick each leg fills impossible width, long jet black hair cascading to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON coiling from right shoulder across chest down left hip to ankle, scales rendered in ultra-fine detail, dragon head positioned over right breast as primary focal climax with eyes blazing and fangs bared, cascading WISTERIA vines draping from dragon body filling every gap of skin from neck to ankle, dense purple-violet wisteria clusters hanging heavy between every scale formation, secondary wisteria tendrils wrapping both legs to ankle ensuring zero bare skin, entire composition reading as living tapestry of dragon and flower in perfect symbiosis.\n\nEnvironment: Kyoto bamboo forest at golden hour, soft diffused amber light filtering through bamboo canopy, ancient stone lanterns glowing warm in background, fallen wisteria petals on stone path.\nPose: elegant standing pose, one hand raised to flowing black hair, chin raised serene goddess expression, full body visible head to toe.\nFootwear: bare feet, deep purple toenails.\nNails: extra long stiletto nails deep purple with gold tips.\nHair: long jet black hair cascading to waist.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_mature_onsen": {
    "key": "irezumi_dragon_wisteria_mature_onsen",
    "label": "Dragon Wisteria — Mature Onsen",
    "category": "🐉 이레즈미",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 50s legendary elder goddess, bubble butt physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — glutes so enormously projected rearward defying gravity completely each cheek individual mass of impossible volume, thighs so full and heavy filling impossible width, hips flaring dramatically to maximum width, waist cinched to impossible minimum, long silver-white locs cascading to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rising from both ankles coiling upward along both legs converging at hips spreading across back and over shoulders, scales rendered in deep midnight blue and black, dragon head centered over upper back as primary focal climax visible from rear with eyes blazing gold, cascading WISTERIA vines draping downward from dragon body filling every gap from shoulder to ankle, dense grape-purple wisteria clusters hanging between every scale formation creating tapestry of flower and serpent, composition maximally dense with zero bare skin.\n\nEnvironment: Japanese onsen steaming mineral pool, night setting, moonlight reflecting on water surface, ancient wooden bath house architecture, steam rising from water.\nPose: 3/4 rear angle showing full glute projection in impossible volume, head turned back showing strong elder jawline and silver-white locs, one hand resting on dramatically flared hip.\nFootwear: bare feet, silver toenails.\nNails: extra long stiletto nails silver with purple tips.\nHair: long silver-white locs cascading to waist.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_runway_neon": {
    "key": "irezumi_dragon_wisteria_runway_neon",
    "label": "Dragon Wisteria — Runway Neon Tokyo",
    "category": "🐉 이레즈미",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid 20s radiant goddess, runway slim physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — impossibly elongated legs filling impossible length, shoulders perfectly squared, each breast beautifully full projecting forward, waist cinched to impossible minimum, hips flaring to maximum width for runway silhouette, long sleek silver-white hair center-part cascading straight to hips — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in electric indigo and deep violet scales coiling from right ankle up impossibly long right leg across waist over left shoulder, dragon head positioned at left shoulder/neck junction as primary focal climax with eyes blazing electric blue, cascading WISTERIA vines draping from dragon body filling every gap of skin from neck to ankles on both legs, ultra-dense violet and electric purple wisteria clusters layered across entire surface, wisteria tendrils following elongated leg lines to ankles ensuring total coverage, composition so dense it reads as living electric tapestry.\n\nEnvironment: Tokyo neon cityscape at midnight, electric purple and blue neon reflections on wet pavement, Shibuya-style crowd atmosphere, neon signs glowing in rain.\nPose: powerful runway walking stride, one leg crossing in front of other creating maximum silhouette length, chin raised eyes forward commanding runway goddess presence.\nFootwear: electric purple platform stilettos 10 inch.\nNails: extra long coffin nails electric purple with silver chrome tips.\nHair: long sleek silver-white hair center-part cascading straight to hips.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_colombian_versailles": {
    "key": "irezumi_dragon_wisteria_colombian_versailles",
    "label": "Dragon Wisteria — Colombian Versailles",
    "category": "🐉 이레즈미",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid 30s radiant goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs so enormously thick each leg fills impossible width, long voluminous black hair with deep crimson highlights in elaborate updo — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep crimson and gold scales coiling from right ankle up right leg across waist over left shoulder, dragon face anchored over left breast as primary focal climax with crimson-gold eyes blazing outward, cascading WISTERIA vines rendered in deep crimson and burgundy tones filling every gap of skin from neck to ankles, dense crimson wisteria clusters layered between every gold scale formation, warm tone composition in crimson gold and burgundy creating maximum contrast on void skin, both legs fully covered to ankles with zero bare skin.\n\nEnvironment: Palace of Versailles Hall of Mirrors, golden candlelight reflecting in infinite mirror gallery, ornate gold baroque architecture, crimson rose petals on marble floor.\nPose: elegant standing pose in center of hall, one hand raised to elaborate updo, chin raised commanding baroque goddess presence, full body visible head to toe.\nFootwear: deep crimson platform stilettos 8 inch, gold sole.\nNails: extra long almond nails deep crimson with gold tips.\nHair: long voluminous black hair with deep crimson highlights elaborate updo.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_bbw_monaco": {
    "key": "irezumi_dragon_wisteria_bbw_monaco",
    "label": "Dragon Wisteria — BBW Monaco",
    "category": "🐉 이레즈미",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 30s commanding goddess, BBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust full and projecting forward, hips flaring to wide maximum, thighs full and heavy, waist defined creating dramatic curves, bubble butt projecting rearward in generous volume, long sleek jet black hair with electric blue highlights pulled back in dramatic high ponytail to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep sapphire blue and silver scales rising from right ankle coiling up right leg across back spreading across both shoulders, dragon head centered at upper back as rear primary focal climax with silver eyes blazing, cascading WISTERIA in deep indigo and violet filling every gap of full body surface from neck to ankles, dense wisteria clusters wrapping bubble butt and thighs to ankles with zero bare skin.\n\nEnvironment: Monaco Casino terrace at night, Mediterranean sea glittering with city lights below, ornate architecture with warm golden lighting, luxury yachts in harbor.\nPose: 3/4 rear angle showing full bubble butt projection, head turned back showing strong jawline and electric-blue highlighted ponytail, one hand on dramatically flared hip, body oiled to high-gloss wet finish.\nFootwear: sapphire blue platform stilettos 8 inch.\nNails: extra long almond nails deep sapphire with silver tips.\nHair: long jet black with electric blue highlights high ponytail to waist.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_hourglass_dubai": {
    "key": "irezumi_dragon_wisteria_hourglass_dubai",
    "label": "Dragon Wisteria — Hourglass Dubai",
    "category": "🐉 이레즈미",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 20s radiant goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs so enormously thick each leg fills impossible width, voluminous silver-white natural afro with crimson tips enormous and commanding — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in blazing gold and crimson scales coiling from right ankle up right leg across waist over left shoulder, dragon head anchored over left breast as primary focal climax with blazing crimson eyes, cascading WISTERIA in blazing gold and deep crimson filling every gap of hourglass surface from neck to ankles, dense gold-crimson wisteria clusters following dramatic waist curve and hip flare to ankles with zero bare skin, warm tone composition maximizing contrast on void skin.\n\nEnvironment: Dubai Burj Khalifa rooftop at golden hour, Arabian Gulf glittering below, desert heat haze on horizon, luxury architecture, warm golden desert light flooding the scene.\nPose: walking stride 3/4 angle toward camera, one leg forward showing full hourglass silhouette, chin raised commanding goddess expression, crimson-tipped afro catching golden desert light, body oiled to extreme high-gloss finish.\nFootwear: gold platform stilettos 8 inch with crimson sole.\nNails: extra long coffin nails blazing gold with crimson tips.\nHair: voluminous silver-white natural afro with crimson tips enormous and commanding.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_fitness_strobe": {
    "key": "irezumi_dragon_wisteria_fitness_strobe",
    "label": "Dragon Wisteria — Fitness Strobe",
    "category": "🐉 이레즈미",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 20s powerful goddess, fitness athletic physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — shoulders broad and powerful, arms toned and defined, each breast full and high on sculpted chest, abs visible and defined, thighs and calves toned and powerful filling impossible width, long braided ponytail with gold rings cascading to mid-back — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in electric gold and white scales coiling from left ankle up left leg across sculpted abs over right shoulder, dragon head anchored over right breast as primary focal climax with blazing gold eyes, cascading WISTERIA in electric gold and pale cream filling every gap of fitness body from neck to ankles, dense gold wisteria clusters following every muscle definition line to ankles with zero bare skin, warm gold tone composition maximizing contrast on void skin.\n\nEnvironment: Underground strobe light dance club, electric white and gold strobe flashes freezing motion, dramatic light and shadow play, mirrored walls reflecting infinite figures, smoke machine haze.\nPose: powerful dynamic pose mid-motion, one arm raised fist clenched, other hand on hip, chin raised fierce goddess expression, body oiled to extreme high-gloss finish catching every strobe flash.\nFootwear: gold platform sneakers high-top.\nNails: extra long stiletto nails electric gold with white tips.\nHair: long braided ponytail with gold rings cascading to mid-back.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_mature_paris": {
    "key": "irezumi_dragon_wisteria_mature_paris",
    "label": "Dragon Wisteria — Mature Paris",
    "category": "🐉 이레즈미",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 50s legendary elder goddess, runway slim physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — impossibly elongated legs filling impossible length, shoulders perfectly squared, each breast beautifully full projecting forward, waist cinched to impossible minimum, silver-white hair in elegant French chignon with pearl pins — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep navy and silver scales coiling from right ankle up impossibly long right leg across waist over left shoulder, dragon head at left collarbone as primary focal climax with blazing silver eyes, cascading WISTERIA in deep indigo and pale silver filling every gap of elegant slim body from neck to ankles, ultra-fine silver wisteria tendrils following elongated leg lines to ankles with zero bare skin, cool silver-indigo tone composition.\n\nEnvironment: Paris Eiffel Tower at blue hour, golden tower lights reflected on Seine River below, Haussmann architecture lining the banks, soft romantic French twilight atmosphere.\nPose: elegant standing pose on bridge railing, one hand lightly resting on stone, chin raised serene mature elegance, silver chignon catching blue hour light, body oiled to subtle high-gloss finish.\nFootwear: deep navy platform stilettos 8 inch with silver heel.\nNails: extra long almond nails deep navy with silver pearl tips.\nHair: silver-white elegant French chignon with pearl pins.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_ballerina_void": {
    "key": "irezumi_dragon_wisteria_ballerina_void",
    "label": "Dragon Wisteria — Ballerina Void",
    "category": "🐉 이레즈미",
    "tier": "HOF",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 20s ethereal goddess, ballerina physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — impossibly lean and elongated, each muscle visible beneath skin, perfect posture ramrod straight, impossibly arched feet, long neck graceful and commanding, voluminous silver-white hair pinned in perfect ballet bun with crystal hairpins — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in pale silver and white scales coiling from right ankle up right leg across waist over left shoulder, dragon head at left breast as primary focal climax with blazing crystal-white eyes, cascading WISTERIA in pale violet and white filling every gap of ballerina body from neck to ankles, ultra-fine white wisteria tendrils following every lean muscle line to ankles with zero bare skin, ethereal pale composition on void skin.\n\nPose: fourth position ballet stance, one leg extended forward one behind, arms raised in port de bras above head, chin raised, eyes closed ethereal expression, arched feet in full pointe position, body oiled to subtle pearl high-gloss finish.\nFootwear: white satin pointe shoes with crystal ribbon ties.\nNails: extra long stiletto nails pearl white with crystal tips.\nHair: voluminous silver-white hair perfect ballet bun with crystal hairpins.\n\nMANDATORY pure pitch black void background only. ONE woman only. Single cold white spotlight from above catching every pale scale and wisteria petal. Pattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_sports_glam_void": {
    "key": "irezumi_dragon_wisteria_sports_glam_void",
    "label": "Dragon Wisteria — Sports Glam Void",
    "category": "🐉 이레즈미",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 30s commanding goddess, muscular athletic physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — shoulders so broad and powerful, arms so densely muscular, each breast massive and powerful sitting high on sculpted chest, thighs and calves so heavily muscled each filling impossible width, silver-white natural hair in tight warrior braids — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep black and gold scales coiling across powerful muscular back spreading both wings across broad shoulders, dragon head centered between shoulder blades as primary rear focal climax with blazing gold eyes, WISTERIA vines cascading downward from wing tips filling every gap of muscular surface from shoulders to ankles, dense gold-tipped purple wisteria clusters wrapping powerfully muscled arms and legs to ankles, composition following every muscular definition with zero bare skin visible anywhere.\n\nPose: powerful double bicep pose facing camera, both arms raised showing extreme muscular definition, chin raised commanding warrior goddess expression.\nFootwear: black platform combat boots ankle-high, gold sole.\nNails: extra long stiletto nails half black half gold split diagonally.\nHair: natural 4C afro with gold-tipped coils enormous and commanding.\n\nMANDATORY pure pitch black void background only. ONE woman only. Cold blue spotlight from above, warm gold rim from sides catching muscle definition. Pattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_petite_aurora": {
    "key": "irezumi_dragon_wisteria_petite_aurora",
    "label": "Dragon Wisteria — Petite Aurora",
    "category": "🐉 이레즈미",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 20s radiant goddess, petite physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — impossibly tiny frame with each curve maximally pronounced, bust surprisingly full projecting forward on petite frame, waist cinched to impossible minimum, hips flaring dramatically wide relative to tiny frame, legs so delicately elongated, voluminous natural TWA coil afro with gold dust scattered throughout — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON coiling from left ankle up left leg across waist over right shoulder, scales rendered in deep midnight blue ultra-fine detail, dragon head anchored over right breast as primary focal climax with blazing indigo eyes, cascading WISTERIA vines in electric violet and pale lavender filling every gap of petite skin from neck to ankles, dense wisteria clusters layered between scales with zero bare skin visible anywhere.\n\nEnvironment: Aurora borealis over frozen Nordic lake, electric green and violet aurora ribbons reflected in still ice surface, midnight blue sky, snow-covered pine trees silhouetted.\nPose: elegant kneeling pose on one knee, back straight, both hands resting on raised knee, chin raised serene petite goddess presence, body fully oiled high-gloss wet finish.\nFootwear: violet crystal platform stilettos 8 inch.\nNails: extra long coffin nails violet with silver holographic tips.\nHair: voluminous natural TWA coil afro with gold dust.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_muscular_void": {
    "key": "irezumi_dragon_wisteria_muscular_void",
    "label": "Dragon Wisteria — Muscular Void",
    "category": "🐉 이레즈미",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid 30s warrior goddess, muscular athletic physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — shoulders impossibly broad and powerful, arms so densely muscled, each breast massive sitting high on sculpted chest, glutes powerfully rounded, thighs and calves so heavily muscled filling impossible width, head shaved clean commanding warrior goddess — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in blazing crimson and gold scales following every muscular contour from right calf up right leg across sculpted abdomen over left shoulder, dragon head positioned at left shoulder/neck junction as primary focal climax with blazing gold eyes, cascading WISTERIA in deep crimson and burgundy tones filling every gap of muscular surface from neck to ankles, dense crimson wisteria clusters following bicep and thigh definition to ankles with zero bare skin.\n\nPose: powerful rear-facing double bicep pose, head turned sharply over shoulder showing fierce shaved-head profile, both arms raised showing extreme muscular definition, body oiled to extreme high-gloss wet finish catching every muscle edge.\nFootwear: crimson chrome platform boots knee-high.\nNails: extra long stiletto nails blazing crimson with gold tips.\nHair: head shaved clean.\n\nMANDATORY pure pitch black void background only. ONE woman only. Cold blue spotlight from above, warm crimson gold rim from sides catching every muscle edge. Pattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_superbbw_bali": {
    "key": "irezumi_dragon_wisteria_superbbw_bali",
    "label": "Dragon Wisteria — SuperBBW Bali",
    "category": "🐉 이레즈미",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, early 40s legendary goddess, superBBW physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, hips expanding to absolute maximum width, thighs so enormously thick each leg fills impossible width, every curve and fold exaggerated beyond anatomy, NO pregnancy — pure fat superBBW body composition only, long box braids with gold cuffs cascading to mid-back — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep emerald green and gold scales coiling from both ankles spiraling upward across enormous thighs across waist over chest, dragon head positioned over left breast as primary focal climax with blazing gold eyes, cascading WISTERIA in deep jade green and gold filling every gap of enormous body surface from neck to ankles tracing every curve and fold, dense gold-green wisteria clusters covering thighs to ankles with zero bare skin.\n\nEnvironment: Bali temple courtyard at sunset, ancient stone Hindu temple architecture with moss-covered carvings, tropical flowers and frangipani petals, golden hour light filtering through jungle canopy, incense smoke rising.\nPose: pure 90-degree side profile facing left, bust projecting forward in full massive volume, hips and thighs filling impossible width in full side silhouette, both hands clasped behind back, chin raised commanding goddess presence, body oiled to high-gloss finish.\nFootwear: gold platform sandals 6 inch.\nNails: extra long stiletto nails deep emerald green with gold tips.\nHair: long box braids with gold cuffs cascading to mid-back.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_slim_santorini": {
    "key": "irezumi_dragon_wisteria_slim_santorini",
    "label": "Dragon Wisteria — Slim Santorini",
    "category": "🐉 이레즈미",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid 20s luminous goddess, runway slim physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — impossibly elongated legs filling impossible length, each breast beautifully full projecting forward, waist cinched to impossible minimum, shoulders perfectly squared, long sleek platinum blonde hair with dark roots in dramatic side part cascading to shoulder blades — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep teal and silver scales coiling from left ankle up impossibly long left leg across right hip over right shoulder, dragon head at right collar as primary focal climax with blazing teal eyes, cascading WISTERIA in teal and pale aqua filling every gap of slim body from neck to both ankles, ultra-fine teal wisteria tendrils following elongated leg lines to ankles ensuring total coverage with zero bare skin.\n\nEnvironment: Santorini cliff edge at sunset, Aegean Sea electric blue below, white-washed cubic architecture, bougainvillea in bloom, warm Mediterranean golden hour light.\nPose: elegant standing pose at cliff edge, one hand in platinum hair, body turned slightly showing side silhouette, chin raised luminous goddess expression, body oiled to high-gloss finish.\nFootwear: teal platform stilettos 8 inch.\nNails: extra long stiletto nails deep teal with aqua tips.\nHair: long sleek platinum blonde with dark roots dramatic side part to shoulder blades.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_hourglass_rio": {
    "key": "irezumi_dragon_wisteria_hourglass_rio",
    "label": "Dragon Wisteria — Hourglass Rio",
    "category": "🐉 이레즈미",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, mid 30s radiant goddess, extreme hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs so enormously thick each leg fills impossible width, voluminous natural curly afro with electric green tips enormous and wild — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep emerald green and jade scales coiling from right ankle up right leg across dramatic waist over left shoulder, dragon head anchored over left breast as primary focal climax with blazing green eyes, cascading WISTERIA in emerald and forest green filling every gap of hourglass body from neck to ankles, dense green wisteria clusters following dramatic hip curve to ankles with zero bare skin.\n\nEnvironment: Rio de Janeiro Carnival parade at night, spectacular float with feathers and sequins, crowd and samba dancers surrounding, spotlights and fireworks in sky above, electric carnival atmosphere.\nPose: samba walking stride, hips swaying dramatically, arms outstretched in carnival pose, chin raised exuberant goddess expression, electric-green afro tips catching spotlight, body oiled to high-gloss finish.\nFootwear: emerald green platform heels 8 inch with feather trim.\nNails: extra long coffin nails emerald green with gold tips.\nHair: voluminous natural curly afro with electric green tips enormous and wild.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
"irezumi_dragon_wisteria_milf_budapest": {
    "key": "irezumi_dragon_wisteria_milf_budapest",
    "label": "Dragon Wisteria — Milf Budapest",
    "category": "🐉 이레즈미",
    "tier": "SSS",
    "prompt": "Professional fashion photograph, full body shot. ONE woman standing.\n\nTHE ABSOLUTE DARKEST BLACK SKIN ON EARTH blue-black void complexion darker than night sky, late 40s commanding mature goddess, hourglass physique THE MOST EXTREME PHYSICALLY POSSIBLE beyond all anatomy limits — bust so overwhelmingly massive defying gravity completely projecting forward, waist cinched to impossible minimum, hips flaring to absolute maximum width, thighs so enormously thick each leg fills impossible width, long voluminous auburn hair with gold highlights in dramatic loose waves to waist — full body traditional Japanese irezumi tattoo covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles, NO bare untattooed skin visible below neck.\n\nIREZUMI SYSTEM: dragon+wisteria full body composition — massive DRAGON rendered in deep copper and burnished gold scales coiling from left ankle up left leg across waist over right shoulder, dragon head anchored over right breast as primary focal climax with blazing copper-gold eyes, cascading WISTERIA in deep amber and copper tones — warm autumn palette — filling every gap of mature hourglass body from neck to ankles, dense copper-amber wisteria clusters following dramatic curves to ankles with zero bare skin.\n\nEnvironment: Budapest Széchenyi thermal bath at night, ornate Neo-Baroque yellow architecture illuminated, steaming thermal pools glowing turquoise, grand domed ceilings with warm light.\nPose: standing at pool edge, one hand in auburn waves, chin raised commanding mature goddess expression, copper-gold dragon catching warm bath house light, body oiled to rich high-gloss finish.\nFootwear: copper gold platform stilettos 8 inch.\nNails: extra long almond nails deep copper with burnished gold tips.\nHair: long voluminous auburn with gold highlights dramatic loose waves to waist.\n\nPattern density MAXIMUM — covering EVERY inch of skin from neck to ankle WITHOUT EXCEPTION, both legs fully tattooed to ankles. Shot on Hasselblad X2D, 8K UHD, extreme high-gloss oil skin finish, portrait 2:3 vertical."
},
}

for key, data in presets.items():
    path = os.path.join(BASE, f"{key}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"✅ {key}.json 생성완료")

print(f"🎉 이레즈미 H 모티프 JSON 총 {len(presets)}개 생성완료")
